/* Non-blocking operational intelligence for Hajj/Umrah. It never creates data; it only explains risks. */
const UmrahCore_Insights={
 warnings(programId){const p=UmrahCore_Ops.program(programId);if(!p)return[];const out=[],segs=UmrahCore_Ops.segments(programId),hotels=segs.filter(x=>x.type==='hotel').sort((a,b)=>S(a.start).localeCompare(S(b.start))),flights=segs.filter(x=>x.type==='flight'),travelers=UmrahCore_Ops.activeTravelers(programId),activeBookings=UmrahCore_Ops.scoped('bookings').filter(b=>b.programId===programId&&UmrahCore_Ops.activeBookingStatuses.has(b.status));
  for(let i=1;i<hotels.length;i++){const prev=hotels[i-1],cur=hotels[i];if(prev.end&&cur.start&&UmrahCore_dateAdd(prev.end,1)<cur.start)out.push({level:'warning',title:`فجوة إقامة — ${p.name}`,text:`هناك فترة غير مغطاة بين ${formatDate(prev.end)} و${formatDate(cur.start)}.`,page:'umrah-hotels',action:'راجع الفنادق'});if(prev.end&&cur.start&&prev.end>=cur.start)out.push({level:'warning',title:`تداخل إقامات — ${p.name}`,text:`إقامة ${prev.title||''} تتداخل مع ${cur.title||''}.`,page:'umrah-hotels',action:'راجع التواريخ'})}
  const seats=flights.length?Math.min(...flights.map(x=>Math.max(0,N(x.seats||x.capacity))).filter(Boolean)):0,need=activeBookings.reduce((z,b)=>z+Math.max(0,N(b.persons)-N(b.infants)),0);if(seats&&need>seats)out.push({level:'critical',title:`مقاعد الطيران غير كافية — ${p.name}`,text:`المطلوب ${need} مقعد بينما أقل قطاع متاح ${seats}.`,page:'umrah-flights',action:'صحح الطيران'});
  try{const c=UmrahCore_Cost.budget(programId),prices=Object.values(p.pricing||{}).map(N).filter(x=>x>0),min=prices.length?Math.min(...prices):0;if(c.costPerPax>0&&min>0&&min+0.01<c.costPerPax)out.push({level:'critical',title:`سعر بيع أقل من التكلفة — ${p.name}`,text:`أقل سعر بيع ${UmrahCore_money(min,p.currency)} مقابل تكلفة تقديرية للفرد ${UmrahCore_money(c.costPerPax,UmrahCore_DB.data.settings.baseCurrency)}.`,page:'umrah-costing',action:'راجع التسعير'})}catch(_){}
  if(travelers.length&&p.departureDate&&daysBetween(today(),p.departureDate)>=0&&daysBetween(today(),p.departureDate)<=7){const missing=travelers.filter(t=>!t.passportNo||t.visaStatus!=='issued').length;if(missing)out.push({level:'warning',title:`مسافرون غير جاهزين — ${p.name}`,text:`${missing} مسافر لديهم جواز أو تأشيرة تحتاج استكمال قبل السفر.`,page:'umrah-trip-ready',action:'راجع الجاهزية'})}
  return out},
 snapshot(programId){const p=UmrahCore_Ops.program(programId);if(!p)return null;const bookings=UmrahCore_Ops.scoped('bookings').filter(x=>x.programId===programId&&x.active!==false),travelers=UmrahCore_Ops.scoped('travelers').filter(x=>x.programId===programId&&x.active!==false),commitments=UmrahCore_Ops.scoped('supplierCommitments').filter(x=>x.programId===programId&&x.active!==false&&x.status!=='cancelled'),invoices=(DB.data.invoices||[]).filter(x=>live(x)&&x.programId===programId),receipts=(DB.data.receipts||[]).filter(r=>live(r)&&(r.allocations||[]).some(a=>invoices.some(i=>i.id===a.invoiceId&&i.kind!=='supplier'))),payments=(DB.data.payments||[]).filter(r=>live(r)&&(r.allocations||[]).some(a=>invoices.some(i=>i.id===a.invoiceId&&i.kind==='supplier')));return{program:p,bookings,travelers,commitments,invoices,receipts,payments,warnings:this.warnings(programId)}}
};
