import { UmrahCore_N, UmrahCore_S, UmrahCore_dateAdd, UmrahCore_iid, UmrahCore_monthsAdd, UmrahCore_now, UmrahCore_roomCap, UmrahCore_roomLabel, UmrahCore_today, UmrahCore_vehicleCaps } from './runtime';
import { UmrahCore_Bridge, UmrahCore_DB } from './data';
import { UmrahCore_ContractCenter } from './contracts';
import { UmrahCore_Ops } from '../late-bindings';
const UmrahCore_OpsContracts = {
    addSeason(o) { UmrahCore_Bridge.require('umrah.seasons', 'add'); const name = UmrahCore_S(o.name).trim(), from = o.from || UmrahCore_today(), to = o.to || UmrahCore_today(), salesFrom = o.salesFrom || '', salesTo = o.salesTo || ''; if (!name)
        throw new Error('اسم الموسم مطلوب'); if (to < from)
        throw new Error('تاريخ نهاية الموسم يجب أن يكون بعد تاريخ البداية'); if (salesFrom && salesTo && salesTo < salesFrom)
        throw new Error('فترة البيع غير صحيحة: تاريخ نهاية البيع قبل بدايته'); const x = { id: UmrahCore_iid(), no: UmrahCore_DB.next('season'), name, hijri: o.hijri || '', from, to, salesFrom, salesTo, status: o.status || 'open', notes: o.notes || '', branchId: UmrahCore_Bridge.branchId(), createdAt: UmrahCore_now() }; UmrahCore_DB.data.seasons.unshift(x); UmrahCore_Bridge.audit('create', 'umrahSeason', x.id, x.no); return x; },
    updateSeason(id, o) { UmrahCore_Bridge.require('umrah.seasons', 'edit'); const x = this.season(id); if (!x)
        throw new Error('الموسم غير موجود'); const from = o.from || x.from, to = o.to || x.to, salesFrom = o.salesFrom || '', salesTo = o.salesTo || ''; if (to < from)
        throw new Error('تاريخ نهاية الموسم يجب أن يكون بعد تاريخ البداية'); if (salesFrom && salesTo && salesTo < salesFrom)
        throw new Error('فترة البيع غير صحيحة: تاريخ نهاية البيع قبل بدايته'); Object.assign(x, { name: UmrahCore_S(o.name).trim() || x.name, hijri: o.hijri || '', from, to, salesFrom, salesTo, status: o.status || x.status, notes: o.notes || '', updatedAt: UmrahCore_now() }); UmrahCore_Bridge.audit('update', 'umrahSeason', id, x.no); return x; },
    addHotelContract(o) { UmrahCore_Bridge.require('umrah.contracts', 'add'); if (!UmrahCore_S(o.hotelName).trim())
        throw new Error('اسم الفندق مطلوب'); if (!o.supplierId)
        throw new Error('اختر مورد الفندق'); const rooms = { single: { qty: UmrahCore_N(o.singleQty), rate: UmrahCore_N(o.singleRate) }, double: { qty: UmrahCore_N(o.doubleQty), rate: UmrahCore_N(o.doubleRate) }, triple: { qty: UmrahCore_N(o.tripleQty), rate: UmrahCore_N(o.tripleRate) }, quad: { qty: UmrahCore_N(o.quadQty), rate: UmrahCore_N(o.quadRate) }, quint: { qty: UmrahCore_N(o.quintQty), rate: UmrahCore_N(o.quintRate) } }; if (!Object.values(rooms).some(r => r.qty > 0 && r.rate > 0))
        throw new Error('أدخل مخزون غرفة واحدًا على الأقل مع سعر الليلة'); for (const [t, r] of Object.entries(rooms))
        if ((r.qty > 0) != (r.rate > 0))
            throw new Error(`أكمل عدد وسعر ${UmrahCore_roomLabel(t)} معًا`); const meta = UmrahCore_ContractCenter.normalizeMeta('hotel', o), x = { id: UmrahCore_iid(), branchId: UmrahCore_Bridge.branchId(), kind: 'hotel', ...meta, hotelName: UmrahCore_S(o.hotelName).trim(), shortName: UmrahCore_S(o.shortName || o.hotelName).trim(), city: o.city || 'Makkah', supplierId: o.supplierId, from: o.from || UmrahCore_today(), to: o.to || UmrahCore_today(), currency: o.currency || UmrahCore_DB.data.settings.defaultCurrency, board: o.board || '', cancellationPolicy: o.cancellationPolicy || '', rooms, active: meta.status !== 'cancelled', createdAt: UmrahCore_now() }; if (x.to <= x.from)
        throw new Error('فترة عقد الفندق غير صحيحة'); if (['confirmed', 'active'].includes(x.status))
        UmrahCore_ContractCenter.assertReady('hotel', x); UmrahCore_DB.data.hotelContracts.unshift(x); UmrahCore_Bridge.audit('create', 'hotelContract', x.id, `${x.contractNo} ${x.hotelName}`); return x; },
    updateHotelContract(id, o) { UmrahCore_Bridge.require('umrah.contracts', 'edit'); const x = UmrahCore_ContractCenter.get('hotel', id); if (!x)
        throw new Error('عقد الفندق غير موجود'); const rooms = { single: { qty: UmrahCore_N(o.singleQty), rate: UmrahCore_N(o.singleRate) }, double: { qty: UmrahCore_N(o.doubleQty), rate: UmrahCore_N(o.doubleRate) }, triple: { qty: UmrahCore_N(o.tripleQty), rate: UmrahCore_N(o.tripleRate) }, quad: { qty: UmrahCore_N(o.quadQty), rate: UmrahCore_N(o.quadRate) }, quint: { qty: UmrahCore_N(o.quintQty), rate: UmrahCore_N(o.quintRate) } }; for (const t of Object.keys(UmrahCore_roomCap)) {
        const reserved = UmrahCore_ContractCenter.hotelStats(id, t).reserved;
        if (UmrahCore_N(rooms[t].qty) < reserved)
            throw new Error(`لا يمكن خفض ${UmrahCore_roomLabel(t)} عن المحجوز (${reserved})`);
    } const reservations = UmrahCore_ContractCenter.activeReservations('hotel', id), meta = UmrahCore_ContractCenter.normalizeMeta('hotel', o, x), next = { ...x, ...meta, hotelName: UmrahCore_S(o.hotelName).trim() || x.hotelName, shortName: UmrahCore_S(o.shortName).trim() || UmrahCore_S(o.hotelName).trim() || x.shortName || x.hotelName, city: o.city || x.city, supplierId: o.supplierId || x.supplierId, from: o.from || x.from, to: o.to || x.to, currency: o.currency || x.currency, board: o.board || '', cancellationPolicy: o.cancellationPolicy || '', rooms, active: meta.status !== 'cancelled', updatedAt: UmrahCore_now() }; if (!next.supplierId || next.to <= next.from)
        throw new Error('بيانات عقد الفندق غير مكتملة'); if (reservations.length && (next.supplierId !== x.supplierId || next.currency !== x.currency))
        throw new Error('لا يمكن تغيير المورد أو العملة بعد تخصيص العقد لبرنامج'); if (reservations.length && (!['confirmed', 'active'].includes(next.status) || next.hotelName !== x.hotelName || next.shortName !== x.shortName || next.city !== x.city || next.board !== x.board || JSON.stringify(next.inventoryPeriods||[])!==JSON.stringify(x.inventoryPeriods||[]) || Object.keys(UmrahCore_roomCap).some(t => UmrahCore_N(next.rooms?.[t]?.rate) !== UmrahCore_N(x.rooms?.[t]?.rate))))
        throw new Error('لا يمكن تغيير حالة/فندق/مدينة/إعاشة/أسعار عقد مستخدم في برنامج؛ أنشئ تعديلًا تعاقديًا جديدًا حتى لا تختلف التكلفة عن المخزون وأمر الشراء'); for (const r of reservations)
        if ((r.from && next.from > r.from) || (r.to && next.to < r.to))
            throw new Error('لا يمكن تقليص فترة العقد بحيث تستبعد تخصيصًا قائمًا'); if (['confirmed', 'active'].includes(next.status))
        UmrahCore_ContractCenter.assertReady('hotel', next); Object.assign(x, next); UmrahCore_Bridge.audit('update', 'hotelContract', x.id, x.contractNo); return x; },
    addFlightBlock(o) { UmrahCore_Bridge.require('umrah.contracts', 'add'); if (!UmrahCore_S(o.airline).trim())
        throw new Error('شركة الطيران مطلوبة'); if (!o.supplierId)
        throw new Error('اختر مورد الطيران'); if (!o.outFlight || !o.returnFlight || !o.outDateTime || !o.returnDateTime)
        throw new Error('أكمل رحلتي الذهاب والعودة ومواعيدهما'); if (UmrahCore_N(o.seats) <= 0 || UmrahCore_N(o.costPerSeat) <= 0)
        throw new Error('عدد المقاعد وتكلفة المقعد مطلوبان'); const meta = UmrahCore_ContractCenter.normalizeMeta('flight', o), x = { id: UmrahCore_iid(), branchId: UmrahCore_Bridge.branchId(), kind: 'flight', ...meta, name: o.name || `${o.airline} ${o.outFlight || ''}`, supplierId: o.supplierId, airline: o.airline, outFlight: o.outFlight || '', outFrom: o.outFrom || '', outTo: o.outTo || '', outDateTime: o.outDateTime || '', returnFlight: o.returnFlight || '', returnFrom: o.returnFrom || '', returnTo: o.returnTo || '', returnDateTime: o.returnDateTime || '', seats: Math.max(1, UmrahCore_N(o.seats)), currency: o.currency || UmrahCore_DB.data.settings.defaultCurrency, costPerSeat: UmrahCore_N(o.costPerSeat), ticketDeadline: o.ticketDeadline || '', fareClass: o.fareClass || '', baggage: o.baggage || '', active: meta.status !== 'cancelled', createdAt: UmrahCore_now() }; if (x.returnDateTime <= x.outDateTime)
        throw new Error('موعد العودة يجب أن يكون بعد الذهاب'); if (['confirmed', 'active'].includes(x.status))
        UmrahCore_ContractCenter.assertReady('flight', x); UmrahCore_DB.data.flightBlocks.unshift(x); UmrahCore_Bridge.audit('create', 'flightBlock', x.id, `${x.contractNo} ${x.name}`); return x; },
    updateFlightBlock(id, o) { UmrahCore_Bridge.require('umrah.contracts', 'edit'); const x = UmrahCore_ContractCenter.get('flight', id); if (!x)
        throw new Error('بلوك الطيران غير موجود'); const reservations = UmrahCore_ContractCenter.activeReservations('flight', id), reserved = UmrahCore_ContractCenter.flightStats(id).reserved; if (UmrahCore_N(o.seats) < reserved)
        throw new Error(`لا يمكن خفض المقاعد عن المحجوز (${reserved})`); const meta = UmrahCore_ContractCenter.normalizeMeta('flight', o, x), next = { ...x, ...meta, name: o.name || x.name, airline: UmrahCore_S(o.airline).trim() || x.airline, supplierId: o.supplierId || x.supplierId, outFlight: o.outFlight || '', outFrom: o.outFrom || '', outTo: o.outTo || '', outDateTime: o.outDateTime || '', returnFlight: o.returnFlight || '', returnFrom: o.returnFrom || '', returnTo: o.returnTo || '', returnDateTime: o.returnDateTime || '', seats: Math.max(1, UmrahCore_N(o.seats)), currency: o.currency || x.currency, costPerSeat: UmrahCore_N(o.costPerSeat), ticketDeadline: o.ticketDeadline || '', fareClass: o.fareClass || '', baggage: o.baggage || '', active: meta.status !== 'cancelled', updatedAt: UmrahCore_now() }; if (!next.supplierId || !next.outFlight || !next.returnFlight || next.returnDateTime <= next.outDateTime || next.costPerSeat <= 0)
        throw new Error('بيانات بلوك الطيران غير مكتملة'); if (reservations.length && (next.supplierId !== x.supplierId || next.currency !== x.currency || next.outFlight !== x.outFlight || next.returnFlight !== x.returnFlight || next.outDateTime !== x.outDateTime || next.returnDateTime !== x.returnDateTime))
        throw new Error('لا يمكن تغيير المورد/العملة/الرحلات بعد تخصيص البلوك لبرنامج؛ أنشئ تعديلًا أو بلوكًا جديدًا'); if (reservations.length && (!['confirmed', 'active'].includes(next.status) || next.name !== x.name || next.airline !== x.airline || next.outFrom !== x.outFrom || next.outTo !== x.outTo || next.returnFrom !== x.returnFrom || next.returnTo !== x.returnTo || UmrahCore_N(next.costPerSeat) !== UmrahCore_N(x.costPerSeat) || next.fareClass !== x.fareClass || next.baggage !== x.baggage))
        throw new Error('لا يمكن تغيير بيانات التشغيل أو تكلفة بلوك مستخدم في برنامج؛ أنشئ بلوك/تعديل تعاقدي جديدًا للحفاظ على تطابق المخزون والتكلفة'); if (['confirmed', 'active'].includes(next.status))
        UmrahCore_ContractCenter.assertReady('flight', next); Object.assign(x, next); UmrahCore_Bridge.audit('update', 'flightBlock', x.id, x.contractNo); return x; },
    addTransportContract(o) { UmrahCore_Bridge.require('umrah.contracts', 'add'); if (!UmrahCore_S(o.provider).trim())
        throw new Error('شركة النقل مطلوبة'); if (!o.supplierId)
        throw new Error('اختر مورد النقل'); const vt = o.vehicleType || 'bus', cap = Math.max(1, UmrahCore_N(o.capacityPerVehicle) || UmrahCore_vehicleCaps[vt] || 50); if (UmrahCore_N(o.vehicles) <= 0 || UmrahCore_N(o.cost) <= 0)
        throw new Error('عدد المركبات والتكلفة مطلوبان'); const meta = UmrahCore_ContractCenter.normalizeMeta('transport', o), x = { id: UmrahCore_iid(), branchId: UmrahCore_Bridge.branchId(), kind: 'transport', ...meta, provider: UmrahCore_S(o.provider).trim(), supplierId: o.supplierId, route: o.route || '', vehicleType: vt, vehicles: Math.max(1, UmrahCore_N(o.vehicles)), capacityPerVehicle: cap, currency: o.currency || UmrahCore_DB.data.settings.defaultCurrency, cost: UmrahCore_N(o.cost), from: o.from || '', to: o.to || '', active: meta.status !== 'cancelled', createdAt: UmrahCore_now() }; if (x.from && x.to && x.to < x.from)
        throw new Error('فترة عقد النقل غير صحيحة'); if (['confirmed', 'active'].includes(x.status))
        UmrahCore_ContractCenter.assertReady('transport', x); UmrahCore_DB.data.transportContracts.unshift(x); UmrahCore_Bridge.audit('create', 'transportContract', x.id, `${x.contractNo} ${x.provider}`); return x; },
    updateTransportContract(id, o) { UmrahCore_Bridge.require('umrah.contracts', 'edit'); const x = UmrahCore_ContractCenter.get('transport', id); if (!x)
        throw new Error('عقد النقل غير موجود'); const reservations = UmrahCore_ContractCenter.activeReservations('transport', id), reserved = UmrahCore_ContractCenter.transportStats(id).reservedVehicles; if (UmrahCore_N(o.vehicles) < reserved)
        throw new Error(`لا يمكن خفض المركبات عن المحجوز (${reserved})`); const vt = o.vehicleType || x.vehicleType, cap = Math.max(1, UmrahCore_N(o.capacityPerVehicle) || UmrahCore_vehicleCaps[vt] || 50), meta = UmrahCore_ContractCenter.normalizeMeta('transport', o, x), next = { ...x, ...meta, provider: UmrahCore_S(o.provider).trim() || x.provider, supplierId: o.supplierId || x.supplierId, route: o.route || '', vehicleType: vt, vehicles: Math.max(1, UmrahCore_N(o.vehicles)), capacityPerVehicle: cap, currency: o.currency || x.currency, cost: UmrahCore_N(o.cost), from: o.from || '', to: o.to || '', active: meta.status !== 'cancelled', updatedAt: UmrahCore_now() }; if (!next.supplierId || next.cost <= 0)
        throw new Error('بيانات عقد النقل غير مكتملة'); if (next.from && next.to && next.to < next.from)
        throw new Error('فترة عقد النقل غير صحيحة'); if (reservations.length && (next.supplierId !== x.supplierId || next.currency !== x.currency || next.vehicleType !== x.vehicleType || next.capacityPerVehicle !== x.capacityPerVehicle))
        throw new Error('لا يمكن تغيير المورد/العملة/نوع المركبة بعد تخصيص العقد لبرنامج'); if (reservations.length && (!['confirmed', 'active'].includes(next.status) || next.provider !== x.provider || next.route !== x.route || UmrahCore_N(next.cost) !== UmrahCore_N(x.cost)))
        throw new Error('لا يمكن تغيير حالة/مسار/تكلفة عقد نقل مستخدم في برنامج؛ أنشئ تعديلًا تعاقديًا جديدًا للحفاظ على تطابق التشغيل والتكلفة'); for (const r of reservations)
        if ((r.from && next.from && next.from > r.from) || (r.to && next.to && next.to < UmrahCore_dateAdd(r.to, -1)))
            throw new Error('لا يمكن تقليص فترة عقد النقل بحيث تستبعد تخصيصًا قائمًا'); if (['confirmed', 'active'].includes(next.status))
        UmrahCore_ContractCenter.assertReady('transport', next); Object.assign(x, next); UmrahCore_Bridge.audit('update', 'transportContract', x.id, x.contractNo); return x; },
    addVisaContract(o) { UmrahCore_Bridge.require('umrah.contracts', 'add'); if (!UmrahCore_S(o.serviceName).trim())
        throw new Error('اسم خدمة التأشيرة مطلوب'); if (!o.supplierId)
        throw new Error('اختر مورد التأشيرات'); if (UmrahCore_N(o.quota) <= 0 || UmrahCore_N(o.costPerVisa) <= 0)
        throw new Error('حصة التأشيرات وتكلفة التأشيرة مطلوبتان'); const meta = UmrahCore_ContractCenter.normalizeMeta('visa', o), x = { id: UmrahCore_iid(), branchId: UmrahCore_Bridge.branchId(), kind: 'visa', ...meta, serviceName: UmrahCore_S(o.serviceName).trim(), programType: ['hajj', 'umrah'].includes(o.programType) ? o.programType : 'all', supplierId: o.supplierId, from: o.from || UmrahCore_today(), to: o.to || UmrahCore_monthsAdd(UmrahCore_today(), 3), quota: Math.max(1, UmrahCore_N(o.quota)), currency: o.currency || UmrahCore_DB.data.settings.defaultCurrency, costPerVisa: UmrahCore_N(o.costPerVisa), processingDays: Math.max(0, UmrahCore_N(o.processingDays)), active: meta.status !== 'cancelled', createdAt: UmrahCore_now() }; if (x.to < x.from)
        throw new Error('فترة اتفاقية التأشيرات غير صحيحة'); if (['confirmed', 'active'].includes(x.status))
        UmrahCore_ContractCenter.assertReady('visa', x); UmrahCore_DB.data.visaContracts.unshift(x); UmrahCore_Bridge.audit('create', 'visaContract', x.id, `${x.contractNo} ${x.serviceName}`); return x; },
    updateVisaContract(id, o) { UmrahCore_Bridge.require('umrah.contracts', 'edit'); const x = UmrahCore_ContractCenter.get('visa', id); if (!x)
        throw new Error('اتفاقية التأشيرات غير موجودة'); const reservations = UmrahCore_ContractCenter.activeReservations('visa', id), reserved = UmrahCore_ContractCenter.visaStats(id).reserved; if (UmrahCore_N(o.quota) < reserved)
        throw new Error(`لا يمكن خفض حصة التأشيرات عن المحجوز (${reserved})`); const meta = UmrahCore_ContractCenter.normalizeMeta('visa', o, x), next = { ...x, ...meta, serviceName: UmrahCore_S(o.serviceName).trim() || x.serviceName, programType: ['hajj', 'umrah'].includes(o.programType) ? o.programType : 'all', supplierId: o.supplierId || x.supplierId, from: o.from || x.from, to: o.to || x.to, quota: Math.max(1, UmrahCore_N(o.quota)), currency: o.currency || x.currency, costPerVisa: UmrahCore_N(o.costPerVisa), processingDays: Math.max(0, UmrahCore_N(o.processingDays)), active: meta.status !== 'cancelled', updatedAt: UmrahCore_now() }; if (!next.supplierId || next.to < next.from || next.costPerVisa <= 0)
        throw new Error('بيانات اتفاقية التأشيرات غير مكتملة'); if (reservations.length && (next.supplierId !== x.supplierId || next.currency !== x.currency || next.programType !== x.programType))
        throw new Error('لا يمكن تغيير المورد أو العملة أو نوع البرنامج بعد تخصيص الاتفاقية لبرنامج'); if (reservations.length && (!['confirmed', 'active'].includes(next.status) || next.serviceName !== x.serviceName || UmrahCore_N(next.costPerVisa) !== UmrahCore_N(x.costPerVisa)))
        throw new Error('لا يمكن تغيير حالة/خدمة/سعر اتفاقية مستخدمة في برنامج؛ أنشئ تعديلًا تعاقديًا جديدًا للحفاظ على التتبع'); for (const r of reservations) {
        const p = UmrahCore_Ops.program(r.programId);
        if ((p?.departureDate && next.from > p.departureDate) || (p?.returnDate && next.to < p.returnDate))
            throw new Error('لا يمكن تقليص فترة الاتفاقية بحيث تستبعد برنامجًا مخصصًا');
    } if (['confirmed', 'active'].includes(next.status))
        UmrahCore_ContractCenter.assertReady('visa', next); Object.assign(x, next); UmrahCore_Bridge.audit('update', 'visaContract', x.id, x.contractNo); return x; }
};
export { UmrahCore_OpsContracts };
