import { UmrahCore_N, UmrahCore_esc, UmrahCore_money } from './runtime';
import { UmrahCore_Bridge } from './data';
import { UmrahCore_Inventory } from './contracts-inventory';
import { UmrahCore_ContractCenter } from './contracts';
import { UmrahCore_Ops } from './operations';
import { UmrahCore_State, UmrahCore_UI } from './ui';
const UmrahCore_PagesContracts = {
    contracts() {
        const canCost=UmrahCore_Bridge.canViewCosts()&&UmrahCore_Bridge.can('umrah.costing','view'),canEdit=UmrahCore_Bridge.can('umrah.contracts','edit'),canAdd=UmrahCore_Bridge.can('umrah.contracts','add'),view=UmrahCore_State.contractView||'overview',kind=UmrahCore_State.contractKind||'all',k=UmrahCore_ContractCenter.kpis(),alerts=UmrahCore_ContractCenter.warnings(),kinds=['hotel','flight','transport','visa','service'];
        const all=kinds.flatMap(type=>UmrahCore_ContractCenter.arr(type).map(c=>({type,c,summary:UmrahCore_Inventory.summary(type,c)}))),filtered=kind==='all'?all:all.filter(x=>x.type===kind);
        const iconLabel={hotel:'الفنادق',flight:'الطيران',transport:'النقل',visa:'التأشيرات',service:'الخدمات التعاقدية'}, editForm=t=>t==='hotel'?'hotelContract':t==='flight'?'flightBlock':t==='transport'?'transportContract':t==='visa'?'visaContract':'serviceContract';
        const actions=(type,c)=>{const st=UmrahCore_ContractCenter.effectiveStatus(type,c),usable=UmrahCore_ContractCenter.usable(type,c);return `<div class="quick-actions"><button class="btn small soft" data-umrah-contract-action="details" data-umrah-contract-kind="${type}" data-umrah-contract-id="${UmrahCore_esc(c.id)}">التفاصيل</button>${usable&&canEdit?`<button class="btn small primary" data-umrah-contract-action="allocation" data-umrah-contract-kind="${type}" data-umrah-contract-id="${UmrahCore_esc(c.id)}">تخصيص</button>`:''}${canEdit||(['draft','negotiating'].includes(st)&&canEdit)?`<details class="compact-action-menu"><summary class="btn small ghost">إدارة</summary><div class="compact-action-pop">${canEdit?`<button class="btn small ghost" data-umrah-contract-edit="${editForm(type)}" data-umrah-contract-id="${UmrahCore_esc(c.id)}">تعديل العقد</button><button class="btn small ghost" data-umrah-contract-action="amendment" data-umrah-contract-kind="${type}" data-umrah-contract-id="${UmrahCore_esc(c.id)}">ملحق تعاقدي</button>`:''}${['draft','negotiating'].includes(st)&&canEdit?`<button class="btn small success" data-umrah-contract-action="confirm" data-umrah-contract-kind="${type}" data-umrah-contract-id="${UmrahCore_esc(c.id)}">تأكيد العقد</button>`:''}</div></details>`:''}</div>`;};
        const newActions=`${canAdd?`<details class="compact-action-menu"><summary class="btn primary">+ تعاقد جديد</summary><div class="compact-action-pop"><button class="btn ghost" data-umrah-form-call="hotelContract">عقد فندق</button><button class="btn ghost" data-umrah-form-call="flightBlock">بلوك طيران</button><button class="btn ghost" data-umrah-form-call="transportContract">عقد نقل</button><button class="btn ghost" data-umrah-form-call="visaContract">اتفاقية تأشيرات</button><button class="btn ghost" data-umrah-form-call="serviceContract">خدمة تعاقدية</button></div></details>`:''}<button class="btn soft" data-umrah-page="procurement">المشتريات</button>`;
        const viewTabs=[['overview','نظرة عامة'],['contracts','العقود'],['inventory','المخزون الحي'],['allocations','تخصيصات البرامج'],['finance','الاستحقاقات والمشتريات']].map(([v,l])=>`<button class="btn small ${view===v?'primary':'ghost'}" data-umrah-contract-view="${v}">${l}</button>`).join('');
        const kindTabs=`<label class="compact-inline-filter">نوع التعاقد <select data-umrah-contract-kind="1">${[['all','الكل'],...kinds.map(x=>[x,iconLabel[x]])].map(([v,l])=>`<option value="${v}" ${kind===v?'selected':''}>${l} (${v==='all'?all.length:all.filter(x=>x.type===v).length})</option>`).join('')}</select></label>`;
        const issue=(type,c)=>{const q=UmrahCore_ContractCenter.issues(type,c);return q.errors.length?`<span class="badge red">${q.errors.length} خطأ</span>`:q.warnings.length?`<span class="badge orange">${q.warnings.length} ملاحظة</span>`:'<span class="badge green">سليم</span>';};
        const release=(c)=>{const cut=UmrahCore_Inventory.releaseCutoff(c,UmrahCore_ContractCenter.startDate(c.kind,c));return c.releaseMode==='rolling'?`قبل الخدمة ${UmrahCore_N(c.releaseDays)} يوم`:cut?cut:'يدوي';};
        const contractRows=filtered.map(({type,c,summary})=>`<tr><td><span class="badge blue">${UmrahCore_ContractCenter.kindLabel(type)}</span><div><b>${UmrahCore_esc(c.contractNo)}</b></div>${c.amendmentOf?`<small>ملحق ${UmrahCore_N(c.amendmentNo)}</small>`:''}</td><td><b>${UmrahCore_esc(UmrahCore_ContractCenter.name(type,c))}</b><div class="muted">${UmrahCore_esc(UmrahCore_Bridge.supplier(c.supplierId)?.name||'مورد غير موجود')}</div></td><td>${UmrahCore_ContractCenter.startDate(type,c)||'-'} → ${UmrahCore_ContractCenter.endDate(type,c)||'-'}<div class="muted">تحرير المخزون: ${UmrahCore_esc(release(c))}</div></td><td><b>${summary.total} ${summary.unit}</b><div class="muted">مخصص ${summary.allocated} • مستخدم ${summary.used} • متاح ${summary.available}</div></td><td>${canCost?UmrahCore_money(UmrahCore_ContractCenter.contractTotal(type,c),c.currency):'••••'}</td><td>${issue(type,c)}<div><span class="badge ${UmrahCore_ContractCenter.statusTone(UmrahCore_ContractCenter.effectiveStatus(type,c))}">${UmrahCore_ContractCenter.statusLabel(UmrahCore_ContractCenter.effectiveStatus(type,c))}</span></div></td><td>${actions(type,c)}</td></tr>`);
        const inventoryRows=filtered.map(({type,c,summary})=>{const blocked=summary.available===0&&(UmrahCore_Inventory.released(c,UmrahCore_ContractCenter.startDate(type,c))||UmrahCore_Inventory.stopSaleOverlap(c,UmrahCore_ContractCenter.startDate(type,c),UmrahCore_ContractCenter.endDate(type,c)));return `<tr><td><b>${UmrahCore_esc(c.contractNo)}</b><div class="muted">${UmrahCore_ContractCenter.kindLabel(type)} • ${UmrahCore_esc(UmrahCore_ContractCenter.name(type,c))}</div></td><td>${summary.total} ${summary.unit}</td><td>${summary.allocated}</td><td>${summary.used}</td><td><b>${summary.available}</b></td><td>${blocked?'<span class="badge red">موقوف / تم تحرير المخزون</span>':'<span class="badge green">متاح للبيع</span>'}${(c.stopSales||[]).length?`<div class="muted">${c.stopSales.length} فترة إيقاف بيع</div>`:''}</td><td>${actions(type,c)}</td></tr>`;});
        const allocRows=UmrahCore_Ops.scoped('contractReservations').filter(r=>r.active!==false&&(kind==='all'||r.kind===kind)).map(r=>{const c=UmrahCore_ContractCenter.get(r.kind,r.contractId),p=UmrahCore_Ops.program(r.programId);if(!c||!p)return '';return `<tr><td><b>${UmrahCore_esc(c.contractNo)}</b><div class="muted">${UmrahCore_ContractCenter.kindLabel(r.kind)}</div></td><td><b>${UmrahCore_esc(p.no)}</b><div class="muted">${UmrahCore_esc(p.name)}</div></td><td>${r.from||'-'}${r.to?' → '+r.to:''}</td><td>${UmrahCore_esc(UmrahCore_ContractCenter.allocationText(r.kind,r))}</td><td>${canEdit&&!['traveling','returned','closed'].includes(p.status)?`<div class="quick-actions"><button class="btn small soft" data-umrah-contract-action="allocationAdjustment" data-umrah-contract-kind="${UmrahCore_esc(r.kind)}" data-umrah-contract-id="${UmrahCore_esc(r.id)}">تعديل الكمية</button><button class="btn small danger" data-umrah-contract-action="unallocation" data-umrah-contract-kind="${UmrahCore_esc(r.kind)}" data-umrah-contract-id="${UmrahCore_esc(r.id)}">تحرير كامل</button></div>`:'<span class="muted">مقفل تشغيليًا</span>'}</td></tr>`;}).filter(Boolean);
        const financeRows=filtered.flatMap(({type,c})=>{const fin=UmrahCore_ContractCenter.financial(type,c.id),pays=UmrahCore_ContractCenter.paymentSchedule(type,c);return pays.map(row=>{const st=UmrahCore_ContractCenter.scheduleState(type,c,row);return `<tr><td><b>${UmrahCore_esc(c.contractNo)}</b><div class="muted">${UmrahCore_esc(UmrahCore_ContractCenter.name(type,c))}</div></td><td>${UmrahCore_esc(row.label)}</td><td>${row.due}</td><td>${canCost?UmrahCore_money(row.amount,c.currency):'••••'}</td><td>${canCost?UmrahCore_money(st.paid,c.currency):'••••'}</td><td>${canCost?UmrahCore_money(st.outstanding,c.currency):'••••'}</td><td>${st.outstanding>.01?`<button class="btn small success" data-umrah-contract-action="payment" data-umrah-contract-kind="${type}" data-umrah-contract-id="${UmrahCore_esc(c.id)}" data-umrah-contract-extra="${UmrahCore_esc(row.id)}">سداد</button>`:'<span class="badge green">مغطاة</span>'}</td></tr>`;});});
        let body='';
        if(view==='overview') body=`<div class="contract-flow"><b>الدورة الصحيحة:</b><span>عقد / ملحق</span><i>←</i><span>مخزون حي بتاريخ الخدمة</span><i>←</i><span>تخصيص للبرنامج</span><i>←</i><span>استخدام فعلي</span><i>←</i><span>أمر شراء / فاتورة مورد</span></div><div class="grid kpis contract-kpis"><div class="card kpi"><div class="label">عقود فعالة</div><div class="value">${k.active}</div></div><div class="card kpi"><div class="label">غرف متاحة</div><div class="value">${k.rooms}</div></div><div class="card kpi"><div class="label">مقاعد متاحة</div><div class="value">${k.seats}</div></div><div class="card kpi"><div class="label">سعة نقل</div><div class="value">${k.transport}</div></div><div class="card kpi"><div class="label">تأشيرات</div><div class="value">${k.visas}</div></div><div class="card kpi"><div class="label">خدمات أخرى</div><div class="value">${k.services||0}</div></div><div class="card kpi"><div class="label">قيمة العقود</div><div class="value">${canCost?UmrahCore_money(k.contractValue,UmrahCore_Bridge.baseCurrency()):'••••'}</div></div><div class="card kpi"><div class="label">تنبيهات</div><div class="value">${k.alerts}</div></div></div>${alerts.length?`<div class="card contract-alerts"><div class="section-head"><div><h2>تنبيهات التعاقدات</h2><p>تحرير المخزون وإيقاف البيع والدفعات والربط بالمشتريات.</p></div></div>${alerts.slice(0,12).map(a=>`<button type="button" class="contract-alert ${a.tone}" data-umrah-contract-alert-kind="${UmrahCore_esc(a.kind)}" data-umrah-contract-alert-id="${UmrahCore_esc(a.id)}" data-umrah-contract-alert-action="${a.action||'details'}" data-umrah-contract-alert-ref="${a.ref||''}"><b>${UmrahCore_esc(a.title)}</b><span>${UmrahCore_esc(a.desc)}</span></button>`).join('')}</div>`:'<div class="card empty">لا توجد تنبيهات تعاقدية حالية</div>'}`;
        else if(view==='contracts') body=UmrahCore_UI.table(['النوع / العقد','الخدمة / المورد','الفترة / تحرير المخزون','المخزون','القيمة','الصحة / الحالة','إجراء'],contractRows,'لا توجد عقود ضمن الفلتر');
        else if(view==='inventory') body=`<div class="info-note">«المخصص» = ما حُجز للبرامج، «المستخدم» = الاستخدام التشغيلي الفعلي، «المتاح» = ما يمكن تخصيصه الآن بعد قواعد تحرير المخزون وإيقاف البيع. الفندق محسوب يومًا بيوم.</div>${UmrahCore_UI.table(['العقد','إجمالي','مخصص','مستخدم','متاح الآن','حالة البيع','إجراء'],inventoryRows,'لا يوجد مخزون ضمن الفلتر')}`;
        else if(view==='allocations') body=UmrahCore_UI.table(['العقد','البرنامج','الفترة','التخصيص','إجراء'],allocRows,'لا توجد تخصيصات نشطة');
        else body=`<div class="info-note">جدول الدفعات هنا لا ينشئ مديونية وحده؛ فاتورة المورد هي التي تنشئ الذمة، والسداد قبل الفاتورة يسجل مقدم مورد.</div>${UmrahCore_UI.table(['العقد','الدفعة','الاستحقاق','القيمة','مدفوع','متبقي','إجراء'],financeRows,'لا توجد استحقاقات تعاقدية')}`;
        return `${UmrahCore_UI.head('مركز التعاقدات والمخزون','مصدر واحد للعقد والمخزون والتخصيص والاستخدام والمشتريات؛ مع مخزون فندقي يومي وقواعد تحرير المخزون وإيقاف البيع والملحقات التعاقدية.',newActions)}<div class="card mb-12"><div class="quick-actions">${viewTabs}</div><div class="quick-actions mt-8">${kindTabs}</div></div>${body}`;
    }
};
export { UmrahCore_PagesContracts };
