import { DeleteCenter } from '../delete-center';
import { UI } from '../../ui/ui';
import { UmrahCore_esc, UmrahCore_programDisplay, UmrahCore_roomLabel, UmrahCore_today } from './runtime';
import { UmrahCore_Bridge } from './data';
import { UmrahCore_Ops } from './operations';
import { UmrahCore_State, UmrahCore_UI, UmrahCore_filterHistory, UmrahCore_historyToolbar, UmrahCore_selectProgram, UmrahCore_ticketStatusLabel, UmrahCore_travelerCategory } from './ui';
import { UmrahCore_Pages } from '../late-bindings';
const UmrahCore_PagesResources = {
    hotels() { const ps = UmrahCore_Ops.scoped('programs').filter(p => UmrahCore_Ops.segments(p.id, 'hotel').length), pid = UmrahCore_State.hotelProgram || ps[0]?.id || ''; if (pid && !ps.some(p => p.id === pid))
        UmrahCore_State.hotelProgram = ps[0]?.id || ''; const p = UmrahCore_Ops.program(UmrahCore_State.hotelProgram || pid); return `${UmrahCore_UI.head('الفنادق وتوزيع الغرف', 'التوزيع مستقل لكل إقامة فندقية داخل نفس البرنامج.', ps.length ? UmrahCore_selectProgram('hotelSelect', p?.id || ps[0].id, 'hotelProgram') : '')}${p ? UmrahCore_Ops.segments(p.id, 'hotel').map(seg => UmrahCore_Pages.hotelSegment(p, seg)).join('') : '<div class="card empty">لا توجد إقامة فندقية داخل البرامج</div>'}`; },
    hotelSegment(p, seg) { const rooms = UmrahCore_Ops.scoped('hotelRooms').filter(r => r.programId === p.id && r.segmentId === seg.id && UmrahCore_Ops.scoped('bookings').some(b => b.id === r.bookingId && UmrahCore_Ops.activeBookingStatuses.has(b.status))), trav = UmrahCore_Ops.scoped('travelers').filter(t => t.programId === p.id && t.active !== false && UmrahCore_Ops.scoped('bookings').some(b => b.id === t.bookingId && UmrahCore_Ops.activeBookingStatuses.has(b.status))); return `<div class="card mb-12"><div class="section-head"><div><h2>${UmrahCore_esc(seg.title)}</h2><p>${seg.start} → ${seg.end} • ${UmrahCore_esc(seg.city || '')}</p></div><button class="btn small ghost" data-umrah-print="rooming" data-umrah-print-id="${UmrahCore_esc(p.id)}" data-umrah-print-extra="${UmrahCore_esc(seg.id)}">طباعة توزيع الغرف</button></div><div class="grid three">${rooms.map(r => { const occ = trav.filter(t => t.roomAssignments?.[seg.id] === r.id); return `<div class="room-card"><div class="metric"><div><b>${r.code}</b><small class="muted">${UmrahCore_roomLabel(r.roomType)}</small></div><span class="badge ${occ.length ? 'green' : 'gray'}">${occ.length}/${r.capacity}</span></div>${occ.map(t => `<div class="info-row"><div><b>${UmrahCore_esc(t.nameAr || t.no)}</b><small>${UmrahCore_travelerCategory(t.category)}</small></div></div>`).join('') || '<div class="muted mt-8">غرفة فارغة</div>'}<div class="muted mt-8">رقم الفندق: ${UmrahCore_esc(r.hotelRoomNo || 'غير محدد')}</div><button class="btn small ghost mt-7" data-umrah-form-call="hotelRoom" data-umrah-form-id="${UmrahCore_esc(r.id)}">تحديد الرقم</button></div>`; }).join('') || '<div class="empty">لا توجد غرف مولدة للحجوزات النشطة</div>'}</div></div>`; },
    visas() { const all = UmrahCore_Ops.scoped('visaBatches'), modeRows = UmrahCore_filterHistory('visas', all), itemRows=v=>UmrahCore_Ops.scoped('visaItems').filter(x=>x.batchId===v.id&&x.active!==false), completePred=v=>{const xs=itemRows(v);return xs.length>0&&xs.every(x=>x.status==='issued')}, pendingPred=v=>!completePred(v), latePred=v=>v.deadline&&v.deadline<UmrahCore_today()&&pendingPred(v), filtered=UI.applyListFilter('umrah-visas',modeRows,{pending:pendingPred,complete:completePred,late:latePred}), batches = filtered.map(v => { const p = UmrahCore_Ops.program(v.programId), items = itemRows(v), issued = items.filter(x => x.status === 'issued').length; return `<div class="card mb-12"><div class="section-head"><div><h2>${v.no} — ${UmrahCore_esc(p ? UmrahCore_programDisplay(p) : '-')}</h2><p>${items.length} مسافر • آخر موعد ${v.deadline || '-'}</p></div><div class="quick-actions"><span class="badge ${issued === items.length && items.length ? 'green' : 'orange'}">صادر ${issued}/${items.length}</span><button class="btn small ghost" data-umrah-visa-batch-overview="${UmrahCore_esc(v.id)}">فتح الدفعة</button>${UmrahCore_Bridge.can('umrah.visas','delete')?DeleteCenter.button('visaBatch',v.id):''}</div></div><div class="progress"><i style="width:${items.length ? issued / items.length * 100 : 0}%"></i></div></div>`; }); return UmrahCore_UI.head('إدارة التأشيرات', 'دفعات التأشيرات ومراحل كل مسافر من المراجعة حتى الإصدار.', `<button class="btn primary" data-umrah-form-call="visaBatch">+ دفعة تأشيرات</button>`) + UmrahCore_historyToolbar('visas', all) + UI.smartFilterStrip('umrah-visas',[{key:'all',label:'كل الدفعات المعروضة',value:modeRows.length,note:'حسب تبويب السجل',cls:'info',ic:'visas'},{key:'pending',label:'غير مكتملة',value:modeRows.filter(pendingPred).length,note:'بها ملفات غير صادرة',cls:'warn',ic:'clock'},{key:'late',label:'متأخرة',value:modeRows.filter(latePred).length,note:'تجاوزت آخر موعد',cls:'bad',ic:'warning'},{key:'complete',label:'مكتملة',value:modeRows.filter(completePred).length,note:'كل التأشيرات صادرة',cls:'good',ic:'check'}]) + (batches.join('') || '<div class="card empty">لا توجد دفعات ضمن الفلتر</div>'); },
    flights() { const ps = UmrahCore_Ops.scoped('programs').filter(p => UmrahCore_Ops.segments(p.id, 'flight').length), pid = UmrahCore_State.flightProgram || ps[0]?.id || ''; if (pid && !ps.some(p => p.id === pid)) {
        UmrahCore_State.flightProgram = ps[0]?.id || '';
        UmrahCore_State.flightSegment = '';
    } const p = UmrahCore_Ops.program(UmrahCore_State.flightProgram || pid); if (!p)
        return UmrahCore_UI.head('الطيران والتذاكر', 'لا توجد قطاعات طيران') + '<div class="card empty">أضف قطاع طيران إلى أحد البرامج أولًا.</div>'; const segs = UmrahCore_Ops.segments(p.id, 'flight'), sid = UmrahCore_State.flightSegment && segs.some(s => s.id === UmrahCore_State.flightSegment) ? UmrahCore_State.flightSegment : segs[0]?.id || '', seg = segs.find(s => s.id === sid), trav = UmrahCore_Ops.activeTravelers(p.id), tickets = UmrahCore_Ops.scoped('tickets').filter(x => x.programId === p.id && x.segmentId === sid && x.active !== false), ticketOf = t => tickets.find(x => x.travelerId === t.id) || {}, rows = trav.map(t => { const x = ticketOf(t), st = x.status || 'not_issued'; return `<tr><td><b>${UmrahCore_esc(t.nameAr || t.no)}</b><div class="muted">${UmrahCore_esc(t.no)}</div></td><td>${UmrahCore_esc(t.passportNo || '-')}</td><td>${UmrahCore_esc(seg?.title || '-')}<div class="muted">${UmrahCore_esc(seg?.route || '')} • ${seg?.start || ''}</div></td><td>${UmrahCore_esc(x.pnr || '-')}</td><td>${UmrahCore_esc(x.ticketNo || '-')}</td><td>${UmrahCore_esc(x.seat || '-')}<div class="muted">${UmrahCore_esc(x.baggage || '-')}</div></td><td><span class="badge ${['issued', 'reissued'].includes(st) ? 'green' : st === 'cancelled' ? 'red' : 'gray'}">${UmrahCore_ticketStatusLabel(st)}</span></td><td><button class="btn small primary" data-umrah-form-call="ticket" data-umrah-form-id="${UmrahCore_esc(t.id)}" data-umrah-form-extra="${sid}">${x.id ? 'تعديل' : 'إدخال'}</button></td></tr>`; }); return `${UmrahCore_UI.head('الطيران والتذاكر', 'كل قطاع طيران مستقل؛ لا تختلط تذكرة الذهاب بالعودة.', `${UmrahCore_selectProgram('flightSelect', p.id, 'flightProgram', 'flightSegment')}`)}<div class="service-leg-tabs">${segs.map(s => `<button class="btn small ${s.id === sid ? 'primary' : 'ghost'}" data-umrah-state-key="flightSegment" data-umrah-state-id="${UmrahCore_esc(s.id)}" data-umrah-state-render="1">${UmrahCore_esc(s.title)}<small>${UmrahCore_esc(s.route || '')} • ${s.start}</small></button>`).join('')}</div>${UmrahCore_UI.table(['المسافر', 'الجواز', 'القطاع', 'PNR', 'التذكرة', 'المقعد/الأمتعة', 'الحالة', 'إجراء'], rows, 'لا يوجد مسافرون نشطون في البرنامج')}`; },
    transport() { const ps = UmrahCore_Ops.scoped('programs').filter(p => UmrahCore_Ops.segments(p.id, 'transport').length), pid = UmrahCore_State.busProgram || ps[0]?.id || ''; if (pid && !ps.some(p => p.id === pid)) {
        UmrahCore_State.busProgram = ps[0]?.id || '';
        UmrahCore_State.busSegment = '';
    } const p = UmrahCore_Ops.program(UmrahCore_State.busProgram || pid); if (!p)
        return UmrahCore_UI.head('النقل والمركبات', 'كل قطاع نقل مستقل') + '<div class="card empty">لا توجد قطاعات نقل في البرامج.</div>'; const segs = UmrahCore_Ops.segments(p.id, 'transport'), sid = UmrahCore_State.busSegment && segs.some(s => s.id === UmrahCore_State.busSegment) ? UmrahCore_State.busSegment : segs[0]?.id || '', seg = segs.find(s => s.id === sid), runs = UmrahCore_Ops.scoped('busRuns').filter(x => x.programId === p.id && x.segmentId === sid && x.active !== false); return `${UmrahCore_UI.head('النقل والمركبات', 'إنشاء المركبات وتوزيع المسافرين لكل قطاع نقل بشكل مستقل.', `${UmrahCore_selectProgram('busSelect', p.id, 'busProgram', 'busSegment')}`)}<div class="service-leg-tabs">${segs.map(s => `<button class="btn small ${s.id === sid ? 'primary' : 'ghost'}" data-umrah-state-key="busSegment" data-umrah-state-id="${UmrahCore_esc(s.id)}" data-umrah-state-render="1">${UmrahCore_esc(s.title)}<small>${UmrahCore_esc(s.route || '')} • ${s.start}</small></button>`).join('')}</div><div class="section-head"><div><h2>${UmrahCore_esc(seg?.title || 'قطاع النقل')}</h2><p>${UmrahCore_esc(seg?.route || '')} • ${seg?.start || ''}${seg?.end && seg.end !== seg.start ? ' → ' + seg.end : ''}</p></div><div class="quick-actions"><button class="btn primary" data-umrah-form-call="busRun" data-umrah-form-id="${UmrahCore_esc(p.id)}" data-umrah-form-extra="${sid}">+ مركبة/رحلة</button>${runs.length ? `<button class="btn ghost" data-umrah-auto-buses="${UmrahCore_esc(p.id)}" data-umrah-segment-id="${sid}">توزيع تلقائي</button>` : ''}</div></div><div class="grid three">${runs.map(r => `<div class="card"><div class="section-head"><div><h2>${r.no}</h2><p>${r.date} • ${UmrahCore_esc(r.route || '-')}</p></div><span class="badge ${(r.travelerIds || []).length >= r.capacity ? 'orange' : 'green'}">${(r.travelerIds || []).length}/${r.capacity}</span></div><div class="info-row"><div><b>المركبة</b></div><span>${UmrahCore_esc(r.vehicleNo || '-')}</span></div><div class="info-row"><div><b>السائق</b><small>${UmrahCore_esc(r.driverPhone || '')}</small></div><span>${UmrahCore_esc(r.driver || '-')}</span></div><div class="quick-actions mt-8"><button class="btn small ghost" data-umrah-print="bus" data-umrah-print-id="${UmrahCore_esc(r.id)}">كشف التشغيل</button><button class="btn small soft" data-umrah-bus-overview="${UmrahCore_esc(r.id)}">المسافرون</button>${UmrahCore_Bridge.can('umrah.transport','delete')?DeleteCenter.button('busRun',r.id):''}</div></div>`).join('') || '<div class="card empty">لم يتم إنشاء مركبات لهذا القطاع بعد.</div>'}</div>`; }
};
export { UmrahCore_PagesResources };
