import { N, byId, esc, formatDate, icon, live, money, toast, today } from '../core/runtime';
import { AdvancedAccounting } from '../accounting/advanced';
import { AdvancedActionsCommands, AdvancedActionsQueries } from '../application/advanced-actions-workflows';
import { Invoices } from '../accounting/invoices';
import { UI } from './ui';
import { Forms } from './forms';
import { composeAdvancedActionsDeps } from '../core/late-bindings';
const advDeps = () => composeAdvancedActionsDeps();
const ActionsDocument: any = document;
const ActionsAdvanced = {
    advancedForm(title,subtitle,body,onSubmit,label='حفظ'){const m=ActionsDocument.getElementById('modal'),f=ActionsDocument.getElementById('modalForm');ActionsDocument.getElementById('modalTitle').textContent=title;ActionsDocument.getElementById('modalSubtitle').textContent=subtitle||'';ActionsDocument.getElementById('modalIcon').innerHTML=icon('journal');UI.resetModalFooter(label);ActionsDocument.getElementById('modalBody').innerHTML=body;m.classList.add('show');f.noValidate=true;f.onsubmit=e=>{e.preventDefault();Forms.submitOnce(f,async()=>{try{Forms.validateForm(f);const o=Object.fromEntries(new FormData(f));await AdvancedActionsCommands.submitForm(advDeps(),()=>onSubmit(o));UI.closeModal(true);UI.renderCurrent();toast('تمت العملية بنجاح')}catch(err){toast(err.message||'تعذر تنفيذ العملية','error')}})}},
 reverseAdvancedSettlement(kind,id){UI.confirmAction('عكس التسوية','سيتم إنشاء قيد عكسي مع الاحتفاظ بالتسوية وسجل التدقيق.',()=>{const reason=prompt('سبب العكس:')||'';AdvancedActionsCommands.reverseSettlement(advDeps(),kind,id,reason);UI.renderCurrent();toast('تم عكس التسوية')},{label:'عكس التسوية'})},
 openDeferredSchedule(id){const x=byId(AdvancedActionsQueries.collection(advDeps(),'deferredRevenueSchedules'),id),inv=x&&byId(AdvancedActionsQueries.collection(advDeps(),'invoices'),x.invoiceId);if(!x)return toast('الجدول غير موجود','error');const m=ActionsDocument.getElementById('modal'),f=ActionsDocument.getElementById('modalForm');ActionsDocument.getElementById('modalTitle').textContent=`جدول الإيراد المؤجل — ${inv?.no||x.no}`;ActionsDocument.getElementById('modalSubtitle').textContent='كل دفعة تُرحل في تاريخ استحقاقها، ويمكن عكس الدفعة المرحّلة بقيد عكسي.';ActionsDocument.getElementById('modalIcon').innerHTML=icon('clock');UI.resetModalFooter('',{hideSubmit:true,cancel:'إغلاق'});ActionsDocument.getElementById('modalBody').innerHTML=`<div class="card"><div class="mini-row"><span>إجمالي الإيراد المؤجل</span><b>${money(x.total,x.currency)}</b></div><div class="mini-row"><span>بداية الاعتراف</span><b>${formatDate(x.recognitionDate)}</b></div></div><div class="mt-16">${UI.table(['التاريخ','القيمة','الحالة','إجراء'],(x.parts||[]).map(p=>`<tr><td>${formatDate(p.date)}</td><td>${money(p.amount,x.currency)}</td><td>${UI.badge(p.status)}</td><td>${p.status==='pending'?`<button type="button" class="btn small success" data-action-panel="recognizeDeferred" data-action-id="${esc(x.id)}" data-action-parent="${esc(p.id)}">ترحيل الاستحقاق</button>`:`<button type="button" class="btn small danger" data-action-panel="reverseDeferred" data-action-id="${esc(x.id)}" data-action-parent="${esc(p.id)}">عكس</button>`}</td></tr>`),'لا توجد دفعات')}</div>`;m.classList.add('show');f.onsubmit=e=>e.preventDefault()},
 recognizeDeferred(id,partId){try{AdvancedActionsCommands.recognizeDeferred(advDeps(),id,partId);UI.closeModal(true);UI.renderCurrent();toast('تم إثبات الإيراد المستحق')}catch(e){toast(e.message,'error')}},
 reverseDeferred(id,partId){UI.confirmAction('عكس الاعتراف بالإيراد','سيتم عكس قيد الاعتراف وإعادة الدفعة إلى حالة معلقة.',()=>{const reason=prompt('سبب العكس:')||'';AdvancedActionsCommands.reverseDeferred(advDeps(),id,partId,reason);UI.renderCurrent();toast('تم العكس')},{label:'عكس القيد'})},
 settleAccruedRevenue(id){const x=byId(AdvancedActionsQueries.collection(advDeps(),'accruedRevenues'),id),items=AdvancedActionsQueries.collection(advDeps(),'invoices').filter(v=>live(v)&&v.kind==='customer'&&v.status!=='draft').map(v=>`<option value="${esc(v.id)}">${esc(v.no)} — ${esc(this.partyName(v.partyType||'customer',v.partyId))} — ${money(Invoices.subtotal(v),v.currency)}</option>`).join('');if(!x)return;this.advancedForm('تسوية الإيراد المستحق','اختر الفاتورة التي تم إصدارها مقابل الإيراد المثبت سابقًا.',`<div class="field"><label>فاتورة المبيعات</label><select name="invoiceId" required><option value="">اختر...</option>${items}</select></div>`,o=>AdvancedAccounting.settleAccruedRevenue(id,o.invoiceId),'تسوية')},
 openDeferredCostSchedule(id){const x=byId(AdvancedActionsQueries.collection(advDeps(),'deferredCostSchedules'),id),inv=x&&byId(AdvancedActionsQueries.collection(advDeps(),'invoices'),x.invoiceId);if(!x)return toast('الجدول غير موجود','error');const m=ActionsDocument.getElementById('modal'),f=ActionsDocument.getElementById('modalForm');ActionsDocument.getElementById('modalTitle').textContent=`جدول التكلفة المؤجلة — ${inv?.no||x.no}`;ActionsDocument.getElementById('modalSubtitle').textContent='تُحمّل كل دفعة على تكلفة البرنامج في تاريخ تنفيذها.';ActionsDocument.getElementById('modalIcon').innerHTML=icon('clock');UI.resetModalFooter('',{hideSubmit:true,cancel:'إغلاق'});ActionsDocument.getElementById('modalBody').innerHTML=`${UI.table(['التاريخ','القيمة','الحالة','إجراء'],(x.parts||[]).map(p=>`<tr><td>${formatDate(p.date)}</td><td>${money(p.amount,x.currency)}</td><td>${UI.badge(p.status)}</td><td>${p.status==='pending'?`<button type="button" class="btn small success" data-action-panel="recognizeDeferredCost" data-action-id="${esc(x.id)}" data-action-parent="${esc(p.id)}">تحميل التكلفة</button>`:`<button type="button" class="btn small danger" data-action-panel="reverseDeferredCost" data-action-id="${esc(x.id)}" data-action-parent="${esc(p.id)}">عكس</button>`}</td></tr>`),'لا توجد دفعات')}`;m.classList.add('show');f.onsubmit=e=>e.preventDefault()},
 recognizeDeferredCost(id,partId){try{AdvancedActionsCommands.recognizeDeferredCost(advDeps(),id,partId);UI.closeModal(true);UI.renderCurrent();toast('تم تحميل التكلفة على البرنامج')}catch(e){toast(e.message,'error')}},
 reverseDeferredCost(id,partId){UI.confirmAction('عكس تحميل التكلفة','سيتم عكس قيد التحميل وإعادة الدفعة إلى معلقة.',()=>{const reason=prompt('سبب العكس:')||'';AdvancedActionsCommands.reverseDeferredCost(advDeps(),id,partId,reason);UI.renderCurrent();toast('تم العكس')},{label:'عكس القيد'})},
 depreciateAsset(id){const x=byId(AdvancedActionsQueries.collection(advDeps(),'fixedAssets'),id);if(!x)return;this.advancedForm(`إهلاك — ${x.name}`,'سيتم إثبات قسط إهلاك شهري وفق العمر والقيمة التخريدية للأصل.',`<div class="field"><label>تاريخ الإهلاك</label><input name="date" type="date" value="${today()}" required></div>`,o=>AdvancedAccounting.depreciateAsset(id,o.date),'إثبات الإهلاك')},
 disposeAsset(id){const x=byId(AdvancedActionsQueries.collection(advDeps(),'fixedAssets'),id),trs=AdvancedActionsQueries.collection(advDeps(),'treasuries').filter(t=>t.active!==false).map(t=>`<option value="${esc(t.id)}">${esc(t.name)} — ${t.currency}</option>`).join('');if(!x)return;this.advancedForm(`استبعاد أصل — ${x.name}`,'أدخل حصيلة البيع إن وجدت؛ سيحسب النظام ربح أو خسارة الاستبعاد تلقائيًا.',`<div class="form-grid"><div class="field"><label>التاريخ</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>حصيلة البيع</label><input name="proceeds" type="number" min="0" step="0.01" value="0" required></div><div class="field"><label>الخزنة / البنك عند وجود حصيلة</label><select name="treasuryId"><option value="">بدون حصيلة</option>${trs}</select></div></div>`,o=>AdvancedAccounting.disposeAsset(id,o),'استبعاد الأصل')},
 payLoanInstallment(id){const s=byId(AdvancedActionsQueries.collection(advDeps(),'loanSchedules'),id),loan=s&&byId(AdvancedActionsQueries.collection(advDeps(),'loans'),s.loanId),trs=AdvancedActionsQueries.collection(advDeps(),'treasuries').filter(t=>t.active!==false).map(t=>`<option value="${esc(t.id)}" ${t.id===loan?.treasuryId?'selected':''}>${esc(t.name)} — ${t.currency}</option>`).join('');if(!s||!loan)return;this.advancedForm(`سداد قسط ${loan.no}`,'القسط مقسّم تلقائيًا بين أصل التمويل والفائدة.',`<div class="form-grid"><div class="field"><label>التاريخ</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>القيمة</label><input value="${money(s.total,s.currency)}" readonly></div><div class="field"><label>الخزنة / البنك</label><select name="treasuryId" required>${trs}</select></div></div>`,o=>AdvancedAccounting.payLoanInstallment(id,o),'سداد القسط')},
 payPayroll(id){const x=byId(AdvancedActionsQueries.collection(advDeps(),'payrollRuns'),id),trs=AdvancedActionsQueries.collection(advDeps(),'treasuries').filter(t=>t.active!==false).map(t=>`<option value="${esc(t.id)}">${esc(t.name)} — ${t.currency}</option>`).join('');if(!x)return;this.advancedForm(`سداد رواتب — ${x.period}`,'سيتم إقفال رصيد الرواتب المستحقة مقابل الخزنة/البنك.',`<div class="form-grid"><div class="field"><label>التاريخ</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>صافي الرواتب</label><input value="${money(x.net,x.currency)}" readonly></div><div class="field"><label>الخزنة / البنك</label><select name="treasuryId" required><option value="">اختر...</option>${trs}</select></div></div>`,o=>AdvancedAccounting.payPayroll(id,o),'سداد الرواتب')},
 useProvision(id){const x=byId(AdvancedActionsQueries.collection(advDeps(),'provisions'),id),sup=AdvancedActionsQueries.collection(advDeps(),'suppliers').filter(v=>v.active!==false).map(v=>`<option value="${esc(v.id)}">${esc(v.no)} — ${esc(v.name)}</option>`).join(''),acc=AdvancedActionsQueries.collection(advDeps(),'accounts').filter(a=>a.posting!==false&&a.active!==false&&!a.control).map(a=>`<option value="${esc(a.id)}">${a.id} — ${esc(a.name)}</option>`).join('');if(!x)return;this.advancedForm(`استخدام مخصص — ${x.name}`,'حمّل المبلغ على مورد مستحق أو حساب أستاذ مناسب.',`<div class="form-grid"><div class="field"><label>التاريخ</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>القيمة</label><input name="amount" type="number" min="0.01" step="0.01" max="${Math.max(0,N(x.amount)-N(x.used))}" required></div><div class="field"><label>الطرف المقابل</label><select name="accountId" required><option value="2100">مورد مستحق</option>${acc}</select></div><div class="field"><label>المورد عند اختيار مورد مستحق</label><select name="supplierId"><option value="">اختر...</option>${sup}</select></div></div>`,o=>AdvancedAccounting.useProvision(id,o),'استخدام المخصص')},
 reconcileImportedBank(treasuryId){try{AdvancedActionsCommands.reconcileImportedBank(advDeps(),treasuryId,r=>{toast(`تمت مطابقة ${r.matched} حركة، والمتبقي ${r.unmatched}`)});UI.renderCurrent()}catch(e){toast(e.message,'error')}}
};
export { ActionsAdvanced };
