import { S, esc, icon, toast, today } from '../core/runtime';
import { DocumentWorkflows } from '../application/document-actions';
import { DB } from '../persistence/browser-store';
import { Currency, Periods } from '../accounting/currency-periods';
import { Accounting } from '../accounting/engine';
import { Tax } from '../accounting/invoices';
import { Transactions } from '../accounting/transactions';
import { Auth } from '../security/auth';
import { UI } from './ui';
import { composeLegacyActionDeps } from '../core/late-bindings';
import { AccessControl } from '../security/access-control';
const ActionsDocument: any = document;
const ActionsFinance = {
    depositCheque(id){try{AccessControl.require('treasury','approve');const banks=DB.data.treasuries.filter(t=>t.active!==false&&t.type==='bank');if(!banks.length)throw new Error('أنشئ حسابًا بنكيًا أولًا');const m=ActionsDocument.getElementById('modal'),f=ActionsDocument.getElementById('modalForm');ActionsDocument.getElementById('modalTitle').textContent='إيداع الشيك الوارد';ActionsDocument.getElementById('modalSubtitle').textContent='الإيداع يغيّر حالة الشيك فقط؛ الأثر النقدي يثبت عند التحصيل الفعلي.';ActionsDocument.getElementById('modalIcon').innerHTML=icon('treasury');ActionsDocument.getElementById('modalSubmitText').textContent='تسجيل الإيداع';ActionsDocument.getElementById('modalBody').innerHTML=`<div class="field"><label>الحساب البنكي</label><select name="bankId" required>${banks.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} — ${esc(t.currency)}</option>`).join('')}</select></div>`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();try{const tid=new FormData(f).get('bankId');DB.atomic('depositCheque',()=>Transactions.depositCheque(id,tid));UI.closeModal(true);toast('تم تسجيل إيداع الشيك')}catch(err){toast(err.message,'error')}}}catch(e){toast(e.message,'error')}},
  clearCheque(id){try{AccessControl.require('treasury','approve');const banks=DB.data.treasuries.filter(t=>t.active!==false&&t.type==='bank');if(!banks.length)throw new Error('أنشئ حسابًا بنكيًا أولًا');const m=ActionsDocument.getElementById('modal'),f=ActionsDocument.getElementById('modalForm');ActionsDocument.getElementById('modalTitle').textContent='تحصيل الشيك';ActionsDocument.getElementById('modalSubtitle').textContent='اختر الحساب البنكي الذي تم التحصيل عليه.';ActionsDocument.getElementById('modalIcon').innerHTML=icon('treasury');ActionsDocument.getElementById('modalSubmitText').textContent='تحصيل';ActionsDocument.getElementById('modalBody').innerHTML=`<div class="field"><label>الحساب البنكي</label><select name="bankId" required>${banks.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} — ${esc(t.currency)}</option>`).join('')}</select></div>`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();try{const tid=new FormData(f).get('bankId');DB.atomic('clearCheque',()=>Transactions.clearCheque(id,tid));UI.closeModal(true);toast('تم تحديث الشيك')}catch(err){toast(err.message,'error')}}}catch(e){toast(e.message,'error')}},bounceCheque(id){try{const execute=DocumentWorkflows.prepareBounceCheque(composeLegacyActionDeps(),id);UI.reasonAction('ارتداد أو إلغاء الشيك','اكتب السبب.',r=>{execute(r);toast('تم عكس الشيك')})}catch(e){toast(e.message,'error')}},
 async liveRate(code){try{AccessControl.require('currencies','edit');await DB.atomicAsync('liveRate',()=>Currency.fetchLive(code));toast(`تم تحديث ${code}`)}catch(e){toast(e.message,'error')}},toggleCurrency(code){try{const execute=DocumentWorkflows.prepareToggleCurrency(composeLegacyActionDeps(),code);execute();toast('تم تحديث حالة العملة')}catch(e){toast(e.message,'error')}},removeCurrency(code){try{const execute=DocumentWorkflows.prepareRemoveCurrency(composeLegacyActionDeps(),code);UI.confirmAction('حذف العملة','لن يتم الحذف إذا كانت العملة مستخدمة تاريخيًا.',()=>{execute();toast('تم حذف العملة')})}catch(e){toast(e.message,'error')}},fxRevalue(){try{AccessControl.require('currencies','approve');const m=ActionsDocument.getElementById('modal'),f=ActionsDocument.getElementById('modalForm');ActionsDocument.getElementById('modalTitle').textContent='إعادة تقييم العملات';ActionsDocument.getElementById('modalSubtitle').textContent='حدد تاريخ التقييم، ويفضل تاريخ نهاية الفترة.';ActionsDocument.getElementById('modalIcon').innerHTML=icon('currencies');ActionsDocument.getElementById('modalSubmitText').textContent='ترحيل';ActionsDocument.getElementById('modalBody').innerHTML=`<div class="field"><label>التاريخ</label><input name="date" type="date" value="${today()}" required></div>`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();try{const d=S(new FormData(f).get('date')||'');DB.atomic('fxRevalue',()=>Accounting.fxRevalue(d));UI.closeModal(true);toast('تم ترحيل إعادة تقييم العملات')}catch(err){toast(err.message,'error')}}}catch(e){toast(e.message,'error')}},
 postManualJournal(id){try{const execute=DocumentWorkflows.preparePostManualJournal(composeLegacyActionDeps(),id);execute();toast('تم ترحيل القيد')}catch(e){toast(e.message,'error')}},removeManualJournal(id){try{const execute=DocumentWorkflows.prepareRemoveManualJournal(composeLegacyActionDeps(),id);UI.confirmAction('حذف مسودة القيد','سيتم حذف المسودة غير المرحلة فقط.',()=>{execute();toast('تم حذف المسودة')})}catch(e){toast(e.message,'error')}},reverseManualJournal(id){try{const execute=DocumentWorkflows.prepareReverseManualJournal(composeLegacyActionDeps(),id);UI.reasonAction('عكس القيد','اكتب سبب عكس القيد.',r=>{execute(r);toast('تم عكس القيد')})}catch(e){toast(e.message,'error')}},runRecurringJournal(id){try{const execute=DocumentWorkflows.prepareRunRecurringJournal(composeLegacyActionDeps(),id);execute();toast('تم إنشاء مسودة من القالب')}catch(e){toast(e.message,'error')}},toggleRecurringJournal(id){try{const execute=DocumentWorkflows.prepareToggleRecurringJournal(composeLegacyActionDeps(),id);execute();toast('تم تحديث القالب')}catch(e){toast(e.message,'error')}},removeRecurringJournal(id){try{const execute=DocumentWorkflows.prepareRemoveRecurringJournal(composeLegacyActionDeps(),id);UI.confirmAction('حذف قالب القيد المتكرر','سيتم حذف القالب فقط دون التأثير على القيود التي سبق إنشاؤها.',()=>{execute();toast('تم حذف القالب')})}catch(e){toast(e.message,'error')}},
 toggleAccount(id){try{const execute=DocumentWorkflows.prepareToggleAccount(composeLegacyActionDeps(),id);execute();toast('تم تحديث الحساب')}catch(e){toast(e.message,'error')}},removeAccount(id){try{const execute=DocumentWorkflows.prepareRemoveAccount(composeLegacyActionDeps(),id);UI.confirmAction('حذف الحساب','لن يسمح النظام بالحذف إذا كان الحساب مستخدمًا.',()=>{execute();toast('تم حذف الحساب')})}catch(e){toast(e.message,'error')}},removeCostCenter(id){try{const execute=DocumentWorkflows.prepareRemoveCostCenter(composeLegacyActionDeps(),id);execute();toast('تم الحذف')}catch(e){toast(e.message,'error')}},toggleTax(id){try{AccessControl.require('taxes','edit');DB.atomic('toggleTax',()=>Tax.toggle(id));toast('تم تحديث الضريبة')}catch(e){toast(e.message,'error')}},removeTax(id){try{AccessControl.require('taxes','delete');DB.atomic('removeTax',()=>Tax.remove(id));toast('تم حذف الكود')}catch(e){toast(e.message,'error')}},
 monthEndChecklist(id){try{AccessControl.require('periods','view');const c=Periods.preCloseChecklist(id),html=[...c.blockers.map(x=>`<div class="danger-note mb-8">${esc(x)}</div>`),...c.warnings.map(x=>`<div class="warn-note mb-8">${esc(x)}</div>`)].join('')||'<div class="ok-note">الفترة جاهزة للإغلاق.</div>';const m=ActionsDocument.getElementById('modal'),f=ActionsDocument.getElementById('modalForm');ActionsDocument.getElementById('modalTitle').textContent=`فحص إقفال ${c.period.month}/${c.period.year}`;ActionsDocument.getElementById('modalSubtitle').textContent=c.ok?'لا توجد موانع حرجة.':'عالج الموانع الحمراء أولًا.';ActionsDocument.getElementById('modalIcon').innerHTML=icon(c.ok?'check':'warning');ActionsDocument.getElementById('modalSubmitText').textContent='إغلاق';ActionsDocument.getElementById('modalBody').innerHTML=html;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)}}catch(e){toast(e.message,'error')}},closePeriod(id){try{AccessControl.require('periods','edit');const c=Periods.preCloseChecklist(id);if(!c.ok)return this.monthEndChecklist(id);UI.confirmAction('إغلاق الفترة',`الفترة ${c.period.month}/${c.period.year} اجتازت فحص الإقفال.`,()=>{DB.atomic('closePeriod',()=>Periods.closePeriod(id));toast('تم إغلاق الفترة')})}catch(e){toast(e.message,'error')}},reopenPeriod(id){try{AccessControl.require('periods','edit');UI.reasonAction('إعادة فتح الفترة','اكتب سبب إعادة الفتح.',r=>{DB.atomic('reopenPeriod',()=>Periods.reopenPeriod(id,r));toast('تمت إعادة الفتح')})}catch(e){toast(e.message,'error')}},closeYear(id){try{AccessControl.require('periods','approve');UI.confirmAction('إقفال السنة المالية','يجب أن تكون جميع الفترات مغلقة. سيقوم النظام بإنشاء قيد الإقفال وفق القواعد الحالية.',()=>{DB.atomic('closeYear',()=>Periods.closeYear(id));toast('تم إقفال السنة')})}catch(e){toast(e.message,'error')}},reopenYear(id){try{AccessControl.require('periods','approve');UI.reasonAction('إعادة فتح السنة المالية','هذا إجراء رقابي حساس. اكتب السبب.',r=>{DB.atomic('reopenYear',()=>Periods.reopenYear(id,r));toast('تمت إعادة فتح السنة')})}catch(e){toast(e.message,'error')}}
};
export { ActionsFinance };
