import { S, esc, formatDateTime, icon, toast } from '../core/runtime';
import { UI } from './ui';
import type { ServerAuditPresentationEntry } from '../application/contracts';
const ArchiveViewer={
 open(data,meta:any={}){const m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement,collections=['invoices','receipts','payments','journals','bookings','umrahBookings','customers','suppliers','attachments'],collectionLabels={invoices:'الفواتير',receipts:'سندات القبض',payments:'سندات الصرف',journals:'القيود',bookings:'الحجوزات',umrahBookings:'حجوزات الحج والعمرة',customers:'العملاء',suppliers:'الموردون',attachments:'المرفقات'};document.getElementById('modalTitle').textContent=meta.label||`أرشيف ${String(meta.archiveThrough||data?.meta?.archivePeriodEnd||'').slice(0,4)}`;document.getElementById('modalSubtitle').textContent='للقراءة فقط — للبحث والعرض والطباعة، ولا يغيّر بيانات الفترة الحالية.';document.getElementById('modalIcon').innerHTML=icon('archive');document.getElementById('modalSubmitText').textContent='إغلاق';const cards=collections.filter(k=>Array.isArray(data?.[k])&&data[k].length).map(k=>`<details class="card mt-12"><summary><b>${esc(collectionLabels[k]||k)}</b> — ${data[k].length}</summary><div class="archive-search-list mt-12">${data[k].slice(0,500).map(x=>`<div class="mini-row archive-row"><span>${esc(x.no||x.name||x.title||x.id||'-')}</span><small>${esc([x.date,x.status,x.amount,x.total].filter(v=>v!==undefined&&v!=='').join(' • '))}</small></div>`).join('')}</div></details>`).join('');document.getElementById('modalBody').innerHTML=`<div class="ok-note"><b>سلامة الأرشيف:</b> ${meta.integrity==='failed'?'فشل التحقق ❌':'سليم ✅'} ${meta.checksum?`<small>${esc(String(meta.checksum).slice(0,18))}…</small>`:''}</div><div class="quick-actions mt-12"><input id="archiveSearch" placeholder="بحث داخل الأرشيف" data-archive-filter="1"><button type="button" class="btn ghost" data-window-print="1">طباعة</button></div>${cards||'<div class="empty-state">لا توجد سجلات للعرض</div>'}`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)}}
};
const CommercialActionViews={
 activityRangeChanged(){UI.openPage('activity','',{skipHistory:true,keepWorkspace:true})},
 activityCleaned(){toast('تم تنظيف سجل النشاط');this.activityRangeChanged()},
 serverAudit(entries:ServerAuditPresentationEntry[]){const m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement,actionLabels={setup:'إعداد النظام','setup-after-reset':'إعداد النظام بعد إعادة التهيئة','state-write':'حفظ تغييرات النظام','whatsapp-send':'إرسال رسالة واتساب','vendor-entitlement':'تحديث ترخيص الشركة','reset-existing-login':'استعادة دخول المدير','vendor-force-password-change':'إجبار تغيير كلمة المرور','login':'تسجيل دخول','logout':'تسجيل خروج','backup-create':'إنشاء نسخة احتياطية','backup-restore':'استعادة نسخة احتياطية','archive-close':'إغلاق وأرشفة فترة'},rows=entries.map(x=>`<tr><td>${formatDateTime(x.created_at)}</td><td>${esc(x.userName)}</td><td>${esc(actionLabels[x.action]||'إجراء نظام')}</td><td>${esc(x.ip_address||'-')}</td><td>${esc(S(x.user_agent||'').slice(0,55))}</td><td>${esc(JSON.stringify(x.changes||[]).slice(0,180))}</td></tr>`);document.getElementById('modalTitle').textContent='سجل الخادم المحمي';document.getElementById('modalSubtitle').textContent='سجل خادمي للأحداث التشغيلية؛ تنظيفه لا يؤثر على القيود أو المستندات.';document.getElementById('modalIcon').innerHTML=icon('audit');document.getElementById('modalSubmitText').textContent='إغلاق';document.getElementById('modalBody').innerHTML=UI.table(['التاريخ','المستخدم','الإجراء','عنوان الشبكة','الجهاز','التغييرات'],rows,'لا توجد أحداث',{export:false});m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)} }
};
export { ArchiveViewer, CommercialActionViews };
