import { APP, S, esc, icon, now } from '../core/runtime';
import { ServerStore } from '../persistence/server-store';
import { DB } from '../persistence/browser-store';
import { Commercial } from '../commercial/product';
import { Auth } from '../security/auth';
import { UI } from './ui';
import { Pages } from './pages';
import { __set_CommercialUX } from '../core/late-bindings';
import { AccessControl } from '../security/access-control';
import { UI_MenusSearch } from './ui-menus-search';
/* Commercial UX layer: shared safeguards and presentation rules for every module. */
const CommercialUX={
 dirtyForm:null,saveTimer:0,saveDelay:0,saveSequence:0,saveVisible:false,notificationFilter:'all',
 training:new URLSearchParams(location.search).get('training')==='1',
 initTraining(){if(!this.training)return;APP.storage+='_training';APP.session+='_training';APP.dataDb+='_training';APP.filesDb+='_training';ServerStore.available=false;ServerStore.authenticated=false;ServerStore.probe=async()=>false;ServerStore.get=async()=>({available:false,data:null});ServerStore.put=async()=>false;ServerStore.clear=async()=>false;document.documentElement.dataset.training='1'},
 ensureSaveIndicator(){let e=document.getElementById('saveStatus');if(e){e.classList.remove('hidden');return e;}const top=document.querySelector('.top-actions');if(!top)return null;e=document.createElement('div');e.id='saveStatus';e.className='save-status saved';e.setAttribute('role','status');e.setAttribute('aria-live','polite');e.innerHTML=`${icon('check','sm')}<span>محفوظ</span>`;top.prepend(e);return e},
 saveState(state,message=''){const e=this.ensureSaveIndicator();if(!e)return;clearTimeout(this.saveTimer);e.className=`save-status ${state}`;const labels={saving:'جارٍ الحفظ…',saved:'محفوظ',warning:'بانتظار المزامنة',error:'تعذر الحفظ'};e.innerHTML=`${icon(state==='error'||state==='warning'?'warning':state==='saving'?'clock':'check','sm')}<span>${esc(message||labels[state]||'')}</span>`},
 beginSave(){const token=++this.saveSequence;clearTimeout(this.saveDelay);this.saveVisible=false;this.saveDelay=setTimeout(()=>{if(token!==this.saveSequence)return;this.saveVisible=true;this.saveState('saving')},900);return token},
 finishSave(token,result,error=null){if(token!==this.saveSequence)return;clearTimeout(this.saveDelay);if(error){this.saveState('error',error?.message||DB.lastSaveError||'تعذر الحفظ');return}if(result?.serverAvailable&&!result?.server){if(ServerStore.lastConflict)this.saveState('error',DB.lastSaveError||'يوجد تعارض يحتاج مراجعة');else this.saveState('warning','تعذر الاتصال مؤقتًا — ستتم إعادة المحاولة تلقائيًا عند عودة الاتصال');return}const e=document.getElementById('saveStatus');if(this.saveVisible||e?.classList.contains('warning')||e?.classList.contains('error'))this.saveState('saved');this.saveVisible=false},
 enhance(root:Document|Element=document){this.ensureSaveIndicator();this.enhanceActions(root);this.enhanceStates(root);this.enhanceSections(root);this.enhanceEmptyStates(root);this.enhanceForms(root);this.enhanceAccessibility(root);if(this.training)this.trainingBanner()},
 enhanceActions(root){for(const cell of root.querySelectorAll('td.compact-action:not([data-actions-ready])')){cell.dataset.actionsReady='1';const buttons=[...cell.querySelectorAll(':scope > button,:scope > a')];if(buttons.length<=3)continue;const keep=buttons.find(b=>b.classList.contains('primary'))||buttons[0],menu=document.createElement('details');menu.className='action-menu';const summary=document.createElement('summary');summary.className='btn small ghost';summary.innerHTML=`${icon('menu','sm')} المزيد`;menu.append(summary);for(const b of buttons)if(b!==keep)menu.append(b);let anchor=null;summary.addEventListener('pointerdown',()=>{anchor=summary.getBoundingClientRect()});menu.addEventListener('toggle',()=>{if(!menu.open)return;document.querySelectorAll('details.action-menu[open]').forEach(x=>{if(x!==menu)(x as HTMLDetailsElement).open=false});const r=anchor||summary.getBoundingClientRect(),w=184,h=Math.min(420,menu.scrollHeight||320),left=Math.max(8,Math.min(innerWidth-w-8,r.right-w)),top=Math.max(8,Math.min(innerHeight-h-8,r.bottom+5));menu.style.setProperty('--action-left',`${left}px`);menu.style.setProperty('--action-top',`${top}px`)});cell.append(menu)}},
 enhanceStates(root){for(const row of root.querySelectorAll('tbody tr')){const badge=row.querySelector('.badge');if(!badge)continue;const state=['gray','green','red','orange','blue'].find(s=>badge.classList.contains(s));if(!state)continue;const wanted=`row-state-${state}`;if(!row.classList.contains(wanted)){for(const s of['gray','green','red','orange','blue']){const cls=`row-state-${s}`;if(cls!==wanted&&row.classList.contains(cls))row.classList.remove(cls)}row.classList.add(wanted)}}for(const form of root.querySelectorAll('form')){const mode=form.querySelector('[name="saveMode"],[name="status"]');if(!mode||form.querySelector('.document-mode-note'))continue;const note=document.createElement('div'),field=mode.closest('.field'),draft=[...mode.options].find(o=>o.value==='draft'),posted=[...mode.options].find(o=>['posted','confirmed'].includes(o.value));note.className='document-mode-note';const update=()=>{const isPosted=['posted','confirmed'].includes(mode.value);note.className=`document-mode-note ${isPosted?'posted':'draft'}`;note.innerHTML=isPosted?`${icon('lock','sm')} <b>تأكيد وترحيل:</b> سينشأ أثر مالي وقد تصبح بعض البيانات للقراءة فقط.`:`${icon('edit','sm')} <b>مسودة:</b> قابلة للتعديل ولا تنشئ التزامًا ماليًا.`;field?.querySelectorAll('.mode-choice button').forEach(b=>b.classList.toggle('active',b.dataset.value===mode.value))};mode.closest('.form-grid')?.insertAdjacentElement('afterend',note);if(field&&draft&&posted){mode.classList.add('visually-hidden-select');const choices=document.createElement('div');choices.className='mode-choice';choices.innerHTML=`<button type="button" class="btn small ghost" data-value="${esc(draft.value)}">${icon('edit','sm')} حفظ مسودة</button><button type="button" class="btn small primary" data-value="${esc(posted.value)}">${icon('check','sm')} تأكيد وترحيل</button>`;choices.addEventListener('click',e=>{const b=(e.target as Element)?.closest('button');if(!b)return;mode.value=b.dataset.value;mode.dispatchEvent(new Event('change',{bubbles:true}))});field.append(choices)}mode.addEventListener('change',update);update()}},
 emptyAction(){const map={customers:['إضافة أول عميل','customer'],suppliers:['إضافة أول مورد','supplier'],crm:['إضافة عميل محتمل','lead'],quotations:['إنشاء عرض سعر','quotation'],purchaseorders:['إنشاء أمر شراء','purchaseOrder'],invoices:['إنشاء فاتورة مبيعات','customerInvoice'],receipts:['إنشاء سند قبض','receipt'],payments:['إنشاء سند صرف','payment']};return map[UI.current]||null},
 enhanceEmptyStates(root){const action=this.emptyAction();for(const empty of root.querySelectorAll('td.empty,.card.empty,.empty-state:not([data-empty-ready])')){empty.dataset.emptyReady='1';if(!empty.querySelector('.empty-icon'))empty.insertAdjacentHTML('afterbegin',`<span class="empty-icon">${icon('file')}</span>`);if(action&&!empty.closest('.modal,.quick-modal,.print-modal,[data-no-page-empty-action]')&&AccessControl.can(UI.current,'add')&&!empty.querySelector('button'))empty.insertAdjacentHTML('beforeend',`<button type="button" class="btn small primary empty-action" data-form-open="${esc(action[1])}">${icon('plus','sm')} ${esc(action[0])}</button>`)}},
 enhanceForms(root){for(const form of root.querySelectorAll('form:not([data-dirty-ready])')){form.dataset.dirtyReady='1';form.dataset.clean='1';const dirty=()=>{form.dataset.clean='0';this.dirtyForm=form};form.addEventListener('input',dirty);form.addEventListener('change',dirty);form.addEventListener('submit',()=>{form.dataset.clean='1';if(this.dirtyForm===form)this.dirtyForm=null})}},
 enhanceSections(root){for(const section of root.querySelectorAll('.line-builder:not([data-collapse-ready])')){section.dataset.collapseReady='1';const head=section.querySelector(':scope > .card-head');if(!head)continue;const b=document.createElement('button');b.type='button';b.className='btn small ghost section-collapse';b.innerHTML=`${icon('chevron','sm')} طي القسم`;b.addEventListener('click',()=>{section.classList.toggle('section-collapsed');b.innerHTML=section.classList.contains('section-collapsed')?`${icon('chevron','sm')} فتح القسم`:`${icon('chevron','sm')} طي القسم`});head.append(b)}},
 enhanceAccessibility(root){for(const b of root.querySelectorAll('button:not([aria-label])')){const text=S(b.textContent).trim();if(text)b.setAttribute('aria-label',text)}for(const input of root.querySelectorAll('input,select,textarea')){if(input.getAttribute('aria-label')||input.id&&root.querySelector(`label[for="${CSS.escape(input.id)}"]`))continue;const label=input.closest('.field')?.querySelector('label')?.textContent?.replace('*','').trim()||input.placeholder;if(label)input.setAttribute('aria-label',label)}},
 canLeave(){const f=this.dirtyForm;if(!f||f.dataset.clean==='1'||!f.isConnected)return true;const ok=confirm('توجد بيانات لم يتم حفظها. هل تريد المغادرة وفقد التعديلات؟');if(ok){f.dataset.clean='1';this.dirtyForm=null}return ok},
 trainingBanner(){if(document.getElementById('trainingBanner'))return;const b=document.createElement('div');b.id='trainingBanner';b.className='training-banner';b.innerHTML=`${icon('info','sm')} <b>وضع التدريب</b><span>بيانات معزولة على هذا الجهاز ولا تُرسل إلى قاعدة الشركة.</span><button class="btn small ghost" data-commercial-ux-action="exitTraining">الخروج</button>`;document.body.append(b)},
 enterTraining(){const u=new URL(location.href);u.searchParams.set('training','1');location.href=u.toString()},
 exitTraining(){const u=new URL(location.href);u.searchParams.delete('training');location.href=u.toString()},
 startForRole(){const role=AccessControl.currentUser()?.role,map={admin:['ابدأ بتهيئة الشركة والصلاحيات','settings'],manager:['ابدأ من مؤشرات الإدارة','reports'],accountant:['راجع القيود والمستحقات','invoices'],cashier:['ابدأ بحركة الخزنة','treasury'],sales:['ابدأ بمتابعة العملاء','crm'],auditor:['ابدأ بمركز الرقابة','audit']};return map[role]||['اختر مساحة العمل المناسبة','dashboard']},
 onboardingKey(){return `${APP.storage}_onboarding_${AccessControl.currentUser()?.id||'user'}`},
 maybeOnboard(){if(AccessControl.currentUser()?.mustChangePassword||AccessControl.currentUser()?.onboardingSeen===true)return;try{if(localStorage.getItem(this.onboardingKey())){this.markOnboarded();return}}catch(_){};setTimeout(()=>this.showOnboarding(0),450)},markOnboarded(){try{localStorage.setItem(this.onboardingKey(),'1')}catch(_){};if(AccessControl.currentUser()&&AccessControl.currentUser().onboardingSeen!==true){AccessControl.currentUser().onboardingSeen=true;AccessControl.currentUser().onboardingSeenAt=now();try{DB.save(false,{silentUi:true})}catch(_){}}},
 showOnboarding(step=0){const start=this.startForRole(),steps=[['مرحبًا بك في النظام','كل مستخدم يرى فقط المساحات والعمليات المسموحة له حسب صلاحياته.','dashboard'],['تنقل أسرع','استخدم البحث العلوي والقائمة المنظمة للوصول إلى أي سجل أو قسم.','search'],['حفظ تلقائي','التعديلات تحفظ في الخلفية، ولن يزعجك النظام برسائل حفظ متكررة. إذا حدث خطأ حقيقي سيظهر تنبيه واضح.','save'],[start[0],'يمكنك تغيير نقطة البداية في أي وقت من الصفحة الرئيسية.',start[1]]],item=steps[Math.min(step,steps.length-1)],m=document.getElementById('modal'),f=document.getElementById('modalForm');document.getElementById('modalTitle').textContent=item[0];document.getElementById('modalSubtitle').textContent=`دليل البدء • ${step+1} من ${steps.length}`;document.getElementById('modalIcon').innerHTML=icon(item[2]);document.getElementById('modalBody').innerHTML=`<div class="onboarding-step"><div class="onboarding-visual">${icon(item[2],'lg')}</div><p>${esc(item[1])}</p><div class="onboarding-dots">${steps.map((_,i)=>`<span class="${i===step?'active':''}"></span>`).join('')}</div></div>`;document.getElementById('modalSubmitText').textContent=step===steps.length-1?'ابدأ العمل':'التالي';m.dataset.onboarding='1';m.classList.add('show');f.onsubmit=e=>{e.preventDefault();if(step<steps.length-1)return this.showOnboarding(step+1);this.markOnboarded();delete m.dataset.onboarding;UI.closeModal(true);if(item[2]!=='dashboard')UI.openPage(item[2])}},
 category(a){if(a.page==='audit'||a.level==='critical')return'رقابة';if(['invoices','receipts','payments','treasury','approvals'].includes(a.page))return'مالية';if(['crm','customers','suppliers','agents'].includes(a.page))return'متابعة';return'تشغيل'},
 notificationId(a){return `${a.page}|${a.title}|${a.text}`},
 readSet(){try{return new Set(JSON.parse(localStorage.getItem(APP.storage+'_read_notifications')||'[]'))}catch(_){return new Set()}},
 markRead(id,page){const s=this.readSet();s.add(id);try{localStorage.setItem(APP.storage+'_read_notifications',JSON.stringify([...s].slice(-300)))}catch(_){};UI.closeMenus();UI.openPage(page)},
 filterNotifications(key){this.notificationFilter=key;renderNotificationPanel(document.getElementById('notificationPanel'))}
};
__set_CommercialUX(CommercialUX);
CommercialUX.initTraining();

const uxSave=DB.save.bind(DB);DB.save=function(render=true,options:any={}){const silent=options?.silentUi===true,background=options?.background===true;if(silent)return uxSave(render,options);if(background){const task=Promise.resolve(uxSave(render,options));task.then(r=>{if(r?.serverAvailable&&!r?.server){if(ServerStore.lastConflict)CommercialUX.saveState('error',DB.lastSaveError||'يوجد تعارض يحتاج مراجعة');else CommercialUX.saveState('warning','محفوظ محليًا • المزامنة بالخلفية')}}).catch(e=>CommercialUX.saveState('warning',e?.message||'المزامنة بالخلفية'));return task}const token=CommercialUX.beginSave();return Promise.resolve(uxSave(render,options)).then(r=>{CommercialUX.finishSave(token,r);return r}).catch(e=>{CommercialUX.finishSave(token,null,e);throw e})};
const uxRender=UI.renderCurrent.bind(UI);UI.renderCurrent=function(){uxRender();CommercialUX.enhance(document)};
const uxTopbar=UI.updateTopbar.bind(UI);UI.updateTopbar=function(){uxTopbar();const all=Commercial.notifications(),read=CommercialUX.readSet(),unread=all.filter(a=>!read.has(CommercialUX.notificationId(a))).length,b=document.getElementById('notificationBadge');if(b){b.textContent=unread>99?'99+':String(unread);b.classList.toggle('hidden',!unread)}};
const uxOpen=UI.openPage.bind(UI);UI.openPage=function(page,id='',opts={}){if(page!==this.current&&!CommercialUX.canLeave())return false;return uxOpen(page,id,opts)};
const uxWorkspace=UI.openWorkspace.bind(UI);UI.openWorkspace=function(id,opts={}){if(!CommercialUX.canLeave())return false;return uxWorkspace(id,opts)};
const uxHome=UI.backHome.bind(UI);UI.backHome=function(opts={}){if(!CommercialUX.canLeave())return false;return uxHome(opts)};
const uxClose=UI.closeModal.bind(UI);UI.closeModal=function(force=false){if(!force&&!CommercialUX.canLeave())return false;const modal=document.getElementById('modal');if(modal?.dataset?.onboarding==='1'){CommercialUX.markOnboarded();delete modal.dataset.onboarding}const r=uxClose(force);CommercialUX.dirtyForm=null;return r};
const uxDashboard=Pages.dashboard.bind(Pages);Pages.dashboard=function(){return uxDashboard()};
function renderNotificationPanel(p){if(!p)return;const all=Commercial.notifications(),read=CommercialUX.readSet(),filter=CommercialUX.notificationFilter,rows=all.map(a=>({...a,category:CommercialUX.category(a),nid:CommercialUX.notificationId(a)})).filter(a=>filter==='all'||a.category===filter),unread=all.filter(a=>!read.has(CommercialUX.notificationId(a))).length,cats=['all','مالية','تشغيل','متابعة','رقابة'];p.innerHTML=`<div class="dropdown-head"><b>مركز التنبيهات</b><span class="badge ${unread?'orange':'green'}">${unread} غير مقروء</span></div><div class="notification-tabs">${cats.map(c=>`<button class="${filter===c?'active':''}" data-commercial-ux-action="filterNotifications" data-commercial-ux-id="${c}">${c==='all'?'الكل':c}</button>`).join('')}</div><div class="dropdown-body">${rows.length?rows.map(a=>`<button class="alert-item ${a.level} ${read.has(a.nid)?'read':''}" data-commercial-ux-action="markRead" data-commercial-ux-id="${esc(a.nid)}" data-commercial-ux-page="${esc(a.page)}"><span class="alert-ico">${icon(a.level==='critical'?'warning':'bell','sm')}</span><span class="alert-copy"><b>${esc(a.title)}</b><small>${esc(a.text)}</small><em>${esc(a.category)}</em></span></button>`).join(''):'<div class="empty-state"><b>لا توجد تنبيهات في هذا التصنيف</b></div>'}</div>`};
UI_MenusSearch.registerNotificationRenderer(renderNotificationPanel);
const uxUserMenu=UI.toggleUserMenu.bind(UI);UI.toggleUserMenu=function(e){uxUserMenu(e);const p=document.getElementById('userMenu');if(!p||p.classList.contains('hidden')||p.querySelector('[data-training-link]'))return;const b=document.createElement('button');b.type='button';b.dataset.trainingLink='1';b.className='btn ghost';b.style.cssText='width:100%;margin-top:6px';b.innerHTML=`${icon('info','sm')} فتح وضع التدريب المعزول`;b.dataset.commercialUxAction='enterTraining';const body=p.querySelector('.dropdown-body');body?.append(b);if(body&&!body.querySelector('[data-onboarding-link]')){const h=document.createElement('button');h.type='button';h.dataset.onboardingLink='1';h.className='btn ghost';h.style.cssText='width:100%;margin-top:6px';h.innerHTML=`${icon('dashboard','sm')} دليل البدء`;h.dataset.commercialUxAction='showOnboarding';body.append(h)}};
window.addEventListener('beforeunload',e=>{if(CommercialUX.dirtyForm&&CommercialUX.dirtyForm.dataset.clean!=='1'){e.preventDefault();e.returnValue=''}});
document.addEventListener('input',e=>{const f=(e.target as Element)?.closest?.('form');if(!f)return;if(!f.dataset.dirtyReady){f.dataset.dirtyReady='1';f.dataset.clean='1'}f.dataset.clean='0';CommercialUX.dirtyForm=f},true);
document.addEventListener('change',e=>{const f=(e.target as Element)?.closest?.('form');if(!f)return;if(!f.dataset.dirtyReady){f.dataset.dirtyReady='1';f.dataset.clean='1'}f.dataset.clean='0';CommercialUX.dirtyForm=f},true);
document.addEventListener('submit',e=>{const f=e.target;if(f instanceof HTMLFormElement){f.dataset.clean='1';if(CommercialUX.dirtyForm===f)CommercialUX.dirtyForm=null}},true);
document.addEventListener('submit',e=>{const f=e.target;if(!(f instanceof HTMLFormElement)||S(f.onsubmit).includes('submitOnce')||f.dataset.submitting==='1'||f.dataset.busy==='1'||f.id==='modalForm')return;f.dataset.submitting='1';const b=f.querySelector<HTMLButtonElement>('[type=submit]');if(b)b.disabled=true;setTimeout(()=>{delete f.dataset.submitting;if(b)b.disabled=false},300)},true);
const uxModal=document.getElementById('modal');if(uxModal)new MutationObserver(records=>{if(!uxModal.classList.contains('show'))return;const relevant=records.some(r=>r.type==='childList'||(r.type==='attributes'&&r.target===uxModal));if(relevant)CommercialUX.enhance(uxModal)}).observe(uxModal,{attributes:true,attributeFilter:['class'],childList:true,subtree:true});
export { CommercialUX, uxClose, uxDashboard, uxHome, uxModal, uxOpen, uxRender, uxSave, uxTopbar, uxUserMenu, uxWorkspace };
