import { N, S } from '../core/runtime';
import { DB } from '../persistence/browser-store';
import { __set_SearchSelect } from '../core/late-bindings';
const Nav:any[]=[
 ['الرئيسية',[['dashboard','dashboard','لوحة التحكم','مركز النظام والأقسام']]],
 ['الحج والعمرة',[['umrah-dashboard','programs','نظام الحج والعمرة','من إنشاء البرنامج حتى إقفال الفوج'],['umrah-contracts','documents','التعاقدات والمخزون','عقود الفنادق والطيران والنقل ومتابعة السعة'],['umrah-control','settings','إدارة الحج والعمرة','الرقابة والتسعير والجاهزية والتشغيل']]],
 ['المبيعات والعملاء CRM',[['crm','customers','العملاء المحتملون والمتابعة','الفرص والمتابعات قبل التحويل لعميل'],['customers','customers','العملاء','الملف والرصيد والحركة'],['agents','agents','المندوبون','العملاء والعمولات والذمم'],['quotations','invoices','عروض الأسعار','من العرض إلى الفاتورة']]],
 ['الخدمات السياحية',[['services','services','الخدمات السياحية','تأشيرات وطيران وفنادق ونقل ورحلات']]],
 ['المشتريات والموردون',[['suppliers','suppliers','الموردون','الالتزامات والعقود والحركة'],['purchaseorders','suppliers','أوامر الشراء','الطلب والاعتماد والاستلام قبل فاتورة المورد']]],
 ['المحاسبة والمالية',[['invoices','invoices','الفواتير','مبيعات وموردين وتسويات'],['receipts','receipts','سندات القبض','التحصيل والتخصيص وطرق الدفع'],['payments','payments','سندات الصرف','السداد والاعتمادات'],['expenses','expenses','المصروفات','مدفوع ومستحق ومقدم'],['settlements','suppliers','التسويات والإلغاءات','تسويات الموردين والعملاء ورسوم الإلغاء والشطب'],['accruals','clock','الاستحقاقات والإيراد المؤجل','إيراد مقدم ومستحق والاعتراف حسب تاريخ الخدمة'],['assets','accounts','الأصول الثابتة','سجل الأصول والإهلاك والاستبعاد'],['loans','payments','القروض والمخصصات','التمويل والفوائد والمخصصات'],['budgets','reports','الموازنات','موازنات الحسابات ومراكز التكلفة ومقارنة الفعلي'],['cheques','documents','الشيكات','واردة وصادرة والتحصيل والارتداد'],['treasury','treasury','الخزن والبنوك','السيولة والتحويل والمطابقة'],['journal','journal','القيود اليومية','القيود اليدوية والمرحلة'],['accounts','accounts','دليل الحسابات','شجرة الحسابات المحمية'],['trial','trial','ميزان المراجعة','الحركة والأرصدة'],['costcenters','costcenters','مراكز التكلفة','تحليل الربحية'],['currencies','currencies','العملات وأسعار الصرف','الأسعار وإعادة التقييم'],['taxes','reports','الضرائب','الأكواد وحسابات المدخلات والمخرجات'],['periods','clock','الفترات المالية','الفتح والإقفال والسنة المالية']]],
 ['التقارير والرقابة',[['workcenter','activity','مركز العمل اليومي','كل ما يحتاج تنفيذًا الآن في مكان واحد'],['owner','dashboard','لوحة الإدارة','المؤشرات التنفيذية للإدارة العليا'],['reports','reports','التقارير','مالية وتشغيلية وضريبية'],['approvals','shield','الاعتمادات','العمليات التي تنتظر قرارًا'],['audit','audit','الرقابة المالية','فحص سلامة القيود والبيانات'],['activity','activity','سجل النشاط','من فعل ماذا ومتى']]],
 ['الإدارة والإعدادات',[['market-readiness','check','جاهزية البيع والتشغيل','فحص ذاتي قبل تسليم النظام للعميل'],['quick-guide','info','دليل البدء السريع','خطوات إعداد الشركة وبدء أول دورة عمل'],['users','users','المستخدمون والصلاحيات','الدخول والأدوار وحدود الاعتماد'],['branches','customers','الفروع','الفروع وصلاحيات الوصول'],['documents','documents','مركز المستندات','الأرشيف والمرفقات'],['sessions','users','الجلسات والأجهزة','الأجهزة المتصلة وإنهاء الجلسات'],['dataexchange','csv','استيراد وتصدير','Excel وCSV ونقل البيانات'],['support','info','الدعم وحالة النظام','التشخيص والترخيص وحالة الاتصال'],['settings','settings','الإعدادات','بيانات الشركة والسياسات والطباعة']]]
];

const adminNav=Nav.find(x=>x[0]==='الإدارة والإعدادات')?.[1];
if(adminNav&&!adminNav.some(x=>x[0]==='period-archiving'))adminNav.splice(1,0,['backup-center','backup','النسخ الاحتياطي والاستعادة','نسخ كاملة + استعادة + نسخ خادمية'],['period-archiving','archive','الأرشفة الذكية','إغلاق الفترات والأرشيف وصحة البيانات']);

const SuiteWorkspaceNav={
 umrah:[
  ['umrah-dashboard','dashboard','لوحة الحج والعمرة','ملخص اليوم والخطوة التالية','ابدأ هنا'],
  ['umrah-program-new','plus','إنشاء برنامج','معالج البرنامج من التعاقد حتى فتح البيع','ابدأ هنا'],
  ['umrah-booking-new','bookings','حجز جديد','العميل والمسافرون والسعر والتحصيل','ابدأ هنا'],
  ['umrah-programs','programs','البرامج','ملف 360 لكل برنامج ومسار الخدمة','الإدارة اليومية'],
  ['umrah-bookings','bookings','الحجوزات','الحالات والتحصيل والإلغاء والجاهزية','الإدارة اليومية'],
  ['umrah-travelers','customers','المسافرون','الجوازات والجاهزية والخدمات','الإدارة اليومية'],
  ['umrah-contracts','documents','التعاقدات والمخزون','فنادق وطيران ونقل وتأشيرات وموردون','التعاقدات'],
  ['umrah-trip-ready','activity','مركز تشغيل الفوج','كل تجهيزات الفوج من مكان واحد','التشغيل'],
  ['umrah-documents','documents','المخرجات والتقارير','الكشوف والمستندات والتقارير التشغيلية','المخرجات'],
  ['umrah-settings','settings','إعدادات الحج والعمرة','سياسات التشغيل والحجز والجاهزية','الإعدادات']
 ],
};

const PageTheme={dashboard:['#c9972f','#fff7e6'],crm:['#7555b7','#f1ecfb'],quotations:['#2869a9','#eaf3fd'],purchaseorders:['#b75b2a','#fff0e8'],programs:['#b98221','#fff5dd'],bookings:['#2c78c7','#eaf3fd'],services:['#537bc4','#edf3fd'],customers:['#08785b','#e8f7f0'],suppliers:['#b75b2a','#fff0e8'],agents:['#7555b7','#f1ecfb'],expenses:['#b42318','#fdeceb'],receipts:['#08785b','#e8f7f0'],payments:['#b42318','#fdeceb'],cheques:['#7b5a2e','#fff5dd'],invoices:['#2869a9','#eaf3fd'],journal:['#435b78','#edf1f6'],documents:['#59677a','#edf1f6'],accounts:['#355c8a','#eaf3fd'],trial:['#7555b7','#f1ecfb'],costcenters:['#2d7f78','#e8f7f3'],treasury:['#08785b','#e8f7f0'],currencies:['#b98221','#fff5dd'],taxes:['#7b5a2e','#fff5dd'],periods:['#58657a','#edf1f6'],reports:['#2869a9','#eaf3fd'],approvals:['#b76b00','#fff4df'],audit:['#b42318','#fdeceb'],activity:['#52647a','#edf1f6'],workcenter:['#176b57','#e8f7f0'],users:['#7555b7','#f1ecfb'],owner:['#176b57','#e8f7f0'],branches:['#2c78c7','#eaf3fd'],sessions:['#7555b7','#f1ecfb'],dataexchange:['#2d7f78','#e8f7f3'],support:['#52647a','#edf1f6'],'market-readiness':['#176b57','#e8f7f0'],'quick-guide':['#2869a9','#eaf3fd'],settings:['#59677a','#edf1f6']};
Object.assign(PageTheme,{settlements:['#8a5a16','#fff5dd'],accruals:['#315f85','#eaf3fd'],assets:['#355c8a','#edf3fd'],loans:['#7555b7','#f1ecfb'],budgets:['#2d7f78','#e8f7f3']});
PageTheme['period-archiving']=['#315f85','#eaf3fd'];PageTheme['backup-center']=['#315f85','#eaf3fd'];
for(const p of Object.values(SuiteWorkspaceNav).flat().map(x=>x[0]))PageTheme[p]=['#b98221','#fff5dd'];
const PageGroup={};for(const[g,items]of Nav)for(const i of items)PageGroup[i[0]]=g;

const RecentEntities={
 stamp(x){return S(x?.updatedAt||x?.createdAt||x?.postedAt||x?.date||x?.createdOn||'')},
 collect(type){const d=DB.data,out=[];const add=(id,x,prefix='')=>{if(!id)return;out.push({value:prefix?`${prefix}|${id}`:id,id,stamp:this.stamp(x)})};
  if(type==='customer'||type==='party'){for(const x of d.services||[])add(x.customerId,x,type==='party'?'customer':'');for(const x of d.bookings||[])add(x.customerId,x,type==='party'?'customer':'');for(const x of d.invoices||[])if(x.kind==='customer'&&(x.partyType||'customer')==='customer')add(x.partyId,x,type==='party'?'customer':'');for(const x of d.receipts||[])if(x.partyType==='customer')add(x.partyId,x,type==='party'?'customer':'');for(const x of d.quotations||[])add(x.partyId,x,type==='party'?'customer':'')}
  if(type==='supplier'){for(const x of d.services||[])add(x.supplierId,x);for(const x of d.purchaseOrders||[])add(x.supplierId,x);for(const x of d.invoices||[])if(x.kind==='supplier')add(x.partyId,x);for(const x of d.payments||[])if(x.partyType==='supplier')add(x.partyId,x)}
  if(type==='agent'||type==='party'){for(const x of d.services||[])add(x.agentId,x,type==='party'?'agent':'');for(const x of d.invoices||[])if(x.partyType==='agent')add(x.partyId,x,type==='party'?'agent':'');for(const x of d.receipts||[])if(x.partyType==='agent')add(x.partyId,x,type==='party'?'agent':'');for(const x of d.payments||[])if(x.partyType==='agent')add(x.partyId,x,type==='party'?'agent':'');for(const x of d.commissions||[])add(x.agentId,x,type==='party'?'agent':'')}
  if(type==='program'){for(const x of d.bookings||[])add(x.programId,x);for(const x of d.purchaseOrders||[])add(x.programId,x);for(const x of d.invoices||[])add(x.programId,x)}
  if(type==='treasury'){for(const x of d.receipts||[])add(x.treasuryId,x);for(const x of d.payments||[])add(x.treasuryId,x);for(const x of d.transfers||[]){add(x.fromTreasuryId,x);add(x.toTreasuryId,x)}for(const x of d.expenses||[])add(x.treasuryId,x)}
  if(type==='costCenter'){for(const x of d.invoices||[])add(x.costCenterId,x);for(const x of d.purchaseOrders||[])add(x.costCenterId,x);for(const x of d.services||[])add(x.costCenterId,x);for(const x of d.expenses||[])add(x.costCenterId,x);for(const j of d.journals||[])for(const l of j.lines||[])add(l.costCenterId,j)}
  if(type==='account'){for(const j of d.journals||[])for(const l of j.lines||[])add(l.accountId,j)}
  const seen=new Set();return out.sort((x,y)=>S(y.stamp).localeCompare(S(x.stamp))).filter(x=>x.value&&!seen.has(x.value)&&(seen.add(x.value),true)).slice(0,4)
 },
 entity(type,id){if(!id)return null;const d=DB.data,map={customer:'customers',supplier:'suppliers',agent:'agents',program:'programs',treasury:'treasuries',account:'accounts',costCenter:'costCenters',currency:'currencies'};if(type==='party'){const [k,v]=S(id).split('|');return this.entity(k,v)}const arr=d[map[type]]||[];return arr.find(x=>x.id===id||x.code===id)||null}
};
const NumericUX={
 menuId:'erp-number-choice-menu',
 options:[1,2,3,4,5,6,7,8,9],
 countName:/qty$|count$|persons?$|passengers?$|adults?$|children?$|child(?:bed|nobed)?$|infants?$|nights?$|days?$|hours?$|months?$|capacity(?:pervehicle)?$|seats?$|vehicles?$|visas?$|quota$|sequence$|maxusers$|maxbranches$|termvalue$|decimals$|roomcount$|roompersons$|holdhours$|holdwarnhours$|passportvaliditymonths$/i,
 countLabel:/عدد|غرف|ليال|ليلة|مقاعد|مركبات|سعة|بالغ|أطفال|رضع|تأشيرات|مدة .*?(?:ساعة|يوم|شهر)|حد المستخدمين|حد الفروع|عدد الكسور/i,
 moneyName:/price|cost|amount|paid|sale|discount|debit|credit|commission|deposit|margin|profit|rate|fee|balance|due|salary|allowance|deduction|payvalue|fxtobase|financialclearancemaxdue|approvalLimit|minBalance/i,
 moneyLabel:/سعر|تكلفة|المبلغ|القيمة|دفعة|عربون|خصم|هامش|ربح|رصيد|عمولة|ضريبة|مديونية|راتب|بدل|استقطاع|معامل التحويل/i,
 meta(input){const name=S(input?.name||input?.id||''),label=S(input?.closest?.('.field')?.querySelector?.('label')?.textContent||'');return{name,label}},
 kind(input){if(!input||input.type!=='number')return'';const {name,label}=this.meta(input);if(input.dataset.numberKind)return input.dataset.numberKind;if(this.moneyName.test(name)||this.moneyLabel.test(label))return'money';if(this.countName.test(name)||this.countLabel.test(label))return'count';return'count'},
 ensureMenu(doc){if(!doc)return null;let menu=doc.getElementById?.(this.menuId);if(menu)return menu;menu=doc.createElement('div');menu.id=this.menuId;menu.className='number-choice-menu';menu.hidden=true;menu.setAttribute('role','listbox');menu.setAttribute('aria-label','اختيار رقم سريع من 1 إلى 9');for(const v of this.options){const b=doc.createElement('button');b.type='button';b.className='number-choice-option';b.dataset.numberChoiceValue=String(v);b.textContent=String(v);b.setAttribute('role','option');menu.appendChild(b)};(doc.body||doc.documentElement)?.appendChild(menu);return menu},
 close(doc=document){const menu=doc?.getElementById?.(this.menuId);if(!menu)return;menu.hidden=true;menu.classList.remove('open');const host=menu.closest?.('.number-choice-host');host?.classList.remove('open');const toggle=host?.querySelector?.('.number-choice-toggle');toggle?.setAttribute?.('aria-expanded','false')},
 toggle(toggle){const host=toggle?.closest?.('.number-choice-host'),input=host?.querySelector?.('input[type="number"]'),doc=toggle?.ownerDocument;if(!host||!input||!doc)return;const menu=this.ensureMenu(doc),wasOpen=!menu.hidden&&menu.closest?.('.number-choice-host')===host;this.close(doc);if(wasOpen)return;host.appendChild(menu);menu.hidden=false;menu.classList.add('open');host.classList.add('open');toggle.setAttribute('aria-expanded','true')},
 choose(button){const menu=button?.closest?.('.number-choice-menu'),host=menu?.closest?.('.number-choice-host'),input=host?.querySelector?.('input[type="number"]'),doc=button?.ownerDocument,win=doc?.defaultView||window;if(!input)return;input.value=button.dataset.numberChoiceValue||'';input.dispatchEvent(new win.Event('input',{bubbles:true}));input.dispatchEvent(new win.Event('change',{bubbles:true}));this.close(doc);input.focus?.()},
 enhance(input){if(!input||input.type!=='number'||input.dataset.erpNumberReady==='1')return;input.dataset.erpNumberReady='1';input.classList.add('erp-number-input');input.setAttribute('dir','ltr');const kind=this.kind(input);input.dataset.numberKind=kind;if(kind==='count'){input.classList.add('number-choice-input');const step=N(input.step||1);input.inputMode=step&&step<1?'decimal':'numeric';if(!input.placeholder)input.placeholder='اختر 1–9 أو اكتب العدد';if(!input.closest?.('.number-choice-host')&&input.parentNode){const doc=input.ownerDocument,host=doc.createElement('div');host.className='number-choice-host';input.parentNode.insertBefore(host,input);host.appendChild(input);const toggle=doc.createElement('button');toggle.type='button';toggle.className='number-choice-toggle';toggle.dataset.numberChoiceToggle='1';toggle.setAttribute('aria-label','اختيار رقم من 1 إلى 9');toggle.setAttribute('aria-haspopup','listbox');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<span aria-hidden="true">⌄</span>';host.appendChild(toggle)}}else input.inputMode='decimal';if(!input.readOnly&&!input.disabled&&N(input.value)===0&&(kind==='count'||kind==='money')){input.value='';if(kind==='money'&&!input.placeholder)input.placeholder='اكتب القيمة'}},
 focus(input){if(!input||input.type!=='number')return;this.enhance(input);const kind=input.dataset.numberKind||this.kind(input);if(!input.readOnly&&!input.disabled&&N(input.value)===0&&(kind==='count'||kind==='money'))input.value=''},
 enhanceDocument(root=document){if(!root?.querySelectorAll)return;const doc=root.ownerDocument||globalThis.document||root;this.ensureMenu(doc);root.querySelectorAll('input[type="number"]').forEach(x=>this.enhance(x))}
};

const SearchSelect={
 docs:new WeakSet(),patterns:/customerId|supplierId|agentId|programId|treasuryId|accountId|costCenterId|employeeId|supervisorId|ownerId|travelerId|providerId|sourceAgentId|sourceEmployeeId|seasonId|currencyId|party$/i,
 norm(v){return S(v??'').toLowerCase().normalize('NFD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/\s+/g,' ').trim()},
 should(sel){if(!sel||sel.multiple||sel.dataset.noSearchSelect==='1'||sel.closest('.search-select-wrap'))return false;return sel.dataset.searchable==='true'||this.patterns.test(sel.name||sel.id||'')||sel.options.length>=8},
 inferType(sel){const n=S(`${sel.name||''} ${sel.id||''}`).toLowerCase();if(/supplier|provider/.test(n))return'supplier';if(/customer/.test(n))return'customer';if(/agent/.test(n))return'agent';if(/program/.test(n))return'program';if(/treasury/.test(n))return'treasury';if(/costcenter/.test(n))return'costCenter';if(/account/.test(n))return'account';if(/employee|supervisor|owner/.test(n))return'employee';if(/currency/.test(n))return'currency';if(/season/.test(n))return'season';const vals=[...sel.options].map(o=>o.value).filter(Boolean);if(vals.some(v=>/^customer\|/.test(v)||/^agent\|/.test(v)))return'party';const probes=[['customer',DB.data.customers],['supplier',DB.data.suppliers],['agent',DB.data.agents],['program',DB.data.programs],['treasury',DB.data.treasuries],['account',DB.data.accounts],['costCenter',DB.data.costCenters]];let best='',score=0;for(const[t,arr]of probes){const ids=new Set((arr||[]).map(x=>x.id));const n=vals.filter(v=>ids.has(v)).length;if(n>score){score=n;best=t}}return best},
 optionEntity(type,val){if(type==='party')return RecentEntities.entity('party',val);return RecentEntities.entity(type,val)},
 styles(doc){if(doc.getElementById('global-search-select-style'))return;const st=doc.createElement('style');st.id='global-search-select-style';st.textContent='.search-select-host{position:relative;min-width:0}.search-select-native{position:absolute;width:1px;height:1px;opacity:.001;pointer-events:none;inset:auto}.search-select-wrap{position:relative;min-width:0}.search-select-input{width:100%;min-width:0;box-sizing:border-box;padding:10px 38px 10px 11px;border:1px solid var(--line,#dbe2ea);border-radius:11px;background:#fff;color:inherit;font:inherit;outline:0}.search-select-input:focus{border-color:var(--brand,#2874b9);box-shadow:0 0 0 3px rgba(40,116,185,.12)}.search-select-arrow{position:absolute;inset-inline-start:10px;top:50%;transform:translateY(-50%);pointer-events:none;color:#778397}.search-select-results{position:absolute;z-index:10000;top:calc(100% + 5px);right:0;left:0;max-height:270px;overflow:auto;background:#fff;border:1px solid var(--line,#dbe2ea);border-radius:12px;box-shadow:0 16px 36px rgba(15,31,48,.16);padding:5px;display:none}.search-select-results.open{display:block}.search-select-option{width:100%;border:0;background:#fff;text-align:right;padding:9px 10px;border-radius:9px;cursor:pointer;font:inherit;color:inherit;min-height:44px}.search-select-option b{display:block;font-weight:800}.search-select-option small{display:block;color:#7b8796;margin-top:2px}.search-select-option:hover,.search-select-option.active{background:var(--soft,#eef6fd)}.search-select-empty{padding:12px;color:#7b8796;text-align:center}.search-select-recent-title{padding:5px 9px 4px;color:#7b8796;font-size:10.5px;font-weight:800}@media(max-width:780px){.search-select-input{min-height:48px;font-size:15px}.search-select-results{max-height:250px}.search-select-option{min-height:48px;font-size:15px;padding:10px 11px}}';doc.head.appendChild(st)},
 sync(sel){if(!sel)return;const host=sel.closest?.('.search-select-host'),input=host?.querySelector?.('.search-select-input'),results=host?.querySelector?.('.search-select-results');if(input&&sel.ownerDocument?.activeElement!==input)input.value=sel.value?(sel.selectedOptions?.[0]?.textContent?.trim()||''):'';if(results&&!host?.contains?.(sel.ownerDocument?.activeElement))results.classList.remove('open')},
 bindDocument(doc){if(!doc||this.docs.has(doc))return;this.docs.add(doc);const root=doc.documentElement||doc.body||doc;if(!root?.addEventListener)return;root.addEventListener('click',(e:any)=>{const numberToggle=e.target?.closest?.('[data-number-choice-toggle]'),numberOption=e.target?.closest?.('[data-number-choice-value]');if(numberToggle){e.preventDefault();NumericUX.toggle(numberToggle)}else if(numberOption){e.preventDefault();NumericUX.choose(numberOption)}else if(!e.target?.closest?.('.number-choice-host'))NumericUX.close(doc);for(const host of doc.querySelectorAll?.('.search-select-host')||[]){if(host.contains(e.target))continue;const sel=host.querySelector?.('select.search-select-native'),results=host.querySelector?.('.search-select-results');results?.classList.remove('open');this.sync(sel)}},{capture:true});root.addEventListener('change',(e:any)=>{const sel=e.target?.matches?.('select.search-select-native')?e.target:null;if(sel)this.sync(sel)},{capture:true});root.addEventListener('focusin',(e:any)=>{const input=e.target?.matches?.('input[type="number"]')?e.target:null;if(input)NumericUX.focus(input)},{capture:true});const mo=new MutationObserver((ms:any[])=>{const seen=new Set<any>(),numbers=new Set<any>();for(const m of ms)for(const n of m.addedNodes||[])if(n.nodeType===1){if(n.matches?.('select'))seen.add(n);for(const sel of n.querySelectorAll?.('select')||[])seen.add(sel);const owner=n.closest?.('select.search-select-native');if(owner)seen.add(owner);if(n.matches?.('input[type="number"]'))numbers.add(n);for(const input of n.querySelectorAll?.('input[type="number"]')||[])numbers.add(input)}for(const sel of seen){if(sel.dataset.searchSelectReady==='1')this.sync(sel);else this.enhance(sel)}for(const input of numbers)NumericUX.enhance(input)});mo.observe(root,{childList:true,subtree:true})},
 enhance(sel){if(!this.should(sel)||sel.dataset.searchSelectReady==='1')return;sel.dataset.searchSelectReady='1';this.styles(sel.ownerDocument);const doc=sel.ownerDocument,win=doc.defaultView||window,host=doc.createElement('div');host.className='search-select-host';sel.parentNode.insertBefore(host,sel);host.appendChild(sel);sel.classList.add('search-select-native');const wrap=doc.createElement('div');wrap.className='search-select-wrap';const input=doc.createElement('input');input.type='search';input.className='search-select-input';input.autocomplete='off';input.placeholder=sel.dataset.searchPlaceholder||'اكتب الاسم أو الكود أو الهاتف...';const arrow=doc.createElement('span');arrow.className='search-select-arrow';arrow.textContent='⌄';const results=doc.createElement('div');results.className='search-select-results';wrap.append(input,arrow,results);host.appendChild(wrap);const type=this.inferType(sel),label=()=>sel.value?(sel.selectedOptions?.[0]?.textContent?.trim()||''):'';input.value=label();let activeIndex=-1;
  const all=()=>[...sel.options].filter(o=>o.value&&!o.disabled).map(o=>{const ent=this.optionEntity(type,o.value),phone=ent?.phone||ent?.mobile||'',code=ent?.code||ent?.no||'',text=o.textContent.trim(),blob=this.norm(`${text} ${o.value} ${code} ${phone}`);return{o,t:text,blob,phone,code}});
  const render=()=>{const q=this.norm(input.value),items=all();let opts=[],recentMode=!q;if(recentMode){const recent=RecentEntities.collect(type),rank=new Map(recent.map((x,i)=>[x.value,i])),ranked=items.filter(x=>rank.has(x.o.value)||rank.has(`${type}|${x.o.value}`)).sort((x,y)=>(rank.get(x.o.value)??rank.get(`${type}|${x.o.value}`)??99)-(rank.get(y.o.value)??rank.get(`${type}|${y.o.value}`)??99));opts=[...ranked,...items.filter(x=>!ranked.includes(x))].slice(0,4);if(sel.value&&!opts.some(x=>x.o.value===sel.value)){const cur=items.find(x=>x.o.value===sel.value);if(cur)opts.unshift(cur);opts=opts.slice(0,4)}}else opts=items.filter(x=>x.blob.includes(q)).sort((a,b)=>{const an=this.norm(a.t),bn=this.norm(b.t),as=an.startsWith(q)?0:1,bs=bn.startsWith(q)?0:1;return as-bs||a.t.localeCompare(b.t,'ar')}).slice(0,16);
   activeIndex=-1;results.innerHTML='';if(recentMode&&opts.length){const h=doc.createElement('div');h.className='search-select-recent-title';h.textContent=RecentEntities.collect(type).length?'آخر تعاملاتك':'اقتراحات سريعة';results.appendChild(h)}if(!opts.length){const e=doc.createElement('div');e.className='search-select-empty';e.textContent=recentMode?'لا توجد بيانات مسجلة':'لا توجد نتائج مطابقة';results.appendChild(e)}else for(const x of opts){const b=doc.createElement('button');b.type='button';b.className='search-select-option'+(x.o.value===sel.value?' active':'');const bb=doc.createElement('b');bb.textContent=x.t;b.appendChild(bb);if(x.phone){const sm=doc.createElement('small');sm.textContent=x.phone;b.appendChild(sm)}b.addEventListener('click',()=>{sel.value=x.o.value;input.value=x.t;results.classList.remove('open');sel.dispatchEvent(new win.Event('input',{bubbles:true}));sel.dispatchEvent(new win.Event('change',{bubbles:true}))});results.appendChild(b)}results.classList.add('open')};
  const move=step=>{const buttons=[...results.querySelectorAll('.search-select-option')];if(!buttons.length)return;activeIndex=(activeIndex+step+buttons.length)%buttons.length;buttons.forEach((b,i)=>b.classList.toggle('active',i===activeIndex));buttons[activeIndex].scrollIntoView({block:'nearest'})};input.addEventListener('focus',()=>{if(!sel.value||input.value===label())input.value='';render()});input.addEventListener('input',render);input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();move(e.key==='ArrowDown'?1:-1)}else if(e.key==='Enter'&&activeIndex>=0){e.preventDefault();results.querySelectorAll('.search-select-option')[activeIndex]?.click()}else if(e.key==='Escape'){results.classList.remove('open');input.value=label()}})},
 enhanceDocument(root=document){if(!root?.querySelectorAll)return;const doc=root.ownerDocument||globalThis.document||root;this.styles(doc);this.bindDocument(doc);NumericUX.enhanceDocument(root);root.querySelectorAll('select').forEach(s=>s.dataset.searchSelectReady==='1'?this.sync(s):this.enhance(s))}
};
__set_SearchSelect(SearchSelect);
export { Nav, NumericUX, PageGroup, PageTheme, RecentEntities, SearchSelect, SuiteWorkspaceNav, adminNav };
