import { EPS, N, S, activityActionLabel, byId, entityLabel, esc, formatDate, formatDateTime, icon, live, money, toast, today } from '../core/runtime';
import { Party360Queries, Party360Commands } from '../application/party360-workflows';
import { Commercial } from '../commercial/product';
import { Accounting } from '../accounting/engine';
import { Invoices, MasterData } from '../accounting/invoices';
import { CRM } from '../crm/crm';
import { DeleteCenter } from '../core/delete-center';
import { Attachments } from '../documents/attachments-backup';
import { Auth } from '../security/auth';
import { UnifiedParty } from '../crm/unified-party';
import { Actions, CommercialUX, Pages, Print, SearchSelect, UI, UmrahCore_PrintView, UmrahCore_Procurement, composeParty360Presentation } from '../core/late-bindings';
import { __set_Party360, composeParty360Deps } from '../core/late-bindings';
import { notify } from '../composition/early-presentation';
import { AccessControl } from '../security/access-control';
const p360=()=>composeParty360Deps();
/* Unified party "More" center. Lightweight shell first; heavy data is lazy and bounded. */
const Party360={
 _loadToken:0,_modelCacheKey:'',_modelCache:null,_chunkSize:500,
 config(type){return({customer:{list:'customers',page:'customers',form:'customer',label:'العميل',icon:'customers'},supplier:{list:'suppliers',page:'suppliers',form:'supplier',label:'المورد',icon:'suppliers'},agent:{list:'agents',page:'agents',form:'agent',label:'المندوب',icon:'agents'}})[type]||null},
 sortDate(a,b){return S(b.createdAt||b.date||b.at||'').localeCompare(S(a.createdAt||a.date||a.at||''))},
 base(type,id){const cfg=this.config(type);if(!cfg)throw new Error('نوع الطرف غير صحيح');const x=byId(Party360Queries.collection(p360(),cfg.list)||[],id);if(!x)throw new Error('السجل غير موجود');AccessControl.require(cfg.page,'view');return{type,id,cfg,x,isCustomer:type==='customer',isSupplier:type==='supplier',isAgent:type==='agent'}},
 async yieldUi(){await new Promise(res=>{if(typeof requestAnimationFrame==='function')requestAnimationFrame(()=>setTimeout(res,0));else setTimeout(res,0)})},
 invalidate(){this._modelCacheKey='';this._modelCache=null},
 async countsAsync(type,id){const d=Party360Queries.root(p360()),c={invoices:0,services:0,moves:0,primary:0,attachments:0,contracts:0,commitments:0};let seen=0;const scan=async(arr,pred,key)=>{for(const x of arr||[]){if(pred(x))c[key]++;if(++seen%this._chunkSize===0)await this.yieldUi()}};
  if(type==='customer'){
   await scan(d.invoices,i=>live(i)&&i.partyId===id&&i.kind!=='supplier'&&(i.partyType||'customer')==='customer','invoices');
   await scan(d.services,s=>live(s)&&s.customerId===id,'services');
   await scan(d.receipts,r=>live(r)&&r.partyId===id&&(r.partyType||'customer')==='customer','moves');
   await scan(d.bookings,b=>live(b)&&b.customerId===id,'primary');await scan(d.umrahBookings,b=>b.active!==false&&b.customerId===id,'primary');
  }else if(type==='supplier'){
   await scan(d.invoices,i=>live(i)&&i.partyId===id&&i.kind==='supplier','invoices');
   await scan(d.services,s=>live(s)&&s.supplierId===id,'services');
   await scan(d.payments,r=>live(r)&&r.partyId===id&&(!r.partyType||r.partyType==='supplier'),'moves');
   await scan(d.purchaseOrders,po=>live(po)&&po.supplierId===id,'primary');
   await scan(d.umrahSupplierCommitments,x=>x.active!==false&&x.status!=='cancelled'&&x.supplierId===id,'commitments');
   for(const name of['umrahHotelContracts','umrahFlightBlocks','umrahTransportContracts','umrahVisaContracts'])await scan(d[name],x=>x.active!==false&&x.supplierId===id,'contracts');
  }else{
   await scan(d.invoices,i=>live(i)&&i.partyId===id&&i.kind!=='supplier'&&i.partyType==='agent','invoices');
   await scan(d.services,s=>live(s)&&s.agentId===id,'services');
   await scan(d.receipts,r=>live(r)&&r.partyId===id&&r.partyType==='agent','moves');await scan(d.payments,r=>live(r)&&r.partyId===id&&r.partyType==='agent','moves');
   await scan(d.commissions,x=>x.agentId===id&&x.status!=='cancelled'&&x.status!=='reversed','primary');
  }
  await scan(d.attachments,a=>a.entityType===type&&a.entityId===id&&a.active!==false,'attachments');return c
 },
 balanceText(type,id){if(type==='customer'){const map=Accounting.partyReceivable('customer',id);return Object.entries(map).map(([c,v])=>`${money(Math.abs(N(v)),c)} ${N(v)>=0?'عليه':'له'}`).join(' • ')||'0'}if(type==='supplier'){const map=Accounting.supplierPayable(id);return Object.entries(map).map(([c,v])=>`${money(Math.abs(N(v)),c)} ${N(v)>=0?'له':'عليه'}`).join(' • ')||'0'}const due=Accounting.partyReceivable('agent',id),pay=Accounting.agentPayable(id),rows=[];for(const[c,v]of Object.entries(due))if(Math.abs(N(v))>EPS)rows.push(`${money(Math.abs(N(v)),c)} ${N(v)>=0?'عليه':'له'}`);for(const[c,v]of Object.entries(pay))if(Math.abs(N(v))>EPS)rows.push(`${money(Math.abs(N(v)),c)} ${N(v)>=0?'له عمولات':'عليه تسوية'}`);return rows.join(' • ')||'0'},
 async modelAsync(type,id){const key=[Party360Queries.updatedAt(p360())||'',type,id].join('|');if(this._modelCacheKey===key&&this._modelCache)return this._modelCache;const b=this.base(type,id),c=await this.countsAsync(type,id),m={...b,...c,balance:this.balanceText(type,id)};this._modelCacheKey=key;this._modelCache=m;return m},
 recent(arr,predicate,limit=24){const out=[];for(const x of arr||[])if(predicate(x))out.push(x);out.sort(this.sortDate);return out.slice(0,limit)},
 child(fn){const inMore=!!document.querySelector('#modal.show #modalBody .party360[data-party-more="1"]');return inMore&&(UI as any)?.modalChild?(UI as any).modalChild(fn):fn()},
 /* ثابت: تعديل ← واتساب ← مستندات ← تعليق ← حذف */
 manageButtons(type,id){const {cfg,x}=this.base(type,id),edit=AccessControl.can(cfg.page,'edit')?`<button type="button" class="btn ghost party-more-manage" data-party-action="edit" data-party-form="${cfg.form}" data-party-id="${id}">${icon('edit','sm')} تعديل</button>`:'',suspend=AccessControl.can(cfg.page,'edit')?`<button type="button" class="btn ${x.active===false?'success':'warn'} party-more-manage" data-party-action="toggleSuspended" data-party-type="${type}" data-party-id="${id}">${icon(x.active===false?'check':'pause','sm')} ${x.active===false?'إلغاء التعليق':'تعليق'}</button>`:'',docs=AccessControl.can(cfg.page,'print')?`<button type="button" class="btn soft party-more-manage" data-party-action="documents" data-party-type="${type}" data-party-id="${id}">${icon('documents','sm')} المستندات</button>`:'',del=AccessControl.can(cfg.page,'delete')?`<button type="button" class="btn danger party-more-manage" ${x.active===false?'':'disabled title="يجب تعليق السجل أولًا"'} data-party-action="delete" data-party-type="${type}" data-party-id="${id}">${icon('trash','sm')} حذف</button>`:'',wa=Commercial.moduleAllowed('whatsapp')?`<button type="button" class="btn success party-more-manage" data-party-action="whatsapp" data-party-type="${type}" data-party-id="${id}">${icon('phone','sm')} واتساب</button>`:'';return `${edit}${wa}${docs}${suspend}${del}`},
 toggleSuspended(type,id){const {cfg,x}=this.base(type,id);AccessControl.require(cfg.page,'edit');const action=x.active===false?'إلغاء تعليق':'تعليق';return this.child(()=>UI.confirmAction(action+' '+cfg.label,x.active===false?'سيعود السجل نشطًا ومتاحًا للعمليات الجديدة.':'سيتم إيقاف العمليات الجديدة مع الاحتفاظ بكل التاريخ. الحذف الآمن يصبح متاحًا بعد التعليق فقط.',async()=>{MasterData.toggle(cfg.list,id);const saved=await Party360Commands.save(p360(),true);this.invalidate();setTimeout(()=>this.refreshVisibleHeader(type,id),30);if(saved.serverAvailable&&!saved.server)notify(`تم ${action} ${cfg.label} محليًا وسيتم اعتماد التعديل تلقائيًا عند استقرار الاتصال`,'warning');else notify(`تم ${action} ${cfg.label}`)},{label:action}))},
 whatsApp(type,id){const x=this.base(type,id).x,phone=Actions.normalizeWhatsApp(x.whatsapp||x.phone);if(!phone)return notify('لا يوجد رقم هاتف/واتساب صالح لهذا الطرف','warning');return Actions.openWhatsApp(type,id)},
 documentItems(type,id,key){const d=Party360Queries.root(p360()),sort=(a,b)=>this.sortDate(a,b);let items=[];if(key==='invoices')items=(d.invoices||[]).filter(x=>live(x)&&x.partyId===id&&((type==='supplier'&&x.kind==='supplier')||(type!=='supplier'&&x.kind!=='supplier'&&(x.partyType||'customer')===type))).sort(sort);else if(key==='receipts')items=(d.receipts||[]).filter(x=>live(x)&&x.partyId===id&&(x.partyType||'customer')===type).sort(sort);else if(key==='payments')items=(d.payments||[]).filter(x=>live(x)&&x.partyId===id&&(x.partyType||'supplier')===type).sort(sort);else if(key==='purchaseOrders')items=(d.purchaseOrders||[]).filter(x=>live(x)&&x.supplierId===id).sort(sort);else if(key==='bookings')items=(d.umrahBookings||[]).filter(x=>x.active!==false&&x.customerId===id).sort(sort);return items},
 documentGroups(type,id){const {cfg}=this.base(type,id),out=[];if(AccessControl.can(cfg.page,'print'))out.push({key:'statement',label:'كشف الحساب',hint:'الحركة والرصيد من الأستاذ العام',count:1,icon:'statement'});const add=(key,label,hint,perm,ico)=>{const count=this.documentItems(type,id,key).length;if(count&&AccessControl.can(perm,'print'))out.push({key,label,hint,count,icon:ico})};add('invoices','الفواتير','الفواتير الفعلية المسجلة','invoices','invoices');if(type==='customer'){add('receipts','سندات القبض','المبالغ المقبوضة من العميل','receipts','receipts');const bc=this.documentItems(type,id,'bookings').length;if(bc&&AccessControl.can('bookings','print'))out.push({key:'bookings',label:'تأكيدات الحجز',hint:'حجوزات الحج والعمرة الفعلية',count:bc,icon:'bookings'})}else if(type==='supplier'){add('payments','سندات الصرف','المدفوعات الفعلية للمورد','payments','payments');add('purchaseOrders','أوامر الشراء','أوامر الشراء المرتبطة بالمورد','purchaseorders','purchaseorders')}else{add('receipts','سندات القبض','المبالغ المقبوضة من المندوب','receipts','receipts');add('payments','سندات الصرف','المدفوعات المسجلة للمندوب','payments','payments')}return out},
 documents(type,id){return this.child(()=>this.openDocuments(type,id))},
 openDocuments(type,id){const {cfg,x}=this.base(type,id),groups=this.documentGroups(type,id),m=document.getElementById('modal'),f=document.getElementById('modalForm');document.getElementById('modalTitle').textContent=`المستندات — ${x.name}`;document.getElementById('modalSubtitle').textContent='مستندات فعلية من النظام فقط؛ لا يتم إنشاء فاتورة أو سند شكلي من هنا.';document.getElementById('modalIcon').innerHTML=icon('documents');document.getElementById('modalSubmitText').textContent='إغلاق';document.getElementById('modalBody').innerHTML=groups.length?`<div class="party-document-grid">${groups.map(g=>`<button type="button" class="party-document-card" data-party-document-group="${esc(g.key)}" data-party-type="${esc(type)}" data-party-id="${esc(id)}"><span class="party-document-icon">${icon(g.icon)}</span><span><b>${esc(g.label)}</b><small>${esc(g.hint)}</small></span><em>${g.count}</em></button>`).join('')}</div>`:'<div class="empty-state">لا توجد مستندات متاحة حسب الصلاحيات الحالية.</div>';m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)}},
 openDocumentGroup(type,id,key){if(key==='statement')return (UI as any).modalChild(()=>Actions.statement(type,id));const {x}=this.base(type,id),items=this.documentItems(type,id,key);if(!items.length)return notify('لا توجد مستندات في هذا القسم','warning');const labels={invoices:'الفواتير',receipts:'سندات القبض',payments:'سندات الصرف',purchaseOrders:'أوامر الشراء',bookings:'تأكيدات الحجز'},m=document.getElementById('modal'),f=document.getElementById('modalForm');(UI as any).modalChild(()=>{document.getElementById('modalTitle').textContent=`${labels[key]||'المستندات'} — ${x.name}`;document.getElementById('modalSubtitle').textContent='اختر المستند الفعلي لفتح المعاينة، ثم اطبع أو نزّل أو شارك PDF.';document.getElementById('modalIcon').innerHTML=icon('documents');document.getElementById('modalSubmitText').textContent='رجوع';document.getElementById('modalBody').innerHTML=`<div class="party-document-list">${items.slice(0,80).map(doc=>{const date=formatDate(doc.date||doc.createdAt||today()),amount=doc.amount!=null?money(doc.amount,doc.currency):doc.total!=null?money(doc.total,doc.currency):'';return`<button type="button" class="party-document-row" data-party-document-open="${esc(key)}" data-party-type="${esc(type)}" data-party-id="${esc(id)}" data-party-document-id="${esc(doc.id)}"><span><b>${esc(doc.no||doc.name||'مستند')}</b><small>${esc(date)}${amount?` • ${esc(amount)}`:''}</small></span><span>${icon('chevronLeft','sm')}</span></button>`}).join('')}</div>${items.length>80?'<div class="field-hint mt-12">يتم عرض أحدث 80 مستندًا للحفاظ على سرعة الواجهة.</div>':''}`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)}})},
 openDocument(type,id,key,docId){if(!docId)return;if(key==='invoices')return Print.invoice(docId);if(key==='receipts')return Print.voucher('receipt',docId);if(key==='payments')return Print.voucher('payment',docId);if(key==='purchaseOrders')return Print.purchaseOrder(docId);if(key==='bookings')return UmrahCore_PrintView.bookingConfirmation(docId)},
 deletePrompt(type,id){const {cfg,x}=this.base(type,id);AccessControl.require(cfg.page,'delete');if(x.active!==false)return notify(`يجب تعليق ${cfg.label} أولًا قبل الحذف`,'warning');return this.child(()=>DeleteCenter.request(type,id))},
 shell(type,id,{active='overview',detail=''}={}){const {cfg,x}=this.base(type,id),tab=(key,label,ico)=>`<button type="button" class="party360-tab ${active===key?'active':''}" data-party360-tab="${key}" data-party-action="tab" data-party-type="${type}" data-party-id="${id}" data-party-key="${key}"><span class="party360-tab-icon">${icon(ico,'sm')}</span><span class="party360-tab-label">${label}</span></button>`,primaryLabel=type==='customer'?'الحجوزات':type==='supplier'?'أوامر الشراء':'العمولات';return `<div class="party360 party360-v3" data-party-more="1" data-no-page-empty-action="1" data-party360-type="${type}" data-party360-id="${id}"><div class="party360-head"><div class="party360-party"><span class="party360-avatar">${icon(cfg.icon)}</span><div><b data-party-more-name>${esc(x.name||x.no||'-')}</b><span>${esc(x.no||'')}${x.phone?` • ${esc(x.phone)}`:''}</span></div></div><span data-party-more-status class="badge ${x.active===false?'gray':'green'}">${x.active===false?'معلّق':'نشط'}</span></div><div class="party-more-management"><div><b>إدارة ${cfg.label}</b></div><div class="party360-actions">${this.manageButtons(type,id)}</div></div><div class="party360-strip"><div><small>الفواتير</small><b data-party360-stat="invoices">…</b></div><div><small>${primaryLabel}</small><b data-party360-stat="primary">…</b></div><div><small>الحركات المالية</small><b data-party360-stat="moves">…</b></div><div><small>المرفقات</small><b data-party360-stat="attachments">…</b></div></div><div class="party360-tabs">${tab('overview','الملخص','dashboard')}${tab('financial','المالية','wallet')}${tab('operations',type==='customer'?'الحجوزات والخدمات':type==='supplier'?'العقود والمشتريات':'العملاء والعمولات','bookings')}${tab('files','المرفقات والنشاط','documents')}${tab('unified','الحساب الشامل','statement')}</div><div class="party360-detail" id="party360-detail">${detail||'<div class="party360-loading">جاري تجهيز الملخص…</div>'}</div></div>`},
 overview(type,id,m){const {cfg,x}=m,c=m;return `<div class="grid kpi-grid party360-kpis">${UI.kpi('الرصيد',m.balance,'من الأستاذ العام',type==='supplier'?'bad':'good','wallet')}${UI.kpi('الفواتير',c.invoices,'مرتبطة بالطرف','info','invoices')}${UI.kpi(type==='customer'?'الحجوزات':type==='supplier'?'العقود':'العمولات',type==='customer'?c.primary:type==='supplier'?c.contracts:c.primary,'ملخص تشغيلي فقط','purple',cfg.icon)}${UI.kpi('المرفقات',c.attachments,'ملفات محفوظة','warn','documents')}</div><div class="split-equal party360-summary"><div class="card"><h3>بيانات الاتصال</h3><div class="mini-list mt-12"><div class="mini-row"><span>الكود</span><b>${esc(x.no||'-')}</b></div><div class="mini-row"><span>الهاتف</span><b>${esc(x.phone||'-')}</b></div><div class="mini-row"><span>واتساب</span><b>${esc(x.whatsapp||'-')}</b></div><div class="mini-row"><span>البريد</span><b>${esc(x.email||'-')}</b></div><div class="mini-row"><span>العنوان</span><b>${esc(x.address||'-')}</b></div></div></div><div class="card"><h3>ملخص الحركة</h3><div class="mini-list mt-12"><div class="mini-row"><span>${type==='customer'?'الحجوزات':type==='supplier'?'أوامر الشراء':'العمولات'}</span><b>${c.primary}</b></div><div class="mini-row"><span>الحركات المالية</span><b>${c.moves}</b></div><div class="mini-row"><span>الخدمات</span><b>${c.services}</b></div><div class="mini-row"><span>${type==='supplier'?'التزامات الموردين':'الحالة'}</span><b>${type==='supplier'?c.commitments:(x.active===false?'موقوف':'نشط')}</b></div></div></div></div>`},
 financial(type,id){let invoices=[],moves=[];if(type==='customer'){invoices=this.recent(Party360Queries.collection(p360(),'invoices'),i=>live(i)&&i.partyId===id&&i.kind!=='supplier'&&(i.partyType||'customer')==='customer',20);moves=this.recent(Party360Queries.collection(p360(),'receipts'),r=>live(r)&&r.partyId===id&&(r.partyType||'customer')==='customer',20)}else if(type==='supplier'){invoices=this.recent(Party360Queries.collection(p360(),'invoices'),i=>live(i)&&i.partyId===id&&i.kind==='supplier',20);moves=this.recent(Party360Queries.collection(p360(),'payments'),r=>live(r)&&r.partyId===id&&(!r.partyType||r.partyType==='supplier'),20)}else{invoices=this.recent(Party360Queries.collection(p360(),'invoices'),i=>live(i)&&i.partyId===id&&i.kind!=='supplier'&&i.partyType==='agent',20);moves=[...this.recent(Party360Queries.collection(p360(),'receipts'),r=>live(r)&&r.partyId===id&&r.partyType==='agent',12),...this.recent(Party360Queries.collection(p360(),'payments'),r=>live(r)&&r.partyId===id&&r.partyType==='agent',12)].sort(this.sortDate).slice(0,20)}const invRows=invoices.map(i=>`<tr><td><b>${esc(i.no)}</b></td><td>${formatDate(i.date)}</td><td>${money(Invoices.total(i),i.currency)}</td><td>${money(Invoices.remaining(i),i.currency)}</td><td>${UI.badge(i.status)}</td><td><button type="button" class="btn small ghost" data-ui-close-page="invoices" data-ui-close-page-id="${esc(i.id)}">فتح</button></td></tr>`),moveRows=moves.map(r=>`<tr><td><b>${esc(r.no||'')}</b></td><td>${formatDate(r.date)}</td><td>${money(N(r.amount),r.currency||Party360Queries.baseCurrency(p360()))}</td><td>${esc(r.paymentMethod||r.method||'-')}</td><td>${UI.badge(r.status||'posted')}</td></tr>`);return `<div class="card"><div class="card-head"><h3>الحساب</h3><b class="party360-balance">${this.balanceText(type,id)}</b></div><div class="muted">آخر الحركات فقط للحفاظ على سرعة «المزيد».</div></div><div class="card mt-12"><h3>آخر الفواتير</h3>${UI.table(['الرقم','التاريخ','الإجمالي','المتبقي','الحالة','فتح'],invRows,'لا توجد فواتير',{export:false})}</div><div class="card mt-12"><h3>آخر الحركات المالية</h3>${UI.table(['الرقم','التاريخ','القيمة','الطريقة','الحالة'],moveRows,'لا توجد حركات',{export:false})}</div>`},
 operations(type,id){if(type==='customer'){const native=this.recent(Party360Queries.collection(p360(),'umrahBookings'),b=>b.active!==false&&b.customerId===id,18),legacy=this.recent(Party360Queries.collection(p360(),'bookings'),b=>live(b)&&b.customerId===id,12),bookings=[...native,...legacy].sort(this.sortDate).slice(0,22),services=this.recent(Party360Queries.collection(p360(),'services'),s=>live(s)&&s.customerId===id,20),rows=bookings.map(b=>{const n=(Party360Queries.collection(p360(),'umrahBookings')||[]).some(x=>x.id===b.id),p=n?byId(Party360Queries.collection(p360(),'umrahPrograms'),b.programId):byId(Party360Queries.collection(p360(),'programs'),b.programId);return`<tr><td><b>${esc(b.no||'')}</b></td><td>${esc(p?.name||'-')}</td><td>${formatDate(b.date||b.createdAt)}</td><td>${b.persons||'-'}</td><td>${UI.badge(b.status)}</td><td>${n?`<button type="button" class="btn small ghost" data-ui-close-page="umrah-bookings" data-ui-close-page-id="${esc(b.id)}">فتح</button>`:'-'}</td></tr>`}),svc=services.map(s=>`<tr><td>${esc(s.no||'')}</td><td>${esc(s.type||s.serviceType||'')}</td><td>${formatDate(s.date||s.serviceDate)}</td><td>${money(N(s.total||s.saleAmount),s.currency||Party360Queries.baseCurrency(p360()))}</td></tr>`);return `<div class="card"><h3>آخر الحجوزات</h3>${UI.table(['الحجز','البرنامج','التاريخ','الأفراد','الحالة','فتح'],rows,'لا توجد حجوزات',{export:false})}</div><div class="card mt-12"><h3>آخر الخدمات</h3>${UI.table(['الرقم','النوع','التاريخ','القيمة'],svc,'لا توجد خدمات',{export:false})}</div>`}
  if(type==='agent'){const assigned=this.recent(Party360Queries.collection(p360(),'customers'),x=>x.agentId===id&&x.active!==false,20),comm=this.recent(Party360Queries.collection(p360(),'commissions'),x=>x.agentId===id&&x.status!=='cancelled'&&x.status!=='reversed',20),aRows=assigned.map(x=>`<tr><td><b>${esc(x.no||'')}</b></td><td>${esc(x.name||'-')}</td><td>${esc(x.phone||'-')}</td><td>${UI.badge(x.active===false?'inactive':'active')}</td></tr>`),cRows=comm.map(x=>`<tr><td><b>${esc(x.no||'')}</b></td><td>${money(N(x.amount),x.currency||Party360Queries.baseCurrency(p360()))}</td><td>${money(N(x.paidAmount),x.currency||Party360Queries.baseCurrency(p360()))}</td><td>${UI.badge(x.status)}</td></tr>`);return `<div class="card"><h3>آخر العملاء المسندين</h3>${UI.table(['الكود','العميل','الهاتف','الحالة'],aRows,'لا يوجد عملاء مسندون',{export:false})}</div><div class="card mt-12"><h3>آخر العمولات</h3>${UI.table(['الرقم','العمولة','المدفوع','الحالة'],cRows,'لا توجد عمولات',{export:false})}</div>`}
  const pos=this.recent(Party360Queries.collection(p360(),'purchaseOrders'),po=>live(po)&&po.supplierId===id,18),com=this.recent(Party360Queries.collection(p360(),'umrahSupplierCommitments'),c=>c.active!==false&&c.status!=='cancelled'&&c.supplierId===id,18),contracts=[];for(const name of['umrahHotelContracts','umrahFlightBlocks','umrahTransportContracts','umrahVisaContracts'])for(const c of Party360Queries.collection(p360(),name)||[])if(c.active!==false&&c.supplierId===id)contracts.push(c);contracts.sort(this.sortDate);const poRows=pos.map(po=>`<tr><td><b>${esc(po.no||'')}</b></td><td>${formatDate(po.date)}</td><td>${money(CRM.poTotal(po),po.currency)}</td><td>${UI.badge(po.status)}</td><td><button type="button" class="btn small ghost" data-ui-close-page="purchaseorders" data-ui-close-page-id="${esc(po.id)}">فتح</button></td></tr>`),comRows=com.map(c=>{const p=byId(Party360Queries.collection(p360(),'umrahPrograms'),c.programId),snap=typeof UmrahCore_Procurement!=='undefined'?UmrahCore_Procurement.status(c):null;return`<tr><td>${esc(c.description||'-')}</td><td>${esc(p?.name||p?.no||'-')}</td><td>${money(c.total,c.currency)}</td><td>${esc(snap?.poNo||c.hostPONo||'-')}</td><td>${esc(snap?.invoiceNo||c.hostInvoiceNo||'-')}</td><td>${UI.badge(c.status)}</td></tr>`}),contractRows=contracts.slice(0,18).map(c=>`<tr><td>${esc(c.contractNo||c.no||'-')}</td><td>${esc(c.name||c.hotelName||c.airline||c.provider||c.serviceName||c.route||'-')}</td><td>${formatDate(c.startDate||c.from||c.date||c.createdAt)}</td><td>${UI.badge(c.status||'active')}</td></tr>`);return `<div class="card"><h3>أوامر الشراء</h3>${UI.table(['الأمر','التاريخ','القيمة','الحالة','فتح'],poRows,'لا توجد أوامر شراء',{export:false})}</div><div class="card mt-12"><h3>التزامات العمرة</h3>${UI.table(['الالتزام','البرنامج','القيمة','أمر الشراء','الفاتورة','الحالة'],comRows,'لا توجد التزامات',{export:false})}</div><div class="card mt-12"><h3>العقود</h3>${UI.table(['الرقم','العقد / الخدمة','التاريخ','الحالة'],contractRows,'لا توجد عقود مرتبطة',{export:false})}</div>`},
 files(type,id){const {x,cfg}=this.base(type,id),attachments=[...Attachments.list(type,id)].sort(this.sortDate).slice(0,24),audit=[];for(const a of (Party360Queries.collection(p360(),'auditLog')||[]).slice(0,1600)){if(a.entityId===id||S(a.details).includes(x.no||'__never__')||S(a.summary).includes(x.no||'__never__'))audit.push(a);if(audit.length>=5)break}const canFileDelete=AccessControl.can('documents','delete'),canActivityDelete=AccessControl.can(cfg.page,'edit')||AccessControl.can(cfg.page,'delete'),fileRows=attachments.map(a=>`<tr><td><button type="button" class="btn link-like" data-attachment-preview="${esc(a.id)}"><b>${esc(a.name||a.fileName||'-')}</b></button></td><td>${esc(a.category||a.type||a.mime||'-')}</td><td>${formatDate(a.date||a.createdAt)}</td><td>${a.expiryDate?formatDate(a.expiryDate):'-'}</td><td><div class="party360-file-actions"><button type="button" class="btn small ghost" data-attachment-preview="${esc(a.id)}">${icon('eye','sm')} فتح</button>${canFileDelete?`<button type="button" class="btn small danger" data-party-action="removeAttachment" data-party-type="${type}" data-party-id="${id}" data-party-ref="${esc(a.id)}">${icon('trash','sm')} مسح</button>`:''}</div></td></tr>`),activity=audit.map(a=>`<div class="party360-activity"><span>${formatDateTime(a.date)}</span><b>${esc(activityActionLabel(a.action))}</b><small>${esc(a.summary||a.details||entityLabel(a.entity))}</small>${canActivityDelete?`<div class="party360-activity-actions"><button type="button" class="btn small danger" data-party-action="removeActivity" data-party-type="${type}" data-party-id="${id}" data-party-ref="${esc(a.id)}">${icon('trash','sm')} مسح</button></div>`:''}</div>`).join('');return `<div class="card party360-files-card"><div class="card-head"><h3>المرفقات</h3>${AccessControl.can('documents','add')?`<button type="button" class="btn small primary" data-party-action="attachment" data-party-type="${type}" data-party-id="${id}">+ إضافة مرفق</button>`:''}</div>${UI.table(['الملف','النوع','التاريخ','الانتهاء','إجراء'],fileRows,'لا توجد مرفقات',{export:false})}</div><div class="card mt-12"><div class="card-head"><h3>آخر النشاط</h3><span class="badge gray">${audit.length}/5</span></div><div class="party360-activity-list">${activity||'<div class="empty-state">لا توجد حركة مسجلة بعد.</div>'}</div></div>`},
 refreshFilesIfVisible(type,id){const root=document.querySelector(`#modal.show #modalBody .party360[data-party360-type="${type}"][data-party360-id="${id}"]`)||document.querySelector(`.party360[data-party360-type="${type}"][data-party360-id="${id}"]`);if(!root)return false;const active=(root.querySelector('.party360-tab.active') as HTMLElement|null)?.dataset?.party360Tab;if(active!=='files')return false;const button=root.querySelector('[data-party360-tab="files"]');this.invalidate();this.loadTab(type,id,'files',button);return true},
 removeAttachment(type,id,attachmentId){AccessControl.require('documents','delete');return this.child(()=>UI.confirmAction('مسح المرفق','سيتم حذف ملف المرفق وبياناته من النظام والخادم.',async()=>{await Party360Commands.removeAttachment(p360(),()=>Attachments.remove(attachmentId));this.invalidate();setTimeout(()=>this.refreshFilesIfVisible(type,id),40)},{label:'مسح المرفق',danger:true}))},
 removeActivity(type,id,auditId){const {cfg}=this.base(type,id);if(!(AccessControl.can(cfg.page,'edit')||AccessControl.can(cfg.page,'delete')))return notify('لا توجد صلاحية لمسح النشاط','error');return this.child(()=>UI.confirmAction('مسح النشاط','سيتم إخفاء هذا السجل من «آخر النشاط» فقط. سجل الخادم المحمي لا يتأثر.',()=>{Party360Commands.removeActivity(p360(),auditId);setTimeout(()=>this.refreshFilesIfVisible(type,id),40)},{label:'مسح',danger:true}))},
 renderTab(type,id,tab,model=null){if(tab==='financial')return this.financial(type,id);if(tab==='operations')return this.operations(type,id);if(tab==='files')return this.files(type,id);if(tab==='unified')return UnifiedParty.renderPanel(type,id);return this.overview(type,id,model)},
 updateStrip(type,model){const root=document.querySelector(`.party360[data-party360-type="${type}"][data-party360-id="${esc(model.id)}"]`);if(!root)return;for(const[k,v]of Object.entries({invoices:model.invoices,primary:model.primary,moves:model.moves,attachments:model.attachments})){const e=root.querySelector(`[data-party360-stat="${k}"]`);if(e)e.textContent=String(v)}},
 refreshVisibleHeader(){const root=document.querySelector<HTMLElement>('#modal.show #modalBody .party360[data-party-more="1"]');if(!root)return;try{const type=root.dataset.party360Type,id=root.dataset.party360Id,{x}=this.base(type,id),name=root.querySelector('[data-party-more-name]'),st=root.querySelector('[data-party-more-status]');if(name)name.textContent=x.name||x.no||'-';if(st){st.textContent=x.active===false?'موقوف':'نشط';st.className=`badge ${x.active===false?'gray':'green'}`}}catch(_){}},
 loadTab(type,id,tab='overview',button=null){const root=button?.closest?.('.party360')||document.querySelector(`.party360[data-party360-type="${type}"][data-party360-id="${id}"]`),target=root?.querySelector?.('.party360-detail');if(!target)return;for(const b of Array.from(root.querySelectorAll('.party360-tab')) as HTMLElement[])b.classList.toggle('active',b.dataset.party360Tab===tab);target.innerHTML='<div class="party360-loading">جاري تجهيز القسم…</div>';const token=++this._loadToken,run=async()=>{if(token!==this._loadToken)return;try{await this.yieldUi();const model=tab==='overview'?await this.modelAsync(type,id):null;if(token!==this._loadToken||!document.body.contains(target))return;if(model)this.updateStrip(type,model);target.innerHTML=this.renderTab(type,id,tab,model);try{UI.enhanceResponsiveTables?.(target);SearchSelect.enhanceDocument?.(target);CommercialUX.enhance?.(target)}catch(_){}}catch(e){if(document.body.contains(target))target.innerHTML=`<div class="danger-note">${esc(e.message||'تعذر فتح المزيد')}</div>`}};setTimeout(run,0)},
 content(type,id){return this.shell(type,id,{active:'overview'})},
 page(type,id){const d=this.base(type,id);setTimeout(()=>this.loadTab(type,id,'overview'),0);return Pages.head(`المزيد — ${d.x.name}`,'',`<button type="button" class="btn ghost" data-ui-go-back="1">رجوع</button>`)+this.content(type,id)},
 openMore(type,id){return this.open(type,id)},
 open(type,id){return composeParty360Presentation(this).open(type,id)}
};
__set_Party360(Party360);
export { Party360 };
