import { toast } from '../core/runtime';
import { DeleteCenter } from '../core/delete-center';
import { AutoOps } from '../documents/attachments-backup';
import { Auth } from '../security/auth';
import { Print } from '../reports/printing';
import { PageTheme, SearchSelect } from './navigation';
import { UIDelegatedActions } from './delegated-actions';
import { Pages } from '../core/late-bindings';
import { UIDocument } from './ui-fonts';
import { AccessControl } from '../security/access-control';
// Commercial overrides bound to the UI object; built once by ui.ts after UI exists.
function createUiBaseMethods(UI) {
return {
renderCurrentCommercial: (function(){this._lazyTables.clear();this.applyBrand();UIDocument.body.classList.toggle('portal-home',this.current==='dashboard'&&!this.activeWorkspace());const pages=UIDocument.getElementById('pages');pages.innerHTML=`<section class="page active">${Pages[this.current]?Pages[this.current]():Pages.notFound()}</section>`;this.enhanceResponsiveTables(pages);SearchSelect.enhanceDocument(pages);this.enhanceKeyboardInputs(pages);try{DeleteCenter?.enhanceDocument?.(pages)}catch(e){console.error('[delete-center] enhance failed',e)}this.updateTopbar()}) .bind(UI),
openPageCommercial: (function(p,id='',opts: any={}){if(!AccessControl.can(p))return toast('لا توجد صلاحية للدخول','error');const previousWorkspace=this.workspaceId,targetFocus=id||'',same=p===this.current&&targetFocus===(this.focusId||'');if(!opts.skipHistory&&!this._navRestoring&&!same)this.pushNavLocation();if(p==='dashboard'&&!opts.keepWorkspace)this.workspaceId='';else if(p!=='dashboard'){const current=this.activeWorkspace();if(!current||!(current.pages||[]).includes(p)){const owner=this.workspaceForPage(p);if(owner)this.workspaceId=owner.id}}this.current=p;this.focusId=targetFocus;this.setSidebarOpen(false);this.closeMenus();const[color,soft]=PageTheme[p]||['#2869a9','#eaf3fd'];UIDocument.documentElement.style.setProperty('--page-accent',color);UIDocument.documentElement.style.setProperty('--page-soft',soft);const navNeedsRebuild=opts.forceNav||previousWorkspace!==this.workspaceId||!UIDocument.getElementById('nav')?.children?.length;if(navNeedsRebuild)this.renderNav();else this.refreshNavActive();const m=this.pageMeta(p),ws=this.activeWorkspace();UIDocument.getElementById('pageTitle').textContent=p==='dashboard'?(ws?.name||'الصفحة الرئيسية'):m[2];UIDocument.getElementById('pageSubtitle').textContent=p==='dashboard'?(ws?.description||'اختر مساحة العمل المطلوبة'):m[3];this.renderCurrent();this.updateNavButtons();if(id)setTimeout(()=>{const el=UIDocument.querySelector(`[data-record="${CSS.escape(id)}"]`);el?.scrollIntoView({behavior:'smooth',block:'center'});el?.classList.add('focus-row');setTimeout(()=>el?.classList.remove('focus-row'),1800)},50)}) .bind(UI),
closeModalBase: (function(force=false){const m=UIDocument.getElementById('modal');if(!force&&m?.dataset.locked==='1'&&AccessControl.currentUser()?.mustChangePassword){toast('يجب تغيير كلمة المرور الافتراضية','warning');return}m?.classList.remove('show');if(m)delete m.dataset.locked;const f=UIDocument.getElementById('modalForm');if(f){f.reset();f.onsubmit=null}}) .bind(UI),
initGlobalModalStack: (function(){this.renderNav();this.applyBrand();this.renderBranchSelector();this.injectStaticIcons();SearchSelect.enhanceDocument(document);this.enhanceKeyboardInputs(document);this.observeKeyboardInputs();this.installFormKeyboardNavigation();this._navRestoring=true;this.openPage(this.current,'',{skipHistory:true});this._navRestoring=false;setTimeout(()=>AutoOps.run(),250);window.addEventListener('online',()=>AutoOps.refreshLiveFx());const gs=UIDocument.getElementById('globalSearch');gs.oninput=e=>this.scheduleGlobalSearch(e.target.value);gs.onfocus=e=>this.globalSearch(e.target.value);UIDocument.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(UIDocument.activeElement?.tagName)){e.preventDefault();if(innerWidth<=780)this.mobileSearch();else gs.focus()}if(e.key==='Escape'){this.closeMobileSidebar();this.closeMenus();this.closeModal();Print.close()}});UIDocument.addEventListener('click',e=>{const clickTarget=e.target as Element,actionMenu=(clickTarget?.closest?.('details.action-menu,details.danger-actions-menu') as HTMLDetailsElement|null)||null;if(!e.target.closest('.top-actions')&&!e.target.closest('.top-search'))this.closeMenus(actionMenu);if(actionMenu&&e.target.closest('button,a'))queueMicrotask(()=>{actionMenu.open=false});if(!clickTarget?.closest?.('.smart-picker'))UIDocument.querySelectorAll('.picker-results').forEach(x=>{x.innerHTML='';x.classList.remove('picker-mobile','picker-up');x.style.cssText=''});UIDelegatedActions.handle(clickTarget,e,this)});UIDocument.addEventListener('change',e=>UIDelegatedActions.handleChange(e.target as Element,e,this));UIDocument.addEventListener('input',e=>UIDelegatedActions.handleInput(e.target as Element,e,this));UIDocument.addEventListener('submit',e=>UIDelegatedActions.handleSubmit(e.target as Element,e,this));window.addEventListener('resize',()=>{if(innerWidth>780)this.setSidebarOpen(false)})}) .bind(UI)
};
}
export { createUiBaseMethods };
