import { S, esc, icon, toast } from '../core/runtime';
import { DB } from '../persistence/browser-store';
import { BranchScope, Commercial } from '../commercial/product';
import { Auth } from '../security/auth';
import { UI } from '../core/late-bindings';
import { UIDocument } from './ui-fonts';
import { AccessControl } from '../security/access-control';
const UI_MenusSearch = {
    closeModal: function(force=false){const m=UIDocument.getElementById('modal');if(!force&&m?.dataset.locked==='1'&&AccessControl.currentUser()?.mustChangePassword){toast('يجب تغيير كلمة المرور الافتراضية','warning');return false}if(this._modalStack.length){this._modalPending=null;const snap=this._modalStack.pop();return this.restoreModal(snap)}const pending=this._modalPending;const out=this._closeModalBase(force);this.resetModalFooter('حفظ البيانات');if(pending)setTimeout(()=>{if(this._modalPending===pending&&!UIDocument.getElementById('modal')?.classList.contains('show'))this._modalPending=null},0);return out},
    closeMenus(exceptActionMenu=null){for(const id of['notificationPanel','userMenu','searchResults'])UIDocument.getElementById(id)?.classList.add('hidden');for(const menu of UIDocument.querySelectorAll('details.action-menu[open],details.danger-actions-menu[open]'))if(menu!==exceptActionMenu)menu.open=false},
    toggleNotifications(e){e?.stopPropagation();const p=UIDocument.getElementById('notificationPanel'),open=p.classList.contains('hidden');this.closeMenus();if(!open)return;const n=Commercial.notifications();p.innerHTML=`<div class="dropdown-head"><b>التنبيهات والمتابعة</b><span class="badge ${n.length?'orange':'green'}">${n.length||'لا يوجد'}</span></div><div class="dropdown-body">${n.length?n.map(a=>`<div class="alert-item ${a.level}" data-ui-page="${esc(a.page)}"><div class="alert-copy"><b>${esc(a.title)}</b><small>${esc(a.text)}</small></div></div>`).join(''):'<div class="empty-state"><b>لا توجد تنبيهات</b></div>'}</div>`;p.classList.remove('hidden')},
    toggleUserMenu(e){e?.stopPropagation();const p=UIDocument.getElementById('userMenu'),open=p.classList.contains('hidden');this.closeMenus();if(!open)return;p.innerHTML=`<div class="dropdown-head"><b>${esc(AccessControl.currentUser()?.name||'')}</b></div><div class="dropdown-body"><div class="mini-row"><span>الفرع</span><b>${esc(BranchScope.current()?.name||'-')}</b></div><button class="btn ghost" style="width:100%;margin-top:6px" data-form-open="changePassword" data-ui-close-menus="1">تغيير كلمة المرور</button>${AccessControl.can('settings')?'<button class="btn ghost" style="width:100%;margin-top:6px" data-ui-page="settings">الإعدادات</button>':''}<button class="btn danger" style="width:100%;margin-top:6px" data-auth-logout="1">تسجيل الخروج</button></div>`;p.classList.remove('hidden')},
    selectSearchResult(page,id){const gs=UIDocument.getElementById('globalSearch');if(gs)gs.value='';const p=UIDocument.getElementById('searchResults');if(p){p.innerHTML='';p.classList.add('hidden')}this.focusId='';this.openPage(page,id)},
    searchNormalize(v){return S(v??'').toLowerCase().normalize('NFD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/\s+/g,' ').trim()},
    searchBlob(v,seen=new WeakSet()){if(v==null)return'';if(['string','number','boolean'].includes(typeof v))return this.searchNormalize(v);if(typeof v!=='object'||seen.has(v))return'';seen.add(v);return Object.values(v).map(x=>this.searchBlob(x,seen)).join(' ')},
    searchRecords(q,limit=40){q=this.searchNormalize(q);if(q.length<2)return[];const defs=[['customers','customers','عميل'],['suppliers','suppliers','مورد'],['agents','agents','مندوب'],['leads','crm','Lead'],['quotations','quotations','عرض'],['purchaseOrders','purchaseorders','أمر شراء'],['invoices','invoices','فاتورة'],['bookings','bookings','حجز'],['travelers','bookings','مسافر'],['services','services','خدمة'],['receipts','receipts','قبض'],['payments','payments','صرف'],['expenses','expenses','مصروف'],['transfers','treasury','تحويل'],['treasuries','treasury','خزنة/بنك'],['cheques','treasury','شيك'],['accounts','accounts','حساب'],['costCenters','costcenters','مركز تكلفة'],['documents','documents','مستند'],['approvals','approvals','اعتماد']];const res=[],add=(x,page,label)=>{if(!x||!this.searchBlob(x).includes(q))return false;res.push({page,id:x.id||'',label,title:x.no||x.name||x.title||x.username||x.code||x.passportNo||x.ticketNo||x.visaNo||'',sub:x.name||x.description||x.title||x.memo||x.phone||x.route||x.passportNo||''});return res.length>=limit};for(const[k,page,label]of defs){for(const x of DB.data[k]||[])if(add(x,page,label))return res}const um={programs:DB.data.umrahPrograms||[],bookings:DB.data.umrahBookings||[],travelers:DB.data.umrahTravelers||[],programSegments:DB.data.umrahProgramSegments||[],visaItems:DB.data.umrahVisaItems||[],tickets:DB.data.umrahTickets||[],busRuns:DB.data.umrahBusRuns||[],incidents:DB.data.umrahIncidents||[]},branchId=BranchScope.currentId(),branchOk=x=>!x?.branchId||!branchId||x.branchId===branchId,extras=[ [(um.programs||[]).filter(x=>x?.deleted!==true&&branchOk(x)),'umrah-programs','برنامج حج/عمرة'],[(um.bookings||[]).filter(branchOk),'umrah-bookings','حجز حج/عمرة'],[(um.travelers||[]).filter(branchOk),'umrah-travelers','مسافر حج/عمرة'],[(um.programSegments||[]).filter(branchOk),'umrah-programs','خدمة برنامج حج/عمرة'],[(um.visaItems||[]).filter(branchOk),'umrah-visas','تأشيرة حج/عمرة'],[(um.tickets||[]).filter(branchOk),'umrah-flights','تذكرة حج/عمرة'],[(um.busRuns||[]).filter(branchOk),'umrah-transport','نقل حج/عمرة'],[(um.incidents||[]).filter(branchOk),'umrah-incidents','مشكلة تشغيل حج/عمرة'] ];for(const[arr,page,label]of extras)for(const x of arr)if(add(x,page,label))return res;return res},
    mobileSearch(){const m=UIDocument.getElementById('modal'),f=UIDocument.getElementById('modalForm');UIDocument.getElementById('modalTitle').textContent='البحث في النظام';UIDocument.getElementById('modalSubtitle').textContent='ابحث بالاسم أو الرقم أو الهاتف أو الجواز أو البيانات المرتبطة.';UIDocument.getElementById('modalIcon').innerHTML=icon('search');UIDocument.getElementById('modalSubmitText').textContent='إغلاق';UIDocument.getElementById('modalBody').innerHTML=`<div class="field"><label>بحث</label><input id="mobileGlobalSearch" type="search" placeholder="اسم، هاتف، رقم مستند، جواز..." data-mobile-search="1"></div><div id="mobileSearchResults" class="mobile-search-results"><div class="empty-state">اكتب حرفين على الأقل.</div></div>`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)};setTimeout(()=>UIDocument.getElementById('mobileGlobalSearch')?.focus(),50)},
    mobileSearchRender(q){const b=UIDocument.getElementById('mobileSearchResults');if(!b)return;const r=this.searchRecords(q,30);b.innerHTML=r.length?r.map(x=>`<button type="button" class="mobile-search-row" data-ui-modal-page="${esc(x.page)}" data-ui-modal-page-id="${esc(x.id)}"><span>${icon(x.page,'sm')}</span><div><b>${esc(x.label)} — ${esc(x.title)}</b><small>${esc(x.sub)}</small></div></button>`).join(''):'<div class="empty-state">لا توجد نتائج.</div>'},
    scheduleGlobalSearch(q){clearTimeout(this._searchTimer);this._searchTimer=setTimeout(()=>this.globalSearch(q),120)},
    globalSearch(q,mobile=false){if(mobile)return this.mobileSearch();q=this.searchNormalize(q);const p=UIDocument.getElementById('searchResults');if(q.length<2){p.classList.add('hidden');return}const r=this.searchRecords(q,40);p.innerHTML=r.length?r.map(x=>`<div class="search-result" data-ui-search-result="${x.page}" data-ui-search-result-id="${esc(x.id)}"><div class="result-icon">${icon(x.page,'sm')}</div><div><b>${esc(x.label)} — ${esc(x.title)}</b><small>${esc(x.sub)}</small></div></div>`).join(''):'<div class="empty-state"><b>لا توجد نتائج</b></div>';p.classList.remove('hidden')},
    enhanceResponsiveTables(root: any=UIDocument){const doc=root.ownerDocument||root,actionRe=/إجراء|الإجراءات|actions?/i,primaryRe=/الكود|الرقم|الاسم|الطرف|العميل|المورد|المندوب|الموظف|النوع|الهاتف|التاريخ|الاستحقاق|الإجمالي|المبلغ|المدفوع|المتبقي|الرصيد|الحالة|البرنامج|العملة|القيمة/i,secondaryRe=/مرجع|دفعة مقدمة|مرفقات|تأخير|ملاحظات|وصف|البنك|طريقة الدفع|أنشئ|تحديث/i;for(const t of root.querySelectorAll('.table-card table.table:not([data-responsive-ready])')){t.dataset.responsiveReady='1';t.classList.add('responsive-card-table','system-compact-table');const hs=[...t.querySelectorAll('thead th')].map(x=>x.textContent.trim());for(const tr of t.querySelectorAll('tbody tr')){if(tr.querySelector('[colspan]'))continue;const cells=[...tr.cells];cells.forEach((td,i)=>{const label=hs[i]||'';td.dataset.label=label;if(actionRe.test(label))td.classList.add('compact-action');else if(primaryRe.test(label)&&!secondaryRe.test(label))td.classList.add('compact-primary');else td.classList.add('compact-secondary')});const action=cells.find(td=>td.classList.contains('compact-action')),secondary=cells.filter(td=>td.classList.contains('compact-secondary'));if(secondary.length&&action&&!action.hasAttribute('data-no-compact-details')&&!action.querySelector('.compact-details-toggle')){const b=doc.createElement('button');b.type='button';b.className='compact-details-toggle';b.textContent='تفاصيل';b.addEventListener('click',e=>{e.stopPropagation();tr.classList.toggle('compact-expanded');b.textContent=tr.classList.contains('compact-expanded')?'إخفاء التفاصيل':'تفاصيل'});action.appendChild(b)}if(!action)for(const td of secondary)td.classList.remove('compact-secondary')}}}
};
export { UI_MenusSearch };
