import { N, icon } from '../core/runtime';
import { UiBaseMethods } from '../core/late-bindings';
import { ensureSystemFontAsset } from './ui-fonts';
import { UIDocument } from './ui-fonts';
const UI_ModalSettings = {
    ensureModalFooter: function(){const m=UIDocument.getElementById('modal'),f=UIDocument.getElementById('modalForm'),foot=UIDocument.getElementById('modalFoot');if(!m?.classList.contains('show')||!f||!foot)return;const submit=foot.querySelector('button[type="submit"]');if(foot.dataset.mode!=='view'&&f.onsubmit&&submit){submit.classList.remove('hidden');submit.style.display='inline-flex';submit.disabled=false;submit.removeAttribute('aria-hidden');submit.removeAttribute('tabindex')}},
    installModalFooterGuard: function(){if(this._modalFooterGuard||!UIDocument.getElementById('modal'))return;this._modalFooterGuard=new MutationObserver(()=>queueMicrotask(()=>this.ensureModalFooter()));this._modalFooterGuard.observe(UIDocument.getElementById('modal'),{attributes:true,attributeFilter:['class']})},
    previewFontScale: function(value,el){const select=UIDocument.getElementById('setFontScale');if(select)select.value=String(value);UIDocument.querySelectorAll('.font-size-option').forEach(b=>b.classList.toggle('active',b===el));const sample=UIDocument.getElementById('fontSizeLivePreview');if(sample){sample.style.fontSize=`${15*N(value)}px`;sample.textContent=`معاينة الخط — ${Math.round(15*N(value))}px • الحج والعمرة والمحاسبة والعملاء`}},
    previewFontFamily: function(value,el){const select=UIDocument.getElementById('setFontFamily');if(select)select.value=String(value);UIDocument.querySelectorAll('.font-family-option').forEach(b=>b.classList.toggle('active',b===el));const font=ensureSystemFontAsset(value);UIDocument.documentElement.style.setProperty('--system-font',font.stack);const sample=UIDocument.getElementById('fontFamilyLivePreview');if(sample)sample.style.fontFamily=font.stack},
    settingsTabId: 'company',
    settingsDirty: false,
    settingsSignature: function(){const active=[...UIDocument.querySelectorAll('.settings-grid>.settings-tab-active input,.settings-grid>.settings-tab-active select,.settings-grid>.settings-tab-active textarea')];return JSON.stringify(active.map(x=>[x.id||x.name||x.dataset.prefix||'',x.type==='checkbox'?x.checked:x.value]))},
    openSettingsTab: function(key,force=false){if(!force&&this.settingsDirty&&!confirm('توجد تعديلات غير محفوظة في هذا القسم. هل تريد الانتقال بدون حفظها؟'))return false;const grid=UIDocument.querySelector('.settings-grid'),jump=UIDocument.querySelector('.settings-jump');if(!grid||!jump)return false;const cards=[...grid.children],groups={company:[0],layout:[1],accounting:[2,3],print:[4],backup:[5],license:[6]},keys=['company','layout','accounting','print','backup','license'];this.settingsTabId=groups[key]?key:'company';cards.forEach((card,i)=>card.classList.toggle('settings-tab-active',(groups[this.settingsTabId]||[]).includes(i)));[...jump.querySelectorAll('button')].forEach((button,i)=>{const tab=keys[i]||'company';button.dataset.settingsTab=tab;button.classList.toggle('active',tab===this.settingsTabId);button.setAttribute('aria-selected',tab===this.settingsTabId?'true':'false')});this.settingsDirty=false;this._settingsBaseline=this.settingsSignature();const flag=jump.querySelector('.settings-unsaved');if(flag)flag.remove();return true},
    initSettingsTabs: function(){const grid=UIDocument.querySelector('.settings-grid'),jump=UIDocument.querySelector('.settings-jump');if(!grid||!jump)return;grid.classList.add('settings-tabs');jump.setAttribute('role','tablist');this.openSettingsTab(this.settingsTabId||'company',true);const updateDirty=()=>{this.settingsDirty=this.settingsSignature()!==this._settingsBaseline;let flag=jump.querySelector('.settings-unsaved');if(this.settingsDirty&&!flag){flag=UIDocument.createElement('span');flag.className='settings-unsaved';flag.textContent='تعديلات غير محفوظة';jump.appendChild(flag)}else if(!this.settingsDirty)flag?.remove()};grid.addEventListener('input',updateDirty);grid.addEventListener('change',updateDirty);grid.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&/حفظ/.test(b.textContent))setTimeout(()=>{this.settingsDirty=false;this._settingsBaseline=this.settingsSignature();jump.querySelector('.settings-unsaved')?.remove()},0)})},
    _modalPending: null,
    _modalRestoring: false,
    _modalStackInstalled: false,
    modalSignature: function(s){return s?[s.title||'',s.subtitle||'',s.submit||'',s.icon||''].join('\u241f'):''},
    _pushModalSnapshot: function(s){if(!s)return false;const sig=this.modalSignature(s),top=this._modalStack[this._modalStack.length-1];if(top&&this.modalSignature(top)===sig)return false;this._modalStack.push(s);if(this._modalStack.length>20)this._modalStack.shift();return true},
    armModalContext: function(){if(this._modalRestoring)return null;const snap=this.captureModal();if(!snap)return null;this._modalPending={snap,ancestry:this._modalStack.slice(),signature:this.modalSignature(snap),at:Date.now()};return snap},
    commitModalContext: function(){if(this._modalRestoring||!this._modalPending)return false;const pending=this._modalPending,current=this.captureModal();if(!current)return false;const changed=this.modalSignature(current)!==pending.signature;if(!changed)return false;this._modalStack=pending.ancestry.slice();this._pushModalSnapshot(pending.snap);this._modalPending=null;return true},
    modalChild: function(fn){const snap=this.captureModal();if(!snap)return fn();const ancestry=this._modalStack.slice();this._pushModalSnapshot(snap);try{return fn()}catch(e){this._modalStack=ancestry;this.restoreModal(snap);throw e}},
    clearModalStack: function(){this._modalStack.length=0;this._modalPending=null},
    _closeModalBase: function(force=false){return UiBaseMethods.closeModalBase(force)},
    closeModalAll: function(force=false){this.clearModalStack();return this._closeModalBase(force)},
    partyControls: function(type,id,{compact=false}={}){const safeType=['customer','supplier','agent'].includes(type)?type:'customer';return `<div class="party-control-pair ${compact?'compact':''}" data-no-compact-details="1"><button type="button" class="btn small primary party-action-trigger" data-ui-party-actions="${safeType}" data-ui-party-id="${id}">${icon('activity','sm')} <span>الإجراءات</span></button><button type="button" class="btn small soft party-more-trigger" data-ui-party-more="${safeType}" data-ui-party-id="${id}">${icon('more','sm')} <span>المزيد</span></button></div>`}
};
export { UI_ModalSettings };
