import { esc, icon } from '../core/runtime';
import { Party360 } from './party360';
import { SearchSelect } from './navigation';
import { UIDocument } from './ui-fonts';
// Modal snapshot/restore stack helpers, installed onto the UI object by ui.ts.
function installUiModalStack(UI) {
UI._modalStack=[];
UI.captureModalControls=function(f){if(!f)return[];return [...f.querySelectorAll('input,select,textarea')].map((el,index)=>({index,name:el.name||'',id:el.id||'',tag:el.tagName,type:el.type||'',value:el.value,checked:!!el.checked,selected:el.tagName==='SELECT'?[...el.options].filter(o=>o.selected).map(o=>o.value):[]}))};
UI.restoreModalControls=function(f,items=[]){if(!f||!items?.length)return;const els=[...f.querySelectorAll('input,select,textarea')];for(const x of items){let el=els[x.index];if(!el||(x.id&&el.id!==x.id)||(x.name&&el.name!==x.name))el=(x.id&&f.querySelector(`#${CSS.escape(x.id)}`))||(x.name&&[...f.querySelectorAll(`[name="${CSS.escape(x.name)}"]`)].find(n=>n.tagName===x.tag))||null;if(!el)continue;if(el.tagName==='SELECT'){const wanted=new Set(x.selected||[x.value]);for(const o of el.options)o.selected=wanted.has(o.value)}else if(el.type==='checkbox'||el.type==='radio')el.checked=!!x.checked;else el.value=x.value??''}};
UI.captureModal=function(){const m=UIDocument.getElementById('modal'),f=UIDocument.getElementById('modalForm'),body=UIDocument.getElementById('modalBody'),foot=UIDocument.getElementById('modalFoot');if(!m?.classList.contains('show')||!f||!body)return null;return{title:UIDocument.getElementById('modalTitle')?.textContent||'',subtitle:UIDocument.getElementById('modalSubtitle')?.textContent||'',icon:UIDocument.getElementById('modalIcon')?.innerHTML||'',submit:UIDocument.getElementById('modalSubmitText')?.textContent||'حفظ',body:body.innerHTML,foot:foot?.innerHTML||'',locked:m.dataset.locked||'',noValidate:!!f.noValidate,onsubmit:f.onsubmit,controls:this.captureModalControls(f),scrollTop:body.scrollTop||0}};
UI.restoreModal=function(s){if(!s)return false;const m=UIDocument.getElementById('modal'),f=UIDocument.getElementById('modalForm'),body=UIDocument.getElementById('modalBody'),foot=UIDocument.getElementById('modalFoot');if(!m||!f||!body)return false;this._modalRestoring=true;try{UIDocument.getElementById('modalTitle').textContent=s.title;UIDocument.getElementById('modalSubtitle').textContent=s.subtitle;UIDocument.getElementById('modalIcon').innerHTML=s.icon;if(foot&&s.foot)foot.innerHTML=s.foot;UIDocument.getElementById('modalSubmitText').textContent=s.submit;body.innerHTML=s.body;if(s.locked)m.dataset.locked=s.locked;else delete m.dataset.locked;f.noValidate=s.noValidate;f.onsubmit=s.onsubmit;this.restoreModalControls(f,s.controls);m.classList.add('show');SearchSelect.enhanceDocument(m);setTimeout(()=>{const mb=UIDocument.getElementById('modalBody');if(mb)mb.scrollTop=s.scrollTop||0;try{Party360?.refreshVisibleHeader?.();const pr=mb?.querySelector?.('.party360[data-party-more="1"]');if(pr&&pr.querySelector('.party360-tab.active')?.dataset?.party360Tab==='files')Party360.refreshFilesIfVisible(pr.dataset.party360Type,pr.dataset.party360Id)}catch(_){ }},0);return true}finally{this._modalRestoring=false}};
UI.installGlobalModalStack=function(){if(this._modalStackInstalled)return;const m=UIDocument.getElementById('modal'),f=UIDocument.getElementById('modalForm'),title=UIDocument.getElementById('modalTitle'),subtitle=UIDocument.getElementById('modalSubtitle'),submit=UIDocument.getElementById('modalSubmitText');if(!m||!f||!title)return;this._modalStackInstalled=true;const arm=(e: any)=>{if(this._modalRestoring||!m.classList.contains('show'))return;const t=e.target?.closest?.('button,a,input[type="button"],input[type="submit"],[role="button"],summary');if(!t||!m.contains(t))return;this.armModalContext()};document.addEventListener('pointerdown',arm,true);f.addEventListener('submit',()=>{if(m.classList.contains('show'))this.armModalContext()},true);const observer=new MutationObserver(()=>{if(this._modalRestoring||!this._modalPending)return;queueMicrotask(()=>this.commitModalContext())});for(const el of[title,subtitle,submit])if(el)observer.observe(el,{childList:true,subtree:true,characterData:true});this._modalObserver=observer};
UI.resetModalFooter=function(label='حفظ البيانات',{danger=false,hideSubmit=false,cancel='إلغاء'}={}){const foot=UIDocument.getElementById('modalFoot');if(!foot)return null;foot.dataset.mode=hideSubmit?'view':'edit';foot.innerHTML=`<button class="btn ${danger?'danger':'primary'}${hideSubmit?' hidden':''}" type="submit" ${hideSubmit?'aria-hidden="true" tabindex="-1"':''}><span id="modalSaveIcon">${icon(danger?'warning':'save','sm')}</span><span id="modalSubmitText">${esc(label||'تأكيد')}</span></button><button class="btn ghost" type="button" data-ui-close-modal="1">${esc(cancel||'إلغاء')}</button>`;const btn=foot.querySelector('[type=submit]');if(btn){btn.style.display=hideSubmit?'none':'inline-flex';btn.disabled=!!hideSubmit}return btn};
}
export { installUiModalStack };
