import { N, S, esc, icon, sc, sl, toast, today } from '../core/runtime';
import { Auth } from '../security/auth';
import { UI } from '../core/late-bindings';
import { UIDocument } from './ui-fonts';
import { AccessControl } from '../security/access-control';
const UI_Tables = {
    confirmAction: function(title,message,onConfirm,opts: any={}){const m=UIDocument.getElementById('modal'),f=UIDocument.getElementById('modalForm');UIDocument.getElementById('modalTitle').textContent=title;UIDocument.getElementById('modalSubtitle').textContent=opts.subtitle||'راجع تأثير العملية قبل التنفيذ.';UIDocument.getElementById('modalIcon').innerHTML=icon('warning');this.resetModalFooter(opts.label||'تأكيد',{danger:opts.danger!==false,cancel:opts.cancel||'إلغاء'});UIDocument.getElementById('modalBody').innerHTML=`<div class="danger-note">${esc(message)}</div>`;m.classList.add('show');f.noValidate=true;f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('[type=submit]');if(btn?.disabled)return;if(btn)btn.disabled=true;try{await onConfirm();if(UIDocument.getElementById('modal')?.classList.contains('show'))UI.closeModal(true)}catch(err){toast(err.message||'تعذر تنفيذ العملية','error');if(btn)btn.disabled=false}}},
    reasonAction: function(title,message,onConfirm){const m=UIDocument.getElementById('modal'),f=UIDocument.getElementById('modalForm');UIDocument.getElementById('modalTitle').textContent=title;UIDocument.getElementById('modalSubtitle').textContent='السبب سيحفظ في سجل المراجعة.';UIDocument.getElementById('modalIcon').innerHTML=icon('warning');this.resetModalFooter('تأكيد',{danger:true});UIDocument.getElementById('modalBody').innerHTML=`<div class="info-note">${esc(message)}</div><div class="field mt-12"><label>السبب</label><textarea name="reason" required minlength="3"></textarea></div>`;m.classList.add('show');f.noValidate=false;f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('[type=submit]');if(btn?.disabled)return;if(btn)btn.disabled=true;try{await onConfirm(S(new FormData(f).get('reason')).trim());UI.closeModal(true)}catch(err){toast(err.message||'تعذر تنفيذ العملية','error');if(btn)btn.disabled=false}}},
    tableRowText(html){try{const t=UIDocument.createElement('template');t.innerHTML=S(html);return S(t.content.textContent||'')}catch{return S(html).replace(/<[^>]*>/g,' ')}},
    tableRowCells(html){try{const t=UIDocument.createElement('template');t.innerHTML=S(html);const tr=t.content.querySelector('tr');return tr?[...tr.cells].map(c=>S(c.innerText||c.textContent||'').trim()):[]}catch{return[]}},
    table(headers,rows,empty='لا توجد بيانات',opts: any={}){
  const list=Array.isArray(rows)?rows:(rows?[S(rows)]:[]),noSort=h=>/إجراء|الإجراءات|actions?/i.test(S(h)),ths=headers.map((h,i)=>`<th class="${noSort(h)?'':'sortable'}" data-export="${noSort(h)?'0':'1'}" ${noSort(h)?'':`data-ui-sort-index="${i}"`}>${h}</th>`).join(''),pageSize=Math.max(10,N(opts.pageSize)||25),paged=opts.paginate!==false&&list.length>pageSize,key=paged?`ui-table-${++this._lazySeq}`:'',shown=paged?list.slice(0,pageSize):list;
  if(paged)this._lazyTables.set(key,{rows:[...list],filtered:[...list],searchIndex:list.map(r=>this.searchNormalize(this.tableRowText(r))),page:1,pageSize,headers:[...headers],empty,query:''});
  const pager=paged?this.tablePager(key,this._lazyTables.get(key)):'';
  return `<div class="table-card" ${key?`data-lazy-table="${key}"`:''}><div class="table-tools"><span class="table-count" data-total="${list.length}">${paged?`1–${shown.length} من ${list.length} سجل`:`${list.length} سجل`}</span>${opts.search===false?'':`<div class="table-search">${icon('search','sm')}<input aria-label="بحث داخل الجدول" placeholder="بحث بالاسم أو الرقم..." data-ui-filter-table="1"></div>`}${opts.export===false||!AccessControl.can(this.current,'export')?'':`<button class="btn small ghost" data-ui-export-table="1">${icon('csv','sm')} CSV</button>`}</div><div class="table-wrap"><table class="table"><thead><tr>${ths}</tr></thead><tbody>${shown.length?shown.join(''):`<tr><td colspan="${headers.length}" class="empty">${empty}</td></tr>`}</tbody></table></div>${pager}</div>`
 },
    tablePager(key,rec){if(!rec)return'';const total=rec.filtered.length,pages=Math.max(1,Math.ceil(total/rec.pageSize));if(total<=rec.pageSize)return'';return `<div class="table-pagination" data-table-pager="${key}"><button type="button" class="btn small ghost" data-ui-page-table="${key}" data-ui-page-dir="-1" ${rec.page<=1?'disabled':''}>السابق</button><span class="table-page-status">صفحة <b>${rec.page}</b> من <b>${pages}</b></span><button type="button" class="btn small ghost" data-ui-page-table="${key}" data-ui-page-dir="1" ${rec.page>=pages?'disabled':''}>التالي</button></div>`},
    renderTablePage(key,card){const rec=this._lazyTables.get(key);if(!rec||!card)return false;const total=rec.filtered.length,pages=Math.max(1,Math.ceil(total/rec.pageSize));rec.page=Math.min(Math.max(1,rec.page),pages);const from=(rec.page-1)*rec.pageSize,to=Math.min(total,from+rec.pageSize),rows=rec.filtered.slice(from,to),body=card.querySelector('tbody');body.innerHTML=rows.length?rows.join(''):`<tr><td colspan="${rec.headers.length}" class="empty">${rec.empty}</td></tr>`;const count=card.querySelector('.table-count');if(count)count.textContent=total?(rec.query?`${from+1}–${to} من ${total} نتيجة`:`${from+1}–${to} من ${total} سجل`):(rec.query?'0 نتيجة':'0 سجل');let pager=card.querySelector('.table-pagination');const html=this.tablePager(key,rec);if(html){if(pager)pager.outerHTML=html;else card.insertAdjacentHTML('beforeend',html)}else pager?.remove();const table=body.closest('table');table?.removeAttribute('data-responsive-ready');this.enhanceResponsiveTables(card);return true},
    pageTable(key,delta,btn){const rec=this._lazyTables.get(key),card=btn?.closest?.('.table-card')||UIDocument.querySelector(`[data-lazy-table="${CSS.escape(key)}"]`);if(!rec||!card)return false;const pages=Math.max(1,Math.ceil(rec.filtered.length/rec.pageSize));rec.page=Math.min(pages,Math.max(1,rec.page+N(delta)));this.renderTablePage(key,card);card.scrollIntoView({behavior:'smooth',block:'nearest'});return true},
    loadMoreTable(key,btn,all=false){const rec=this._lazyTables.get(key);if(!rec)return false;if(all){rec.pageSize=Math.max(rec.pageSize,rec.filtered.length||1);rec.page=1;return this.renderTablePage(key,btn?.closest?.('.table-card')||UIDocument.querySelector(`[data-lazy-table="${CSS.escape(key)}"]`))}return this.pageTable(key,1,btn)},
    loadAllTable(card){const key=card?.dataset?.lazyTable;return key?this._lazyTables.get(key):null},
    filterTable(input){const card=input.closest('.table-card'),q=this.searchNormalize(input.value),key=card?.dataset?.lazyTable,rec=key?this._lazyTables.get(key):null;if(rec){rec.query=q;rec.filtered=q?rec.rows.filter((_,i)=>rec.searchIndex[i].includes(q)):[...rec.rows];rec.page=1;return this.renderTablePage(key,card)}const rows=[...card.querySelectorAll('tbody tr')].filter(tr=>!tr.querySelector('td.empty'));let shown=0;for(const tr of rows){const ok=!q||this.searchNormalize(tr.textContent).includes(q);tr.style.display=ok?'':'none';if(ok)shown++}const count=card.querySelector('.table-count'),total=N(count?.dataset?.total||rows.length);if(count)count.textContent=q?`${shown} من ${total} سجل`:`${total} سجل`},
    sortTable(th,index){if(th.dataset.export==='0')return;const card=th.closest('.table-card'),key=card?.dataset?.lazyTable,rec=key?this._lazyTables.get(key):null,stateKey=`${this.current}:${index}`,dir=this.sortState[stateKey]==='asc'?'desc':'asc';this.sortState[stateKey]=dir;for(const x of th.parentElement.children)x.removeAttribute('aria-sort');th.setAttribute('aria-sort',dir==='asc'?'ascending':'descending');const cmp=(a,b)=>{const A=this.tableRowCells(a)[index]||'',B=this.tableRowCells(b)[index]||'',an=parseFloat(A.replace(/[^0-9.-]/g,'')),bn=parseFloat(B.replace(/[^0-9.-]/g,'')),v=Number.isFinite(an)&&Number.isFinite(bn)?an-bn:A.localeCompare(B,'ar',{numeric:true,sensitivity:'base'});return dir==='asc'?v:-v};if(rec){if(rec.query)rec.filtered.sort(cmp);else{rec.rows.sort(cmp);rec.searchIndex=rec.rows.map(r=>this.searchNormalize(this.tableRowText(r)));rec.filtered=[...rec.rows]}rec.page=1;return this.renderTablePage(key,card)}const body=th.closest('table').tBodies[0],rows=[...body.rows].filter(r=>!r.querySelector('td.empty'));rows.sort((a,b)=>{const A=a.cells[index]?.innerText.trim()||'',B=b.cells[index]?.innerText.trim()||'',an=parseFloat(A.replace(/[^0-9.-]/g,'')),bn=parseFloat(B.replace(/[^0-9.-]/g,'')),cmp=Number.isFinite(an)&&Number.isFinite(bn)?an-bn:A.localeCompare(B,'ar',{numeric:true,sensitivity:'base'});return dir==='asc'?cmp:-cmp});rows.forEach(r=>body.appendChild(r))},
    exportTable(btn){const card=btn.closest('.table-card'),table=card.querySelector('table'),include=[...table.tHead.rows[0].cells].map((c,i)=>c.dataset.export!=='0'?i:-1).filter(i=>i>=0),key=card?.dataset?.lazyTable,rec=key?this._lazyTables.get(key):null,quote=v=>`"${S(v).replace(/"/g,'""').replace(/\n+/g,' ')}"`;let lines;if(rec){lines=[include.map(i=>quote(table.tHead.rows[0].cells[i]?.innerText||'')).join(','),...rec.filtered.map(html=>{const cells=this.tableRowCells(html);return include.map(i=>quote(cells[i]||'')).join(',')})]}else lines=[...table.rows].filter(r=>r.style.display!=='none'&&!r.querySelector('td.empty')).map(r=>include.map(i=>quote(r.cells[i]?.innerText||'')).join(','));const blob=new Blob(['﻿'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=UIDocument.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`${UIDocument.getElementById('pageTitle').textContent}_${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},
    kpi(label,value,note='',cls='info',ic='reports'){return `<div class="kpi ${cls}"><div class="kpi-top"><div class="label">${label}</div><div class="kpi-icon">${icon(ic)}</div></div><div class="value">${value}</div><div class="note">${note}</div></div>`},
    listFilter(scope){return this.listFilters?.[scope]||'all'},
    setListFilter(scope,key){this.listFilters=this.listFilters||{};this.listFilters[scope]=key||'all';this.renderCurrent();return true},
    applyListFilter(scope,items,rules={}){const list=Array.isArray(items)?items:[],key=this.listFilter(scope),fn=rules?.[key];return key==='all'||typeof fn!=='function'?list:list.filter((x,i)=>{try{return !!fn(x,i)}catch{return false}})},
    smartFilterStrip(scope,cards=[],opts: any={}){const active=this.listFilter(scope),safeScope=esc(scope),extra=esc(opts?.className||''),rich=opts?.rich===true||S(opts?.className||'').includes('dashboard-filter-grid');return `<div class="smart-filter-grid ${rich?'':'simple-list-filter'} ${extra}" role="group" aria-label="فلترة سريعة">${cards.map(c=>{const key=S(c.key||'all'),on=active===key,label=esc(c.label||''),note=esc(c.note||'فلترة'),value=c.value==null?'0':c.value,targetScope=esc(c.targetScope||''),targetKey=esc(c.targetKey||''),targetPage=esc(c.targetPage||''),targetKind=esc(c.targetKind||''),attrs=`data-ui-filter-scope="${safeScope}" data-ui-filter-key="${esc(key)}"${targetScope?` data-ui-filter-target-scope="${targetScope}"`:''}${targetKey?` data-ui-filter-target-key="${targetKey}"`:''}${targetPage?` data-ui-filter-target-page="${targetPage}"`:''}${targetKind?` data-ui-filter-target-kind="${targetKind}"`:''}`;return rich?`<button type="button" class="smart-filter-kpi ${c.cls||'info'} ${on?'filter-active':''}" aria-pressed="${on?'true':'false'}" title="${label}${note?' — '+note:''}" ${attrs}><span class="smart-filter-icon">${icon(c.ic||'reports','sm')}</span><span class="smart-filter-copy"><b>${label}</b><small>${note}</small></span><strong class="smart-filter-value">${value}</strong></button>`:`<button type="button" class="smart-filter-kpi simple-filter-option ${on?'filter-active':''}" aria-pressed="${on?'true':'false'}" title="${label}${note?' — '+note:''}" ${attrs}><span class="simple-filter-label">${label}</span><strong class="simple-filter-count">${value}</strong></button>`}).join('')}</div>`},
    filterOption(label,count,on,action,ic='reports',cls='info'){const text=esc(label||''),spec=action&&typeof action==='object'?action:null,code=spec?'':S(action||''),m=code.match(/^UI\.setListFilter\(['"]([^'"]+)['"],['"]([^'"]+)['"]\)$/),scope=esc(spec?.scope||m?.[1]||''),key=esc(spec?.key||m?.[2]||'all'),history=spec?.type==='umrahHistory'&&spec?.kind&&spec?.value?` data-umrah-history-kind="${esc(spec.kind)}" data-umrah-history-value="${esc(spec.value)}"`:'',attrs=history||scope?`${history}${scope?` data-ui-filter-scope="${scope}" data-ui-filter-key="${key}"`:''}`:' disabled';return `<button type="button" class="smart-filter-kpi smart-filter-mini simple-filter-option ${on?'filter-active':''}" aria-pressed="${on?'true':'false'}"${attrs}><span class="simple-filter-label">${text}</span><strong class="simple-filter-count">${count??0}</strong></button>`},
    badge(s){return `<span class="badge ${sc(s)}">${sl(s)}</span>`}
};
export { UI_Tables };
