import { EPS, N, S, deep, esc, icon, live, toast } from '../core/runtime';
import { DB } from '../persistence/browser-store';
import { Commercial } from '../commercial/product';
import { Accounting } from '../accounting/engine';
import { Invoices } from '../accounting/invoices';
import { Auth } from '../security/auth';
import { Nav, SuiteWorkspaceNav } from './navigation';
import { WorkCenter } from '../core/late-bindings';
import { UI } from '../core/late-bindings';
import { UiBaseMethods } from '../core/late-bindings';
import { UIDocument } from './ui-fonts';
import { AccessControl } from '../security/access-control';
const UI_WorkspaceNav = {
    workspaces(){const rows=(DB.data.settings.workspaces||[]).filter(w=>w.active!==false&&w.id!=='vendor-owner').map(w=>({...w,pages:(w.pages||[]).filter(p=>p!=='vendorowner')}));if(typeof Auth==='undefined'||!AccessControl.currentUser())return rows;return rows.filter(w=>(w.pages||[]).some(p=>AccessControl.can(p)))},
    activeWorkspace(){return this.workspaces().find(w=>w.id===this.workspaceId)||null},
    workspaceForPage(page){return this.workspaces().find(w=>(w.pages||[]).includes(page))||null},
    workspaceModules(ws=this.activeWorkspace()){if(!ws)return[];if(SuiteWorkspaceNav[ws.id])return SuiteWorkspaceNav[ws.id].filter(m=>AccessControl.can(m[0]));const meta=Nav.flatMap(g=>g[1]);return (ws.pages||[]).map(p=>meta.find(m=>m[0]===p)).filter(Boolean).filter(m=>m[0]!=='vendorowner').filter(m=>AccessControl.can(m[0]))},
    captureNavLocation(){return{type:'page',page:this.current||'dashboard',workspaceId:this.workspaceId||'',focusId:this.focusId||''}},
    navKey(loc){return loc?`page:${loc.workspaceId||''}:${loc.page||''}:${loc.focusId||''}`:''},
    pushNavLocation(loc=this.captureNavLocation()){if(this._navRestoring||!loc)return;const last=this.navHistory[this.navHistory.length-1];if(last&&this.navKey(last)===this.navKey(loc))return;this.navHistory.push(deep(loc));if(this.navHistory.length>60)this.navHistory.shift();this.updateNavButtons()},
    restoreNavLocation(loc){if(!loc)return false;this._navRestoring=true;try{this.workspaceId=loc.workspaceId||'';if(loc.page==='dashboard'&&this.workspaceId){this.openWorkspace(this.workspaceId,{skipHistory:true});return true}this.openPage(loc.page||'dashboard',loc.focusId||'',{skipHistory:true,keepWorkspace:true,forceNav:true});return true}finally{this._navRestoring=false;this.updateNavButtons()}},
    navModuleActive(p){return this.current===p},
    openModule(p){return this.openPage(p)},
    openWorkspaceModule(p,e){e?.preventDefault?.();e?.stopPropagation?.();if(typeof p!=='string'||!p)return toast('مسار الوحدة غير صالح','error');const allowed=this.workspaceModules().some(x=>x[0]===p);if(!allowed)return toast('الوحدة المطلوبة غير متاحة','error');this.setSidebarOpen(false);return this.openPage(p)},
    openWorkspace(id,opts: any={}){const ws=this.workspaces().find(w=>w.id===id);if(!ws)return toast('القسم غير موجود أو موقوف','error');const modules=this.workspaceModules(ws);if(!modules.length)return toast('لا توجد وحدات متاحة لك داخل هذا القسم','warning');if(!opts.skipHistory&&!this._navRestoring)this.pushNavLocation();this.workspaceId=id;this.current=id==='umrah'?modules[0][0]:'dashboard';this.focusId='';this.setSidebarOpen(false);this.closeMenus();this.renderNav();UIDocument.getElementById('pageTitle').textContent=ws.name;UIDocument.getElementById('pageSubtitle').textContent=ws.description||'مساحة عمل';this.renderCurrent();this.updateNavButtons()},
    backHome(opts: any={}){if(!opts.skipHistory&&!this._navRestoring&&!(this.current==='dashboard'&&!this.workspaceId))this.pushNavLocation();this.workspaceId='';this.current='dashboard';this.focusId='';this.openPage('dashboard','',{skipHistory:true,keepWorkspace:true,forceNav:true});this.updateNavButtons()},
    filterReportCards(input){const q=S(input.value).trim().toLowerCase();UIDocument.querySelectorAll('#reportGrid .report-card').forEach(c=>c.style.display=!q||S(c.dataset.search).includes(q)?'':'none')},
    pageMeta(p=this.current){if(p==='customer-more')return[p,'customers','المزيد','ملف العميل الكامل والإجراءات'];return Nav.flatMap(x=>x[1]).find(x=>x[0]===p)||Object.values(SuiteWorkspaceNav).flat().find(x=>x[0]===p)||[p,'file',p,'']},
    shortcutKey(){return `elhafez-shortcuts:${AccessControl.currentUser()?.id||'guest'}`},
    shortcutAllowed(p){return !!p&&p!=='dashboard'&&AccessControl.can(p)&&(!!this.workspaceForPage(p)||Nav.flatMap(x=>x[1]).some(x=>x[0]===p)||Object.values(SuiteWorkspaceNav).flat().some(x=>x[0]===p))},
    shortcuts(){let a=[];try{a=JSON.parse(localStorage.getItem(this.shortcutKey())||'[]')}catch(_){a=[]}const seen=new Set();return(Array.isArray(a)?a:[]).filter(p=>typeof p==='string'&&this.shortcutAllowed(p)&&!seen.has(p)&&(seen.add(p),true)).slice(0,12)},
    saveShortcuts(a){localStorage.setItem(this.shortcutKey(),JSON.stringify(a.slice(0,12)))},
    isShortcut(p=this.current){return this.shortcuts().includes(p)},
    toggleShortcut(p=this.current){if(!this.shortcutAllowed(p))return toast('هذه الصفحة لا تحتاج اختصارًا','warning');const a=this.shortcuts(),i=a.indexOf(p);if(i>=0)a.splice(i,1);else a.push(p);this.saveShortcuts(a);this.renderNav();this.updateShortcutButton();toast(i>=0?'تمت إزالة الصفحة من اختصاراتي':'تمت إضافة الصفحة إلى اختصاراتي')},
    shortcutNav(){const a=this.shortcuts();if(!a.length)return'';const active=a.includes(this.current);return `<div class="nav-group shortcut-nav-group workspace-accordion"><details class="umrah-nav-group shortcut-nav-details" data-sidebar-accordion="1" ${active?'open':''} ontoggle="UI.workspaceAccordionToggle(this)"><summary class="umrah-nav-group-title"><span>★ اختصاراتي</span><i class="workspace-nav-chevron" aria-hidden="true"></i></summary><div class="umrah-nav-group-body">${a.map(p=>{const m=this.pageMeta(p);return `<button type="button" class="nav-btn ${this.current===p?'active':''}" data-ui-page="${p}"><span class="nav-ico">${icon(m[1]||'file')}</span><span class="nav-copy"><b>${esc(m[2]||p)}</b></span></button>`}).join('')}</div></details></div>`},
    updateShortcutButton(){const b=UIDocument.getElementById('shortcutToggleBtn');if(!b)return;const allowed=this.shortcutAllowed(this.current);b.classList.toggle('hidden',!allowed);if(!allowed)return;const on=this.isShortcut(this.current);b.textContent=on?'★':'☆';b.title=on?'إزالة الصفحة من اختصاراتي':'إضافة الصفحة إلى اختصاراتي';b.setAttribute('aria-label',b.title)},
    workspaceNavItems(mods){const button=i=>`<button type="button" class="nav-btn ${this.navModuleActive(i[0])?'active':''}" data-workspace-page="${i[0]}"><span class="nav-ico">${icon(i[1])}</span><span class="nav-copy"><b>${i[2]}</b></span>${this.navBadge(i[0])?`<span class="nav-badge">${this.navBadge(i[0])}</span>`:''}</button>`;if(this.activeWorkspace()?.id==='umrah'){const groups=[];for(const item of mods){const name=item[4]||'أخرى';let g=groups.find(x=>x.name===name);if(!g){g={name,items:[]};groups.push(g)}g.items.push(item)}return `<div class="umrah-workspace-nav workspace-accordion">${groups.map((g,index)=>{const active=g.items.some(i=>this.navModuleActive(i[0]));return `<details class="umrah-nav-group" data-sidebar-accordion="1" ${active||this.current==='dashboard'&&index===0?'open':''} ontoggle="UI.workspaceAccordionToggle(this)"><summary class="umrah-nav-group-title"><span>${esc(g.name)}</span><i class="workspace-nav-chevron" aria-hidden="true"></i></summary><div class="umrah-nav-group-body">${g.items.map(button).join('')}</div></details>`}).join('')}</div>`}if(!mods.some(i=>i[4]))return mods.map(button).join('');const groups=[];for(const item of mods){const name=item[4]||'أخرى';let g=groups.find(x=>x.name===name);if(!g){g={name,items:[]};groups.push(g)}g.items.push(item)}return `<div class="workspace-nav-groups workspace-accordion">${groups.map((g,index)=>{const active=g.items.some(i=>this.navModuleActive(i[0]));return `<details class="workspace-nav-section" data-sidebar-accordion="1" ${active||(!this.current||this.current==='dashboard')&&index===0?'open':''} ontoggle="UI.workspaceAccordionToggle(this)"><summary><span>${esc(g.name)}</span><i class="workspace-nav-chevron" aria-hidden="true"></i></summary><div class="workspace-nav-section-body">${g.items.map(button).join('')}</div></details>`}).join('')}</div>`},
    workspaceAccordionToggle(el){if(!el?.open)return;const group=el.parentElement?.closest?.('.workspace-accordion');if(!group)return;for(const other of group.children)if(other!==el&&other instanceof HTMLDetailsElement&&other.open)other.open=false},
    renderNav(){const mobile=`<div class="mobile-side-tools"><button class="btn small ghost" data-ui-mobile-search="1">${icon('search','sm')} بحث</button><button class="btn small ghost" data-form-open="changePassword">${icon('lock','sm')} كلمة المرور</button><button class="btn small danger" data-auth-logout="1">${icon('logout','sm')} خروج</button></div>`,ws=this.activeWorkspace(),home=`<div class="nav-group"><button data-main-home="1" class="nav-btn ${!ws&&this.current==='dashboard'?'active':''}" data-ui-back-home="1"><span class="nav-ico">${icon('dashboard')}</span><span class="nav-copy"><b>الصفحة الرئيسية</b><small>مساحات العمل</small></span></button></div>`;let body=home+this.shortcutNav();if(ws){const mods=this.workspaceModules(ws);body+=`<div class="nav-group"><div class="nav-title">${esc(ws.name)}</div>${ws.id==='umrah'?'':`<button data-workspace-home="${esc(ws.id)}" class="nav-btn ${this.current==='dashboard'?'active':''}" data-ui-workspace="${esc(ws.id)}"><span class="nav-ico">${icon(ws.icon||'file')}</span><span class="nav-copy"><b>واجهة القسم</b></span></button>`}${this.workspaceNavItems(mods)}</div>`}UIDocument.getElementById('nav').innerHTML=body+mobile},
    refreshNavActive(){const nav=UIDocument.getElementById('nav');if(!nav)return;const ws=this.activeWorkspace();for(const b of nav.querySelectorAll('.nav-btn.active'))b.classList.remove('active');const main=nav.querySelector('[data-main-home="1"]');if(main&& !ws&&this.current==='dashboard')main.classList.add('active');if(ws&&this.current==='dashboard')nav.querySelector(`[data-workspace-home="${CSS.escape(ws.id)}"]`)?.classList.add('active');if(this.current!=='dashboard'){const b=nav.querySelector(`[data-workspace-page="${CSS.escape(this.current)}"]`);b?.classList.add('active');const group=b?.closest('details.workspace-nav-section,details.umrah-nav-group,details.shortcut-nav-details');if(group)group.open=true}},
    navBadge(p){if(p==='workcenter'&&typeof WorkCenter!=='undefined')return WorkCenter.items().length||'';if(p==='audit')return Accounting.audit().filter(x=>x.level==='critical').length||'';if(p==='invoices'){const inv=DB.data.invoices||[],metrics=Invoices.listMetrics(inv);return inv.filter(x=>live(x)&&x.status!=='draft'&&N(metrics.get(x.id)?.remaining)>EPS).length||'';}if(p==='agents')return DB.data.commissions.filter(x=>x.status==='pending').length||'';if(p==='approvals')return DB.data.approvals.filter(x=>x.status==='pending').length||'';return''},
    setSidebarOpen(open){const sidebar=UIDocument.getElementById('sidebar'),backdrop=UIDocument.getElementById('mainSidebarBackdrop'),mobile=innerWidth<=780,on=mobile&&!!open;sidebar?.classList.toggle('open',on);backdrop?.classList.toggle('show',on);UIDocument.body.classList.toggle('main-sidebar-open',on);return on},
    closeMobileSidebar(){if(innerWidth<=780)this.setSidebarOpen(false);return true},
    toggleMenu(){const sidebar=UIDocument.getElementById('sidebar');if(innerWidth<=780){this.setSidebarOpen(!sidebar?.classList.contains('open'));return true}UIDocument.body.classList.toggle('sidebar-temp-hidden');if(UIDocument.body.classList.contains('sidebar-hidden'))UIDocument.body.classList.remove('sidebar-hidden');return true},
    openPage: function(page,id='',opts: any={}){if(this.current==='settings'&&page!=='settings'&&this.settingsDirty&&!confirm('توجد تعديلات غير محفوظة في الإعدادات. هل تريد مغادرة الصفحة؟'))return false;if(page!=='settings')this.settingsDirty=false;return UiBaseMethods.openPageCommercial(page,id,opts)},
    renderCurrent: function(){UiBaseMethods.renderCurrentCommercial();if(this.current==='settings')this.initSettingsTabs()},
    updateTopbar(){const n=Commercial.notifications(),b=UIDocument.getElementById('notificationBadge');if(b){b.textContent=n.length>99?'99+':n.length;b.classList.toggle('hidden',!n.length)}this.updateNavButtons();this.updateShortcutButton()},
    updateNavButtons(){const backs=[...UIDocument.querySelectorAll('[data-global-nav="back"]')],ups=[...UIDocument.querySelectorAll('[data-global-nav="up"]')];for(const back of backs)back.disabled=!this.navHistory.length;const canUp=this.current!=='dashboard'||!!this.workspaceId;for(const up of ups)up.disabled=!canUp},
    goBack(){const loc=this.navHistory.pop();if(!loc){this.updateNavButtons();return toast('لا يوجد مكان سابق للرجوع إليه','warning')}return this.restoreNavLocation(loc)},
    goUp(){if(this.current!=='dashboard'&&this.workspaceId){this.pushNavLocation();return this.openWorkspace(this.workspaceId,{skipHistory:true})}if(this.current==='dashboard'&&this.workspaceId){this.pushNavLocation();return this.backHome({skipHistory:true})}return toast('أنت بالفعل في أعلى مستوى','warning')}
};
export { UI_WorkspaceNav };
