/* Actionable daily work center. Deliberately excludes HR; it combines finance, CRM and Hajj/Umrah follow-up. */
const WorkCenter={
 _expanded:false,
 expand(){this._expanded=true;UI.renderCurrent();return true},
 severityRank:{critical:0,warning:1,info:2,good:3},
 branchOk(x){const id=BranchScope.currentId();return !x?.branchId||!id||x.branchId===id},
 item(level,title,text,page,id='',group='متابعة',action='فتح'){return{id:iid(),level,title,text,page,recordId:id,group,action}},
 items(){const out=[],seen=new Set(),add=x=>{if(!x?.title)return;const k=[x.page,x.recordId,x.title,x.text].join('|');if(seen.has(k))return;seen.add(k);out.push(x)};
  for(const n of Commercial.notifications())add(this.item(n.level||'info',n.title,n.text||'',n.page||'dashboard','',n.page?.startsWith('umrah-')?'الحج والعمرة':'تنبيهات','راجع'));
  for(const a of DB.data.approvals||[])if(this.branchOk(a)&&a.status==='pending')add(this.item('warning',`اعتماد ينتظر القرار — ${approvalTypeLabel(a.type)}`,a.reason||a.notes||'عملية تنتظر الاعتماد','approvals',a.id,'الاعتمادات','اتخذ قرارًا'));
  const nowDate=today();
  for(const f of DB.data.followups||[]){const lead=byId(DB.data.leads,f.leadId);if(!lead||lead.customerId||['won','lost'].includes(lead.status)||!f.nextDate)continue;const d=daysBetween(nowDate,f.nextDate);if(d<=1)add(this.item(d<0?'critical':'warning',`متابعة CRM — ${lead.name||lead.no}`,`${f.type||'متابعة'}${f.result?' • '+f.result:''} • ${d<0?'متأخرة '+Math.abs(d)+' يوم':d===0?'اليوم':'غدًا'}`,'crm',lead.id,'CRM والمتابعات','سجل المتابعة'))}
  for(const ch of DB.data.cheques||[]){if(!this.branchOk(ch)||['collected','cleared','cancelled','void','bounced','returned'].includes(ch.status)||!ch.valueDate)continue;const d=daysBetween(nowDate,ch.valueDate);if(d<=3)add(this.item(d<0?'critical':'warning',`${ch.direction==='out'?'شيك صادر':'شيك وارد'} — ${ch.no||'-'}`,`${money(ch.amount,ch.currency)} • ${d<0?'متأخر '+Math.abs(d)+' يوم':d===0?'يستحق اليوم':'يستحق خلال '+d+' يوم'}`,'cheques',ch.id,'الخزينة والبنوك','راجع الشيك'))}
  for(const inv of DB.data.invoices||[]){if(!this.branchOk(inv)||!live(inv)||inv.status==='draft'||Invoices.remaining(inv)<=EPS)continue;const party=Actions.partyName(inv.kind==='supplier'?'supplier':(inv.partyType||'customer'),inv.partyId)||'-',days=inv.dueDate?daysBetween(nowDate,inv.dueDate):999;if(days<=7)add(this.item(days<0?'critical':'warning',`${inv.kind==='supplier'?'استحقاق مورد':'تحصيل عميل'} — ${inv.no}`,`${party} • متبقي ${money(Invoices.remaining(inv),inv.currency)}${inv.dueDate?` • ${days<0?'متأخر '+Math.abs(days)+' يوم':'خلال '+days+' يوم'}`:''}`,'invoices',inv.id,'الاستحقاقات',inv.kind==='supplier'?'راجع السداد':'راجع التحصيل'))}
  const programs=(DB.data.umrahPrograms||[]).filter(p=>this.branchOk(p)&&p.active!==false&&!['cancelled','closed','returned'].includes(p.status));
  for(const p of programs){let gaps=[];try{gaps=UmrahCore_Ops.programOpenGaps(p.id)||[]}catch(_){}if(gaps.length)add(this.item('warning',`برنامج يحتاج استكمال — ${p.name||p.no}`,gaps.slice(0,3).join(' • ')+(gaps.length>3?` • +${gaps.length-3}`:''),'umrah-programs',p.id,'الحج والعمرة','استكمل البرنامج'));
   let smart=[];try{smart=UmrahCore_Insights.warnings(p.id)||[]}catch(_){}for(const w of smart)add(this.item(w.level||'warning',w.title||`تنبيه ${p.name}`,w.text||'',w.page||'umrah-programs',p.id,'الحج والعمرة',w.action||'راجع'))}
  for(const b of DB.data.umrahBookings||[]){if(!this.branchOk(b)||b.active===false)continue;const p=programs.find(x=>x.id===b.programId);if(b.status==='hold'&&b.holdUntil){const h=(new Date(b.holdUntil).getTime()-Date.now())/3600000;if(h>=0&&h<=12)add(this.item('warning',`الحجز المؤقت ينتهي قريبًا — ${b.no}`,`${b.customerSnapshot?.name||''}${p?.name?' • '+p.name:''} • متبقي ${Math.max(0,Math.ceil(h))} ساعة`,'umrah-bookings',b.id,'الحج والعمرة','استكمل الحجز'))}if(['docsPending','cancelRequested'].includes(b.status))add(this.item(b.status==='cancelRequested'?'critical':'warning',`${b.status==='cancelRequested'?'طلب إلغاء':'مستندات ناقصة'} — ${b.no}`,`${b.customerSnapshot?.name||''}${p?.name?' • '+p.name:''}`,'umrah-bookings',b.id,'الحج والعمرة','راجع الحجز'))}
  for(const t of DB.data.umrahTravelers||[]){if(!this.branchOk(t)||t.active===false)continue;const p=programs.find(x=>x.id===t.programId);if(p&&daysBetween(today(),p.departureDate)>=0&&daysBetween(today(),p.departureDate)<=14&&t.visaStatus!=='issued')add(this.item('warning',`تأشيرة غير صادرة — ${t.nameAr||t.no}`,`${p.name||p.no} • الحالة ${sl(t.visaStatus||'pending')}`,'umrah-visas',t.id,'الحج والعمرة','راجع التأشيرة'))}
  for(const c of DB.data.umrahSupplierCommitments||[]){if(!this.branchOk(c)||c.active===false||c.status==='cancelled')continue;let snap=null;try{snap=UmrahCore_Procurement.status(c)}catch(_){}if(c.status!=='invoiced'&&!snap?.invoiceId)add(this.item('info',`التزام مورد لم يتحول لفاتورة`,`${c.description||''} • ${money(c.total,c.currency)} • ${byId(DB.data.suppliers,c.supplierId)?.name||'-'}`,'umrah-procurement',c.id,'الموردون','راجع المستند'))}
  return out.sort((a,b)=>(this.severityRank[a.level]??9)-(this.severityRank[b.level]??9)||S(a.group).localeCompare(S(b.group))).slice(0,250)},
 summary(){const x=this.items();return{all:x.length,critical:x.filter(i=>i.level==='critical').length,warning:x.filter(i=>i.level==='warning').length,umrah:x.filter(i=>i.group==='الحج والعمرة').length,finance:x.filter(i=>['الاستحقاقات','الاعتمادات'].includes(i.group)).length}},
 open(page,id=''){UI.openPage(page,id)},
 page(){const items=this.items(),s=this.summary(),native=document.documentElement.classList.contains('native-android'),shown=native&&!this._expanded?items.slice(0,60):items,groups=[...new Set(shown.map(x=>x.group))],more=native&&shown.length<items.length?`<div class="card table-load-more"><button type="button" class="btn ghost" data-work-action="expand">عرض باقي المهام <span>${items.length-shown.length}</span></button></div>`:'';return Pages.head('مركز العمل اليومي','قائمة واحدة للأعمال التي تحتاج تنفيذًا الآن بدل الدوران بين الأقسام.',`<button class="btn ghost" data-work-action="collapse">${icon('activity','sm')} تحديث</button>`)+`<div class="grid kpi-grid work-center-kpis">${UI.kpi('تحتاج متابعة',s.all,'كل الأعمال المفتوحة',s.all?'warn':'good','activity')}${UI.kpi('حرجة',s.critical,'ابدأ بها أولًا',s.critical?'bad':'good','warning')}${UI.kpi('الحج والعمرة',s.umrah,'تشغيل وحجوزات ومستندات',s.umrah?'info':'good','programs')}${UI.kpi('مالية واعتمادات',s.finance,'تحصيل وسداد وقرارات',s.finance?'purple':'good','invoices')}</div><div class="work-center">${shown.length?groups.map(g=>{const xs=shown.filter(x=>x.group===g);return`<section class="card work-group"><div class="card-head"><h3>${esc(g)}</h3><span class="badge ${xs.some(x=>x.level==='critical')?'red':xs.some(x=>x.level==='warning')?'orange':'blue'}">${xs.length}</span></div><div class="work-list">${xs.map(x=>`<div class="work-item ${esc(x.level)}"><div class="work-copy"><b>${esc(x.title)}</b><p>${esc(x.text||'')}</p></div><button class="btn small ${x.level==='critical'?'danger':x.level==='warning'?'soft':'ghost'}" data-work-action="open" data-work-page="${x.page}" data-work-id="${x.recordId||''}">${esc(x.action||'فتح')}</button></div>`).join('')}</div></section>`}).join(''):'<div class="card empty-state work-empty"><div class="empty-icon">'+icon('check')+'</div><h3>لا توجد أعمال عاجلة الآن</h3><p>كل العناصر التي يراقبها النظام في وضع سليم حاليًا.</p></div>'}</div>${more}`}
};
