import type { PoolClient } from 'pg';
import { pool, withTx } from '../context.js';
import { allowedBranches, BRANCH_COLLECTIONS } from '../authz.js';
import { MIRRORED_COLLECTION_KEYS, hydrateMirroredPayload } from '../entity-mirror-core.js';
import { readEntityMirror, entityBackedWritePlan, markEntityMirrorRevision, rebuildEntityMirror } from '../entity-mirror.js';
export { mergeConcurrentPayload } from '../state-merge.js';
async function readState(c:any,t:string,lock=false){
 const lockSql=lock?' for update of s':'';
 const light=await c.query(`select s.schema_version,s.revision,s.updated_at,s.storage_mode,s.entity_row_count,s.entity_present_keys,s.payload-$2::text[] as payload,m.revision as mirror_revision,m.row_count,m.present_keys from erp_state s left join erp_entity_mirror_meta m on m.tenant_key=s.tenant_key where s.tenant_key=$1${lockSql}`,[t,[...MIRRORED_COLLECTION_KEYS]]);
 if(!light.rowCount)return null;const row=light.rows[0],revision=Number(row.revision||0),mirrorRevision=Number(row.mirror_revision||0),storageMode=String(row.storage_mode||'legacy-full');
 if(storageMode==='entity-backed'){const mirror=await readEntityMirror(c,t,revision,Number(row.entity_row_count||0),row.entity_present_keys||[]);if(mirror)return{payload:hydrateMirroredPayload(row.payload,mirror.rows,mirror.presentKeys),schema_version:row.schema_version,revision,updated_at:row.updated_at,entityBacked:true,storageMode};throw Object.assign(new Error('entity_storage_inconsistent'),{statusCode:503})}
 if(mirrorRevision===revision){const mirror=await readEntityMirror(c,t,revision,Number(row.row_count||0),row.present_keys||[]);if(mirror)return{payload:hydrateMirroredPayload(row.payload,mirror.rows,mirror.presentKeys),schema_version:row.schema_version,revision,updated_at:row.updated_at,entityBacked:true,storageMode}}
 const fallback=await c.query('select payload,schema_version,revision,updated_at,storage_mode from erp_state where tenant_key=$1',[t]);return fallback.rows[0]||null
}
export async function currentState(t:string){return readState(pool,t,false)}
export async function currentStateForUpdate(c:any,t:string){return readState(c,t,true)}
export function mergeUserSecrets(oldPayload:any,newPayload:any){const oldUsers=new Map((oldPayload?.users||[]).map((u:any)=>[u.id,u]));newPayload.users=(newPayload.users||[]).map((u:any)=>{const old:any=oldUsers.get(u.id);if(!old)return{...u,emailVerifiedAt:''};const sameEmail=String(u.email||'').trim().toLowerCase()===String(old.email||'').trim().toLowerCase();return{...u,passwordHash:u.passwordHash||old.passwordHash,passwordSalt:u.passwordSalt||old.passwordSalt,passwordAlgo:u.passwordAlgo||old.passwordAlgo,passwordIterations:u.passwordIterations||old.passwordIterations,emailVerifiedAt:sameEmail?String(old.emailVerifiedAt||''):''}});return newPayload}
export function assertUserDirectoryChangeAllowed(sessionUser:any,oldPayload:any,newPayload:any){if(sessionUser?.role==='admin'||sessionUser?.permissions?.all)return;const strip=(u:any,self=false)=>{const x={...u};delete x.passwordHash;delete x.passwordSalt;if(self){delete x.lastLogin;delete x.mustChangePassword}return x},oldUsers=oldPayload?.users||[],newById=new Map((newPayload?.users||[]).map((u:any)=>[u.id,u]));if(oldUsers.length!==(newPayload?.users||[]).length)throw Object.assign(new Error('غير مسموح بتغيير المستخدمين بهذه الصلاحية'),{statusCode:403});for(const old of oldUsers){const nu:any=newById.get(old.id);if(!nu||JSON.stringify(strip(old,old.id===sessionUser.id))!==JSON.stringify(strip(nu,old.id===sessionUser.id)))throw Object.assign(new Error('غير مسموح بتغيير بيانات المستخدم أو الصلاحيات'),{statusCode:403})}}
export function clientPayload(payload:any,user:any,license:any){const p=structuredClone(payload);p.license={...p.license,...license,activationKey:''};for(const u of p.users||[]){delete u.passwordHash;delete u.passwordSalt;delete u.password}const allowed=allowedBranches(user,payload);if(allowed){for(const name of BRANCH_COLLECTIONS)p[name]=(p[name]||[]).filter((x:any)=>!x.branchId||allowed.has(String(x.branchId)));p.branches=(p.branches||[]).filter((b:any)=>allowed.has(String(b.id)))}return p}
export function mergeScopedPayload(server:any,submitted:any,user:any){const allowed=allowedBranches(user,server);if(!allowed)return submitted;const out=structuredClone(server);for(const k of Object.keys(submitted))if(!BRANCH_COLLECTIONS.has(k)&&k!=='branches')out[k]=submitted[k];for(const name of BRANCH_COLLECTIONS){const hidden=(server?.[name]||[]).filter((x:any)=>x.branchId&&!allowed.has(String(x.branchId))),visible=(submitted?.[name]||[]).filter((x:any)=>!x.branchId||allowed.has(String(x.branchId)));out[name]=[...hidden,...visible]}out.branches=server.branches;return out}

export async function persistStateRecord(c:any,t:string,payload:any,schemaVersion?:string){const plan=await entityBackedWritePlan(c,t,payload);const up=await c.query(`update erp_state set schema_version=coalesce($2,schema_version),payload=$3::jsonb,storage_mode=$4,entity_row_count=$5,entity_present_keys=$6::text[],revision=revision+1,updated_at=now() where tenant_key=$1 returning revision,updated_at,storage_mode`,[t,schemaVersion??null,JSON.stringify(plan.payload),plan.storageMode,plan.rowCount,plan.presentKeys]);if(!up.rowCount)throw Object.assign(new Error('company_not_initialized'),{statusCode:409});const revision=Number(up.rows[0].revision);await markEntityMirrorRevision(c,t,revision,payload);return{revision,updated_at:up.rows[0].updated_at,storageMode:up.rows[0].storage_mode}}
export async function insertStateRecord(c:any,t:string,payload:any,schemaVersion:string,revision=1){const plan=await entityBackedWritePlan(c,t,payload);await c.query(`insert into erp_state(tenant_key,schema_version,payload,storage_mode,entity_row_count,entity_present_keys,revision,created_at,updated_at) values($1,$2,$3::jsonb,$4,$5,$6::text[],$7,now(),now())`,[t,schemaVersion,JSON.stringify(plan.payload),plan.storageMode,plan.rowCount,plan.presentKeys,revision]);await markEntityMirrorRevision(c,t,revision,payload);return{revision,storageMode:plan.storageMode}}

/** One-way startup migration from the transitional full JSON payload. */
export async function migrateLegacyFullStates(){
 const tenants=await pool.query("select tenant_key from erp_state where storage_mode='legacy-full' order by tenant_key");let migrated=0;
 for(const item of tenants.rows)await withTx(async (c: PoolClient)=>{const tenant=String(item.tenant_key),state=await currentStateForUpdate(c,tenant);if(!state)throw new Error('company_not_initialized');await rebuildEntityMirror(c,tenant,state.payload);const saved=await persistStateRecord(c,tenant,state.payload,state.schema_version);if(saved.storageMode!=='entity-backed')throw new Error('entity_storage_migration_failed');migrated++});
 return{migrated,total:tenants.rowCount||0};
}
