const PurchaseOrderFulfillment={
 normalizeLines(lines=[],previous=[]){return (lines||[]).map((line,index)=>{const old=(previous||[]).find(x=>x.id&&x.id===line.id)||(previous||[])[index]||{};const qty=Math.max(0,N(line.qty));return{...line,id:line.id||old.id||iid(),qty,receivedQty:Math.min(qty,Math.max(0,N(old.receivedQty||line.receivedQty))),invoicedQty:Math.min(qty,Math.max(0,N(old.invoicedQty||line.invoicedQty)))}})},
 received(po){return (po.lines||[]).reduce((s,l)=>s+Math.min(N(l.qty),N(l.receivedQty)),0)},
 ordered(po){return (po.lines||[]).reduce((s,l)=>s+N(l.qty),0)},
 status(po){const ordered=this.ordered(po),received=this.received(po);if(received<=EPS)return'approved';if(received+EPS<ordered)return'partiallyReceived';return'received'},
 record(po,quantities={}){if(!po||!['approved','partiallyReceived','received','partiallyInvoiced'].includes(po.status))throw new Error('اعتمد أمر الشراء أولًا');po.lines=this.normalizeLines(po.lines,po.lines);for(const l of po.lines){const raw=quantities[l.id]??quantities[l.description];if(raw===undefined)continue;const next=Math.max(0,N(raw));if(next+EPS<N(l.invoicedQty))throw new Error(`لا يمكن خفض المنفذ من «${l.description}» عن الكمية المفوترة`);if(next-N(l.qty)>EPS)throw new Error(`الكمية المنفذة في «${l.description}» أكبر من كمية أمر الشراء`);l.receivedQty=next}const receiptStatus=this.status(po),invoiced=po.lines.reduce((s,l)=>s+Math.min(N(l.qty),N(l.invoicedQty)),0),ordered=this.ordered(po);po.status=invoiced>EPS&&invoiced+EPS<ordered?'partiallyInvoiced':(invoiced+EPS>=ordered&&receiptStatus==='received'?'converted':receiptStatus);po.receivedAt=receiptStatus==='received'?(po.receivedAt||now()):'';po.updatedAt=now();DB.log('fulfill','purchaseOrder',po.id,`${po.no} — ${this.received(po)}/${this.ordered(po)}`);return po},
 receiveAll(po){const q={};for(const l of this.normalizeLines(po.lines,po.lines))q[l.id]=N(l.qty);po.lines=this.normalizeLines(po.lines,po.lines);return this.record(po,q)},
 uninvoicedLines(po,{legacyFull=true}={}){po.lines=this.normalizeLines(po.lines,po.lines);const tracked=po.lines.some(l=>N(l.receivedQty)>EPS||N(l.invoicedQty)>EPS);return po.lines.map(l=>{const received=tracked?N(l.receivedQty):(legacyFull?N(l.qty):0),qty=Math.max(0,received-N(l.invoicedQty));return qty>EPS?{...l,qty}:null}).filter(Boolean)},
 markInvoiced(po,lines){po.lines=this.normalizeLines(po.lines,po.lines);for(const src of lines||[]){const l=po.lines.find(x=>x.id===src.id)||po.lines.find(x=>x.description===src.description);if(l)l.invoicedQty=Math.min(N(l.qty),N(l.invoicedQty)+N(src.qty))}po.invoiceIds=[...new Set([...(po.invoiceIds||[]),po.invoiceId].filter(Boolean))];const remaining=this.uninvoicedLines(po,{legacyFull:false}).length;const allReceived=this.status(po)==='received';po.status=remaining?(allReceived?'received':'partiallyReceived'):(allReceived?'converted':'partiallyInvoiced');po.updatedAt=now()},
 rollbackInvoice(po,inv){if(!po||!inv)return;po.lines=this.normalizeLines(po.lines,po.lines);for(const src of inv.lines||[]){const id=src.purchaseOrderLineId;const l=(id&&po.lines.find(x=>x.id===id))||po.lines.find(x=>x.description===src.description);if(l)l.invoicedQty=Math.max(0,N(l.invoicedQty)-N(src.qty))}po.invoiceIds=(po.invoiceIds||[]).filter(x=>x!==inv.id);po.invoiceId=po.invoiceIds.at(-1)||'';po.status=this.status(po);po.updatedAt=now()}
};
