import { EPS, Money, N, S, byId, esc, formatDate, icon, iid, live, money, now, today } from '../core/runtime';
import { PartyNettingRules } from './party-business-rules';
import { NettingWorkflows } from '../application/netting-workflows';
import { DB } from '../persistence/browser-store';
import { Accounting } from '../accounting/engine';
import { Invoices } from '../accounting/invoices';
import { Transactions } from '../accounting/transactions';
import { Auth } from '../security/auth';
import { Actions, Party360, Print, UI, composeLegacyNettingDeps, composeLegacyPhonePolicy, composeUnifiedPartyPresentation } from '../core/late-bindings';
/* Unified commercial party identity. Role ledgers stay separate (AR/AP/agent) and
   are only offset through an explicit, auditable netting document. */
const UnifiedParty={
 roleConfig:{
  customer:{list:'customers',label:'عميل',accountIds:['1200','2400']},
  supplier:{list:'suppliers',label:'مورد',accountIds:['2100','1400']},
  agent:{list:'agents',label:'مندوب',accountIds:['1210','2200','2410']}
 },
 ensureData(){DB.data.partyGroups=Array.isArray(DB.data.partyGroups)?DB.data.partyGroups:[];DB.data.partyNettings=Array.isArray(DB.data.partyNettings)?DB.data.partyNettings:[];return DB.data},
 record(type,id){const c=this.roleConfig[type];return c?byId(DB.data[c.list]||[],id):null},
 groupById(id){this.ensureData();return byId(DB.data.partyGroups,id)},
 groupFor(type,id){const x=this.record(type,id);return x?.partyGroupId?this.groupById(x.partyGroupId):null},
 roleIds(group){const roles={customer:group?.roles?.customer||'',supplier:group?.roles?.supplier||'',agent:group?.roles?.agent||''};let changed=false;for(const t of['customer','supplier','agent'])if(roles[t]&&!this.record(t,roles[t])){roles[t]='';changed=true}if(changed&&group){group.roles=roles;group.updatedAt=now()}return roles},
 roleRecord(group,type){const id=this.roleIds(group)[type];return id?this.record(type,id):null},
 canonical(type,id){const x=this.record(type,id),g=this.groupFor(type,id);return g||x||null},
 roleLabel(type){return this.roleConfig[type]?.label||type},
 identityFrom(x){return{name:S(x?.name||'').trim(),phone:S(x?.phone||''),whatsapp:S(x?.whatsapp||''),email:S(x?.email||''),address:S(x?.address||''),taxNo:S(x?.taxNo||'')};},
 ensureGroup(type,id){this.ensureData();const x=this.record(type,id);if(!x)throw new Error('الطرف غير موجود');let g=this.groupFor(type,id);if(g)return g;g={id:iid(),name:S(x.name||'').trim(),phone:S(x.phone||''),whatsapp:S(x.whatsapp||''),email:S(x.email||''),address:S(x.address||''),taxNo:S(x.taxNo||''),roles:{customer:'',supplier:'',agent:'',[type]:id},active:true,createdAt:now(),updatedAt:now()};x.partyGroupId=g.id;DB.data.partyGroups.unshift(g);DB.log('link','partyGroup',g.id,`إنشاء طرف موحد — ${x.name||x.no||id}`);return g},
 touch(type,id){const x=this.record(type,id),g=this.groupFor(type,id);if(!x||!g)return;const roles=this.roleIds(g);roles[type]=id;g.roles=roles;const current=this.identityFrom(x);for(const k of['name','phone','whatsapp','email','address','taxNo'])if(current[k])g[k]=current[k];g.updatedAt=now()},
 cloneRoleData(source,targetType,groupId){const base=this.identityFrom(source),currency=source?.currency||source?.commissionCurrency||DB.data.settings.baseCurrency;if(targetType==='customer')return{...base,type:'company',creditLimit:0,creditDays:N(source?.creditDays),partyGroupId:groupId,notes:`طرف موحد مع ${source?.no||source?.name||''}`};if(targetType==='supplier')return{...base,type:'أخرى',currency,creditDays:N(source?.creditDays),partyGroupId:groupId,notes:`طرف موحد مع ${source?.no||source?.name||''}`};return{name:base.name,phone:base.phone,whatsapp:base.whatsapp,email:base.email,address:base.address,commissionMode:'fixed',commissionValue:0,commissionCurrency:currency,partyGroupId:groupId,note:`طرف موحد مع ${source?.no||source?.name||''}`}},
 async createRole(type,id,targetType){if(!this.roleConfig[targetType]||targetType===type)throw new Error('الدور المطلوب غير صالح');const source=this.record(type,id);if(!source)throw new Error('الطرف غير موجود');return DB.atomicAsync('unifiedPartyCreateRole',()=>{const g=this.ensureGroup(type,id),roles=this.roleIds(g);if(roles[targetType])throw new Error(`الطرف مسجل بالفعل كـ ${this.roleLabel(targetType)}`);const data=this.cloneRoleData(source,targetType,g.id);let x;if(targetType==='customer')x=Transactions.addCustomer(data);else if(targetType==='supplier')x=Transactions.addSupplier(data);else x=Transactions.addAgent(data);x.partyGroupId=g.id;roles[targetType]=x.id;g.roles=roles;g.updatedAt=now();DB.log('link','partyGroup',g.id,`إضافة دور ${this.roleLabel(targetType)} — ${x.no}`);return x},{save:true,render:true,waitForSave:true,rollback:true})},
 linkCandidates(type,id,targetType){const source=this.record(type,id),g=this.groupFor(type,id),cfg=this.roleConfig[targetType];if(!source||!cfg)return[];const phone=composeLegacyPhonePolicy(source.whatsapp||source.phone),name=S(source.name||'').trim().toLowerCase();return(DB.data[cfg.list]||[]).filter(x=>x.id!==id&&x.active!==false&&(!x.partyGroupId||x.partyGroupId===g?.id)).map(x=>{const xp=composeLegacyPhonePolicy(x.whatsapp||x.phone),xn=S(x.name||'').trim().toLowerCase(),score=(phone&&xp===phone?4:0)+(name&&xn===name?3:0)+((name&&xn&&(xn.includes(name)||name.includes(xn)))?1:0);return{x,score}}).sort((a,b)=>b.score-a.score||S(a.x.name).localeCompare(S(b.x.name),'ar')).slice(0,60).map(z=>z.x)},
 async linkRole(type,id,targetType,targetId){if(!this.roleConfig[targetType]||targetType===type)throw new Error('الدور المطلوب غير صالح');const target=this.record(targetType,targetId);if(!target)throw new Error('السجل المراد ربطه غير موجود');return DB.atomicAsync('unifiedPartyLinkRole',()=>{const g=this.ensureGroup(type,id),roles=this.roleIds(g);if(roles[targetType]&&roles[targetType]!==targetId)throw new Error(`يوجد ${this.roleLabel(targetType)} مرتبط بالفعل`);if(target.partyGroupId&&target.partyGroupId!==g.id)throw new Error('السجل المحدد مرتبط بطرف موحد آخر');target.partyGroupId=g.id;roles[targetType]=target.id;g.roles=roles;g.updatedAt=now();DB.log('link','partyGroup',g.id,`ربط ${this.roleLabel(targetType)} موجود — ${target.no}`);return target},{save:true,render:true,waitForSave:true,rollback:true})},
 allRoleEntries(group){const out=[];for(const type of['customer','supplier','agent']){const x=this.roleRecord(group,type);if(x)out.push({type,id:x.id,x,label:this.roleLabel(type)})}return out},
 controlComponents(group,to=''){const out=[];const add=(type,x,accountId,label,kind,values)=>{for(const[c,raw]of Object.entries(values||{})){const v=N(raw);if(v>EPS)out.push({key:`${type}|${x.id}|${accountId}|${c}`,type,partyId:x.id,accountId,label,currency:c,kind,available:v})}};
  const c=this.roleRecord(group,'customer');if(c){add('customer',c,'1200','ذمة العميل — عليه','receivable',Accounting.partyReceivable('customer',c.id,'',to));add('customer',c,'2400','دفعات مقدمة من العميل — له','payable',Accounting.customerAdvance('customer',c.id,'',to))}
  const s=this.roleRecord(group,'supplier');if(s){add('supplier',s,'2100','ذمة المورد — له','payable',Accounting.supplierPayable(s.id,'',to));add('supplier',s,'1400','دفعات مقدمة للمورد — عليه','receivable',Accounting.supplierAdvance(s.id,'',to))}
  const a=this.roleRecord(group,'agent');if(a){add('agent',a,'1210','ذمة المندوب — عليه','receivable',Accounting.partyReceivable('agent',a.id,'',to));add('agent',a,'2200','عمولات مستحقة للمندوب — له','payable',Accounting.agentPayable(a.id,'',to));add('agent',a,'2410','دفعات مقدمة من المندوب — له','payable',Accounting.customerAdvance('agent',a.id,'',to))}
  return out},
 summary(type,id,to=''){const g=this.groupFor(type,id);if(!g)return null;const byCurrency={};for(const c of this.controlComponents(g,to)){const row=byCurrency[c.currency]||(byCurrency[c.currency]={currency:c.currency,له:0,عليه:0,net:0});if(c.kind==='payable')row.له+=c.available;else row.عليه+=c.available;row.net=row.له-row.عليه}return{group:g,rows:Object.values(byCurrency),components:this.controlComponents(g,to)}},
 lines(group,from='',to=''){const refs=new Map();for(const r of this.allRoleEntries(group))for(const aid of this.roleConfig[r.type].accountIds)refs.set(`${r.type}|${r.id}|${aid}`,r);return Accounting.lines(from,to).filter(l=>!l.baseOnly&&refs.has(`${l.partyType}|${l.partyId}|${l.accountId}`)).map(l=>({...l,_role:refs.get(`${l.partyType}|${l.partyId}|${l.accountId}`)})).sort((a,b)=>S(a.date).localeCompare(S(b.date))||S(a.journalNo).localeCompare(S(b.journalNo)))},
 position(group,to=''){const out={};for(const l of this.lines(group,'',to)){out[l.currency]??=0;out[l.currency]+=N(l.debit)-N(l.credit)}return out},
 nettingPairs(type,id,to=''){const g=this.groupFor(type,id);if(!g)return[];const parts=this.controlComponents(g,to),pay=parts.filter(x=>x.kind==='payable'),rec=parts.filter(x=>x.kind==='receivable'),out=[];for(const p of pay)for(const r of rec)if(p.currency===r.currency&&p.type!==r.type){const max=Math.min(p.available,r.available);if(max>EPS)out.push({key:`${p.key}>>${r.key}`,payable:p,receivable:r,currency:p.currency,max})}return out.sort((a,b)=>b.max-a.max)},
 parseComponentKey(key){return PartyNettingRules.parseComponentKey(key)},
 componentAvailable(c,to=''){if(c.accountId==='1200')return Math.max(0,N(Accounting.partyReceivable('customer',c.partyId,'',to)[c.currency]));if(c.accountId==='2400')return Math.max(0,N(Accounting.customerAdvance('customer',c.partyId,'',to)[c.currency]));if(c.accountId==='2100')return Math.max(0,N(Accounting.supplierPayable(c.partyId,'',to)[c.currency]));if(c.accountId==='1400')return Math.max(0,N(Accounting.supplierAdvance(c.partyId,'',to)[c.currency]));if(c.accountId==='1210')return Math.max(0,N(Accounting.partyReceivable('agent',c.partyId,'',to)[c.currency]));if(c.accountId==='2200')return Math.max(0,N(Accounting.agentPayable(c.partyId,'',to)[c.currency]));if(c.accountId==='2410')return Math.max(0,N(Accounting.customerAdvance('agent',c.partyId,'',to)[c.currency]));return 0},
 componentKind(accountId){return PartyNettingRules.componentKind(accountId)},
 invoiceCandidates(c){if(c.accountId==='2100')return(DB.data.invoices||[]).filter(inv=>live(inv)&&inv.status!=='draft'&&inv.kind==='supplier'&&inv.partyId===c.partyId&&inv.currency===c.currency&&Invoices.remaining(inv)>EPS);if(c.accountId==='1200')return(DB.data.invoices||[]).filter(inv=>live(inv)&&inv.status!=='draft'&&inv.kind!=='supplier'&&(inv.partyType||'customer')==='customer'&&inv.partyId===c.partyId&&inv.currency===c.currency&&Invoices.remaining(inv)>EPS);if(c.accountId==='1210')return(DB.data.invoices||[]).filter(inv=>live(inv)&&inv.status!=='draft'&&inv.kind!=='supplier'&&inv.partyType==='agent'&&inv.partyId===c.partyId&&inv.currency===c.currency&&Invoices.remaining(inv)>EPS);return[]},
 allocateInvoices(c,amount){let left=Money.round(amount,c.currency),out=[];const rows=this.invoiceCandidates(c).sort((a,b)=>S(a.dueDate).localeCompare(S(b.dueDate))||S(a.date).localeCompare(S(b.date))||S(a.no).localeCompare(S(b.no)));for(const inv of rows){if(left<=EPS)break;const use=Money.round(Math.min(left,Invoices.remaining(inv)),c.currency);if(use<=EPS)continue;out.push({invoiceId:inv.id,invoiceNo:inv.no,invoiceAmount:use,invoiceCurrency:inv.currency,partyType:c.type,partyId:c.partyId,accountId:c.accountId});left=Money.round(Math.max(0,left-use),c.currency)}return out},
 refreshNettingInvoices(x){const ids=[...new Set((x?.invoiceAllocations||[]).map(a=>a.invoiceId))];for(const id of ids){const inv=byId(DB.data.invoices,id);if(inv)Invoices.refresh(inv)}},
 async postNetting(type,id,o){return NettingWorkflows.postNetting(composeLegacyNettingDeps(this),type,id,o)},
 async reverseNetting(id,reason='إلغاء المقاصة'){return NettingWorkflows.reverseNetting(composeLegacyNettingDeps(this),id,reason)},
 recentNettings(groupId,limit=12){return(this.ensureData().partyNettings||[]).filter(x=>x.partyGroupId===groupId).sort((a,b)=>S(b.date).localeCompare(S(a.date))||S(b.createdAt).localeCompare(S(a.createdAt))).slice(0,limit)},
 roleBadges(type,id){const g=this.groupFor(type,id);if(!g)return`<span class="badge gray">${this.roleLabel(type)} فقط</span>`;return this.allRoleEntries(g).map(r=>`<span class="badge ${r.type===type?'green':'gray'}">${r.label} — ${esc(r.x.no||'')}</span>`).join(' ')},
 summaryHtml(type,id){const s=this.summary(type,id);if(!s)return'<div class="form-note">هذا السجل بدور واحد حاليًا. يمكنك إضافة أو ربط دور عميل/مورد/مندوب لنفس الطرف بدون دمج الحسابات الرقابية.</div>';const rows=s.rows as any[];return rows.length?rows.map(r=>`<div class="mini-row"><span>${esc(r.currency)}</span><b>له ${money(r.له,r.currency)} • عليه ${money(r.عليه,r.currency)} • ${Math.abs(r.net)<=EPS?'متعادل':r.net>0?`الصافي له ${money(r.net,r.currency)}`:`الصافي عليه ${money(Math.abs(r.net),r.currency)}`}</b></div>`).join(''):'<div class="mini-row"><span>الصافي</span><b>لا يوجد رصيد مستحق</b></div>'},
 missingRoles(type,id){const g=this.groupFor(type,id),roles=g?this.roleIds(g):{customer:type==='customer'?id:'',supplier:type==='supplier'?id:'',agent:type==='agent'?id:''};return['customer','supplier','agent'].filter(t=>!roles[t])},
 renderPanel(type,id){const x=this.record(type,id),g=this.groupFor(type,id),missing=this.missingRoles(type,id),roleCards=(g?this.allRoleEntries(g):[{type,id,x,label:this.roleLabel(type)}]).map(r=>`<div class="mini-row"><span>${r.label}</span><b>${esc(r.x.no||'')} — ${esc(r.x.name||'')}</b></div>`).join(''),create=Auth.can('journal','edit')?missing.map(t=>{const page=t==='customer'?'customers':t==='supplier'?'suppliers':'agents',candidates=this.linkCandidates(type,id,t).length;if(!Auth.can(page,'edit')&&!Auth.can(page,'add'))return'';return`<div class="party360-file-actions"><button type="button" class="btn small primary" data-party-action="unifiedCreateRole" data-party-type="${type}" data-party-id="${id}" data-party-key="${t}">+ إنشاء دور ${this.roleLabel(t)}</button>${candidates?`<button type="button" class="btn small ghost" data-party-action="unifiedLinkRole" data-party-type="${type}" data-party-id="${id}" data-party-key="${t}">ربط ${this.roleLabel(t)} موجود</button>`:''}</div>`}).join(''):'',pairs=this.nettingPairs(type,id),nettings=g?this.recentNettings(g.id):[],netRows=nettings.map(n=>`<tr><td><b>${esc(n.no)}</b></td><td>${formatDate(n.date)}</td><td>${money(n.amount,n.currency)}</td><td>${UI.badge(n.status)}</td><td>${n.status==='posted'&&Auth.can('journal','add')?`<button type="button" class="btn small danger" data-party-action="unifiedReverseNetting" data-party-type="${type}" data-party-id="${id}" data-party-ref="${n.id}">عكس</button>`:'-'}</td></tr>`);return `<div class="split-equal"><div class="card"><div class="card-head"><h3>الأدوار المرتبطة</h3><span>${this.roleBadges(type,id)}</span></div><div class="mini-list mt-12">${roleCards}</div><div class="mt-12">${create||'<div class="form-note">الأدوار الثلاثة مرتبطة بهذا الطرف.</div>'}</div></div><div class="card"><div class="card-head"><h3>الموقف الشامل</h3>${g?`<button type="button" class="btn small ghost" data-party-action="unifiedStatement" data-party-type="${type}" data-party-id="${id}">${icon('statement','sm')} كشف شامل PDF</button>`:''}</div><div class="mini-list mt-12">${this.summaryHtml(type,id)}</div><div class="form-note mt-12">الصافي المعروض للبيان فقط. ذمم العميل والمورد والمندوب تظل منفصلة محاسبيًا، ولا تتغير إلا بمستند مقاصة معتمد.</div>${pairs.length&&Auth.can('journal','add')?`<button type="button" class="btn primary mt-12" data-party-action="unifiedNetting" data-party-type="${type}" data-party-id="${id}">إجراء مقاصة معتمدة</button>`:''}</div></div>${g?`<div class="card mt-12"><div class="card-head"><h3>سجل المقاصات</h3><span class="badge gray">${nettings.length}</span></div>${UI.table(['المستند','التاريخ','القيمة','الحالة','إجراء'],netRows,'لا توجد مقاصات معتمدة',{export:false})}</div>`:''}`},
 refreshPanel(type,id){Party360.invalidate();const root=document.querySelector(`.party360[data-party360-type="${type}"][data-party360-id="${id}"]`),btn=root?.querySelector('[data-party360-tab="unified"]');if(root&&btn)Party360.loadTab(type,id,'unified',btn as HTMLElement)},
 openLinkRole(type,id,targetType){return composeUnifiedPartyPresentation(this).openLinkRole(type,id,targetType)},
 openNetting(type,id){return composeUnifiedPartyPresentation(this).openNetting(type,id)},
 openStatementOptions(type,id){const g=this.groupFor(type,id);if(!g)return Actions.statement(type,id);const modal=document.getElementById('modal'),form=document.getElementById('modalForm') as HTMLFormElement;document.getElementById('modalTitle').textContent='كشف الحساب الشامل للطرف';document.getElementById('modalSubtitle').textContent='يجمع العميل والمورد والمندوب في بيان واحد مع بقاء كل ذمة منفصلة محاسبيًا.';document.getElementById('modalIcon').innerHTML=icon('statement');document.getElementById('modalSubmitText').textContent='عرض الكشف';document.getElementById('modalBody').innerHTML=`<div class="form-grid"><div class="field"><label>من تاريخ</label><input name="from" type="date"></div><div class="field"><label>إلى تاريخ</label><input name="to" type="date" value="${today()}"></div><div class="field full"><label>مستوى البيان</label><select name="level"><option value="short">مختصر</option><option value="full">تفصيلي</option></select></div></div>`;modal.classList.add('show');form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form);UI.closeModal(true);Print.showUnifiedStatement(g.id,S(fd.get('from')),S(fd.get('to')),S(fd.get('level')||'short'))}},
 async reversePrompt(type,id,nettingId){return composeUnifiedPartyPresentation(this).reversePrompt(type,id,nettingId)}
};
export { UnifiedParty };
