import { EPS, N, S, byId, esc, iid, live, now, today } from '../core/runtime';
import { DB } from '../persistence/browser-store';
import { Accounting, Auth } from '../core/late-bindings';
import { __set_Currency, __set_Periods } from '../core/late-bindings';
const Currency={
 active(){return DB.data.currencies.filter(x=>x.active!==false)},get(code){return DB.data.currencies.find(x=>x.code===S(code).toUpperCase())},
 rate(code,date=today()){code=S(code||DB.data.settings.baseCurrency).toUpperCase();if(code===DB.data.settings.baseCurrency)return 1;let best=null;for(const x of DB.data.fxRates)if(x.code===code&&x.date<=date&&(!best||x.date>=best.date))best=x;return N(best?.rate)},
 toBase(amount,code,date=today(),rate=0){const r=N(rate)||this.rate(code,date);if(!(r>0))throw new Error(`لا يوجد سعر صرف صالح للعملة ${code}`);return N(amount)*r},convert(amount,from,to,date=today()){const b=this.toBase(amount,from,date),r=this.rate(to,date);if(!(r>0))throw new Error(`لا يوجد سعر صرف صالح للعملة ${to}`);return b/r},
 options(selected=''){return this.active().map(c=>`<option value="${c.code}" ${c.code===selected?'selected':''}>${c.code} — ${esc(c.name)}</option>`).join('')},
 used(code){const d=DB.data;return d.journals.some(j=>j.lines?.some(l=>l.currency===code))||d.treasuries.some(t=>t.currency===code)||d.invoices.some(x=>x.currency===code)||d.programs.some(x=>x.currency===code)||d.services.some(x=>x.saleCurrency===code||x.costCurrency===code)||d.suppliers.some(x=>x.currency===code)||d.expenses.some(x=>x.currency===code)||d.commissions.some(x=>x.currency===code)},
 add(o){const code=S(o.code).trim().toUpperCase();if(!/^[A-Z]{3,5}$/.test(code))throw new Error('كود العملة غير صحيح');if(this.get(code))throw new Error('العملة موجودة');DB.data.currencies.push({id:iid(),code,name:S(o.name).trim(),symbol:o.symbol||'',decimals:Math.min(6,Math.max(0,N(o.decimals??2))),active:true,base:false,rateMode:o.rateMode||'manual'});if(code!==DB.data.settings.baseCurrency)this.setRate(code,N(o.rate),o.date||today(),'manual');DB.log('create','currency',code,o.name)},
 edit(code,o){const c=this.get(code);if(!c)throw new Error('العملة غير موجودة');const dec=Math.min(6,Math.max(0,N(o.decimals??c.decimals??2)));if(this.used(code)&&dec!==N(c.decimals??2))throw new Error('لا يمكن تغيير عدد الكسور بعد استخدام العملة ماليًا');c.name=S(o.name||c.name).trim();c.symbol=o.symbol??c.symbol;c.decimals=dec;c.rateMode=o.rateMode||c.rateMode;if(N(o.rate)>0&&code!==DB.data.settings.baseCurrency)this.setRate(code,N(o.rate),o.date||today(),'manual');DB.log('update','currency',code,c.name)},
 setRate(code,rate,date=today(),source='manual'){if(code===DB.data.settings.baseCurrency)return;if(!(N(rate)>0))throw new Error('سعر الصرف يجب أن يكون أكبر من صفر');const same=DB.data.fxRates.find(x=>x.code===code&&x.date===date);if(same)Object.assign(same,{rate:N(rate),source,updatedAt:now()});else DB.data.fxRates.push({id:iid(),code,date,rate:N(rate),source,createdAt:now()});DB.log('rate','currency',code,`${rate} بتاريخ ${date} — ${source}`)},
 async fetchLive(code){const c=this.get(code);if(!c||code===DB.data.settings.baseCurrency)throw new Error('العملة غير صالحة للتحديث المباشر');const base=DB.data.settings.baseCurrency,res=await fetch(`https://api.frankfurter.dev/v2/rate/${encodeURIComponent(code)}/${encodeURIComponent(base)}`);if(!res.ok)throw new Error('تعذر جلب سعر الصرف');const d=await res.json();if(!(N(d.rate)>0))throw new Error('السعر المباشر غير صالح');this.setRate(code,N(d.rate),d.date||today(),'Frankfurter');c.rateMode='live';return d},
 toggle(code){const c=this.get(code);if(!c)throw new Error('العملة غير موجودة');if(code===DB.data.settings.baseCurrency)throw new Error('لا يمكن إيقاف العملة الأساسية');c.active=c.active===false;DB.log(c.active?'activate':'deactivate','currency',code,c.name)},
 remove(code){const c=this.get(code);if(!c)throw new Error('العملة غير موجودة');if(code===DB.data.settings.baseCurrency)throw new Error('لا يمكن حذف العملة الأساسية');if(this.used(code))throw new Error('العملة مستخدمة تاريخيًا؛ يمكن إيقافها فقط');DB.data.currencies=DB.data.currencies.filter(x=>x.code!==code);DB.data.fxRates=DB.data.fxRates.filter(x=>x.code!==code);DB.log('delete','currency',code,c.name)}
};
__set_Currency(Currency);

const Periods={
 fiscalForDate(date){return DB.data.fiscalYears.find(f=>date>=f.from&&date<=f.to)},
 buildYear(startYear){const sm=Math.min(12,Math.max(1,N(DB.data.settings.fiscalYearStartMonth)||1)),from=`${startYear}-${String(sm).padStart(2,'0')}-01`,endYear=sm===1?startYear:startYear+1,endMonth=sm===1?12:sm-1,endDay=new Date(endYear,endMonth,0).getDate(),to=`${endYear}-${String(endMonth).padStart(2,'0')}-${String(endDay).padStart(2,'0')}`,label=sm===1?String(startYear):`${startYear}/${startYear+1}`;const fy={id:iid(),label,startYear,from,to,status:'open',closedAt:'',closedBy:''};DB.data.fiscalYears.push(fy);for(let i=0;i<12;i++){const dt=new Date(startYear,sm-1+i,1),y=dt.getFullYear(),m=dt.getMonth()+1,last=new Date(y,m,0).getDate();DB.data.periods.push({id:iid(),fiscalYearId:fy.id,year:y,month:m,from:`${y}-${String(m).padStart(2,'0')}-01`,to:`${y}-${String(m).padStart(2,'0')}-${last}`,status:'open',closedAt:'',closedBy:'',reopenReason:''})}return fy},
 ensureDate(date){if(!DB.data?.fiscalYears)return;let fy=this.fiscalForDate(date);if(fy)return fy;const y=new Date(`${date}T00:00:00`).getFullYear(),sm=Math.min(12,Math.max(1,N(DB.data.settings.fiscalYearStartMonth)||1)),startYear=new Date(`${date}T00:00:00`).getMonth()+1<sm?y-1:y;return this.buildYear(startYear)},
 forDate(date){this.ensureDate(date);return DB.data.periods.find(p=>date>=p.from&&date<=p.to)},assertOpen(date){const p=this.forDate(date),fy=p&&byId(DB.data.fiscalYears,p.fiscalYearId);if(fy?.status==='closed')throw new Error(`السنة المالية ${fy.label} مغلقة`);if(p?.status==='closed')throw new Error(`الفترة المحاسبية ${p.month}/${p.year} مغلقة`)},
 preCloseChecklist(id){const p=byId(DB.data.periods,id);if(!p)throw new Error('الفترة غير موجودة');const blockers=[],warnings=[];const crit=Accounting.audit().filter(x=>x.level==='critical');if(crit.length)blockers.push(`يوجد ${crit.length} أخطاء حرجة في مركز الرقابة`);const pend=DB.data.approvals.filter(a=>a.status==='pending'&&((a.date||a.requestedAt?.slice?.(0,10)||a.createdAt?.slice?.(0,10)||p.to)<=p.to));if(pend.length)blockers.push(`يوجد ${pend.length} طلب اعتماد معلق حتى نهاية الفترة`);const cheques=DB.data.cheques.filter(c=>!['cleared','bounced','cancelled','void'].includes(c.status)&&((c.valueDate||c.date||p.to)<=p.to));if(cheques.length)warnings.push(`يوجد ${cheques.length} شيك غير مسوى حتى نهاية الفترة`);for(const c of Currency.active().filter(c=>c.code!==DB.data.settings.baseCurrency&&Currency.used(c.code)))if(!DB.data.fxRates.some(r=>r.code===c.code&&r.date===p.to))blockers.push(`سجل سعر إقفال ${c.code} بتاريخ ${p.to} قبل الإغلاق`);const counted=new Set(DB.data.cashCounts.filter(x=>x.date>=p.from&&x.date<=p.to).map(x=>x.treasuryId));for(const t of DB.data.treasuries.filter(t=>t.active!==false&&t.type==='cash'))if(!counted.has(t.id))warnings.push(`لم يتم تسجيل جرد خزنة ${t.name} خلال الفترة`);const dueRevenue=(DB.data.deferredRevenueSchedules||[]).flatMap(x=>(x.parts||[]).filter(v=>v.status==='pending'&&v.date<=p.to));if(dueRevenue.length)warnings.push(`يوجد ${dueRevenue.length} دفعة إيراد مؤجل مستحقة للترحيل حتى نهاية الفترة`);const dueCosts=(DB.data.deferredCostSchedules||[]).flatMap(x=>(x.parts||[]).filter(v=>v.status==='pending'&&v.date<=p.to));if(dueCosts.length)warnings.push(`يوجد ${dueCosts.length} دفعة تكلفة مؤجلة مستحقة للتحميل حتى نهاية الفترة`);const dueLoans=(DB.data.loanSchedules||[]).filter(x=>x.status==='pending'&&x.dueDate<=p.to);if(dueLoans.length)warnings.push(`يوجد ${dueLoans.length} قسط تمويل مستحق حتى نهاية الفترة`);return{period:p,blockers,warnings,ok:!blockers.length}},
 closePeriod(id){const c=this.preCloseChecklist(id),p=c.period;if(p.status==='closed')throw new Error('الفترة مغلقة بالفعل');if(!c.ok)throw new Error('لا يمكن إغلاق الفترة: '+c.blockers.join(' — '));p.status='closed';p.closedAt=now();p.closedBy=Auth.user?.id||'';p.closeChecklist={at:now(),warnings:c.warnings};DB.log('close','period',id,`${p.month}/${p.year}`)},
 reopenPeriod(id,reason){const p=byId(DB.data.periods,id);if(!p||p.status!=='closed')throw new Error('الفترة غير مغلقة');if(!S(reason).trim())throw new Error('سبب إعادة الفتح مطلوب');const fy=byId(DB.data.fiscalYears,p.fiscalYearId);if(fy?.status==='closed')throw new Error('أعد فتح السنة المالية أولًا');p.status='open';p.reopenReason=reason;p.reopenedAt=now();p.reopenedBy=Auth.user?.id||'';DB.log('reopen','period',id,reason)},
 closeYear(fyId){const fy=byId(DB.data.fiscalYears,fyId);if(!fy||fy.status==='closed')throw new Error('السنة غير متاحة');const open=DB.data.periods.filter(p=>p.fiscalYearId===fy.id&&p.status!=='closed');if(open.length)throw new Error('يجب إغلاق جميع فترات السنة أولًا');const lines=[];for(const a of DB.data.accounts.filter(a=>a.posting&&['revenue','expense'].includes(a.type))){const b=Accounting.accountBalance(a.id,fy.from,fy.to,{excludeRefTypes:['year-close','year-reopen']});const net=b.debit-b.credit;if(Math.abs(net)<=EPS)continue;if(net<0){lines.push({accountId:a.id,debit:-net,currency:DB.data.settings.baseCurrency,baseDebit:-net,baseOnly:true});lines.push({accountId:'3200',credit:-net,currency:DB.data.settings.baseCurrency,baseCredit:-net,baseOnly:true})}else{lines.push({accountId:'3200',debit:net,currency:DB.data.settings.baseCurrency,baseDebit:net,baseOnly:true});lines.push({accountId:a.id,credit:net,currency:DB.data.settings.baseCurrency,baseCredit:net,baseOnly:true})}}if(lines.length)Accounting.post({date:fy.to,memo:`إقفال السنة المالية ${fy.label}`,refType:'year-close',refId:fy.id,lines,skipPeriod:true});fy.status='closed';fy.closedAt=now();fy.closedBy=Auth.user?.id||'';DB.log('close','fiscalYear',fy.id,fy.label)},
 reopenYear(fyId,reason){const fy=byId(DB.data.fiscalYears,fyId);if(!fy||fy.status!=='closed')throw new Error('السنة غير مغلقة');if(!S(reason).trim())throw new Error('سبب إعادة الفتح مطلوب');const closeJs=DB.data.journals.filter(j=>live(j)&&j.refType==='year-close'&&j.refId===fy.id&&j.status==='posted'),reopenIds=[];for(const j of closeJs){j.status='reversed';j.voidReason=`إعادة فتح السنة — ${reason}`;Accounting.documentStatus('journal',j.id,'reversed');const r=Accounting.post({date:fy.to,memo:`إعادة فتح السنة ${fy.label} — عكس ${j.no} — ${reason}`,refType:'year-reopen',refId:fy.id,skipPeriod:true,lines:Accounting.reversalLines(j.lines)});reopenIds.push(r.id)}fy.status='open';fy.reopenedAt=now();fy.reopenedBy=Auth.user?.id||'';fy.reopenReason=reason;fy.reopenJournalIds=reopenIds;DB.log('reopen','fiscalYear',fy.id,reason)}
};
__set_Periods(Periods);
export { Currency, Periods };
