import { EPS, N, S, byId, fmt, iid, live, money, now, sl, today } from '../core/runtime';
import { JournalRules } from './journal-rules';
import { ManualJournalWorkflows } from '../application/manual-journal-workflows';
import { IntegrityWorkflows } from '../application/integrity-workflows';
import { Numbering } from '../core/numbering';
import { AdvancedAccounting } from './advanced';
import { DB } from '../persistence/browser-store';
import { BranchScope } from '../commercial/product';
import { Currency, Periods } from './currency-periods';
import { Auth, Invoices, Tax, UI, composeLegacyIntegrityDeps, composeLegacyJournalRules, composeLegacyManualJournalDeps } from '../core/late-bindings';
import { __set_Accounting } from '../core/late-bindings';
import { AccessControl } from '../security/access-control';
import { UiPort } from '../core/ui-port';
const Accounting={
 account(id){return byId(DB.data.accounts,id)},descendants(id){const out=[],seen=new Set();const walk=p=>{if(seen.has(p))return;seen.add(p);for(const a of DB.data.accounts.filter(x=>x.parentId===p)){out.push(a.id);walk(a.id)}};walk(id);return out},
 treasuryAccountId(tid){const t=byId(DB.data.treasuries,tid);return t?.glAccountId||(t?.no?`11T${S(t.no).split('-').pop()}`:`11T${S(tid).slice(-5)}`)},ensureTreasuryAccount(t){const id=this.treasuryAccountId(t.id);t.glAccountId=id;const e=this.account(id);if(e){e.name=`${t.name} (${t.currency})`;e.currency=t.currency;e.active=t.active!==false;return id}DB.data.accounts.push({id,name:`${t.name} (${t.currency})`,type:'asset',nature:'debit',parentId:'1100',posting:true,system:true,active:true,treasuryId:t.id,currency:t.currency});return id},
 documentStatus(type,refId,status){const d=DB.data.documents.find(x=>x.type===type&&x.refId===refId);if(d)d.status=status;return d},accountLocked(id){return DB.data.journals.some(j=>j.lines?.some(l=>l.accountId===id))},treasuryHasHistory(tid){const aid=this.treasuryAccountId(tid);return DB.data.journals.some(j=>j.lines?.some(l=>l.accountId===aid))},
 validateLine(l){const a=this.account(l.accountId);if(!a)throw new Error('حساب غير موجود: '+l.accountId);if(a.active===false)throw new Error(`الحساب ${a.name} موقوف`);if(a.posting===false||a.type==='group')throw new Error(`الحساب ${a.name} تجميعي وغير قابل للترحيل`);const controls={1200:'customer',1210:'agent',2100:'supplier',2200:'agent',1400:'supplier',2400:'customer',2410:'agent'};if(controls[a.id]&&(!l.partyId||l.partyType!==controls[a.id]))throw new Error(`الحساب ${a.name} يتطلب تحديد الطرف المرتبط`);if(a.treasuryId&&l.treasuryId!==a.treasuryId)throw new Error(`حركة ${a.name} تتطلب الخزنة المرتبطة`)},
 post({date=today(),memo='',refType='',refId='',costCenterId='',branchId='',lines=[],skipPeriod=false}){if(!skipPeriod)Periods.assertOpen(date);const norm=JournalRules.normalize(composeLegacyJournalRules(this),lines,date);const j={id:iid(),no:Numbering.next('journal',date),date,memo,refType,refId,costCenterId,branchId:branchId||(typeof BranchScope!=='undefined'?BranchScope.currentId():''),status:'posted',createdAt:now(),createdBy:AccessControl.currentUser()?.id||'',lines:norm};DB.data.journals.unshift(j);DB.data.documents.unshift({id:iid(),no:j.no,date,type:'journal',refId:j.id,refNo:j.no,title:`قيد ${j.no}`,status:'posted'});this.invalidateLineCache();return j},
 reversalLines(lines=[]){return JournalRules.reversalLines(lines)},
 reverseJournal(j,reason,{date=today(),skipPeriod=false}={}){if(!j||j.status!=='posted')return;j.status='reversed';j.voidReason=reason;this.documentStatus('journal',j.id,'reversed');return this.post({date,memo:`عكس ${j.no}: ${j.memo} — ${reason}`,refType:'reversal',refId:j.id,costCenterId:j.costCenterId,skipPeriod,lines:this.reversalLines(j.lines)})},
 reverse(refType,refId,reason='إلغاء',opts={}){for(const j of DB.data.journals.filter(j=>j.status==='posted'&&j.refType===refType&&j.refId===refId))this.reverseJournal(j,reason,opts)},
 _lineCacheKey:'',_lineCache:null,_partyBalanceCacheKey:'',_partyBalanceCache:null,
 lineCacheKey(){const js=DB.data.journals||[],first=js[0],last=js[js.length-1];return[DB.data?.meta?.updatedAt||'',js.length,first?.id||'',first?.status||'',last?.id||'',last?.status||''].join('|')},
 invalidateLineCache(){this._lineCacheKey='';this._lineCache=null;this._partyBalanceCacheKey='';this._partyBalanceCache=null},
 allLines(){const key=this.lineCacheKey();if(this._lineCache&&this._lineCacheKey===key)return this._lineCache;const out=[];for(const j of DB.data.journals||[]){if(!live(j))continue;for(const l of j.lines||[])out.push({...l,journalId:j.id,journalNo:j.no,date:j.date,memo:j.memo,refType:j.refType,refId:j.refId,costCenterId:l.costCenterId||j.costCenterId,branchId:j.branchId||''})}this._lineCacheKey=key;this._lineCache=out;this._partyBalanceCacheKey='';this._partyBalanceCache=null;return out},
 lines(from='',to='',opts:any={}){const ex=new Set(opts.excludeRefTypes||[]),branchId=S(opts.branchId||''),all=this.allLines();if(!from&&!to&&!ex.size&&!branchId)return all;return all.filter(l=>!ex.has(l.refType)&&(!branchId||l.branchId===branchId)&&(!from||l.date>=from)&&(!to||l.date<=to))},
 partyBalanceIndex(){const key=this.lineCacheKey();if(this._partyBalanceCache&&this._partyBalanceCacheKey===key)return this._partyBalanceCache;const buckets={receivable:new Map(),advance:new Map(),supplierPayable:new Map(),supplierAdvance:new Map(),agentPayable:new Map()},add=(map,k,c,v)=>{if(!k||Math.abs(v)<=EPS)return;let o=map.get(k);if(!o){o={};map.set(k,o)}o[c]=(o[c]||0)+v};for(const l of this.allLines()){const k=`${l.partyType||''}|${l.partyId||''}`,c=l.currency||DB.data.settings.baseCurrency;if(l.accountId==='1200'&&l.partyType==='customer')add(buckets.receivable,k,c,l.debit-l.credit);else if(l.accountId==='1210'&&l.partyType==='agent')add(buckets.receivable,k,c,l.debit-l.credit);else if(l.accountId==='2400'&&l.partyType==='customer')add(buckets.advance,k,c,l.credit-l.debit);else if(l.accountId==='2410'&&l.partyType==='agent')add(buckets.advance,k,c,l.credit-l.debit);else if(l.accountId==='2100'&&l.partyType==='supplier')add(buckets.supplierPayable,k,c,l.credit-l.debit);else if(l.accountId==='1400'&&l.partyType==='supplier')add(buckets.supplierAdvance,k,c,l.debit-l.credit);else if(l.accountId==='2200'&&l.partyType==='agent')add(buckets.agentPayable,k,c,l.credit-l.debit)}this._partyBalanceCacheKey=key;this._partyBalanceCache=buckets;return buckets},
 cachedPartyBalance(bucket,type,id){return{...(this.partyBalanceIndex()[bucket]?.get(`${type}|${id}`)||{})}},
 accountBalance(id,from='',to='',opts={}){const ids=new Set([id,...this.descendants(id)]);let debit=0,credit=0;for(const l of this.lines(from,to,opts))if(ids.has(l.accountId)){debit+=l.baseDebit;credit+=l.baseCredit}return{debit,credit,net:debit-credit}},
 nativeBalance(id,partyType='',partyId='',currency='',to=''){let out=0;for(const l of this.lines('',to))if(l.accountId===id&&(!partyType||l.partyType===partyType)&&(!partyId||l.partyId===partyId)&&(!currency||l.currency===currency))out+=l.debit-l.credit;return out},
 carryingBase(id,partyType='',partyId='',currency='',to=''){let out=0;for(const l of this.lines('',to))if(l.accountId===id&&(!partyType||l.partyType===partyType)&&(!partyId||l.partyId===partyId)&&(!currency||l.currency===currency))out+=l.baseDebit-l.baseCredit;return out},
 partyReceivable(type,id,from='',to=''){if(!from&&!to)return this.cachedPartyBalance('receivable',type,id);const acct=type==='customer'?'1200':'1210',out={};for(const l of this.lines(from,to))if(l.accountId===acct&&l.partyType===type&&l.partyId===id){out[l.currency]??=0;out[l.currency]+=l.debit-l.credit}return out},
 customerAdvance(type,id,from='',to=''){if(!from&&!to)return this.cachedPartyBalance('advance',type,id);const acct=type==='agent'?'2410':'2400',out={};for(const l of this.lines(from,to))if(l.accountId===acct&&l.partyType===type&&l.partyId===id){out[l.currency]??=0;out[l.currency]+=l.credit-l.debit}return out},
 supplierPayable(id,from='',to=''){if(!from&&!to)return this.cachedPartyBalance('supplierPayable','supplier',id);const out={};for(const l of this.lines(from,to))if(l.accountId==='2100'&&l.partyType==='supplier'&&l.partyId===id){out[l.currency]??=0;out[l.currency]+=l.credit-l.debit}return out},supplierAdvance(id,from='',to=''){if(!from&&!to)return this.cachedPartyBalance('supplierAdvance','supplier',id);const out={};for(const l of this.lines(from,to))if(l.accountId==='1400'&&l.partyType==='supplier'&&l.partyId===id){out[l.currency]??=0;out[l.currency]+=l.debit-l.credit}return out},agentPayable(id,from='',to=''){if(!from&&!to)return this.cachedPartyBalance('agentPayable','agent',id);const out={};for(const l of this.lines(from,to))if(l.accountId==='2200'&&l.partyType==='agent'&&l.partyId===id){out[l.currency]??=0;out[l.currency]+=l.credit-l.debit}return out},
 treasuryBalance(id,to=''){const t=byId(DB.data.treasuries,id);if(!t)return 0;const aid=this.treasuryAccountId(id);return this.lines('',to).filter(l=>l.accountId===aid&&!l.baseOnly).reduce((s,l)=>s+l.debit-l.credit,0)},
 validateTreasury(id,amount){const t=byId(DB.data.treasuries,id);if(!t||t.active===false)throw new Error('الخزنة غير متاحة');if(DB.data.settings.preventNegativeTreasury&&this.treasuryBalance(id)+EPS<N(amount))throw new Error(`الرصيد غير كافٍ. المتاح ${money(this.treasuryBalance(id),t.currency)}`)},
 postOpeningTreasury(t,amount,date=today()){amount=N(amount);if(amount<=0)return;const aid=this.ensureTreasuryAccount(t);this.post({date,memo:`رصيد افتتاحي — ${t.name}`,refType:'treasury-opening',refId:t.id,lines:[{accountId:aid,debit:amount,currency:t.currency,treasuryId:t.id},{accountId:'3100',credit:Currency.toBase(amount,t.currency,date),currency:DB.data.settings.baseCurrency}]})},
 fxRevalue(date=today()){Periods.assertOpen(date);const base=DB.data.settings.baseCurrency,positions=[];for(const l of this.lines('',date)){if(l.currency===base)continue;const a=this.account(l.accountId);if(!a||a.type==='revenue'||a.type==='expense'||a.type==='equity')continue;const key=[l.accountId,l.partyType||'',l.partyId||'',l.treasuryId||'',l.currency].join('|');let p=positions.find(x=>x.key===key);if(!p){p={key,accountId:l.accountId,partyType:l.partyType||'',partyId:l.partyId||'',treasuryId:l.treasuryId||'',currency:l.currency,native:0,carrying:0};positions.push(p)}if(!l.baseOnly)p.native+=l.debit-l.credit;p.carrying+=l.baseDebit-l.baseCredit}const lines=[],details=[];for(const p of positions){if(Math.abs(p.native)<=EPS)continue;const target=p.native*Currency.rate(p.currency,date),diff=target-p.carrying;if(Math.abs(diff)<=0.01)continue;const common={partyType:p.partyType,partyId:p.partyId,treasuryId:p.treasuryId,currency:p.currency,baseOnly:true};if(diff>0){lines.push({accountId:p.accountId,baseDebit:diff,...common},{accountId:'4510',baseCredit:diff,currency:base,baseOnly:true})}else{lines.push({accountId:p.accountId,baseCredit:-diff,...common},{accountId:'5510',baseDebit:-diff,currency:base,baseOnly:true})}details.push({...p,target,diff})}if(!lines.length)throw new Error('لا توجد فروق إعادة تقييم تحتاج ترحيل');const ref=iid(),j=this.post({date,memo:`إعادة تقييم العملات ${date}`,refType:'fx-revaluation',refId:ref,lines});DB.data.fxRevaluations.unshift({id:ref,no:Numbering.next('fxRevaluation',date),date,journalId:j.id,details,status:'posted'});return details},
 audit(){
  const issues=[],d=DB.data,seen=new Set();
  for(const a of d.accounts){
   if(seen.has(a.id))issues.push({level:'critical',code:'DUP_ACCOUNT',msg:`كود حساب مكرر ${a.id}`});
   seen.add(a.id);
   const trail=new Set([a.id]);let p=a;
   while(p?.parentId){if(trail.has(p.parentId)){issues.push({level:'critical',code:'ACCOUNT_CYCLE',msg:`دورة غير صحيحة في شجرة الحسابات عند ${a.id}`});break}trail.add(p.parentId);p=this.account(p.parentId)}
  }
  for(const t of d.treasuries){
   const aid=this.treasuryAccountId(t.id);
   if(!this.account(aid))issues.push({level:'critical',code:'TREASURY_ACCOUNT',msg:`الخزنة ${t.name} بدون حساب أستاذ`,fixable:true,treasuryId:t.id});
   if(this.treasuryBalance(t.id)<-EPS)issues.push({level:'critical',code:'NEG_TREASURY',msg:`رصيد سالب في ${t.name}`});
  }
  for(const j of d.journals.filter(live)){
   const dr=j.lines.reduce((s,l)=>s+N(l.baseDebit),0),cr=j.lines.reduce((s,l)=>s+N(l.baseCredit),0);
   if(Math.abs(dr-cr)>0.01)issues.push({level:'critical',code:'UNBALANCED',msg:`قيد غير متزن ${j.no}`});
   for(const l of j.lines){
    if(!this.account(l.accountId))issues.push({level:'critical',code:'MISSING_ACCOUNT',msg:`القيد ${j.no} يشير لحساب مفقود ${l.accountId}`});
    if(['1200','1210','2100','2200','1400','2400','2410'].includes(l.accountId)&&!l.partyId)issues.push({level:'critical',code:'CONTROL_NO_PARTY',msg:`قيد ${j.no} على حساب رقابة بدون طرف`});
   }
  }
  for(const c of Currency.active())if(c.code!==d.settings.baseCurrency&&!(Currency.rate(c.code)>0))issues.push({level:'critical',code:'FX_RATE',msg:`سعر صرف غير صالح للعملة ${c.code}`});
  for(const inv of d.invoices.filter(live)){
   const total=Invoices.total(inv),alloc=Invoices.allocations(inv.id),adj=Invoices.adjustmentEffect(inv.id);
   const net=Math.max(0,total+adj),backedAdvance=DB.data.invoiceAdjustments.filter(x=>live(x)&&x.invoiceId===inv.id).reduce((z,x)=>z+N(x.advanceEffect),0);if(alloc-net>backedAdvance+0.01)issues.push({level:'critical',code:'OVER_ALLOCATED',msg:`الفاتورة ${inv.no} مسددة بأكثر من صافيها دون رصيد مقدم مقابل`});
   const arr=inv.kind==='supplier'?d.suppliers:(inv.partyType==='agent'?d.agents:d.customers);
   if(!byId(arr,inv.partyId))issues.push({level:'critical',code:'ORPHAN_PARTY',msg:`الفاتورة ${inv.no} مرتبطة بطرف مفقود`});
   if(inv.status!=='draft'&&!d.journals.some(j=>j.refType==='invoice'&&j.refId===inv.id))issues.push({level:'critical',code:'INV_NO_JOURNAL',msg:`الفاتورة ${inv.no} بدون قيد`});
  }
  for(const r of d.receipts.filter(live)){
   if(r.paymentMethod!=='cheque'&&!byId(d.treasuries,r.treasuryId))issues.push({level:'critical',code:'MISSING_TREASURY',msg:`سند القبض ${r.no} بخزنة مفقودة`});
   for(const a of r.allocations||[]){const inv=byId(d.invoices,a.invoiceId);if(!inv||inv.kind!=='customer'||inv.partyId!==r.partyId)issues.push({level:'critical',code:'BAD_ALLOCATION',msg:`تخصيص غير صحيح في ${r.no}`})}
  }
  for(const p of d.payments.filter(live)){
   if(p.paymentMethod!=='cheque'&&!byId(d.treasuries,p.treasuryId))issues.push({level:'critical',code:'MISSING_TREASURY',msg:`سند الصرف ${p.no} بخزنة مفقودة`});
   for(const a of p.allocations||[]){const inv=byId(d.invoices,a.invoiceId);if(!inv||inv.kind!=='supplier'||inv.partyId!==p.partyId)issues.push({level:'critical',code:'BAD_ALLOCATION',msg:`تخصيص غير صحيح في ${p.no}`})}
  }
  for(const srv of d.services.filter(x=>['confirmed','completed'].includes(x.status))){
   if(N(srv.cost)>0&&!srv.supplierId)issues.push({level:'critical',code:'SERVICE_COST_NO_SUPPLIER',msg:`الخدمة ${srv.no} بها تكلفة بدون مورد`});
   if(N(srv.sale)>0&&!srv.customerInvoiceId)issues.push({level:'critical',code:'SERVICE_NO_SALES_INV',msg:`الخدمة ${srv.no} بدون فاتورة بيع`});
   if(N(srv.cost)>0&&!srv.supplierInvoiceId)issues.push({level:'critical',code:'SERVICE_NO_PURCHASE_INV',msg:`الخدمة ${srv.no} بدون فاتورة تكلفة`});
  }
  for(const b of d.bookings.filter(x=>['confirmed','completed'].includes(x.status))){
   if(!b.invoiceId)issues.push({level:'critical',code:'BOOKING_NO_INV',msg:`الحجز ${b.no} بدون فاتورة`});
   const activeTrav=d.travelers.filter(t=>t.bookingId===b.id&&t.active!==false).length;
   if(activeTrav!==N(b.persons))issues.push({level:'warning',code:'TRAVELER_COUNT',msg:`الحجز ${b.no}: عدد المسافرين ${activeTrav} لا يساوي ${b.persons}`});
  }
  for(const a of d.attachments){const map={customer:'customers',supplier:'suppliers',booking:'bookings',service:'services',invoice:'invoices',traveler:'travelers',agent:'agents'},arr=d[map[a.entityType]||'']||[];if(!byId(arr,a.entityId))issues.push({level:'warning',code:'ORPHAN_ATTACHMENT',msg:`مرفق ${a.no} مرتبط بسجل مفقود`})}
  for(const tc of d.taxCodes)if(!this.account(tc.inputAccount)||!this.account(tc.outputAccount))issues.push({level:'critical',code:'TAX_ACCOUNT',msg:`كود الضريبة ${tc.id} مرتبط بحساب مفقود`});
  for(const arrName of ['invoices','receipts','payments','expenses','bookings','services','transfers','quotations','purchaseOrders']){const nums=new Set();for(const x of d[arrName]){if(nums.has(x.no))issues.push({level:'critical',code:'DUP_DOC',msg:`رقم مستند مكرر ${x.no}`});nums.add(x.no)}}
  const specs=[['customer',d.customers,'1200'],['supplier',d.suppliers,'2100'],['agent',d.agents,'1210']];
  for(const [key,parties,acct] of specs){
   let sub=0;
   for(const party of parties){const carry=this.carryingBase(acct,key,party.id);sub+=key==='supplier'?-carry:carry}
   const gl=key==='supplier'?-this.accountBalance(acct).net:this.accountBalance(acct).net;
   if(Math.abs(sub-gl)>0.01)issues.push({level:'critical',code:'SUBLEDGER_GL',msg:`عدم تطابق دفتر ${key} مع حساب الرقابة`});
  }
  const controlSpecs=[['دفعات العملاء','2400','customer',d.customers,'liability'],['دفعات المندوبين','2410','agent',d.agents,'liability'],['دفعات الموردين','1400','supplier',d.suppliers,'asset'],['عمولات المندوبين','2200','agent',d.agents,'liability']];
  for(const [label,acct,ptype,parties,nature] of controlSpecs){let sub=0;for(const party of parties){const c=this.carryingBase(acct,ptype,party.id);sub+=nature==='liability'?-c:c}const gl=nature==='liability'?-this.accountBalance(acct).net:this.accountBalance(acct).net;if(Math.abs(sub-gl)>0.01)issues.push({level:'critical',code:'CONTROL_SUBLEDGER_GL',msg:`عدم تطابق ${label} مع حساب الرقابة ${acct}`})}
  for(const r of d.receipts.filter(live))if(!d.journals.some(j=>j.refType==='receipt'&&j.refId===r.id))issues.push({level:'critical',code:'RECEIPT_NO_JOURNAL',msg:`سند القبض ${r.no} بدون قيد`});
  for(const p of d.payments.filter(live))if(!d.journals.some(j=>j.refType==='payment'&&j.refId===p.id))issues.push({level:'critical',code:'PAYMENT_NO_JOURNAL',msg:`سند الصرف ${p.no} بدون قيد`});
  for(const t of d.transfers.filter(live))if(!d.journals.some(j=>j.refType==='transfer'&&j.refId===t.id))issues.push({level:'critical',code:'TRANSFER_NO_JOURNAL',msg:`التحويل ${t.no} بدون قيد`});
  for(const a of d.invoiceAdjustments.filter(live))if(!d.journals.some(j=>j.refType==='invoice-adjustment'&&j.refId===a.id))issues.push({level:'critical',code:'ADJUSTMENT_NO_JOURNAL',msg:`الإشعار ${a.no} بدون قيد`});
  for(const inv of d.invoices.filter(x=>live(x)&&x.status!=='draft')){if(!d.journals.some(j=>j.status!=='void'&&j.refType==='invoice'&&j.refId===inv.id))issues.push({level:'critical',code:'INVOICE_NO_JOURNAL',msg:`الفاتورة ${inv.no} بدون قيد ترحيل`});const rem=Invoices.remaining(inv),net=Math.max(0,Invoices.total(inv)+Invoices.adjustmentEffect(inv.id)),expected=rem<=EPS?'paid':rem<net?'partial':'open';if(inv.status!==expected)issues.push({level:'warning',code:'INVOICE_STATUS_MISMATCH',msg:`حالة الفاتورة ${inv.no} (${sl(inv.status)}) لا تطابق الرصيد الحالي (${sl(expected)})`})}
  for(const r of d.receipts.filter(x=>x.status==='void'))if(d.journals.some(j=>j.status==='posted'&&j.refType==='receipt-advance-apply'&&j.refId===r.id))issues.push({level:'critical',code:'VOID_RECEIPT_ACTIVE_ADVANCE_APPLY',msg:`سند القبض ${r.no} ملغي لكن تسوية الدفعة المقدمة ما زالت مرحّلة`});
  for(const p of d.payments.filter(x=>x.status==='void'))if(d.journals.some(j=>j.status==='posted'&&j.refType==='payment-advance-apply'&&j.refId===p.id))issues.push({level:'critical',code:'VOID_PAYMENT_ACTIVE_ADVANCE_APPLY',msg:`سند الصرف ${p.no} ملغي لكن تسوية الدفعة المقدمة ما زالت مرحّلة`});
  const supplierRefs=new Set();for(const inv of d.invoices.filter(x=>live(x)&&x.kind==='supplier'&&S(x.externalNo).trim())){const k=`${inv.partyId}|${S(inv.externalNo).trim().toLowerCase()}`;if(supplierRefs.has(k))issues.push({level:'critical',code:'DUP_SUPPLIER_EXTERNAL_NO',msg:`رقم فاتورة مورد مكرر للمورد نفسه: ${inv.externalNo}`});supplierRefs.add(k)}
  for(const e of d.expenses.filter(x=>x.status==='posted')){if(['paid','prepaid'].includes(e.mode)&&(!e.paymentId||!byId(d.payments,e.paymentId)))issues.push({level:'critical',code:'EXPENSE_NO_PAYMENT',msg:`المصروف ${e.no} بدون سند صرف مرتبط`});if(e.mode==='accrued'&&(!e.invoiceId||!byId(d.invoices,e.invoiceId)))issues.push({level:'critical',code:'EXPENSE_NO_AP',msg:`المصروف المستحق ${e.no} بدون فاتورة مورد`})}
  for(const ch of d.cheques){const voucher=ch.direction==='in'?byId(d.receipts,ch.voucherId):byId(d.payments,ch.voucherId);if(!voucher)issues.push({level:'critical',code:'CHEQUE_NO_VOUCHER',msg:`الشيك ${ch.no} بدون سند مرتبط`});if(ch.status==='cleared'&&!d.journals.some(j=>j.refType==='cheque-clear'&&j.refId===ch.id))issues.push({level:'critical',code:'CHEQUE_NO_CLEAR_JOURNAL',msg:`الشيك المحصل ${ch.no} بدون قيد تحصيل`})}
  const taxSeen=new Set();for(const tc of d.taxCodes){if(taxSeen.has(tc.id))issues.push({level:'critical',code:'DUP_TAX',msg:`كود ضريبة مكرر ${tc.id}`});taxSeen.add(tc.id)}
  const docMap={invoice:'invoices',receipt:'receipts',payment:'payments',transfer:'transfers',expense:'expenses',invoiceAdjustment:'invoiceAdjustments',journal:'journals'};for(const doc of d.documents){const arr=d[docMap[doc.type]];if(arr&&!byId(arr,doc.refId))issues.push({level:'warning',code:'ORPHAN_DOCUMENT',msg:`المستند ${doc.no||doc.title} يشير إلى سجل مفقود`})}
   const taxLedger=Tax.ledger(),taxByAccount={};for(const r of taxLedger){const tc=Tax.get(r.taxId);if(!tc)continue;const aid=r.kind==='supplier'?tc.inputAccount:tc.outputAccount;taxByAccount[aid]=(taxByAccount[aid]||0)+(r.kind==='supplier'?r.baseTax:-r.baseTax)}for(const[aid,expectedNet]of Object.entries(taxByAccount) as [string,number][]){const gl=this.accountBalance(aid).net;if(Math.abs(gl-expectedNet)>0.01)issues.push({level:'critical',code:'TAX_LEDGER_GL',msg:`عدم تطابق دفتر الضرائب مع حساب ${aid}: دفتر ${fmt(expectedNet)} / أستاذ ${fmt(gl)}`})}
   for(const fy of d.fiscalYears){for(const j of d.journals.filter(j=>j.refType==='year-reopen'&&j.refId===fy.id))if(j.date<fy.from||j.date>fy.to)issues.push({level:'critical',code:'YEAR_REOPEN_DATE',msg:`قيد إعادة فتح السنة ${fy.label} خارج حدود السنة`})}
   for(const x of d.approvals.filter(a=>a.status==='approved'))if(DB.data.settings.allowSelfApproval!==true&&x.requestedBy&&x.requestedBy===x.approvedBy)issues.push({level:'warning',code:'SELF_APPROVAL',msg:`طلب ${x.no} اعتمده نفس طالب العملية`});
  const um={programs:d.umrahPrograms||[],bookings:d.umrahBookings||[],travelers:d.umrahTravelers||[],programSegments:d.umrahProgramSegments||[],tickets:d.umrahTickets||[],supplierCommitments:d.umrahSupplierCommitments||[]};
  if(um.programs.length||um.bookings.length||um.travelers.length){
   const activeBookingStatuses=new Set(['confirmed','partiallyPaid','fullyPaid','docsPending','ready','checkedIn','traveling','returned']);for(const pr of um.programs||[]){const used=(um.bookings||[]).filter(b=>b.programId===pr.id&&activeBookingStatuses.has(b.status)).reduce((z,b)=>z+N(b.persons),0);if(used>N(pr.capacity)+EPS)issues.push({level:'critical',code:'UMRAH_OVER_CAPACITY',msg:`البرنامج ${pr.no||pr.name||pr.id} متجاوز السعة: ${used} محجوز / ${N(pr.capacity)} سعة`})}for(const b of um.bookings||[]){if(!['cancelled','refunded','closed'].includes(b.status)){const count=(um.travelers||[]).filter(t=>t.bookingId===b.id&&t.active!==false).length;if(count!==N(b.persons))issues.push({level:'warning',code:'UMRAH_TRAVELER_COUNT',msg:`حجز العمرة ${b.no||b.id}: عدد ملفات المسافرين ${count} لا يساوي عدد الحجز ${N(b.persons)}`})}}
   for(const b of um.bookings||[]){const inv=d.invoices.find(x=>x.sourceType==='umrah-booking'&&x.sourceId===b.id&&live(x));if(['cancelled','refunded'].includes(b.status)&&inv&&live(inv)&&inv.status!=='void')issues.push({level:'critical',code:'UMRAH_CANCEL_OPEN_INVOICE',msg:`حجز العمرة ${b.no||b.id} ملغي لكن الفاتورة ${inv.no} ما زالت مفتوحة`});if(!['cancelled','refunded','closed'].includes(b.status)&&b.hostInvoiceId&&!byId(d.invoices,b.hostInvoiceId))issues.push({level:'critical',code:'UMRAH_MISSING_INVOICE',msg:`حجز العمرة ${b.no||b.id} يشير إلى فاتورة مفقودة`});if(inv){const rem=Invoices.remaining(inv),pay=b.paymentStatus||'';if(pay==='fullyPaid'&&rem>EPS)issues.push({level:'critical',code:'UMRAH_PAYMENT_STATUS',msg:`حجز ${b.no||b.id} حالته المالية مسدد بالكامل بينما متبقي الفاتورة ${money(rem,inv.currency)}`});if(pay==='unpaid'&&Invoices.allocations(inv.id)>EPS)issues.push({level:'warning',code:'UMRAH_PAYMENT_STATUS',msg:`حجز ${b.no||b.id} مسجل غير مسدد رغم وجود تحصيلات`})}}
   const segs=um.programSegments||[];for(const tk of (um.tickets||[]).filter(x=>x.active!==false&&['issued','reissued'].includes(x.status))){const sg=segs.find(x=>x.id===tk.segmentId);if(!sg||sg.type!=='flight'||sg.programId!==tk.programId||sg.active===false)issues.push({level:'critical',code:'UMRAH_INVALID_TICKET_SEGMENT',msg:`تذكرة ${tk.ticketNo||tk.id} مرتبطة بقطاع طيران غير صالح`})}
   for(const c of um.supplierCommitments||[]){if(c.hostPOId&&!byId(d.purchaseOrders,c.hostPOId))issues.push({level:'critical',code:'UMRAH_MISSING_PO',msg:`التزام مورد في العمرة مرتبط بأمر شراء مفقود`});if(c.hostInvoiceId&&!byId(d.invoices,c.hostInvoiceId))issues.push({level:'critical',code:'UMRAH_MISSING_AP',msg:`التزام مورد في العمرة مرتبط بفاتورة مورد مفقودة`})}
  }
  for(const po of d.purchaseOrders.filter(x=>['approved','partiallyReceived','received','partiallyInvoiced','converted'].includes(x.status))){
   const ids=[...new Set([...(po.invoiceIds||[]),po.invoiceId].filter(Boolean))],activeInvoices=ids.map(id=>byId(d.invoices,id)).filter(x=>x&&live(x)&&!['void','cancelled'].includes(x.status)),receivedUninvoiced=(po.lines||[]).reduce((z,l)=>z+Math.max(0,Math.min(N(l.qty),N(l.receivedQty))-N(l.invoicedQty)),0);
   if(po.status==='converted'&&!activeInvoices.length)issues.push({level:'critical',code:'PO_STALE_CONVERTED',category:'purchases',page:'purchaseorders',refId:po.id,msg:`أمر الشراء ${po.no} ظاهر كمحوّل بدون فاتورة مورد فعالة`});
   if((po.status==='received'&&!activeInvoices.length)||receivedUninvoiced>EPS)issues.push({level:'warning',code:'RECEIVED_NOT_INVOICED',category:'purchases',page:'purchaseorders',refId:po.id,msg:`أمر الشراء ${po.no} به كمية منفذة غير مفوترة (${fmt(receivedUninvoiced)})`});
  }
  for(const inv of d.invoices.filter(x=>live(x)&&x.status!=='draft')){
   if(['void','cancelled'].includes(inv.status)&&Invoices.remaining(inv)>EPS)issues.push({level:'critical',code:'VOID_INVOICE_BALANCE',category:'invoices',page:'invoices',refId:inv.id,msg:`الفاتورة الملغاة ${inv.no} ما زال لها رصيد`});
   if((inv.programId||inv.sourceType==='umrah-booking')&&!inv.costCenterId&&!inv.lines?.some(l=>l.costCenterId))issues.push({level:'critical',code:'PROGRAM_INVOICE_NO_COST_CENTER',category:'cost-centers',page:'invoices',refId:inv.id,msg:`الفاتورة ${inv.no} مرتبطة ببرنامج بدون مركز تكلفة`});
  }
  for(const j of d.journals.filter(live))for(const l of j.lines||[]){
   if(l.costCenterId&&!byId(d.costCenters,l.costCenterId))issues.push({level:'critical',code:'MISSING_COST_CENTER',category:'cost-centers',page:'journal',refId:j.id,msg:`القيد ${j.no} يشير إلى مركز تكلفة مفقود`});
   if(!l.baseOnly&&l.currency!==d.settings.baseCurrency&&!(N(l.rate)>0))issues.push({level:'critical',code:'JOURNAL_FX_RATE',category:'currency',page:'journal',refId:j.id,msg:`القيد ${j.no} يحتوي سعر صرف غير صالح للعملة ${l.currency}`});
  }
  if(typeof AdvancedAccounting!=='undefined')issues.push(...AdvancedAccounting.integrity());
  return issues
 },
 integrityReport(){const started=performance.now(),issues=this.audit(),critical=issues.filter(x=>x.level==='critical'),warnings=issues.filter(x=>x.level!=='critical'),categories={};for(const i of issues){const key=i.category||(/TAX/.test(i.code)?'tax':/FX|CURRENCY/.test(i.code)?'currency':/UMRAH|PROGRAM|BOOKING/.test(i.code)?'umrah':/PO|SUPPLIER|PAYMENT/.test(i.code)?'purchases':/INVOICE|RECEIPT|ALLOC/.test(i.code)?'invoices':/ACCOUNT|JOURNAL|SUBLEDGER|CONTROL/.test(i.code)?'ledger':'other');categories[key]=(categories[key]||0)+1}const report={checkedAt:now(),durationMs:Math.round(performance.now()-started),issues,critical,warnings,categories,counts:{journals:(DB.data.journals||[]).filter(live).length,invoices:(DB.data.invoices||[]).filter(live).length,purchaseOrders:(DB.data.purchaseOrders||[]).filter(x=>x.status!=='void').length,parties:(DB.data.customers||[]).length+(DB.data.suppliers||[]).length+(DB.data.agents||[]).length},ok:critical.length===0};this._lastIntegrityReport=report;return report},
 lastIntegrityReport(){return this._lastIntegrityReport||this.integrityReport()},
 rerunIntegrity(){return IntegrityWorkflows.rerun(composeLegacyIntegrityDeps(this));},
 openIssue(page,refId=''){if(page)UiPort.openPage(page,refId);},
 autoFix(){return IntegrityWorkflows.repair(composeLegacyIntegrityDeps(this));}
};
__set_Accounting(Accounting);

const ManualJournal={createDraft(o){return ManualJournalWorkflows.createDraft(composeLegacyManualJournalDeps(),o)},updateDraft(id,o){return ManualJournalWorkflows.updateDraft(composeLegacyManualJournalDeps(),id,o)},postDraft(id){return ManualJournalWorkflows.postDraft(composeLegacyManualJournalDeps(),id)},removeDraft(id){return ManualJournalWorkflows.removeDraft(composeLegacyManualJournalDeps(),id)},reverse(id,reason){return ManualJournalWorkflows.reverse(composeLegacyManualJournalDeps(),id,reason)},addRecurring(o){return ManualJournalWorkflows.addRecurring(composeLegacyManualJournalDeps(),o)},toggleRecurring(id){return ManualJournalWorkflows.toggleRecurring(composeLegacyManualJournalDeps(),id)},removeRecurring(id){return ManualJournalWorkflows.removeRecurring(composeLegacyManualJournalDeps(),id)},runRecurring(id){return ManualJournalWorkflows.runRecurring(composeLegacyManualJournalDeps(),id)}};
export { Accounting, ManualJournal };
