import { EPS, Money, N, S, byId, iid, live, money, now, today } from '../core/runtime';
import { AdvancedAccountingRules } from './advanced-rules';
import { VoucherRules } from './voucher-rules';
import { VoucherWorkflows } from '../application/voucher-workflows';
import { ApprovalWorkflows } from '../application/approval-workflows';
import { TourismWorkflows } from '../application/tourism-workflows';
import { TransferWorkflows } from '../application/transfer-workflows';
import { ExpenseWorkflows } from '../application/expense-workflows';
import { Numbering } from '../core/numbering';
import { DB } from '../persistence/browser-store';
import { Currency, Periods } from './currency-periods';
import { Accounting } from './engine';
import { Invoices, MasterData } from './invoices';
import { TourismServiceInventory, composeLegacyApprovalDeps, composeLegacyExpenseDeps, composeLegacyTourismDeps, composeLegacyTransferDeps, composeLegacyVoucherDeps } from '../core/late-bindings';
import { __set_Transactions } from '../core/late-bindings';
const Transactions: any = {
 addCustomer(o){if(!S(o.name).trim())throw new Error('اسم العميل مطلوب');if(o.nationalId&&DB.data.customers.some(x=>x.nationalId===o.nationalId))throw new Error('الرقم القومي مستخدم');if(o.passport&&DB.data.customers.some(x=>x.passport===o.passport))throw new Error('رقم الجواز مستخدم');const x={id:iid(),no:Numbering.next('customer'),active:true,type:o.type||'individual',creditLimit:N(o.creditLimit),...o,createdAt:now()};DB.data.customers.unshift(x);DB.log('create','customer',x.id,x.no);return x},
 addSupplier(o){if(!S(o.name).trim())throw new Error('اسم المورد مطلوب');const x={id:iid(),no:Numbering.next('supplier'),active:true,creditDays:N(o.creditDays),currency:o.currency||DB.data.settings.baseCurrency,...o,createdAt:now()};DB.data.suppliers.unshift(x);DB.log('create','supplier',x.id,x.no);return x},
 addAgent(o){if(!S(o.name).trim())throw new Error('اسم المندوب مطلوب');const x={id:iid(),no:Numbering.next('agent'),active:true,commissionMode:o.commissionMode||'fixed',commissionValue:N(o.commissionValue),commissionCurrency:o.commissionCurrency||DB.data.settings.baseCurrency,...o,createdAt:now()};DB.data.agents.unshift(x);DB.log('create','agent',x.id,x.no);return x},
 addProgram(o){if(!S(o.name).trim())throw new Error('اسم البرنامج مطلوب');const id=iid(),no=Numbering.next('program'),cc={id:iid(),no:Numbering.next('costCenter'),name:`${no} — ${o.name}`,description:'مركز ربحية برنامج حج/عمرة',active:true,programId:id,system:false};DB.data.costCenters.push(cc);const x={id,no,active:true,status:'open',capacity:N(o.capacity),priceQuad:N(o.priceQuad||o.price),priceTriple:N(o.priceTriple||o.price),priceDouble:N(o.priceDouble||o.price),priceSingle:N(o.priceSingle||o.price),childPrice:N(o.childPrice),currency:o.currency||DB.data.settings.baseCurrency,costCenterId:cc.id,...o};DB.data.programs.unshift(x);DB.log('create','program',x.id,x.no);return x},
 updateProgram(id,o){const p=byId(DB.data.programs,id);if(!p)throw new Error('البرنامج غير موجود');const used=this.bookedCount(id),cap=N(o.capacity);if(cap<used)throw new Error(`السعة لا تقل عن المحجوز (${used})`);Object.assign(p,o,{capacity:cap,id:p.id,no:p.no,costCenterId:p.costCenterId,active:p.active});const cc=byId(DB.data.costCenters,p.costCenterId);if(cc)cc.name=`${p.no} — ${p.name}`;DB.log('update','program',id,p.no)},
 bookedCount(pid){return DB.data.bookings.filter(x=>['confirmed','completed'].includes(x.status)&&x.programId===pid).reduce((s,x)=>s+N(x.persons),0)},
 roomLimit(pr,type){return N(({single:pr.singleRooms,double:pr.doubleRooms,triple:pr.tripleRooms,quad:pr.quadRooms})[type])},bookedRooms(pid,type,exclude=''){return DB.data.roomAllocations.filter(r=>r.programId===pid&&r.roomType===type&&r.bookingId!==exclude&&DB.data.bookings.some(b=>b.id===r.bookingId&&['confirmed','completed'].includes(b.status))).reduce((s,r)=>s+N(r.rooms),0)},
 validateBooking(pr,persons,allocations=[],exclude=''){const existing=DB.data.bookings.filter(x=>['confirmed','completed'].includes(x.status)&&x.programId===pr.id&&x.id!==exclude).reduce((s,x)=>s+N(x.persons),0);if(existing+N(persons)>N(pr.capacity))throw new Error('لا توجد سعة إجمالية كافية');for(const r of allocations){const limit=this.roomLimit(pr,r.roomType);if(limit>0&&this.bookedRooms(pr.id,r.roomType,exclude)+N(r.rooms)>limit)throw new Error(`لا يوجد مخزون كافٍ من غرف ${r.roomType}`)}},
 normalizeRoomAllocations(persons,raw){const list=(raw||[]).filter(r=>N(r.rooms)>0).map(r=>({roomType:r.roomType||'quad',rooms:Math.max(1,N(r.rooms)),persons:Math.max(0,N(r.persons))}));if(!list.length)list.push({roomType:'quad',rooms:Math.max(1,Math.ceil(N(persons)/4)),persons:N(persons)});const assigned=list.reduce((s,r)=>s+r.persons,0);if(assigned!==N(persons)){if(list.length===1)list[0].persons=N(persons);else throw new Error(`مجموع الأفراد في توزيع الغرف (${assigned}) يجب أن يساوي ${persons}`)}return list},
 syncTravelers(booking,text){const names=S(text).split(/\n|,/).map(x=>x.trim()).filter(Boolean),existing=DB.data.travelers.filter(t=>t.bookingId===booking.id).sort((a,b)=>a.no.localeCompare(b.no)),needed=N(booking.persons),active=[];for(let i=0;i<needed;i++){let t=existing[i];if(!t){t={id:iid(),bookingId:booking.id,no:`${booking.no}-${String(i+1).padStart(2,'0')}`,nameAr:'',nameEn:'',passport:'',nationality:'',birthDate:'',gender:'',passportIssue:'',passportExpiry:'',issuePlace:'',visaStatus:'pending',roomType:'',active:true};DB.data.travelers.push(t)}t.active=true;if(names[i])t.nameAr=names[i];else if(!t.nameAr&&i===0){const c=byId(DB.data.customers,booking.customerId);t.nameAr=c?.name||'';t.passport=t.passport||c?.passport||'';t.nationality=t.nationality||c?.nationality||'';t.birthDate=t.birthDate||c?.birthDate||'';t.gender=t.gender||c?.gender||'';t.passportExpiry=t.passportExpiry||c?.passportExpiry||''}active.push(t)}for(const t of existing.slice(needed))t.active=false;return active},
 saveRoomAllocations(booking,raw){DB.data.roomAllocations=DB.data.roomAllocations.filter(r=>r.bookingId!==booking.id);for(const r of this.normalizeRoomAllocations(booking.persons,raw))DB.data.roomAllocations.push({id:iid(),bookingId:booking.id,programId:booking.programId,roomType:r.roomType,rooms:N(r.rooms),persons:N(r.persons)})},
 addBooking(o){return DB.atomic('addBooking',()=>{const pr=byId(DB.data.programs,o.programId),c=byId(DB.data.customers,o.customerId);if(!pr||!c)throw new Error('اختر العميل والبرنامج');const persons=N(o.persons);if(persons<=0)throw new Error('عدد المسافرين يجب أن يكون أكبر من صفر');const rooms=this.normalizeRoomAllocations(persons,o.roomAllocations),total=N(o.total)||this.priceForRooms(pr,rooms);if(o.status!=='draft')this.validateBooking(pr,persons,rooms);const b={id:iid(),no:Numbering.next('booking',o.date||today()),date:o.date||today(),customerId:c.id,programId:pr.id,persons,total,currency:pr.currency,status:o.status||'confirmed',costCenterId:pr.costCenterId,note:o.note||'',createdAt:now()};DB.data.bookings.unshift(b);this.saveRoomAllocations(b,rooms);this.syncTravelers(b,o.travelersText);if(b.status!=='draft')this.confirmBooking(b.id,o);DB.log('create','booking',b.id,b.no);return b})},
 priceForRooms(pr,rooms){const price={single:N(pr.priceSingle),double:N(pr.priceDouble),triple:N(pr.priceTriple),quad:N(pr.priceQuad),child:N(pr.childPrice)};return rooms.reduce((s,r)=>s+N(r.persons)*price[r.roomType],0)},
 updateBooking(id,o){return DB.atomic('updateBooking',()=>{const b=byId(DB.data.bookings,id);if(!b)throw new Error('الحجز غير موجود');const financialLocked=b.status!=='draft';const pr=byId(DB.data.programs,o.programId||b.programId),c=byId(DB.data.customers,o.customerId||b.customerId);if(!pr||!c)throw new Error('اختر العميل والبرنامج');if(financialLocked){b.note=o.note??b.note;this.syncTravelers(b,o.travelersText);DB.log('update-nonfinancial','booking',id,b.no);return b}const persons=N(o.persons);if(persons<=0)throw new Error('عدد المسافرين يجب أن يكون أكبر من صفر');const rooms=this.normalizeRoomAllocations(persons,o.roomAllocations);Object.assign(b,{date:o.date||b.date,customerId:c.id,programId:pr.id,persons,total:N(o.total)||this.priceForRooms(pr,rooms),currency:pr.currency,costCenterId:pr.costCenterId,note:o.note||''});this.saveRoomAllocations(b,rooms);this.syncTravelers(b,o.travelersText);DB.log('update','booking',id,b.no);return b})},
 confirmBooking(id,o:any={}){const b=byId(DB.data.bookings,id),pr=b&&byId(DB.data.programs,b.programId),c=b&&byId(DB.data.customers,b.customerId);if(!b||!pr||!c)throw new Error('الحجز غير موجود');if(b.invoiceId)return b;const rooms=DB.data.roomAllocations.filter(r=>r.bookingId===b.id);this.validateBooking(pr,b.persons,rooms,b.id);Periods.assertOpen(b.date);b.status='confirmed';const inv:any=Invoices.create({kind:'customer',partyId:c.id,partyType:'customer',currency:b.currency,date:b.date,dueDate:o.dueDate||b.date,recognitionDate:pr.date||'',description:`حجز ${pr.name}`,sourceType:'booking',sourceId:b.id,costCenterId:b.costCenterId,lines:[{description:`حجز برنامج ${pr.name}`,qty:1,price:b.total,discount:0,discountMode:'fixed',taxId:o.taxId||'TAX0',accountId:'4100',costCenterId:b.costCenterId}],status:'draft'});inv.programId=b.programId||'';inv.bookingId=b.id||'';inv.revenueAccountId='4100';Invoices.post(inv);b.invoiceId=inv.id;if(N(o.paid)>0)this.addReceipt({date:b.date,partyType:'customer',partyId:c.id,treasuryId:o.treasuryId,amount:N(o.paid),currency:o.payCurrency||b.currency,note:`دفعة حجز ${b.no}`,invoiceId:inv.id,paymentMethod:o.paymentMethod||'cash',referenceNo:o.referenceNo||'',bankName:o.bankName||'',valueDate:o.valueDate||''});return b},
 reopenBooking(id,reason){return TourismWorkflows.reopenBooking(composeLegacyTourismDeps(this),id,reason)},completeBooking(id){return TourismWorkflows.completeBooking(composeLegacyTourismDeps(this),id)},
 cancelBooking(id,reason){return DB.atomic('cancelBooking',()=>{const b=byId(DB.data.bookings,id);if(!b||!['draft','confirmed'].includes(b.status))throw new Error('الحجز غير متاح للإلغاء');if(b.invoiceId){const inv=byId(DB.data.invoices,b.invoiceId);if(inv&&Invoices.allocations(inv.id)>EPS)throw new Error('اعكس التحصيلات المرتبطة أولًا');if(inv)Invoices.cancel(inv.id,reason)}b.status='cancelled';b.cancelReason=reason||'إلغاء';DB.log('cancel','booking',id,reason);return b})},
 removeProgram(id){const p=byId(DB.data.programs,id);if(!p)throw new Error('البرنامج غير موجود');MasterData.assertUnused('program',id);if(DB.data.services.some(s=>s.costCenterId===p.costCenterId)||DB.data.journals.some(j=>j.costCenterId===p.costCenterId))throw new Error('البرنامج له تاريخ مالي؛ يمكن إيقافه فقط');DB.data.costCenters=DB.data.costCenters.filter(c=>c.id!==p.costCenterId);DB.data.programs=DB.data.programs.filter(x=>x.id!==id)},updateTraveler(id,o){const t=byId(DB.data.travelers,id);if(!t)throw new Error('المسافر غير موجود');Object.assign(t,o,{id:t.id,bookingId:t.bookingId,no:t.no,active:t.active});DB.log('update','traveler',id,t.no)},
 addService(o){return DB.atomic('addService',()=>{const c=byId(DB.data.customers,o.customerId);if(!c)throw new Error('العميل مطلوب');if(!DB.data.serviceTypes.some(t=>t.active!==false&&t.name===o.type))throw new Error('اختر نوع خدمة صالح');const stock=typeof TourismServiceInventory!=='undefined'?TourismServiceInventory.prepare(o):null,agent=o.agentId?byId(DB.data.agents,o.agentId):byId(DB.data.agents,c.agentId);if(o.billToAgent==='yes'&&!agent)throw new Error('اختر المندوب لأن المديونية محددة عليه');if(N(o.externalCost)>0&&!o.supplierId)throw new Error('الجزء الذي سيتم شراؤه خارجيًا يتطلب موردًا');const requested=o.status||'draft',s={id:iid(),no:Numbering.next('service',o.date||today()),date:o.date||today(),type:o.type,customerId:c.id,supplierId:o.supplierId||'',agentId:agent?.id||'',billTo:o.billToAgent==='yes'?'agent':'customer',sale:N(o.sale),cost:N(o.cost),inventoryCost:N(o.inventoryCost),inventoryCostBase:N(o.inventoryCostBase),externalCost:N(o.externalCost),externalCostCurrency:o.externalCostCurrency||o.costCurrency||DB.data.settings.baseCurrency,externalCostBase:N(o.externalCostBase),saleCurrency:o.saleCurrency||DB.data.settings.baseCurrency,costCurrency:o.costCurrency||o.saleCurrency||DB.data.settings.baseCurrency,saleTaxId:o.saleTaxId||'TAX0',costTaxId:o.costTaxId||'TAX0',dueDate:o.dueDate||o.date||today(),supplierDueDate:o.supplierDueDate||o.date||today(),costCenterId:o.costCenterId||'CC-TOUR',commissionMode:o.commissionMode||'auto',commissionValue:N(o.commissionValue),commissionCurrency:o.commissionCurrency||o.saleCurrency||DB.data.settings.baseCurrency,status:'draft',billingStatus:'draft',inventoryMode:o.inventoryMode||'external',description:o.description||'',details:{country:o.country||'',applicationNo:o.applicationNo||'',pnr:o.pnr||'',ticketNo:o.ticketNo||'',airline:o.airline||'',flightNo:o.flightNo||'',route:o.route||'',checkIn:o.checkIn||'',checkOut:o.checkOut||'',hotelName:o.hotelName||'',roomType:o.roomType||'',rooms:o.rooms||'',from:o.from||'',to:o.to||'',vehicle:o.vehicle||'',passengers:o.passengers||'',serviceDate:o.serviceDate||''},createdAt:now()};DB.data.services.unshift(s);if(stock)TourismServiceInventory.bind(s,stock);if(requested!=='draft')this.confirmService(s.id);DB.log('create','service',s.id,`${s.no}${stock?' • من مخزون الشركة':''}`);return s})},
 updateService(id,o,{financial=false}={}){const s=byId(DB.data.services,id);if(!s)throw new Error('الخدمة غير موجودة');if(s.status!=='draft'&&!financial){s.description=o.description??s.description;s.details={...s.details,...o.details,...Object.fromEntries(['country','applicationNo','pnr','ticketNo','airline','flightNo','route','checkIn','checkOut','hotelName','roomType','rooms','from','to','vehicle','passengers','serviceDate'].map(k=>[k,o[k]??s.details?.[k]??'']))};DB.log('update-nonfinancial','service',id,s.no);return s}if(s.status!=='draft')throw new Error('البيانات المالية لا تعدل بعد الترحيل؛ استخدم الإلغاء/التصحيح');if(typeof TourismServiceInventory!=='undefined')TourismServiceInventory.release(s.id,'إعادة ربط مسودة الخدمة');const stock=typeof TourismServiceInventory!=='undefined'?TourismServiceInventory.prepare(o,s.id):null;if(N(o.externalCost)>0&&!o.supplierId)throw new Error('الجزء الخارجي من التكلفة يتطلب موردًا');Object.assign(s,{type:o.type,customerId:o.customerId,supplierId:o.supplierId||'',agentId:o.agentId||'',billTo:o.billToAgent==='yes'?'agent':'customer',sale:N(o.sale),cost:N(o.cost),inventoryCost:N(o.inventoryCost),inventoryCostBase:N(o.inventoryCostBase),externalCost:N(o.externalCost),externalCostCurrency:o.externalCostCurrency||o.costCurrency||DB.data.settings.baseCurrency,externalCostBase:N(o.externalCostBase),saleCurrency:o.saleCurrency,costCurrency:o.costCurrency,saleTaxId:o.saleTaxId||'TAX0',costTaxId:o.costTaxId||'TAX0',dueDate:o.dueDate||s.date,supplierDueDate:o.supplierDueDate||s.date,costCenterId:o.costCenterId||'CC-TOUR',commissionMode:o.commissionMode||'auto',commissionValue:N(o.commissionValue),commissionCurrency:o.commissionCurrency||o.saleCurrency||DB.data.settings.baseCurrency,inventoryMode:o.inventoryMode||'external',inventorySource:null,description:o.description||'',details:{...s.details,...o}});if(stock)TourismServiceInventory.bind(s,stock);return s},
 serviceCommissionAmount(s){if(!s.agentId||s.commissionMode==='none'||s.sale<=0)return null;const a=byId(DB.data.agents,s.agentId);if(!a)return null;let mode=s.commissionMode||'auto',value=N(s.commissionValue),currency=s.commissionCurrency||s.saleCurrency||DB.data.settings.baseCurrency,amount=0,rule=null;if(mode==='auto'){rule=this.commissionRule(a.id,s.id);if(rule){mode=rule.mode;value=N(rule.value);currency=rule.currency||currency}else{mode=a.commissionMode||'fixed';value=N(a.commissionValue);currency=a.commissionCurrency||currency}}if(mode==='percent'){const base=Currency.toBase(s.sale,s.saleCurrency,s.date)*value/100,rate=Currency.rate(currency,s.date);if(!(rate>0))throw new Error(`لا يوجد سعر صرف لعملة العمولة ${currency}`);amount=base/rate}else amount=value;if(amount<=EPS)return null;return{amount,currency,mode,value,ruleId:rule?.id||''}},
 ensureServiceCommission(s){if(!s||s.commissionId)return s?.commissionId?byId(DB.data.commissions,s.commissionId):null;const calc=this.serviceCommissionAmount(s);if(!calc)return null;const c:any={id:iid(),no:Numbering.next('commission',s.date),date:s.date,agentId:s.agentId,amount:calc.amount,currency:calc.currency,status:'pending',note:`عمولة تلقائية عن الخدمة ${s.no}`,sourceId:s.id,sourceType:'service',paidAmount:0,payments:[],rejectionReason:'',ruleId:calc.ruleId,commissionMode:calc.mode,commissionValue:calc.value};DB.data.commissions.unshift(c);const ap=Approvals.create('commission',{commissionId:c.id},Currency.toBase(c.amount,c.currency,s.date));c.approvalId=ap.id;s.commissionId=c.id;DB.log('auto-commission','service',s.id,`${c.no} / ${ap.no}`);return c},
 syncServiceBillingByInvoice(inv){if(!inv||inv.sourceType!=='service'||!inv.sourceId)return;const s=byId(DB.data.services,inv.sourceId);if(!s)return;if(inv.id===s.customerInvoiceId)s.billingStatus=inv.status;if(inv.id===s.supplierInvoiceId)s.supplierBillingStatus=inv.status},
 confirmService(id){return TourismWorkflows.confirmService(composeLegacyTourismDeps(this),id)},
 cancelService(id,reason){return DB.atomic('cancelService',()=>{const s=byId(DB.data.services,id);if(!s||!['draft','confirmed','completed'].includes(s.status))throw new Error('الخدمة غير متاحة للإلغاء');for(const invId of [s.customerInvoiceId,s.supplierInvoiceId].filter(Boolean)){const inv=byId(DB.data.invoices,invId);if(inv&&Invoices.allocations(inv.id)>EPS)throw new Error('اعكس السداد/التحصيل المرتبط بالخدمة أولًا')}if(s.commissionId){const c=byId(DB.data.commissions,s.commissionId);if(c&&['approved','partial','paid'].includes(c.status))throw new Error('اعكس/ألغِ اعتماد عمولة الخدمة أولًا');if(c?.approvalId){const ap=byId(DB.data.approvals,c.approvalId);if(ap?.status==='pending'){ap.status='rejected';ap.reason='ألغيت الخدمة'}}if(c&&c.status==='pending')c.status='rejected'}for(const invId of [s.customerInvoiceId,s.supplierInvoiceId].filter(Boolean)){const inv=byId(DB.data.invoices,invId);if(inv&&live(inv))Invoices.cancel(inv.id,reason)}if(typeof TourismServiceInventory!=='undefined')TourismServiceInventory.release(s.id,reason||'إلغاء الخدمة');s.status='cancelled';s.billingStatus='void';s.cancelReason=reason;DB.log('cancel','service',id,reason)})},deleteService(id){const s=byId(DB.data.services,id);if(!s||s.status!=='draft')throw new Error('الحذف مسموح للمسودة فقط');if(typeof TourismServiceInventory!=='undefined')TourismServiceInventory.release(s.id,'حذف مسودة الخدمة');if(s.commissionId)DB.data.commissions=DB.data.commissions.filter(x=>x.id!==s.commissionId);DB.data.services=DB.data.services.filter(x=>x.id!==id)},completeService(id){return TourismWorkflows.completeService(composeLegacyTourismDeps(this),id)},reopenService(id,reason){return TourismWorkflows.reopenService(composeLegacyTourismDeps(this),id,reason)},
 paymentMeta(o){return VoucherRules.paymentMeta(o)},
 pendingDraftInvoice(kind,partyType,partyId,currency,requestedId=''){
  const partyMatch=inv=>inv&&live(inv)&&inv.status==='draft'&&inv.kind===kind&&inv.partyId===partyId&&(kind!=='customer'||(inv.partyType||'customer')===partyType);
  if(requestedId){
   const inv=byId(DB.data.invoices,requestedId)||DB.data.invoices.find(x=>x.no===requestedId);
   if(!inv)throw new Error('الفاتورة المحددة غير موجودة');
   if(inv.status!=='draft')return null;
   if(!partyMatch(inv))throw new Error('الفاتورة المسودة لا تخص الطرف المحدد');
   return inv;
  }
  const sameCurrency=DB.data.invoices.filter(inv=>partyMatch(inv)&&inv.currency===currency);if(sameCurrency.length===1)return sameCurrency[0];if(sameCurrency.length>1)return null;
  const all=DB.data.invoices.filter(partyMatch);return all.length===1?all[0]:null
 },
 voucherUnallocatedUnits(v){const rate=Currency.rate(v.currency,v.date);if(!(rate>0))return 0;const usedBase=(v.allocations||[]).reduce((z,a)=>z+N(a.paymentBase),0);return Money.round(Math.max(0,N(v.amount)-usedBase/rate),v.currency)},
 applyPendingInvoiceAdvances(inv,opts:any={}){
  if(!inv||inv.status==='draft'||!live(inv))return[];
  const sourceType=S(opts.sourceType||''),sourceId=S(opts.sourceId||''),isSupplier=inv.kind==='supplier',ptype=isSupplier?'supplier':(inv.partyType||'customer'),vouchers=(isSupplier?DB.data.payments:DB.data.receipts).filter(v=>live(v)&&v.partyId===inv.partyId&&(v.pendingInvoiceId===inv.id||(sourceType&&sourceId&&v.sourceType===sourceType&&v.sourceId===sourceId))&&(isSupplier?v.partyType==='supplier':v.partyType===ptype)).sort((a,b)=>S(a.date).localeCompare(S(b.date))||S(a.createdAt||'').localeCompare(S(b.createdAt||''))),created=[];
  for(const v of vouchers){
   const remUnits=this.voucherUnallocatedUnits(v),invoiceRem=Invoices.remaining(inv);if(remUnits<=EPS||invoiceRem<=EPS){v.pendingInvoiceId='';continue}
   const settleDate=[S(v.date),S(inv.date)].filter(Boolean).sort().slice(-1)[0]||today(),payRate=Currency.rate(v.currency,v.date),settleRate=Currency.rate(inv.currency,settleDate),carryRate=N(inv.baseRate)||Currency.rate(inv.currency,inv.date);
   if(!(payRate>0&&settleRate>0&&carryRate>0))throw new Error('تعذر تطبيق الدفعة المقدمة لعدم اكتمال أسعار الصرف');
   const availableBase=Money.round(remUnits*payRate,DB.data.settings.baseCurrency),invoiceAmount=Money.round(Math.min(invoiceRem,availableBase/settleRate),inv.currency),paymentBase=Money.round(invoiceAmount*settleRate,DB.data.settings.baseCurrency),paymentUnits=Money.round(paymentBase/payRate,v.currency),carryingBase=Money.round(invoiceAmount*carryRate,DB.data.settings.baseCurrency),realizedFx=Money.round(paymentBase-carryingBase,DB.data.settings.baseCurrency);
   if(invoiceAmount<=EPS||paymentUnits<=EPS){v.pendingInvoiceId='';continue}
   const a={invoiceId:inv.id,invoiceNo:inv.no,invoiceAmount,invoiceCurrency:inv.currency,paymentCurrency:v.currency,paymentAmount:paymentUnits,paymentBase,carryingBase,realizedFx,settlementRate:settleRate,source:'advance'},lines=[];
   if(isSupplier){lines.push({accountId:'2100',debit:invoiceAmount,currency:inv.currency,rate:carryRate,partyType:'supplier',partyId:inv.partyId},{accountId:'1400',credit:paymentUnits,currency:v.currency,rate:payRate,partyType:'supplier',partyId:inv.partyId});if(realizedFx>0)lines.push({accountId:'5500',debit:realizedFx,currency:DB.data.settings.baseCurrency,baseDebit:realizedFx,baseOnly:true});else if(realizedFx<0)lines.push({accountId:'4500',credit:-realizedFx,currency:DB.data.settings.baseCurrency,baseCredit:-realizedFx,baseOnly:true})}
   else{const ar=ptype==='agent'?'1210':'1200',adv=ptype==='agent'?'2410':'2400';lines.push({accountId:adv,debit:paymentUnits,currency:v.currency,rate:payRate,partyType:ptype,partyId:inv.partyId},{accountId:ar,credit:invoiceAmount,currency:inv.currency,rate:carryRate,partyType:ptype,partyId:inv.partyId});if(realizedFx>0)lines.push({accountId:'4500',credit:realizedFx,currency:DB.data.settings.baseCurrency,baseCredit:realizedFx,baseOnly:true});else if(realizedFx<0)lines.push({accountId:'5500',debit:-realizedFx,currency:DB.data.settings.baseCurrency,baseDebit:-realizedFx,baseOnly:true})}
   Accounting.post({date:settleDate,memo:`تسوية دفعة مقدمة على الفاتورة ${inv.no} — ${v.no}`,refType:isSupplier?'payment-advance-apply':'receipt-advance-apply',refId:v.id,costCenterId:inv.costCenterId,lines});v.allocations=[...(v.allocations||[]),a];if(this.voucherUnallocatedUnits(v)<=Money.epsilon(v.currency)||Invoices.remaining(inv)<=Money.epsilon(inv.currency))v.pendingInvoiceId='';created.push(a);Invoices.refresh(inv)
  }
  return created
 },

 addReceipt(o){return VoucherWorkflows.addReceipt(composeLegacyVoucherDeps(),o)},
 addPayment(o,{ignoreApproval=false}={}){return VoucherWorkflows.addPayment(composeLegacyVoucherDeps(),o,{ignoreApproval})},
 depositCheque(id,treasuryId,date=today()){return DB.atomic('depositCheque',()=>{const ch=byId(DB.data.cheques,id);if(!ch||ch.direction!=='in'||ch.status!=='received')throw new Error('الشيك الوارد غير متاح للإيداع');const t=byId(DB.data.treasuries,treasuryId);if(!t||t.active===false||t.type!=='bank')throw new Error('اختر حسابًا بنكيًا نشطًا');ch.status='deposited';ch.treasuryId=t.id;ch.depositedAt=date;DB.log('deposit','cheque',ch.id,`${ch.no} — ${t.name}`);return ch})},
  clearCheque(id,treasuryId,date=today()){return DB.atomic('clearCheque',()=>{const ch=byId(DB.data.cheques,id);if(!ch||!['received','deposited','issued'].includes(ch.status))throw new Error('الشيك غير متاح للتحصيل');const t=byId(DB.data.treasuries,treasuryId||ch.treasuryId);if(!t||t.active===false)throw new Error('اختر خزنة/بنك نشط');const currentBase=Currency.toBase(ch.amount,ch.currency,date),carrying=N(ch.carryingBase)||Currency.toBase(ch.amount,ch.currency,ch.date),tAmt=currentBase/Currency.rate(t.currency,date),holdingRate=ch.amount?carrying/ch.amount:Currency.rate(ch.currency,ch.date),lines=[];if(ch.direction==='in'){lines.push({accountId:Accounting.ensureTreasuryAccount(t),debit:tAmt,currency:t.currency,treasuryId:t.id},{accountId:'1150',credit:ch.amount,currency:ch.currency,rate:holdingRate});const diff=currentBase-carrying;if(diff>0.01)lines.push({accountId:'4500',credit:diff,currency:DB.data.settings.baseCurrency,baseCredit:diff,baseOnly:true});else if(diff<-0.01)lines.push({accountId:'5500',debit:-diff,currency:DB.data.settings.baseCurrency,baseDebit:-diff,baseOnly:true})}else{Accounting.validateTreasury(t.id,tAmt);lines.push({accountId:'2150',debit:ch.amount,currency:ch.currency,rate:holdingRate},{accountId:Accounting.ensureTreasuryAccount(t),credit:tAmt,currency:t.currency,treasuryId:t.id});const diff=currentBase-carrying;if(diff>0.01)lines.push({accountId:'5500',debit:diff,currency:DB.data.settings.baseCurrency,baseDebit:diff,baseOnly:true});else if(diff<-0.01)lines.push({accountId:'4500',credit:-diff,currency:DB.data.settings.baseCurrency,baseCredit:-diff,baseOnly:true})}Accounting.post({date,memo:`تحصيل/صرف شيك ${ch.no}`,refType:'cheque-clear',refId:ch.id,lines});ch.status='cleared';ch.clearedAt=date;ch.treasuryId=t.id})},
 bounceCheque(id,reason,date=today()){return DB.atomic('bounceCheque',()=>{const ch=byId(DB.data.cheques,id);if(!ch||!['received','issued','deposited'].includes(ch.status))throw new Error('الشيك غير متاح للارتداد');if(!S(reason).trim())throw new Error('سبب ارتداد الشيك مطلوب');const voucher=ch.direction==='in'?byId(DB.data.receipts,ch.voucherId):byId(DB.data.payments,ch.voucherId);if(!voucher)throw new Error('السند المرتبط مفقود');Accounting.reverse(ch.direction==='in'?'receipt-advance-apply':'payment-advance-apply',voucher.id,reason,{date});Accounting.reverse(ch.direction==='in'?'receipt':'payment',voucher.id,reason,{date});voucher.status='void';voucher.voidReason=reason;Accounting.documentStatus(ch.direction==='in'?'receipt':'payment',voucher.id,'void');ch.status='bounced';ch.bounceReason=reason;for(const a of voucher.allocations||[]){const inv=byId(DB.data.invoices,a.invoiceId);if(inv)Invoices.refresh(inv)}})},
 voidReceipt(id,reason){return DB.atomic('voidReceipt',()=>{const r=byId(DB.data.receipts,id);if(!r||!live(r))throw new Error('السند غير متاح');if(!S(reason).trim())throw new Error('سبب عكس سند القبض مطلوب');const ch=DB.data.cheques.find(c=>c.voucherId===id&&c.direction==='in');if(ch?.status==='cleared')throw new Error('الشيك تم تحصيله؛ اعكس حركة التحصيل أولًا');r.status='void';r.voidReason=reason;Accounting.documentStatus('receipt',r.id,'void');Accounting.reverse('receipt-advance-apply',r.id,reason);Accounting.reverse('receipt',r.id,reason);if(ch)ch.status='void';for(const a of r.allocations||[]){const inv=byId(DB.data.invoices,a.invoiceId);if(inv)Invoices.refresh(inv)}})},
 voidPayment(id,reason){return DB.atomic('voidPayment',()=>{const p=byId(DB.data.payments,id);if(!p||!live(p))throw new Error('السند غير متاح');if(!S(reason).trim())throw new Error('سبب عكس سند الصرف مطلوب');const ch=DB.data.cheques.find(c=>c.voucherId===id&&c.direction==='out');if(ch?.status==='cleared')throw new Error('الشيك تم صرفه؛ اعكس حركة التحصيل أولًا');p.status='void';p.voidReason=reason;Accounting.documentStatus('payment',p.id,'void');Accounting.reverse('payment-advance-apply',p.id,reason);Accounting.reverse('payment',p.id,reason);if(ch)ch.status='void';for(const a of p.allocations||[]){const inv=byId(DB.data.invoices,a.invoiceId);if(inv)Invoices.refresh(inv)}if(p.commissionId){const c=byId(DB.data.commissions,p.commissionId);if(c){c.paidAmount=Math.max(0,N(c.paidAmount)-N(p.agentSettlement?.amount));c.paymentIds=(c.paymentIds||[]).filter(x=>x!==p.id);c.status=c.paidAmount<=EPS?'approved':(c.amount-c.paidAmount<=0.0001?'paid':'partial')}}})},
 addExpense(o){return ExpenseWorkflows.addExpense(composeLegacyExpenseDeps(this),o)},
 postExpense(e,o:any={}){return ExpenseWorkflows.postExpense(composeLegacyExpenseDeps(this),e,o)},
 buildPrepaidSchedule(e){DB.data.prepaidSchedules=DB.data.prepaidSchedules.filter(x=>x.expenseId!==e.id);for(let i=0;i<e.months;i++){const part=AdvancedAccountingRules.prepaidPart(e,i);DB.data.prepaidSchedules.push({id:iid(),expenseId:e.id,date:part.date,amount:part.amount,currency:e.currency,status:'pending'})}},
 updateExpense(id,o){return ExpenseWorkflows.updateExpense(composeLegacyExpenseDeps(this),id,o)},deleteExpense(id){return ExpenseWorkflows.deleteExpense(composeLegacyExpenseDeps(this),id)},voidExpense(id,reason){return ExpenseWorkflows.voidExpense(composeLegacyExpenseDeps(this),id,reason)},recognizePrepaid(id){return ExpenseWorkflows.recognizePrepaid(composeLegacyExpenseDeps(this),id)},reversePrepaid(id,reason){return ExpenseWorkflows.reversePrepaid(composeLegacyExpenseDeps(this),id,reason)},
 addCommissionRule(o){const a=byId(DB.data.agents,o.agentId);if(!a)throw new Error('المندوب غير موجود');const r={id:iid(),agentId:a.id,scopeType:o.scopeType||'all',scopeValue:o.scopeValue||'',mode:o.mode||'fixed',value:N(o.value),currency:o.currency||a.commissionCurrency||DB.data.settings.baseCurrency,minAmount:N(o.minAmount),active:true};if(r.value<=0)throw new Error('قيمة القاعدة غير صحيحة');DB.data.commissionRules.push(r);return r},commissionRule(agentId,sourceId){const ss=DB.data.services.find(x=>x.id===sourceId||x.no===sourceId),bb=DB.data.bookings.find(x=>x.id===sourceId||x.no===sourceId),basis=ss?N(ss.sale):bb?N(bb.total):0;return DB.data.commissionRules.filter(r=>r.active!==false&&r.agentId===agentId&&basis>=N(r.minAmount)&&((r.scopeType==='all')||(r.scopeType==='service'&&ss&&(!r.scopeValue||r.scopeValue===ss.type))||(r.scopeType==='program'&&bb&&(!r.scopeValue||[bb.programId,byId(DB.data.programs,bb.programId)?.no].includes(r.scopeValue))))).sort((a,b)=>N(b.minAmount)-N(a.minAmount))[0]},
 addCommission(o){const a=byId(DB.data.agents,o.agentId);if(!a)throw new Error('المندوب غير موجود');let amount=N(o.amount),rule=o.sourceId?this.commissionRule(a.id,o.sourceId):null;if(!amount&&rule){const src=DB.data.services.find(x=>x.id===o.sourceId||x.no===o.sourceId)||DB.data.bookings.find(x=>x.id===o.sourceId||x.no===o.sourceId),basis=N(src?.sale||src?.total);amount=rule.mode==='percent'?basis*N(rule.value)/100:N(rule.value)}if(!amount&&o.sourceId&&a.commissionMode==='percent'){const src=DB.data.services.find(x=>x.no===o.sourceId||x.id===o.sourceId)||DB.data.bookings.find(x=>x.no===o.sourceId||x.id===o.sourceId);if(src)amount=N(src.sale||src.total)*N(a.commissionValue)/100}if(!amount&&a.commissionMode==='fixed')amount=N(a.commissionValue);if(amount<=0)throw new Error('قيمة العمولة غير صحيحة');if(o.sourceId&&DB.data.commissions.some(c=>live(c)&&c.agentId===a.id&&c.sourceId===o.sourceId))throw new Error('تم إنشاء عمولة لهذا المرجع بالفعل');const c={id:iid(),no:Numbering.next('commission',o.date||today()),date:o.date||today(),agentId:a.id,amount,currency:rule?.currency||o.currency||a.commissionCurrency||DB.data.settings.baseCurrency,status:'pending',note:o.note||'',sourceId:o.sourceId||'',rejectionReason:'',paidAmount:0,paymentIds:[],baseRate:0};DB.data.commissions.unshift(c);return c},
 approveCommission(id){const c=byId(DB.data.commissions,id);if(!c||c.status!=='pending')throw new Error('العمولة غير متاحة');const date=today();c.baseRate=Currency.rate(c.currency,date);if(!(c.baseRate>0))throw new Error('سعر صرف العمولة غير صالح');c.status='approved';c.approvedAt=date;c.paidAmount=0;c.paymentIds=[];Accounting.post({date,memo:`اعتماد عمولة ${c.no}`,refType:'commission',refId:c.id,lines:[{accountId:'5300',debit:c.amount,currency:c.currency,rate:c.baseRate},{accountId:'2200',credit:c.amount,currency:c.currency,rate:c.baseRate,partyType:'agent',partyId:c.agentId}]})},
 rejectCommission(id,reason){const c=byId(DB.data.commissions,id);if(!c||c.status!=='pending')throw new Error('العمولة غير متاحة');c.status='rejected';c.rejectionReason=reason},
 payCommission(id,o){return DB.atomic('payCommission',()=>{const c=byId(DB.data.commissions,id);if(!c||!['approved','partial'].includes(c.status))throw new Error('اعتمد العمولة أولًا');const date=o.date||today(),remaining=Math.max(0,N(c.amount)-N(c.paidAmount));if(remaining<=EPS)throw new Error('العمولة مسددة بالكامل');const payCur=o.currency||c.currency,payAmt=N(o.amount);if(payAmt<=0)throw new Error('مبلغ السداد غير صحيح');const payBase=Currency.toBase(payAmt,payCur,date),currentRate=Currency.rate(c.currency,date);if(!(currentRate>0))throw new Error('سعر صرف عملة العمولة غير صالح');const settleUnits=payBase/currentRate;if(settleUnits>remaining+0.0001)throw new Error(`السداد يتجاوز المتبقي ${money(remaining,c.currency)}`);const p=this.addPayment({date,partyType:'agent',partyId:c.agentId,treasuryId:o.treasuryId,amount:payAmt,currency:payCur,note:o.note||`سداد عمولة ${c.no}`,paymentMethod:o.paymentMethod||'cash',referenceNo:o.referenceNo||'',bankName:o.bankName||'',valueDate:o.valueDate||'',commissionId:c.id,agentSettlement:{amount:settleUnits,currency:c.currency,rate:N(c.baseRate)||Currency.rate(c.currency,c.approvedAt||c.date)}});return p})},
 reverseCommissionPayment(id,reason,paymentId=''){return DB.atomic('reverseCommissionPayment',()=>{const c=byId(DB.data.commissions,id);if(!c||!['paid','partial'].includes(c.status))throw new Error('لا يوجد سداد عمولة');const ids=(c.paymentIds||[]).filter(pid=>{const p=byId(DB.data.payments,pid);return p&&live(p)}),pid=paymentId||ids.at(-1);if(!pid)throw new Error('لا يوجد سند سداد نشط');this.voidPayment(pid,reason);return c})},
 createTreasury(o){const date=o.date||today(),t={id:iid(),no:Numbering.next('treasury',date),name:o.name,type:o.type||'cash',currency:o.currency||DB.data.settings.baseCurrency,active:true,custodian:o.custodian||'',bankName:o.bankName||'',accountNo:o.accountNo||'',iban:o.iban||'',branch:o.branch||'',minBalance:N(o.minBalance),createdAt:now()};DB.data.treasuries.push(t);Accounting.ensureTreasuryAccount(t);if(N(o.opening)>0)Accounting.postOpeningTreasury(t,N(o.opening),date);if(!o.silent)DB.log('create','treasury',t.id,t.no);return t},updateTreasury(id,o){const t=byId(DB.data.treasuries,id);if(!t)throw new Error('الخزنة غير موجودة');const has=Accounting.treasuryHasHistory(id);if(has&&o.currency&&o.currency!==t.currency)throw new Error('لا يمكن تغيير عملة خزنة عليها تاريخ');if(has&&o.type&&o.type!==t.type)throw new Error('لا يمكن تغيير نوع خزنة/بنك عليها تاريخ مالي');Object.assign(t,{name:o.name||t.name,type:o.type||t.type,currency:o.currency||t.currency,custodian:o.custodian||'',bankName:o.bankName||'',accountNo:o.accountNo||'',iban:o.iban||'',branch:o.branch||'',minBalance:N(o.minBalance)});Accounting.ensureTreasuryAccount(t);DB.log('update','treasury',id,t.name)},toggleTreasury(id){const t=byId(DB.data.treasuries,id);if(!t)throw new Error('الخزنة غير موجودة');if(t.active!==false&&Math.abs(Accounting.treasuryBalance(id))>EPS)throw new Error('صفّر الرصيد أو انقله قبل إيقاف الخزنة');t.active=t.active===false;Accounting.ensureTreasuryAccount(t)},removeTreasury(id){const t=byId(DB.data.treasuries,id);if(!t)throw new Error('الخزنة غير موجودة');if(Accounting.treasuryHasHistory(id))throw new Error('الخزنة لها تاريخ مالي؛ يمكن إيقافها فقط');DB.data.accounts=DB.data.accounts.filter(a=>a.treasuryId!==id);DB.data.treasuries=DB.data.treasuries.filter(x=>x.id!==id)},
 transfer(o){return TransferWorkflows.transfer(composeLegacyTransferDeps(),o)},reverseTransfer(id,reason){return TransferWorkflows.reverseTransfer(composeLegacyTransferDeps(),id,reason)},
 cashCount(o){const t=byId(DB.data.treasuries,o.treasuryId);if(!t||t.type!=='cash')throw new Error('اختر خزنة نقدية');const date=o.date||today();Periods.assertOpen(date);const system=Accounting.treasuryBalance(t.id),actual=N(o.actual),diff=actual-system,postDifference=o.postDifference==='yes',differenceAccountId=diff>0?'4600':diff<0?'5600':'',x={id:iid(),no:Numbering.next('cashCount',date),date,treasuryId:t.id,system,actual,diff,currency:t.currency,note:o.note||'',differencePosted:false,differenceAccountId,status:'checked'};DB.data.cashCounts.unshift(x);if(Math.abs(diff)>0.01&&postDifference){const lines=diff>0?[{accountId:Accounting.ensureTreasuryAccount(t),debit:diff,currency:t.currency,treasuryId:t.id},{accountId:'4600',credit:diff,currency:t.currency}]:[{accountId:'5600',debit:-diff,currency:t.currency},{accountId:Accounting.ensureTreasuryAccount(t),credit:-diff,currency:t.currency,treasuryId:t.id}];Accounting.post({date:x.date,memo:`فرق جرد خزنة ${x.no}`,refType:'cash-count',refId:x.id,lines});x.differencePosted=true;x.status='posted'}DB.log('cash-count','treasury',t.id,`${x.no} • فرق ${money(diff,t.currency)}`);return x},
 reconcileBank(o){const t=byId(DB.data.treasuries,o.treasuryId);if(!t||t.type!=='bank')throw new Error('اختر حسابًا بنكيًا');const date=o.date||today(),system=Accounting.treasuryBalance(t.id,date),statement=N(o.statementBalance),diff=statement-system,x={id:iid(),no:Numbering.next('reconciliation',date),date,treasuryId:t.id,system,statement,diff,currency:t.currency,note:o.note||'',status:Math.abs(diff)<=0.01?'matched':'difference'};DB.data.bankReconciliations.unshift(x);DB.log('bank-compare','treasury',t.id,`${x.no} • فرق ${money(diff,t.currency)}`);return x}
};
__set_Transactions(Transactions);

const Approvals={create(type,payload,baseAmount=0){return ApprovalWorkflows.create(composeLegacyApprovalDeps(),type,payload,baseAmount)},approve(id){return ApprovalWorkflows.approve(composeLegacyApprovalDeps(),id)},reject(id,reason){return ApprovalWorkflows.reject(composeLegacyApprovalDeps(),id,reason)}};
export { Approvals, Transactions };
