/* v32.4.68 — Safe delete framework. Hard delete is limited to drafts/master records with no history. */
const DeleteCenter={
 label(kind){return({customer:'عميل',supplier:'مورد',agent:'مندوب',season:'موسم',umrahProgram:'برنامج حج/عمرة',umrahBooking:'حجز حج/عمرة',visaBatch:'دفعة تأشيرات',busRun:'رحلة نقل',task:'مهمة تشغيل',incident:'واقعة',attachment:'مرفق',umrahTraveler:'ملف مسافر'}[kind]||'السجل')},
 button(kind,id,label='حذف'){return `<button type="button" class="btn small danger delete-center-btn" data-delete-kind="${esc(kind)}" data-delete-id="${esc(id)}">${icon('trash','sm')} ${esc(label)}</button>`},
 request(kind,id){const label=this.label(kind),message=kind==='umrahProgram'?'إذا كان البرنامج ملغيًا بلا تاريخ مالي سيُحذف نهائيًا. إذا كان ملغيًا وله قيود/فواتير تاريخية فسيختفي من القوائم فقط مع الاحتفاظ بسجله كمرجع محاسبي، ولن تُمس أي قيود.':kind==='umrahTraveler'?'يُسمح بمسح ملف المسافر فقط بعد إلغاء الحجز، وبشرط عدم وجود تأشيرة أو تذكرة أو تصريح/مخيم أو تكلفة تشغيلية تم إثباتها للمسافر. سيُنظف النظام بيانات الملف التابعة غير التاريخية فقط.':'سيتم حذف '+label+' نهائيًا فقط إذا كان غير مرتبط بحركة مالية أو تشغيلية تمنع الحذف. إذا كان مرتبطًا سيشرح النظام سبب المنع ولن يغيّر البيانات.';return UI.confirmAction(`${kind==='umrahTraveler'?'مسح':'حذف'} ${label}`,message,()=>this.execute(kind,id),{label:kind==='umrahProgram'?'مسح البرنامج':kind==='umrahTraveler'?'مسح الملف':'حذف نهائي',danger:true})},
 async execute(kind,id){const out=await DB.atomicAsync('safeDelete:'+kind,()=>this.remove(kind,id),{save:true,render:true,strict:true,waitForSave:true,rollback:true});toast(out?.retainedForAudit?`تم مسح ${this.label(kind)} من القوائم مع الاحتفاظ بالأثر المحاسبي`:`تم حذف ${this.label(kind)} نهائيًا من النظام والخادم`);return out},
 hasExactRef(value,id,seen=new WeakSet()){if(value===id)return true;if(value==null||typeof value!=='object')return false;if(seen.has(value))return false;seen.add(value);if(Array.isArray(value))return value.some(v=>this.hasExactRef(v,id,seen));return Object.values(value).some(v=>this.hasExactRef(v,id,seen))},
 programFinancialRefs(id){const d=DB.data||{},collections=['invoices','invoiceAdjustments','receipts','payments','expenses','journals','manualJournalDrafts','transfers','purchaseOrders','commissions','cheques','approvals'],labels={invoices:'فواتير',invoiceAdjustments:'إشعارات فواتير',receipts:'سندات قبض',payments:'سندات صرف',expenses:'مصروفات',journals:'قيود محاسبية',manualJournalDrafts:'مسودات قيود',transfers:'تحويلات',purchaseOrders:'أوامر شراء',commissions:'عمولات',cheques:'شيكات',approvals:'اعتمادات'},out=[];for(const k of collections)if((d[k]||[]).some(x=>x?.deleted!==true&&this.hasExactRef(x,id)))out.push(labels[k]||k);return out},
 programOperationalRefs(id){const d=UmrahCore_DB?.data||{},out=[];if((d.bookings||[]).some(b=>b.programId===id&&!['cancelled','expired'].includes(b.status)))out.push('حجوزات قائمة');if((d.supplierCommitments||[]).some(x=>x.programId===id&&x.active!==false&&x.status!=='cancelled'))out.push('التزامات موردين');if((d.tickets||[]).some(x=>x.programId===id&&x.active!==false&&['issued','reissued'].includes(x.status)))out.push('تذاكر مصدرة');const batchIds=new Set((d.visaBatches||[]).filter(x=>x.programId===id).map(x=>x.id));if((d.visaItems||[]).some(x=>x.active!==false&&(x.programId===id||batchIds.has(x.batchId))&&['submitted','processing','issued'].includes(x.status)))out.push('تأشيرات مقدمة/مصدرة');if((d.busRuns||[]).some(x=>x.programId===id&&(x.travelerIds||[]).length))out.push('رحلات نقل عليها مسافرون');return out},
 travelerDeleteBlockers(id){const d=UmrahCore_DB?.data||{},t=(d.travelers||[]).find(x=>x.id===id),out=[];if(!t)return['ملف المسافر غير موجود'];const b=(d.bookings||[]).find(x=>x.id===t.bookingId);if(!b)return['الحجز المرتبط غير موجود'];if(b.status!=='cancelled')out.push('الحجز ليس ملغيًا');const visas=(d.visaItems||[]).filter(x=>x.travelerId===id);if(visas.some(x=>['submitted','processing','more_info','issued','rejected'].includes(x.status)))out.push('له سجل تأشيرة تم تقديمه أو معالجته');const tickets=(d.tickets||[]).filter(x=>x.travelerId===id);if(tickets.some(x=>['issued','reissued'].includes(x.status)))out.push('له تذكرة مصدرة');if(['submitted','processing','issued','rejected'].includes(t.hajjPermitStatus))out.push('له سجل تصريح/نسك تشغيلي');if(S(t.campAssignment).trim())out.push('له توزيع مخيم/مشاعر');if((d.incidents||[]).some(x=>x.travelerId===id))out.push('مرتبط بواقعة تشغيلية');const recognized=Object.values(b.costActualization||{}).some(m=>m&&typeof m==='object'&&m[id]);if(recognized||(d.supplierCommitments||[]).some(c=>(c.itemTrace||[]).some(z=>z.travelerId===id)||(c.travelerIds||[]).includes(id)))out.push('مرتبط بتكلفة مورد/إثبات تشغيلي');return[...new Set(out)]},
 canRemoveTraveler(id){return this.travelerDeleteBlockers(id).length===0},
  remove(kind,id){
  if(kind==='customer'||kind==='supplier'||kind==='agent'){const cfg={customer:['customers','removeCustomer','عميل'],supplier:['suppliers','removeSupplier','مورد'],agent:['agents','removeAgent','مندوب']}[kind],x=byId(DB.data[cfg[0]],id);if(!x)throw new Error(cfg[2]+' غير موجود');if(x.active!==false)throw new Error(`يجب تعليق ${cfg[2]} أولًا قبل الحذف النهائي`);return MasterData[cfg[1]](id)}
  if(kind==='attachment'){const a=byId(DB.data.attachments,id);if(!a)throw new Error('المرفق غير موجود');return Attachments.remove(id)}
  const d=UmrahCore_DB?.data;if(!d)throw new Error('بيانات الحج والعمرة غير متاحة');
  if(kind==='season'){const x=d.seasons.find(x=>x.id===id);if(!x)throw new Error('الموسم غير موجود');if(d.programs.some(p=>p.seasonId===id&&p.status!=='cancelled'))throw new Error('لا يمكن حذف الموسم: توجد برامج مرتبطة به. احذف/انقل البرامج أولًا.');d.seasons=d.seasons.filter(x=>x.id!==id);return}
  if(kind==='umrahProgram'){const p=d.programs.find(x=>x.id===id);if(!p)throw new Error('البرنامج غير موجود');if(p.status==='closed')throw new Error('البرنامج المغلق جزء من السجل التشغيلي والمحاسبي ولا يُحذف؛ يمكن الرجوع إليه للتقارير والمراجعة.');if(!['planning','contracting','pricing','cancelled'].includes(p.status))throw new Error('لا يمكن مسح البرنامج أثناء البيع أو التشغيل. استخدم «إلغاء البرنامج» أولًا.');const op=this.programOperationalRefs(id);if(op.length)throw new Error(`لا يمكن مسح البرنامج: ${op.join('، ')}.`);const fin=this.programFinancialRefs(id);if(p.status==='cancelled'&&fin.length){p.deleted=true;p.active=false;p.deletedAt=now();p.deleteMode='audit-retained';p.deleteReason='مسح برنامج ملغي مع الاحتفاظ بالأثر المحاسبي';UmrahCore_Bridge.audit('archive-delete','umrahProgram',id,`${p.no} — احتفاظ محاسبي: ${fin.join('، ')}`);return{retainedForAudit:true,financialRefs:fin}}if(fin.length)throw new Error(`لا يمكن حذف مسودة البرنامج: توجد معاملات مالية مرتبطة (${fin.join('، ')}). ألغِ البرنامج أولًا.`);const bookingIds=new Set((d.bookings||[]).filter(x=>x.programId===id).map(x=>x.id)),travelerIds=new Set((d.travelers||[]).filter(x=>x.programId===id||bookingIds.has(x.bookingId)).map(x=>x.id)),batchIds=new Set((d.visaBatches||[]).filter(x=>x.programId===id).map(x=>x.id));for(const r of d.busRuns||[])r.travelerIds=(r.travelerIds||[]).filter(tid=>!travelerIds.has(tid));if(Array.isArray(d.travelers))d.travelers=d.travelers.filter(x=>!travelerIds.has(x.id));if(Array.isArray(d.bookings))d.bookings=d.bookings.filter(x=>!bookingIds.has(x.id));if(Array.isArray(d.hotelRooms))d.hotelRooms=d.hotelRooms.filter(x=>x.programId!==id&&!bookingIds.has(x.bookingId));if(Array.isArray(d.visaItems))d.visaItems=d.visaItems.filter(x=>x.programId!==id&&!batchIds.has(x.batchId)&&!travelerIds.has(x.travelerId));if(Array.isArray(d.tickets))d.tickets=d.tickets.filter(x=>x.programId!==id&&!travelerIds.has(x.travelerId));for(const k of['programSegments','programCosts','operationTasks','busRuns','visaBatches','incidents','supplierCommitments','contractReservations'])if(Array.isArray(d[k]))d[k]=d[k].filter(x=>x.programId!==id);d.programs=d.programs.filter(x=>x.id!==id);UmrahCore_Bridge.audit('hard-delete','umrahProgram',id,`${p.no} — حذف آمن بلا أثر مالي مع تنظيف ${bookingIds.size} حجز و${travelerIds.size} ملف مسافر`);return{retainedForAudit:false,removedBookings:bookingIds.size,removedTravelers:travelerIds.size}}
  if(kind==='umrahBooking'){const b=d.bookings.find(x=>x.id===id);if(!b)throw new Error('الحجز غير موجود');if(!['inquiry','quotation','hold','waitlist'].includes(b.status))throw new Error('لا يمكن حذف الحجز بعد التأكيد؛ استخدم إلغاء الحجز حتى يظل التاريخ المالي محفوظًا.');const fin:any=UmrahCore_Bridge.financeSnapshot(b);if(fin?.invoiceId||N(fin?.paid)>0)throw new Error('لا يمكن حذف الحجز: توجد فاتورة أو تحصيل مرتبط.');const travelerIds=new Set(d.travelers.filter(x=>x.bookingId===id).map(x=>x.id));for(const r of d.busRuns||[])r.travelerIds=(r.travelerIds||[]).filter(tid=>!travelerIds.has(tid));d.travelers=d.travelers.filter(x=>x.bookingId!==id);d.hotelRooms=d.hotelRooms.filter(x=>x.bookingId!==id);d.bookings=d.bookings.filter(x=>x.id!==id);return}
  if(kind==='umrahTraveler'){const t=d.travelers.find(x=>x.id===id);if(!t)throw new Error('ملف المسافر غير موجود');const blockers=this.travelerDeleteBlockers(id);if(blockers.length)throw new Error(`لا يمكن مسح ملف المسافر: ${blockers.join('، ')}.`);const b=d.bookings.find(x=>x.id===t.bookingId);for(const r of d.busRuns||[])r.travelerIds=(r.travelerIds||[]).filter(tid=>tid!==id);if(Array.isArray(d.visaItems))d.visaItems=d.visaItems.filter(x=>x.travelerId!==id);if(Array.isArray(d.tickets))d.tickets=d.tickets.filter(x=>x.travelerId!==id);for(const category of Object.keys(b?.costActualization||{})){const map=b.costActualization[category];if(map&&typeof map==='object')delete map[id]}const attachmentIds=new Set((DB.data.attachments||[]).filter(a=>a.entityType==='traveler'&&a.entityId===id).map(a=>a.id));return(async()=>{for(const aid of attachmentIds){try{await AttachmentStore.remove(aid)}catch(e){throw new Error('تعذر تنظيف مرفقات ملف المسافر؛ لم يتم المسح. '+S(e?.message||e))}}if(attachmentIds.size){DB.data.attachments=(DB.data.attachments||[]).filter(a=>!attachmentIds.has(a.id));try{Attachments.invalidateCounts?.()}catch(_){}}d.travelers=d.travelers.filter(x=>x.id!==id);UmrahCore_Bridge.audit('hard-delete','umrahTraveler',id,`${t.no} — مسح آمن بعد إلغاء الحجز ${b?.no||''} بلا أثر تشغيلي/مالي`);return{retainedForAudit:false,removedAttachments:attachmentIds.size}})()}
  if(kind==='visaBatch'){const b=d.visaBatches.find(x=>x.id===id);if(!b)throw new Error('دفعة التأشيرات غير موجودة');const items=d.visaItems.filter(x=>x.batchId===id&&x.active!==false);if(items.some(x=>['submitted','processing','issued'].includes(x.status)))throw new Error('لا يمكن حذف الدفعة: توجد ملفات تم تقديمها أو إصدارها.');d.visaItems=d.visaItems.filter(x=>x.batchId!==id);d.visaBatches=d.visaBatches.filter(x=>x.id!==id);return}
  if(kind==='busRun'){const r=d.busRuns.find(x=>x.id===id);if(!r)throw new Error('رحلة النقل غير موجودة');if((r.travelerIds||[]).length)throw new Error('لا يمكن حذف رحلة النقل: عليها مسافرون. أزل التوزيع أولًا.');d.busRuns=d.busRuns.filter(x=>x.id!==id);return}
  if(kind==='task'){const t=d.operationTasks.find(x=>x.id===id);if(!t)throw new Error('المهمة غير موجودة');if(!S(t.code).startsWith('custom-'))throw new Error('هذه مهمة تلقائية للنظام ولا تحذف؛ يتم إكمالها أو إعادة فتحها فقط.');d.operationTasks=d.operationTasks.filter(x=>x.id!==id);return}
  if(kind==='incident'){const x=d.incidents.find(x=>x.id===id);if(!x)throw new Error('الواقعة غير موجودة');if(x.status==='closed')throw new Error('الواقعة المغلقة جزء من سجل التشغيل ولا تحذف.');d.incidents=d.incidents.filter(x=>x.id!==id);return}
  throw new Error('هذا النوع لا يدعم الحذف النهائي؛ استخدم الإلغاء/العكس إذا كان مستندًا تاريخيًا.')
 },
 enhanceDocument(root=document){if(!root?.querySelectorAll)return;/* explicit UI owns most delete buttons; this hook is intentionally conservative. */}
};
