// Generated by scripts/codemods/modularize-src.cjs.
// Late-bound live bindings for references that point at a file which, in the original manual order, was
// initialised AFTER the referencing file. The owner assigns the value right after its declaration
// (function declarations: at the top of the module, like hoisting), so initialisation order stays identical.
export let Accounting: typeof import('../accounting/engine').Accounting;
export function __set_Accounting(value: typeof Accounting): void { Accounting = value; }
export let Actions: typeof import('../ui/actions').Actions;
export function __set_Actions(value: typeof Actions): void { Actions = value; }
export let AttachmentStore: typeof import('../documents/attachments-backup').AttachmentStore;
export function __set_AttachmentStore(value: typeof AttachmentStore): void { AttachmentStore = value; }
export let Attachments: typeof import('../documents/attachments-backup').Attachments;
export function __set_Attachments(value: typeof Attachments): void { Attachments = value; }
export let Auth: typeof import('../security/auth').Auth;
export function __set_Auth(value: typeof Auth): void { Auth = value; }
export let Backup: typeof import('../documents/attachments-backup').Backup;
export function __set_Backup(value: typeof Backup): void { Backup = value; }
export let BranchScope: typeof import('../commercial/product').BranchScope;
export function __set_BranchScope(value: typeof BranchScope): void { BranchScope = value; }
export let CRM: typeof import('../crm/crm').CRM;
export function __set_CRM(value: typeof CRM): void { CRM = value; }
export let CleanPages: typeof import('../ui/clean-pages').CleanPages;
export function __set_CleanPages(value: typeof CleanPages): void { CleanPages = value; }
export let Commercial: typeof import('../commercial/product').Commercial;
export function __set_Commercial(value: typeof Commercial): void { Commercial = value; }
export let CommercialActions: typeof import('../commercial/actions').CommercialActions;
export function __set_CommercialActions(value: typeof CommercialActions): void { CommercialActions = value; }
export let CommercialUX: typeof import('../ui/commercial-ux').CommercialUX;
export function __set_CommercialUX(value: typeof CommercialUX): void { CommercialUX = value; }
export let CoreSuites: typeof import('./suites').CoreSuites;
export function __set_CoreSuites(value: typeof CoreSuites): void { CoreSuites = value; }
export let Currency: typeof import('../accounting/currency-periods').Currency;
export function __set_Currency(value: typeof Currency): void { Currency = value; }
export let DB: typeof import('../persistence/browser-store').DB;
export function __set_DB(value: typeof DB): void { DB = value; }
export let ERPIntegration: typeof import('../integrated/bridge').ERPIntegration;
export function __set_ERPIntegration(value: typeof ERPIntegration): void { ERPIntegration = value; }
export let Forms: typeof import('../ui/forms').Forms;
export function __set_Forms(value: typeof Forms): void { Forms = value; }
export let Insights: typeof import('../finance/insights').Insights;
export function __set_Insights(value: typeof Insights): void { Insights = value; }
export let Invoices: typeof import('../accounting/invoices').Invoices;
export function __set_Invoices(value: typeof Invoices): void { Invoices = value; }
export let ManualJournalRules: typeof import('../accounting/manual-journal-rules').ManualJournalRules;
export function __set_ManualJournalRules(value: typeof ManualJournalRules): void { ManualJournalRules = value; }
export let OutputCenter: typeof import('../documents/output-center').OutputCenter;
export function __set_OutputCenter(value: typeof OutputCenter): void { OutputCenter = value; }
export let Pages: typeof import('../ui/pages').Pages;
export function __set_Pages(value: typeof Pages): void { Pages = value; }
export let Party360: typeof import('../crm/party360').Party360;
export function __set_Party360(value: typeof Party360): void { Party360 = value; }
export let Periods: typeof import('../accounting/currency-periods').Periods;
export function __set_Periods(value: typeof Periods): void { Periods = value; }
export let Print: typeof import('../reports/printing').Print;
export function __set_Print(value: typeof Print): void { Print = value; }
export let PurchaseOrderFulfillment: typeof import('../crm/purchase-order-fulfillment').PurchaseOrderFulfillment;
export function __set_PurchaseOrderFulfillment(value: typeof PurchaseOrderFulfillment): void { PurchaseOrderFulfillment = value; }
export let RolePermissions: typeof import('../security/auth').RolePermissions;
export function __set_RolePermissions(value: typeof RolePermissions): void { RolePermissions = value; }
export let SearchSelect: typeof import('../ui/navigation').SearchSelect;
export function __set_SearchSelect(value: typeof SearchSelect): void { SearchSelect = value; }
export let Security: typeof import('../security/auth').Security;
export function __set_Security(value: typeof Security): void { Security = value; }
export let Tax: typeof import('../accounting/invoices').Tax;
export function __set_Tax(value: typeof Tax): void { Tax = value; }
export let TourismServiceInventory: typeof import('../integrated/service-inventory').TourismServiceInventory;
export function __set_TourismServiceInventory(value: typeof TourismServiceInventory): void { TourismServiceInventory = value; }
export let Transactions: typeof import('../accounting/transactions').Transactions;
export function __set_Transactions(value: typeof Transactions): void { Transactions = value; }
export let UI: typeof import('../ui/ui').UI;
export function __set_UI(value: typeof UI): void { UI = value; }
export let UmrahCore_Actions: typeof import('./umrah/actions-print').UmrahCore_Actions;
export function __set_UmrahCore_Actions(value: typeof UmrahCore_Actions): void { UmrahCore_Actions = value; }
export let UmrahCore_Bridge: typeof import('./umrah/data').UmrahCore_Bridge;
export function __set_UmrahCore_Bridge(value: typeof UmrahCore_Bridge): void { UmrahCore_Bridge = value; }
export let UmrahCore_ContractCenter: typeof import('./umrah/contracts').UmrahCore_ContractCenter;
export function __set_UmrahCore_ContractCenter(value: typeof UmrahCore_ContractCenter): void { UmrahCore_ContractCenter = value; }
export let UmrahCore_DB: typeof import('./umrah/data').UmrahCore_DB;
export function __set_UmrahCore_DB(value: typeof UmrahCore_DB): void { UmrahCore_DB = value; }
export let UmrahCore_Forms: typeof import('./umrah/forms').UmrahCore_Forms;
export function __set_UmrahCore_Forms(value: typeof UmrahCore_Forms): void { UmrahCore_Forms = value; }
export let UmrahCore_Guided: typeof import('./umrah/guided').UmrahCore_Guided;
export function __set_UmrahCore_Guided(value: typeof UmrahCore_Guided): void { UmrahCore_Guided = value; }
export let UmrahCore_Inventory: typeof import('./umrah/contracts-inventory').UmrahCore_Inventory;
export function __set_UmrahCore_Inventory(value: typeof UmrahCore_Inventory): void { UmrahCore_Inventory = value; }
export let UmrahCore_Ops: typeof import('./umrah/operations').UmrahCore_Ops;
export function __set_UmrahCore_Ops(value: typeof UmrahCore_Ops): void { UmrahCore_Ops = value; }
export let UmrahCore_PrintView: typeof import('./umrah/actions-print').UmrahCore_PrintView;
export function __set_UmrahCore_PrintView(value: typeof UmrahCore_PrintView): void { UmrahCore_PrintView = value; }
export let UmrahCore_Procurement: typeof import('./umrah/procurement').UmrahCore_Procurement;
export function __set_UmrahCore_Procurement(value: typeof UmrahCore_Procurement): void { UmrahCore_Procurement = value; }
export let UmrahCore_ProgramWizard: typeof import('./umrah/program-wizard').UmrahCore_ProgramWizard;
export function __set_UmrahCore_ProgramWizard(value: typeof UmrahCore_ProgramWizard): void { UmrahCore_ProgramWizard = value; }
export let UmrahCore_QuickCreate: typeof import('./umrah/guided').UmrahCore_QuickCreate;
export function __set_UmrahCore_QuickCreate(value: typeof UmrahCore_QuickCreate): void { UmrahCore_QuickCreate = value; }
export let UmrahCore_State: typeof import('./umrah/ui').UmrahCore_State;
export function __set_UmrahCore_State(value: typeof UmrahCore_State): void { UmrahCore_State = value; }
export let UmrahCore_UI: typeof import('./umrah/ui').UmrahCore_UI;
export function __set_UmrahCore_UI(value: typeof UmrahCore_UI): void { UmrahCore_UI = value; }
export let UmrahCore_Wizard: typeof import('./umrah/guided').UmrahCore_Wizard;
export function __set_UmrahCore_Wizard(value: typeof UmrahCore_Wizard): void { UmrahCore_Wizard = value; }
export let UmrahCore_currencyOptions: typeof import('./umrah/ui').UmrahCore_currencyOptions;
export function __set_UmrahCore_currencyOptions(value: typeof UmrahCore_currencyOptions): void { UmrahCore_currencyOptions = value; }
export let UmrahCore_entityOptions: typeof import('./umrah/ui').UmrahCore_entityOptions;
export function __set_UmrahCore_entityOptions(value: typeof UmrahCore_entityOptions): void { UmrahCore_entityOptions = value; }
export let UmrahCore_fxLabel: typeof import('./umrah/ui').UmrahCore_fxLabel;
export function __set_UmrahCore_fxLabel(value: typeof UmrahCore_fxLabel): void { UmrahCore_fxLabel = value; }
export let UmrahCore_treasuryOptions: typeof import('./umrah/ui').UmrahCore_treasuryOptions;
export function __set_UmrahCore_treasuryOptions(value: typeof UmrahCore_treasuryOptions): void { UmrahCore_treasuryOptions = value; }
export let UmrahCore_vehicleCaps: typeof import('./umrah/runtime').UmrahCore_vehicleCaps;
export function __set_UmrahCore_vehicleCaps(value: typeof UmrahCore_vehicleCaps): void { UmrahCore_vehicleCaps = value; }
export let UmrahCore_visaStatusLabel: typeof import('./umrah/ui').UmrahCore_visaStatusLabel;
export function __set_UmrahCore_visaStatusLabel(value: typeof UmrahCore_visaStatusLabel): void { UmrahCore_visaStatusLabel = value; }
export let VendorOwner: typeof import('../commercial/vendor-owner').VendorOwner;
export function __set_VendorOwner(value: typeof VendorOwner): void { VendorOwner = value; }
export let WorkCenter: typeof import('../ui/work-center').WorkCenter;
export function __set_WorkCenter(value: typeof WorkCenter): void { WorkCenter = value; }
export let composeAuthEntryPresentation: typeof import('../bootstrap').composeAuthEntryPresentation;
export function __set_composeAuthEntryPresentation(value: typeof composeAuthEntryPresentation): void { composeAuthEntryPresentation = value; }
export let composeContactPresentation: typeof import('../bootstrap').composeContactPresentation;
export function __set_composeContactPresentation(value: typeof composeContactPresentation): void { composeContactPresentation = value; }
export let composeLegacyActionDeps: typeof import('../bootstrap').composeLegacyActionDeps;
export function __set_composeLegacyActionDeps(value: typeof composeLegacyActionDeps): void { composeLegacyActionDeps = value; }
export let composeLegacyApprovalDeps: typeof import('../bootstrap').composeLegacyApprovalDeps;
export function __set_composeLegacyApprovalDeps(value: typeof composeLegacyApprovalDeps): void { composeLegacyApprovalDeps = value; }
export let composeLegacyBranchAccess: typeof import('../bootstrap').composeLegacyBranchAccess;
export function __set_composeLegacyBranchAccess(value: typeof composeLegacyBranchAccess): void { composeLegacyBranchAccess = value; }
export let composeLegacyBranchDeps: typeof import('../bootstrap').composeLegacyBranchDeps;
export function __set_composeLegacyBranchDeps(value: typeof composeLegacyBranchDeps): void { composeLegacyBranchDeps = value; }
export let composeLegacyCommercialDeps: typeof import('../bootstrap').composeLegacyCommercialDeps;
export function __set_composeLegacyCommercialDeps(value: typeof composeLegacyCommercialDeps): void { composeLegacyCommercialDeps = value; }
export let composeLegacyCommercialPermissions: typeof import('../bootstrap').composeLegacyCommercialPermissions;
export function __set_composeLegacyCommercialPermissions(value: typeof composeLegacyCommercialPermissions): void { composeLegacyCommercialPermissions = value; }
export let composeLegacyCrmDeps: typeof import('../bootstrap').composeLegacyCrmDeps;
export function __set_composeLegacyCrmDeps(value: typeof composeLegacyCrmDeps): void { composeLegacyCrmDeps = value; }
export let composeLegacyExpenseDeps: typeof import('../bootstrap').composeLegacyExpenseDeps;
export function __set_composeLegacyExpenseDeps(value: typeof composeLegacyExpenseDeps): void { composeLegacyExpenseDeps = value; }
export let composeLegacyFinancialQueries: typeof import('../bootstrap').composeLegacyFinancialQueries;
export function __set_composeLegacyFinancialQueries(value: typeof composeLegacyFinancialQueries): void { composeLegacyFinancialQueries = value; }
export let composeLegacyIntegrityDeps: typeof import('../bootstrap').composeLegacyIntegrityDeps;
export function __set_composeLegacyIntegrityDeps(value: typeof composeLegacyIntegrityDeps): void { composeLegacyIntegrityDeps = value; }
export let composeLegacyInvoiceDeps: typeof import('../bootstrap').composeLegacyInvoiceDeps;
export function __set_composeLegacyInvoiceDeps(value: typeof composeLegacyInvoiceDeps): void { composeLegacyInvoiceDeps = value; }
export let composeLegacyInvoiceRules: typeof import('../bootstrap').composeLegacyInvoiceRules;
export function __set_composeLegacyInvoiceRules(value: typeof composeLegacyInvoiceRules): void { composeLegacyInvoiceRules = value; }
export let composeLegacyJournalRules: typeof import('../bootstrap').composeLegacyJournalRules;
export function __set_composeLegacyJournalRules(value: typeof composeLegacyJournalRules): void { composeLegacyJournalRules = value; }
export let composeLegacyManualJournalDeps: typeof import('../bootstrap').composeLegacyManualJournalDeps;
export function __set_composeLegacyManualJournalDeps(value: typeof composeLegacyManualJournalDeps): void { composeLegacyManualJournalDeps = value; }
export let composeLegacyNettingDeps: typeof import('../bootstrap').composeLegacyNettingDeps;
export function __set_composeLegacyNettingDeps(value: typeof composeLegacyNettingDeps): void { composeLegacyNettingDeps = value; }
export let composeLegacyPartyNames: typeof import('../bootstrap').composeLegacyPartyNames;
export function __set_composeLegacyPartyNames(value: typeof composeLegacyPartyNames): void { composeLegacyPartyNames = value; }
export let composeLegacyPhonePolicy: typeof import('../bootstrap').composeLegacyPhonePolicy;
export function __set_composeLegacyPhonePolicy(value: typeof composeLegacyPhonePolicy): void { composeLegacyPhonePolicy = value; }
export let composeLegacyTourismDeps: typeof import('../bootstrap').composeLegacyTourismDeps;
export function __set_composeLegacyTourismDeps(value: typeof composeLegacyTourismDeps): void { composeLegacyTourismDeps = value; }
export let composeLegacyTransferDeps: typeof import('../bootstrap').composeLegacyTransferDeps;
export function __set_composeLegacyTransferDeps(value: typeof composeLegacyTransferDeps): void { composeLegacyTransferDeps = value; }
export let composeLegacyUmrahLifecycleDeps: typeof import('../bootstrap').composeLegacyUmrahLifecycleDeps;
export function __set_composeLegacyUmrahLifecycleDeps(value: typeof composeLegacyUmrahLifecycleDeps): void { composeLegacyUmrahLifecycleDeps = value; }
export let composeLegacyVoucherDeps: typeof import('../bootstrap').composeLegacyVoucherDeps;
export function __set_composeLegacyVoucherDeps(value: typeof composeLegacyVoucherDeps): void { composeLegacyVoucherDeps = value; }
export let composeParty360Presentation: typeof import('../bootstrap').composeParty360Presentation;
export function __set_composeParty360Presentation(value: typeof composeParty360Presentation): void { composeParty360Presentation = value; }
export let composePrintPresentation: typeof import('../bootstrap').composePrintPresentation;
export function __set_composePrintPresentation(value: typeof composePrintPresentation): void { composePrintPresentation = value; }
export let composeUmrahPresentationCommands: typeof import('../bootstrap').composeUmrahPresentationCommands;
export function __set_composeUmrahPresentationCommands(value: typeof composeUmrahPresentationCommands): void { composeUmrahPresentationCommands = value; }
export let composeUnifiedPartyPresentation: typeof import('../bootstrap').composeUnifiedPartyPresentation;
export function __set_composeUnifiedPartyPresentation(value: typeof composeUnifiedPartyPresentation): void { composeUnifiedPartyPresentation = value; }
