const Seed={
 meta:{version:APP.version,schema:APP.schema,createdAt:now(),updatedAt:now(),lastBackupAt:'',migratedFrom:'',serviceTypesInitialized:true,release:'v32.2 • Hajj & Umrah Autofill + Editable Contracts',setupComplete:false,fix20Applied:true,fix20Build:'2026-08-19',v20NineFixes:true,v21SmartContracts:true,v22UmrahRootSections:true},
 company:{name:'اسم الشركة',taxNo:'',commercialNo:'',phone:'',whatsapp:'',email:'',website:'',address:'',logo:'',country:'EG',city:'',companyId:''},
 settings:{baseCurrency:'EGP',preventNegativeTreasury:true,passwordMin:8,printAmountWords:true,printSignatures:true,printFooter:'مع تحيات شركتكم',appearance:'light',accentColor:'#c9972f',animations:true,fontScale:1,fontFamily:'default',activityRetentionDays:90,activityViewDays:30,expenseCategories:['إيجار ومقر','تسويق وإعلان','تشغيل برامج','اتصالات وإنترنت','رواتب وأجور','نقل وانتقالات','رسوم حكومية','صيانة','ضيافة','مصروفات بنكية','أخرى'],prefixes:deep(PrefixDefaults),fiscalYearStartMonth:1,approvalPayments:true,allowSelfApproval:false,printPaper:'A4',printOrientation:'portrait',signatureLabels:['المحاسب','المراجع','الاعتماد'],loginTagline:'السياحة • المحاسبة • العملاء • الحج والعمرة',loginHeadline:'إدارة شركة السياحة بالكامل من منصة واحدة.',loginDescription:'الحجوزات والخدمات والحج والعمرة والعملاء والموردون والحسابات والتقارير تعمل في دورة تشغيلية ومالية موحّدة.',loginButton:'دخول إلى النظام',sidebarSubtitle:'نظام السياحة والحج والعمرة',sidebarEdition:'من تطوير Elhafez Technology',productName:'Elhafez',productEdition:'نظام السياحة والحج والعمرة',sidebarMode:'fixed',whatsappCountryCode:'20',workspaces:[
 {id:'umrah',name:'الحج والعمرة',description:'تشغيل الحج والعمرة من البرنامج والحجز حتى التعاقدات والجاهزية والإدارة.',icon:'programs',color:'#315f85',active:true,pages:['umrah-dashboard','umrah-program-new','umrah-booking-new','umrah-booking-resume','umrah-seasons','umrah-programs','umrah-program-workspace','umrah-costing','umrah-bookings','umrah-travelers','umrah-contracts','umrah-procurement','umrah-visas','umrah-hotels','umrah-flights','umrah-transport','umrah-hajj-services','umrah-trip-ready','umrah-control','umrah-tripops','umrah-incidents','umrah-documents','umrah-settings']},
 {id:'sales',name:'المبيعات والعملاء CRM',description:'العملاء المحتملون والعملاء والمندوبون وعروض الأسعار قبل الدورة المالية.',icon:'customers',color:'#08785b',active:true,pages:['crm','customers','agents','quotations']},
 {id:'tourism',name:'الخدمات السياحية',description:'تشغيل خدمات التأشيرات والطيران والفنادق والنقل والرحلات.',icon:'services',color:'#2c78c7',active:true,pages:['services']},
 {id:'procurement',name:'المشتريات والموردون',description:'الموردون وأوامر الشراء والالتزامات التشغيلية قبل فاتورة المورد.',icon:'suppliers',color:'#b75b2a',active:true,pages:['suppliers','purchaseorders']},
 {id:'finance',name:'المحاسبة والمالية',description:'الفواتير والتحصيل والسداد والخزن والقيود والحسابات والعملات والفترات المالية.',icon:'accounts',color:'#176b57',active:true,pages:['invoices','receipts','payments','expenses','settlements','accruals','assets','loans','budgets','cheques','treasury','journal','accounts','trial','costcenters','currencies','taxes','periods']},
 {id:'control',name:'التقارير والرقابة',description:'لوحة الإدارة والتقارير والاعتمادات والرقابة وسجل النشاط.',icon:'reports',color:'#355c8a',active:true,pages:['workcenter','owner','reports','approvals','audit','activity']},
 {id:'admin',name:'الإدارة والإعدادات',description:'المستخدمون والفروع والمستندات والجلسات والدعم وإعدادات الشركة.',icon:'settings',color:'#52647a',active:true,pages:['market-readiness','quick-guide','users','branches','documents','sessions','dataexchange','support','settings']}
]},
 license:{mode:'offline',status:'active',edition:'professional',expiresAt:'',clientName:'',maxUsers:20,companyId:'OFFLINE-LOCAL',activationKey:'',modules:['accounting','tourism','umrah','crm','branches','reports','whatsapp','imports'],maxBranches:5,source:'local-offline'},branches:[],notificationPrefs:{passportDays:180,invoiceDueDays:3,programDays:7,lowTreasuryAmount:0},sequences:{},
 serviceTypes:[{id:'ST-VISA',name:'تأشيرة',active:true},{id:'ST-FLIGHT',name:'طيران',active:true},{id:'ST-HOTEL',name:'فندق',active:true},{id:'ST-TRANSPORT',name:'نقل',active:true},{id:'ST-TOUR',name:'رحلة',active:true}],
 currencies:[{id:iid(),code:'EGP',name:'الجنيه المصري',symbol:'ج.م',decimals:2,active:true,base:true,rateMode:'manual'},{id:iid(),code:'SAR',name:'الريال السعودي',symbol:'ر.س',decimals:2,active:true,base:false,rateMode:'manual'}],
 fxRates:[{id:iid(),code:'EGP',date:'2000-01-01',rate:1,source:'system'},{id:iid(),code:'SAR',date:'2000-01-01',rate:13.5,source:'manual'}],
 accounts:[
  {id:'1000',name:'الأصول',type:'group',nature:'debit',parentId:'',posting:false,system:true,active:true},{id:'1100',name:'النقدية والبنوك',type:'asset',nature:'debit',parentId:'1000',posting:false,system:true,active:true},{id:'1150',name:'شيكات تحت التحصيل',type:'asset',nature:'debit',parentId:'1000',posting:true,system:true,active:true},{id:'1200',name:'ذمم العملاء',type:'asset',nature:'debit',parentId:'1000',posting:true,control:'customer',system:true,active:true},{id:'1210',name:'ذمم المندوبين',type:'asset',nature:'debit',parentId:'1000',posting:true,control:'agentReceivable',system:true,active:true},{id:'1300',name:'مصروفات مقدمة',type:'asset',nature:'debit',parentId:'1000',posting:true,system:true,active:true},{id:'1310',name:'ضريبة مدخلات قابلة للاسترداد',type:'asset',nature:'debit',parentId:'1000',posting:true,system:true,active:true},{id:'1400',name:'دفعات مقدمة للموردين',type:'asset',nature:'debit',parentId:'1000',posting:true,control:'supplierAdvance',system:true,active:true},
  {id:'2000',name:'الخصوم',type:'group',nature:'credit',parentId:'',posting:false,system:true,active:true},{id:'2100',name:'ذمم الموردين',type:'liability',nature:'credit',parentId:'2000',posting:true,control:'supplier',system:true,active:true},{id:'2150',name:'شيكات صادرة',type:'liability',nature:'credit',parentId:'2000',posting:true,system:true,active:true},{id:'2200',name:'عمولات مستحقة للمندوبين',type:'liability',nature:'credit',parentId:'2000',posting:true,control:'agentPayable',system:true,active:true},{id:'2300',name:'ضريبة مخرجات مستحقة',type:'liability',nature:'credit',parentId:'2000',posting:true,system:true,active:true},{id:'2400',name:'دفعات مقدمة من العملاء',type:'liability',nature:'credit',parentId:'2000',posting:true,control:'customerAdvance',system:true,active:true},{id:'2410',name:'دفعات مقدمة من المندوبين',type:'liability',nature:'credit',parentId:'2000',posting:true,control:'agentAdvance',system:true,active:true},
  {id:'3000',name:'حقوق الملكية',type:'group',nature:'credit',parentId:'',posting:false,system:true,active:true},{id:'3100',name:'أرصدة افتتاحية / رأس المال',type:'equity',nature:'credit',parentId:'3000',posting:true,system:true,active:true},{id:'3200',name:'أرباح محتجزة',type:'equity',nature:'credit',parentId:'3000',posting:true,system:true,active:true},
  {id:'4000',name:'الإيرادات',type:'group',nature:'credit',parentId:'',posting:false,system:true,active:true},{id:'4100',name:'إيرادات برامج العمرة',type:'revenue',nature:'credit',parentId:'4000',posting:true,system:true,active:true},{id:'4200',name:'إيرادات الخدمات السياحية',type:'revenue',nature:'credit',parentId:'4000',posting:true,system:true,active:true},{id:'4500',name:'أرباح فروق عملة محققة',type:'revenue',nature:'credit',parentId:'4000',posting:true,system:true,active:true},{id:'4510',name:'أرباح إعادة تقييم عملة غير محققة',type:'revenue',nature:'credit',parentId:'4000',posting:true,system:true,active:true},{id:'4600',name:'فروق جرد نقدية دائنة',type:'revenue',nature:'credit',parentId:'4000',posting:true,system:true,active:true},
  {id:'5000',name:'التكاليف والمصروفات',type:'group',nature:'debit',parentId:'',posting:false,system:true,active:true},{id:'5100',name:'تكلفة الخدمات السياحية',type:'expense',nature:'debit',parentId:'5000',posting:true,system:true,active:true},{id:'5200',name:'مصروفات تشغيلية',type:'expense',nature:'debit',parentId:'5000',posting:true,system:true,active:true},{id:'5300',name:'مصروف عمولات المندوبين',type:'expense',nature:'debit',parentId:'5000',posting:true,system:true,active:true},{id:'5500',name:'خسائر فروق عملة محققة',type:'expense',nature:'debit',parentId:'5000',posting:true,system:true,active:true},{id:'5510',name:'خسائر إعادة تقييم عملة غير محققة',type:'expense',nature:'debit',parentId:'5000',posting:true,system:true,active:true},{id:'5600',name:'فروق جرد نقدية مدينة',type:'expense',nature:'debit',parentId:'5000',posting:true,system:true,active:true}
 ],
 taxCodes:[{id:'TAX0',name:'بدون ضريبة',rate:0,type:'both',active:true,inputAccount:'1310',outputAccount:'2300'},{id:'VAT14',name:'ضريبة قيمة مضافة 14%',rate:14,type:'both',active:true,inputAccount:'1310',outputAccount:'2300'}],
 costCenters:[{id:'CC-UMRAH',no:'CC0001',name:'برامج العمرة',description:'إيرادات وتكاليف برامج العمرة',active:true,system:true},{id:'CC-TOUR',no:'CC0002',name:'الخدمات السياحية',description:'الطيران والفنادق والنقل والتأشيرات',active:true,system:true}],
 treasuries:[],customers:[],suppliers:[],agents:[],leads:[],followups:[],quotations:[],purchaseOrders:[],programs:[],bookings:[],travelers:[],roomAllocations:[],services:[],serviceInventoryAllocations:[],invoices:[],invoiceAdjustments:[],receipts:[],payments:[],cheques:[],expenses:[],prepaidSchedules:[],commissions:[],commissionRules:[],manualJournalDrafts:[],recurringJournals:[],journals:[],documents:[],attachments:[],transfers:[],cashCounts:[],bankReconciliations:[],bankStatementLines:[],bankMatches:[],fxRevaluations:[],supplierSettlements:[],customerSettlements:[],partyGroups:[],partyNettings:[],deferredRevenueSchedules:[],deferredCostSchedules:[],accruedRevenues:[],fixedAssets:[],assetDepreciations:[],loans:[],loanSchedules:[],provisions:[],doubtfulAllowances:[],payrollRuns:[],accountBudgets:[],openingBalanceBatches:[],approvals:[],users:[],auditLog:[],fiscalYears:[],periods:[],printNarratives:[],dataImports:[],supportNotes:[],
 // Native Hajj & Umrah core collections. These are first-class ERP state, not integrated-module mirrors.
 umrahSeasons:[],umrahHotelContracts:[],umrahFlightBlocks:[],umrahTransportContracts:[],umrahVisaContracts:[],umrahContractReservations:[],umrahPrograms:[],umrahProgramSegments:[],umrahProgramCosts:[],umrahBookings:[],umrahTravelers:[],umrahHotelRooms:[],umrahVisaBatches:[],umrahVisaItems:[],umrahTickets:[],umrahBusRuns:[],umrahOperationTasks:[],umrahIncidents:[],umrahSupplierCommitments:[],umrahActivity:[],umrahOutbox:[],
 umrahMeta:{},umrahSettings:{},umrahSequences:{}

};

const SequenceMigration={
 run(d){if(d.meta?.sequenceReadyV10)return;d.sequences=d.sequences||{};const master=new Set(['customer','supplier','agent','program','costCenter','treasury','lead']),specs=[['customers','customer'],['suppliers','supplier'],['agents','agent'],['leads','lead'],['programs','program'],['costCenters','costCenter'],['treasuries','treasury'],['quotations','quotation'],['purchaseOrders','purchaseOrder'],['bookings','booking'],['services','service'],['receipts','receipt'],['payments','payment'],['expenses','expense'],['journals','journal'],['transfers','transfer'],['commissions','commission'],['attachments','attachment'],['approvals','approval'],['cashCounts','cashCount'],['bankReconciliations','reconciliation'],['fxRevaluations','fxRevaluation']];
  const key=(type,date='')=>master.has(type)?type:`${type}:${year2(date||today())}`;const bump=(type,x)=>{const no=S(x?.no),date=x?.date||x?.createdAt?.slice?.(0,10)||today(),digits=(no.match(/(\d+)$/)||[])[1]||'';if(!digits)return;let n;if(master.has(type))n=N(digits);else{const y=year2(date),idx=digits.indexOf(y);n=idx>=0?N(digits.slice(idx+2)):N(digits.slice(-4))}if(!(n>0))return;const k=key(type,date);d.sequences[k]=Math.max(N(d.sequences[k]),n)};for(const[arr,type]of specs)for(const x of d[arr]||[])bump(type,x);for(const x of d.invoices||[])bump(x.kind==='supplier'?'purchaseInvoice':'salesInvoice',x);for(const x of d.invoiceAdjustments||[])bump(x.type==='credit'?'creditNote':'debitNote',x);d.meta=d.meta||{};d.meta.sequenceReadyV10=true;d.meta.numberingPolicy='historical-numbers-immutable'}
};
