import { APP, FileNames, N, S, byId, deep, iid, now, toast, today } from '../core/runtime';
import { Numbering } from '../core/numbering';
import { SequenceMigration } from '../core/seed';
import { ServerStore } from '../persistence/server-store';
import { DB, DataStore } from '../persistence/browser-store';
import { Currency } from '../accounting/currency-periods';
import { Auth, Party360 } from '../core/late-bindings';
import { __set_AttachmentStore, __set_Attachments, __set_Backup } from '../core/late-bindings';
const AttachmentStore={db:null,legacyDb:null,
 async open(name=APP.filesDb){if(name===APP.filesDb&&this.db)return this.db;if(name===APP.legacyFilesDb&&this.legacyDb)return this.legacyDb;const db=await new Promise((res,rej)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(name===APP.filesDb)this.db=db;else if(name===APP.legacyFilesDb)this.legacyDb=db;return db},
 async localPut(id,file){try{const db=await this.open();return await new Promise((res,rej)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=()=>res(true);tx.onerror=()=>rej(tx.error)})}catch(_){return false}},
 async put(id,file){const local=await this.localPut(id,file);if(ServerStore.available===true&&ServerStore.authenticated){const r=await fetch(`/api/files/${encodeURIComponent(id)}`,{method:'PUT',headers:ServerStore.headers({'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name||'file')}),credentials:'include',body:file});if(!r.ok){if(local)await this.localRemove(id);throw new Error('تعذر رفع المرفق إلى الخادم')}}return true},
 async _get(name,id){try{const db=await this.open(name);return await new Promise((res,rej)=>{const r=db.transaction('files').objectStore('files').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}catch(_){return null}},
 async get(id){if(ServerStore.available===true&&ServerStore.authenticated){try{const r=await fetch(`/api/files/${encodeURIComponent(id)}`,{headers:ServerStore.headers(),credentials:'include',cache:'no-store'});if(r.ok){const b=await r.blob();await this.localPut(id,b);return b}}catch(_){}}let f=await this._get(APP.filesDb,id);if(!f&&APP.legacyFilesDb){try{f=await this._get(APP.legacyFilesDb,id);if(f)await this.put(id,f)}catch(_){}}return f},
 async localRemove(id){try{const db=await this.open();return await new Promise((res,rej)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=()=>res(true);tx.onerror=()=>rej(tx.error)})}catch(_){return false}},
 async remove(id){if(ServerStore.available===true&&ServerStore.authenticated){const r=await fetch(`/api/files/${encodeURIComponent(id)}`,{method:'DELETE',headers:ServerStore.headers(),credentials:'include'});if(!r.ok&&r.status!==404)throw new Error('تعذر حذف المرفق من الخادم')}await this.localRemove(id)},
 async clear(){try{const db=await this.open();return await new Promise<void>((res,rej)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').clear();tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}catch(_){}}
};
__set_AttachmentStore(AttachmentStore);
const Attachments={
 _countSource:null,_countIndex:null,
 _counts(){const src=DB.data.attachments||[];if(this._countSource===src&&this._countIndex)return this._countIndex;const m=new Map();for(const x of src){const k=`${x.entityType}|${x.entityId}`;m.set(k,(m.get(k)||0)+1)}this._countSource=src;this._countIndex=m;return m},
 count(type,id){return this._counts().get(`${type}|${id}`)||0},
 invalidateCounts(){this._countSource=null;this._countIndex=null},
 async add(o,file){Auth.require('documents','add');if(!file)throw new Error('اختر ملفًا');if(file.size>20*1024*1024)throw new Error('الحد الأقصى للمرفق 20MB');const same=DB.data.attachments.filter(x=>x.entityType===o.entityType&&x.entityId===o.entityId&&S(x.name||x.fileName).toLowerCase()===S(o.name||file.name).toLowerCase()),version=(same.reduce((m,x)=>Math.max(m,N(x.version)||1),0)||0)+1,a={id:iid(),no:Numbering.next('attachment'),entityType:o.entityType,entityId:o.entityId,name:o.name||file.name,fileName:file.name,mime:file.type,size:file.size,version,expiryDate:o.expiryDate||'',createdAt:now(),createdBy:Auth.user?.id||''};await AttachmentStore.put(a.id,file);DB.data.attachments.unshift(a);this.invalidateCounts();DB.log('attach',o.entityType,o.entityId,`${a.fileName} v${version}`);setTimeout(()=>{try{if(typeof Party360!=='undefined')Party360.refreshFilesIfVisible(o.entityType,o.entityId)}catch(_){}},40);return a},
 list(type,id){return DB.data.attachments.filter(x=>x.entityType===type&&x.entityId===id)},
 async file(id){const a=byId(DB.data.attachments,id);if(!a)throw new Error('المرفق غير موجود');const file=await AttachmentStore.get(id);if(!file)throw new Error('ملف المرفق غير موجود في التخزين المحلي');return{a,file}},
 async preview(id){Auth.require('documents','view');const{a,file}=await this.file(id),u=URL.createObjectURL(file);if(/^image\//.test(a.mime)||a.mime==='application/pdf'){const e=document.createElement('a');e.href=u;e.target='_blank';e.rel='noopener';e.click();setTimeout(()=>URL.revokeObjectURL(u),60000)}else{URL.revokeObjectURL(u);await this.download(id)}},
 async download(id){Auth.require('documents','view');const{a,file}=await this.file(id),u=URL.createObjectURL(file),e=document.createElement('a');e.href=u;e.download=a.fileName;e.click();setTimeout(()=>URL.revokeObjectURL(u),1000)},
 async remove(id){Auth.require('documents','delete');const a=byId(DB.data.attachments,id);if(!a)return;await AttachmentStore.remove(id);DB.data.attachments=DB.data.attachments.filter(x=>x.id!==id);this.invalidateCounts();DB.log('delete','attachment',id,a.fileName);setTimeout(()=>{try{if(typeof Party360!=='undefined')Party360.refreshFilesIfVisible(a.entityType,a.entityId)}catch(_){}},40)}
};
__set_Attachments(Attachments);
const Backup={
 async blobToBase64(blob){const buf=new Uint8Array(await blob.arrayBuffer());let bin='';const step=0x8000;for(let i=0;i<buf.length;i+=step)bin+=String.fromCharCode(...buf.subarray(i,i+step));return btoa(bin)},
 base64ToBlob(b64,mime='application/octet-stream'){const bin=atob(b64),buf=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)buf[i]=bin.charCodeAt(i);return new Blob([buf],{type:mime})},
 async checksum(text){if(globalThis.crypto?.subtle){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}return btoa(unescape(encodeURIComponent(text))).slice(0,64)},
 async blobHash(blob){const buf=await blob.arrayBuffer();if(globalThis.crypto?.subtle){const d=await crypto.subtle.digest('SHA-256',buf);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}return this.checksum(await this.blobToBase64(blob))},
 key(){return`erp_external_protection_v2:${ServerStore?.tenant?.()||'default'}`},
 status(){try{return JSON.parse(localStorage.getItem(this.key())||'{}')}catch(_){return{}}},
 mark(kind,name){try{const x=this.status();x[kind]={at:now(),name};localStorage.setItem(this.key(),JSON.stringify(x))}catch(_){}},
 cleanName(v){return S(v||'ERP').replace(/[^\p{L}\p{N}._-]+/gu,'_').replace(/^_+|_+$/g,'').slice(0,80)||'ERP'},
 filename(kind='backup',through=''){const company=DB.data?.company?.name||APP.name||'Elhafez Tourism';return kind==='archive'?FileNames.archive(company,through):FileNames.backup(company)},
 async fullState(sourceData){if(sourceData)return deep(sourceData);if(ServerStore.available===true||ServerStore.remoteRequired?.()){if(!(await ServerStore.probe(true))||!ServerStore.authenticated)throw new Error('يجب تسجيل الدخول كمدير لإنشاء نسخة كاملة');const full=await ServerStore.exportState();if(full)return deep(full)}return deep(DB.data)},
 async build(kind='backup',opts:any={}){const data=await this.fullState(opts.sourceData);if(data.license)data.license={...data.license,activationKey:''};const attachments=[],blobMap=new Map<string,any>();for(const a of data.attachments||[]){const f=await AttachmentStore.get(a.id);if(!f)throw new Error(`تعذر إنشاء نسخة كاملة: ملف المرفق ${a.fileName||a.no||a.id} غير موجود`);const hash=await this.blobHash(f);attachments.push({id:a.id,name:a.fileName||f.name||'',mime:a.mime||f.type||'',size:f.size,sha256:hash});if(!blobMap.has(hash))blobMap.set(hash,{sha256:hash,mime:a.mime||f.type||'',size:f.size,data:await this.blobToBase64(f)})}const blobs=[...blobMap.values()],payload=JSON.stringify({data,attachments,blobs}),pkg={format:kind==='archive'?'erp-professional-suite-archive':'erp-professional-suite-backup',formatVersion:4,kind:kind==='archive'?'archive':'backup',schema:APP.schema,appVersion:APP.version,companyId:S(data.company?.companyId||data.license?.companyId||''),companyName:S(data.company?.name||''),archiveThrough:S(opts.archiveThrough||''),label:S(opts.label||''),exportedAt:now(),checksum:await this.checksum(payload),data,attachments,blobs};return pkg},
 bytesBase64(bytes){let bin='';const step=0x8000;for(let i=0;i<bytes.length;i+=step)bin+=String.fromCharCode(...bytes.subarray(i,i+step));return btoa(bin)},
 nativeBridge(){const bridge=(globalThis as any).NativeBackup;return bridge&&typeof bridge.beginBackupTransfer==='function'&&typeof bridge.appendBackupChunk==='function'&&typeof bridge.finishBackupTransfer==='function'?bridge:null},
 waitNativeDelivery(id,timeoutMs=120000){return new Promise<any>((resolve,reject)=>{let timer:any=null;const done=(e:any)=>{const d=e?.detail||{};if(S(d.id)!==S(id))return;window.removeEventListener('erp:native-backup-delivery',done as EventListener);if(timer)clearTimeout(timer);if(d.status==='success')resolve(d);else reject(new Error(S(d.message||'تعذر تسليم ملف النسخة الاحتياطية')))};window.addEventListener('erp:native-backup-delivery',done as EventListener);timer=setTimeout(()=>{window.removeEventListener('erp:native-backup-delivery',done as EventListener);reject(new Error('انتهت مهلة حفظ أو مشاركة ملف النسخة الاحتياطية'))},timeoutMs)})},
 async nativeDeliver(blob,name,type,mode){const bridge=this.nativeBridge();if(!bridge)throw new Error('واجهة حفظ النسخ على Android غير متاحة');const id=S(bridge.beginBackupTransfer(name,type,mode));if(!id)throw new Error('تعذر بدء إنشاء ملف النسخة على الجهاز');try{const chunkSize=192*1024;for(let offset=0;offset<blob.size;offset+=chunkSize){const bytes=new Uint8Array(await blob.slice(offset,Math.min(blob.size,offset+chunkSize)).arrayBuffer()),chunk=this.bytesBase64(bytes);if(bridge.appendBackupChunk(id,chunk)!==true)throw new Error('تعذر كتابة ملف النسخة على الجهاز')}const result=this.waitNativeDelivery(id);if(bridge.finishBackupTransfer(id)!==true)throw new Error('تعذر إكمال ملف النسخة على الجهاز');const detail=await result;return{name,shared:mode==='share',saved:mode==='download',native:true,detail}}catch(e){try{bridge.cancelBackupTransfer?.(id)}catch(_){}throw e}},
 browserSave(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000);return{name,shared:false,saved:true,native:false}},
 async browserShare(blob,name,type,pkg){const file=new File([blob],name,{type});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({title:pkg.kind==='archive'?'أرشيف النظام':'نسخة احتياطية للنظام',text:pkg.kind==='archive'?`أرشيف ${pkg.archiveThrough||''}`:'نسخة احتياطية كاملة للنظام',files:[file]});return{name,shared:true,saved:false,native:false}}catch(e){if(e?.name==='AbortError')return{name,shared:false,saved:false,cancelled:true,native:false};throw e}}const out=this.browserSave(blob,name);toast('المشاركة المباشرة غير مدعومة في هذا المتصفح؛ تم تنزيل الملف ويمكن مشاركته من Downloads.','warning');return{...out,fallback:true}},
 async deliver(pkg,mode='download'){const text=JSON.stringify(pkg),name=this.filename(pkg.kind,pkg.archiveThrough),type=pkg.kind==='archive'?'application/x-erp-archive':'application/x-erp-backup',blob=new Blob([text],{type}),bridge=this.nativeBridge();if(bridge)return this.nativeDeliver(blob,name,type,mode);if(mode==='share')return this.browserShare(blob,name,type,pkg);return this.browserSave(blob,name)},
 async export(mode='download',opts:any={}){const kind=opts.kind==='archive'?'archive':'backup',pkg=await this.build(kind,opts),out=await this.deliver(pkg,mode);if(out.cancelled)return pkg;if(out.saved)this.mark(kind,out.name);toast(kind==='archive'?(out.shared?'تم إنشاء الأرشيف وفتح قائمة المشاركة':out.fallback?'تم حفظ الأرشيف في Downloads ويمكن مشاركته من هناك':'تم حفظ ملف الأرشيف على الجهاز'):(out.shared?'تم إنشاء النسخة وفتح قائمة المشاركة':out.fallback?'تم حفظ النسخة في Downloads ويمكن مشاركتها من هناك':'تم حفظ النسخة الاحتياطية على الجهاز'),'ok');return pkg},
 async normalizeLegacy(raw){if(raw?.formatVersion>=4&&(raw?.format==='erp-professional-suite-backup'||raw?.format==='erp-professional-suite-archive'))return raw;if(raw?.format==='erp-professional-suite-portable'||raw?.format==='erp-professional-suite-backup'){const files=raw.files||[],attachments=[],blobMap=new Map<string,any>();for(const f of files){const blob=this.base64ToBlob(f.data,f.mime),hash=await this.blobHash(blob);attachments.push({id:f.id,name:f.name||f.id,mime:f.mime||'',size:blob.size,sha256:hash});if(!blobMap.has(hash))blobMap.set(hash,{sha256:hash,mime:f.mime||'',size:blob.size,data:f.data})}return{...raw,format:raw.kind==='archive'?'erp-professional-suite-archive':'erp-professional-suite-backup',formatVersion:4,attachments,blobs:[...blobMap.values()]}}return{format:'legacy',formatVersion:1,kind:'backup',data:raw,attachments:[],blobs:[]}},
 async verifyPackage(pkg){const data=pkg.data;if(!data||!Array.isArray(data.accounts)||!Array.isArray(data.users))throw new Error('ملف النسخة غير صالح');const blobMap=new Map<string,any>((pkg.blobs||[]).map((x:any)=>[x.sha256,x] as [string,any]));for(const a of pkg.attachments||[]){const b=blobMap.get(a.sha256);if(!b)throw new Error(`النسخة غير مكتملة: مرفق ${a.name||a.id} مفقود`);const blob=this.base64ToBlob(b.data,b.mime||a.mime),hash=await this.blobHash(blob);if(hash!==a.sha256||blob.size!==N(a.size))throw new Error(`فشل فحص سلامة المرفق ${a.name||a.id}`)}if(pkg.checksum){const check=await this.checksum(JSON.stringify({data:pkg.data,attachments:pkg.attachments||[],blobs:pkg.blobs||[]}));if(check!==pkg.checksum)throw new Error('فشل فحص سلامة الملف؛ النسخة قد تكون تالفة أو ناقصة')}return true},
 async read(file){if(!file)throw new Error('اختر ملف النسخة');let raw;try{raw=JSON.parse(await file.text())}catch(_){throw new Error('الملف غير صالح أو غير قابل للقراءة')}const pkg=await this.normalizeLegacy(raw);await this.verifyPackage(pkg);const d=pkg.data;if(d.meta?.schema!==APP.schema&&d.meta?.schema!=='erp-professional-suite-v8')throw new Error('ملف النسخة غير متوافق مع هذا النظام');const currentCompany=S(DB.data?.company?.companyId||DB.data?.license?.companyId||''),fileCompany=S(pkg.companyId||d.company?.companyId||d.license?.companyId||'');if(currentCompany&&fileCompany&&currentCompany!==fileCompany)throw new Error('هذه النسخة تخص شركة مختلفة ولا يمكن فتحها هنا');return pkg},
 async restorePackage(pkg){if(pkg.kind==='archive')throw new Error('ملف الأرشيف للعرض فقط ولا يمكن استعادته كبيانات تشغيل');await this.verifyPackage(pkg);const d=deep(pkg.data),blobMap=new Map<string,any>((pkg.blobs||[]).map((x:any)=>[x.sha256,x] as [string,any]));d.meta={...(d.meta||{}),schema:APP.schema,version:APP.version,setupComplete:d.meta?.setupComplete!==false,restoredAt:now(),restoredFrom:'backup'};if(ServerStore.available===true||ServerStore.remoteRequired?.()){if(!(await ServerStore.probe(true))||!ServerStore.authenticated)throw new Error('يجب تسجيل الدخول كمدير لاستعادة النسخة');for(const f of pkg.attachments||[]){const b=blobMap.get(f.sha256),blob=this.base64ToBlob(b.data,b.mime||f.mime),file=new File([blob],f.name||f.id,{type:f.mime||b.mime||'application/octet-stream'});await AttachmentStore.put(f.id,file)}const r=await ServerStore.restoreState(d,(pkg.attachments||[]).map(f=>f.id));if(!r?.ok)throw new Error('تعذر استعادة النسخة على الخادم');await AttachmentStore.clear();await DataStore.localPut(d);try{sessionStorage.removeItem(APP.session)}catch(_){}toast('تمت استعادة النسخة بنجاح. سيتم إعادة تسجيل الدخول.','ok');setTimeout(()=>location.reload(),700);return r}DB.data=d;DB.ensure();SequenceMigration.run(DB.data);await AttachmentStore.clear();for(const f of pkg.attachments||[]){const b=blobMap.get(f.sha256);await AttachmentStore.localPut(f.id,new File([this.base64ToBlob(b.data,b.mime||f.mime)],f.name||f.id,{type:f.mime||b.mime||'application/octet-stream'}))}await DataStore.localPut(DB.data);toast('تمت استعادة النسخة على الجهاز','ok');setTimeout(()=>location.reload(),500);return{ok:true}},
 async import(file){const pkg=await this.read(file);return this.restorePackage(pkg)}
};
__set_Backup(Backup);
const AutoOps={async snapshot(){return false},async refreshLiveFx(){if(!navigator.onLine)return;for(const c of Currency.active().filter(x=>x.code!==DB.data.settings.baseCurrency&&x.rateMode==='live')){const last=DB.data.fxRates.filter(r=>r.code===c.code).sort((a,b)=>b.date.localeCompare(a.date))[0];if(last?.date===today())continue;try{await Currency.fetchLive(c.code)}catch(e){DB.log('automation-warning','currency',c.code,'تعذر تحديث السعر المباشر: '+S(e.message||e))}}DB.save(false)},run(){this.refreshLiveFx()}};
export { AttachmentStore, Attachments, AutoOps, Backup };
