/* Unified operational output hub; all output continues to use the ERP print engine. */
const OutputCenter={
 select(title,subtitle,items,onSelect,iconName='documents'){const m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement|null;if(!m||!f)return;document.getElementById('modalTitle').textContent=title;document.getElementById('modalSubtitle').textContent=subtitle;document.getElementById('modalIcon').innerHTML=icon(iconName);document.getElementById('modalSubmitText').textContent='فتح';document.getElementById('modalBody').innerHTML=`<div class="field"><label>اختر السجل</label><select name="pick" required><option value="">— اختر —</option>${items.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('')}</select></div>`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();const id=S(new FormData(f).get('pick'));if(!id)return;UI.closeModal(true);onSelect(id)}},
 quotation(){const list=(DB.data.quotations||[]).filter(q=>live(q)).map(q=>({id:q.id,label:`${q.no||''} — ${Actions.partyName('customer',q.partyId)||'-'} — ${formatDate(q.date)}`}));this.select('عرض سعر','اختر عرض السعر لفتح المعاينة والطباعة.',list,id=>Print.quotation(id),'invoices')},
 invoice(){const list=(DB.data.invoices||[]).filter(i=>live(i)).map(i=>({id:i.id,label:`${i.no||''} — ${i.kind==='supplier'?'مورد':'مبيعات'} — ${formatDate(i.date)}`}));this.select('فاتورة','اختر الفاتورة لفتح المعاينة والطباعة.',list,id=>Print.invoice(id),'invoices')},
 party(type){const list=(type==='customer'?DB.data.customers:DB.data.suppliers).filter(x=>x.active!==false).map(x=>({id:x.id,label:`${x.no||''} — ${x.name}`}));this.select(type==='customer'?'كشف حساب عميل':'كشف حساب مورد','اختر الطرف ثم حدد فترة ومستوى كشف الحساب.',list,id=>Actions.statement(type,id),type==='customer'?'customers':'suppliers')},
 umrah(kind){const map={programSummary:['ملخص البرنامج للوكيل','ملخص الوصول والإقامات والتفويج والمغادرة والمسافرين','programSummary'],manifest:['كشف المسافرين','الأسماء والجوازات والتذاكر والتأشيرات','manifest'],roomingList:['كشف توزيع الغرف','توزيع الغرف لكل إقامات البرنامج','roomingList'],hotelVoucher:['قسيمة إقامة','تفاصيل الفنادق والإقامات للبرنامج','hotelVoucher'],flightReport:['تقرير الطيران','كل قطاعات الرحلة والمقاعد والتذاكر','flightReport'],dispatchList:['كشف التفويج','حركات الباصات والمسافرين','dispatchList'],transportOrder:['أمر النقل','مسارات النقل والمركبات والسائقين','transportOrder'],supplierDues:['مستحقات الموردين','التزامات الموردين والفواتير والمتبقي','supplierDues']},x=map[kind];if(!x)return;const list=(DB.data.umrahPrograms||[]).filter(p=>p.active!==false).map(p=>({id:p.id,label:`${p.no||''} — ${p.name}`}));this.select(x[0],x[1],list,id=>UmrahCore_PrintView[x[2]](id),'programs')},
 booking(){const list=(DB.data.umrahBookings||[]).filter(b=>b.active!==false).map(b=>{const p=byId(DB.data.umrahPrograms,b.programId);return{id:b.id,label:`${b.no||''} — ${b.customerSnapshot?.name||''}${p?.name?' — '+p.name:''}`}});this.select('تأكيد حجز حج/عمرة','مستند مختصر يمكن تسليمه للعميل ويعرض الحجز والبرنامج والمبالغ والمسافرين.',list,id=>UmrahCore_PrintView.bookingConfirmation(id),'bookings')},
 render(){const groups:any[]=[['مالية وعملاء',[['quotation','عرض سعر','العروض التجارية الجاهزة للطباعة','invoices'],['invoice','فاتورة','فواتير المبيعات والموردين','invoices'],['customer','كشف حساب عميل','الحركة والرصيد','customers'],['supplier','كشف حساب مورد','الحركة والرصيد','suppliers']]],['الحج والعمرة',[['booking','تأكيد حجز','الحجز والبرنامج والمسافرون والمبالغ','bookings'],['programSummary','ملخص البرنامج للوكيل','الوصول والإقامة والتفويج والمغادرة','programs'],['manifest','كشف المسافرين','الجوازات والتذاكر والتأشيرات','customers'],['roomingList','كشف توزيع الغرف','توزيع الغرف في جميع الفنادق','suppliers']]],['التشغيل والموردون',[['hotelVoucher','قسيمة إقامة','الفنادق والتواريخ وبيانات البرنامج','documents'],['flightReport','تقرير الطيران','القطاعات والمواعيد والمقاعد','services'],['dispatchList','كشف التفويج','الباصات والمسارات والمسافرون','activity'],['transportOrder','أمر النقل','المركبات والمسارات والسائقون','services'],['supplierDues','مستحقات الموردين','أوامر الشراء والفواتير والمتبقي','payments']]]];return`<div class="output-hub"><div class="card-head output-head"><div><h3>مركز الطباعة</h3><p class="muted">اختر نوع المستند؛ الأرشيف والمرفقات منفصلان عن إنشاء المطبوعات.</p></div></div><div class="clean-output-groups">${groups.map(([name,cards])=>`<section class="output-group"><h4>${name}</h4><div class="output-grid">${cards.map(x=>`<button class="output-card" data-output-action="${esc(x[0])}"><span class="output-icon">${icon(x[3])}</span><b>${esc(x[1])}</b><small>${esc(x[2])}</small></button>`).join('')}</div></section>`).join('')}</div></div>`}
};
