const CommercialActions={
 setActivityRange(range){DB.data.settings.activityRange=range;DB.save(false);UI.openPage('activity','',{skipHistory:true,keepWorkspace:true})},
 async clearActivity(range){const labels={day:'آخر 24 ساعة','7d':'آخر 7 أيام','30d':'آخر 30 يومًا','365d':'آخر سنة',all:'كل سجل النشاط'},days={day:1,'7d':7,'30d':30,'365d':365},cut=range==='all'?Infinity:Date.now()-(days[range]||30)*86400000;if(!confirm(`مسح ${labels[range]||'السجل'}؟\n\nلن يتم حذف الفواتير أو القيود أو المستندات المالية.`))return;DB.data.auditLog=(DB.data.auditLog||[]).filter(x=>range!=='all'&&Date.parse(x.date)<cut);try{if(typeof UmrahCore_DB!=='undefined'&&UmrahCore_DB?.data?.activity)UmrahCore_DB.data.activity=(UmrahCore_DB.data.activity||[]).filter(x=>range!=='all'&&Date.parse(x.at)<cut)}catch(_){};await DB.save(false);try{await CommercialSupport.clearAudit(range)}catch(e){console.warn('[audit] cleanup failed',e?.message||e)}toast('تم تنظيف سجل النشاط');UI.openPage('activity','',{skipHistory:true,keepWorkspace:true})},
 bytes(n){n=N(n);if(n<1024)return`${n} B`;if(n<1024**2)return`${fmt(n/1024,1)} KB`;if(n<1024**3)return`${fmt(n/1024**2,1)} MB`;return`${fmt(n/1024**3,2)} GB`},
 branch(id=''){try{Auth.require('branches',id?'edit':'add');const b=id?byId(DB.data.branches,id):null,m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement;document.getElementById('modalTitle').textContent=b?'تعديل الفرع':'فرع جديد';document.getElementById('modalSubtitle').textContent='العمليات الجديدة ترتبط بالفرع الحالي تلقائيًا.';document.getElementById('modalIcon').innerHTML=icon('customers');document.getElementById('modalSubmitText').textContent='حفظ';document.getElementById('modalBody').innerHTML=`<div class="form-grid"><div class="field"><label>الكود</label><input name="code" value="${esc(b?.code||'')}"></div><div class="field"><label>اسم الفرع</label><input name="name" required value="${esc(b?.name||'')}"></div><div class="field"><label>الهاتف</label><input name="phone" value="${esc(b?.phone||'')}"></div><div class="field full"><label>العنوان</label><input name="address" value="${esc(b?.address||'')}"></div>${b?`<label class="toggle-line"><input type="checkbox" name="active" ${b.active!==false?'checked':''}> الفرع نشط</label>`:''}</div>`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();try{const o:any=Object.fromEntries(new FormData(f));if(b)o.active=new FormData(f).has('active');DB.atomic('branch',()=>b?Commercial.updateBranch(id,o):Commercial.createBranch(o));UI.closeModal(true);toast('تم حفظ الفرع')}catch(err){toast(err.message,'error')}}}catch(e){toast(e.message,'error')}},
 switchBranch(id){try{BranchScope.switch(id);toast(`الفرع الحالي: ${BranchScope.label(id)}`)}catch(e){toast(e.message,'error')}},
 assignUserBranches(id){try{Auth.require('users','edit');const u=byId(DB.data.users,id);if(!u)throw new Error('المستخدم غير موجود');const m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement,allowed=new Set(u.allowedBranchIds||[u.branchId].filter(Boolean));document.getElementById('modalTitle').textContent=`فروع المستخدم — ${u.name}`;document.getElementById('modalSubtitle').textContent='حدد الفروع التي يستطيع المستخدم التعامل معها.';document.getElementById('modalIcon').innerHTML=icon('users');document.getElementById('modalSubmitText').textContent='حفظ الفروع';document.getElementById('modalBody').innerHTML=`<div class="module-check-grid">${DB.data.branches.filter(b=>b.active!==false).map(b=>`<label class="module-check"><input type="checkbox" name="branch_${b.id}" ${allowed.has(b.id)||u.role==='admin'?'checked':''} ${u.role==='admin'?'disabled':''}> ${esc(b.name)}</label>`).join('')}</div>`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),ids=u.role==='admin'?DB.data.branches.filter(b=>b.active!==false).map(b=>b.id):DB.data.branches.filter(b=>fd.has(`branch_${b.id}`)).map(b=>b.id);if(!ids.length)throw new Error('اختر فرعًا واحدًا على الأقل');u.allowedBranchIds=ids;u.branchId=ids.includes(u.branchId)?u.branchId:ids[0];DB.log('branches','user',u.id,ids.join(','));DB.save();UI.closeModal(true);toast('تم تحديث فروع المستخدم')}}catch(e){toast(e.message,'error')}},
 async revokeSession(id){try{await CommercialSupport.revokeSession(id);toast('تم إنهاء الجلسة');CommercialPages.loadSessions()}catch(e){toast(e.message,'error')}},
 async downloadDiagnostics(){try{const d=await CommercialSupport.diagnostics(true),blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ERP_Diagnostics_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast(e.message,'error')}},
 async showServerAudit(){try{const b=await CommercialSupport.audit(),m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement,actionLabels={setup:'إعداد النظام','setup-after-reset':'إعداد النظام بعد إعادة التهيئة','state-write':'حفظ تغييرات النظام','whatsapp-send':'إرسال رسالة واتساب','vendor-entitlement':'تحديث ترخيص الشركة','reset-existing-login':'استعادة دخول المدير','vendor-force-password-change':'إجبار تغيير كلمة المرور','login':'تسجيل دخول','logout':'تسجيل خروج','backup-create':'إنشاء نسخة احتياطية','backup-restore':'استعادة نسخة احتياطية','archive-close':'إغلاق وأرشفة فترة'},rows=(b.items||[]).map(x=>`<tr><td>${formatDateTime(x.created_at)}</td><td>${esc(byId(DB.data.users,x.user_id)?.name||x.user_id||'نظام')}</td><td>${esc(actionLabels[x.action]||'إجراء نظام')}</td><td>${esc(x.ip_address||'-')}</td><td>${esc(S(x.user_agent||'').slice(0,55))}</td><td>${esc(JSON.stringify(x.changes||[]).slice(0,180))}</td></tr>`);document.getElementById('modalTitle').textContent='سجل الخادم المحمي';document.getElementById('modalSubtitle').textContent='سجل خادمي للأحداث التشغيلية؛ تنظيفه لا يؤثر على القيود أو المستندات.';document.getElementById('modalIcon').innerHTML=icon('audit');document.getElementById('modalSubmitText').textContent='إغلاق';document.getElementById('modalBody').innerHTML=UI.table(['التاريخ','المستخدم','الإجراء','عنوان الشبكة','الجهاز','التغييرات'],rows,'لا توجد أحداث',{export:false});m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)}}catch(e){toast(e.message,'error')}},
 party360(type,id){try{Party360.open(type,id)}catch(e){toast(e.message,'error')}},
 async refreshLicenseStatus(){try{const btn=document.getElementById('refreshLicenseBtn') as HTMLButtonElement|null;if(btn){btn.disabled=true;btn.textContent='جاري التحديث...'}const l=await ServerStore.refreshLicense(true);toast('تم تحديث حالة الترخيص من الخادم','ok');UI.openPage('settings','',{skipHistory:true,keepWorkspace:true});setTimeout(()=>document.getElementById('settings-license')?.scrollIntoView({behavior:'smooth',block:'start'}),60);return l}catch(e){toast(e.message||'تعذر تحديث حالة الترخيص','error');const btn=document.getElementById('refreshLicenseBtn') as HTMLButtonElement|null;if(btn){btn.disabled=false;btn.textContent='تحديث حالة الترخيص'}}}
};
Object.assign(Actions,CommercialActions);

const ArchiveViewer={
 open(data,meta:any={}){const m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement,collections=['invoices','receipts','payments','journals','bookings','umrahBookings','customers','suppliers','attachments'],collectionLabels={invoices:'الفواتير',receipts:'سندات القبض',payments:'سندات الصرف',journals:'القيود',bookings:'الحجوزات',umrahBookings:'حجوزات الحج والعمرة',customers:'العملاء',suppliers:'الموردون',attachments:'المرفقات'};document.getElementById('modalTitle').textContent=meta.label||`أرشيف ${String(meta.archiveThrough||data?.meta?.archivePeriodEnd||'').slice(0,4)}`;document.getElementById('modalSubtitle').textContent='للقراءة فقط — للبحث والعرض والطباعة، ولا يغيّر بيانات الفترة الحالية.';document.getElementById('modalIcon').innerHTML=icon('archive');document.getElementById('modalSubmitText').textContent='إغلاق';const cards=collections.filter(k=>Array.isArray(data?.[k])&&data[k].length).map(k=>`<details class="card mt-12"><summary><b>${esc(collectionLabels[k]||k)}</b> — ${data[k].length}</summary><div class="archive-search-list mt-12">${data[k].slice(0,500).map(x=>`<div class="mini-row archive-row"><span>${esc(x.no||x.name||x.title||x.id||'-')}</span><small>${esc([x.date,x.status,x.amount,x.total].filter(v=>v!==undefined&&v!=='').join(' • '))}</small></div>`).join('')}</div></details>`).join('');document.getElementById('modalBody').innerHTML=`<div class="ok-note"><b>سلامة الأرشيف:</b> ${meta.integrity==='failed'?'فشل التحقق ❌':'سليم ✅'} ${meta.checksum?`<small>${esc(String(meta.checksum).slice(0,18))}…</small>`:''}</div><div class="quick-actions mt-12"><input id="archiveSearch" placeholder="بحث داخل الأرشيف" data-archive-filter="1"><button type="button" class="btn ghost" data-window-print="1">طباعة</button></div>${cards||'<div class="empty-state">لا توجد سجلات للعرض</div>'}`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)}}
};
Object.assign(CommercialActions,{
 isAdmin(){return Auth.user?.role==='admin'||Auth.user?.permissions?.all},
 requireProtectionAdmin(){if(!this.isAdmin())throw new Error('هذه العملية متاحة لمدير النظام فقط')},
 async externalBackup(mode='download'){try{this.requireProtectionAdmin();await Backup.export(mode,{kind:'backup',label:'نسخة احتياطية يدوية'});if(UI.current==='backup-center')CommercialPages.loadBackups?.()}catch(e){toast(e.message,'error')}},
 async selectRestoreFile(file){try{this.requireProtectionAdmin();const pkg=await Backup.read(file);if(pkg.kind==='archive')throw new Error('هذا ملف أرشيف للقراءة فقط. افتحه من شاشة الأرشفة بدل الاستعادة.');const m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement;document.getElementById('modalTitle').textContent='استعادة نسخة احتياطية';document.getElementById('modalSubtitle').textContent='تم فحص الملف بنجاح. راجع المعلومات قبل الاستعادة.';document.getElementById('modalIcon').innerHTML=icon('backup');document.getElementById('modalSubmitText').textContent='استعادة النسخة';document.getElementById('modalBody').innerHTML=`<div class="mini-list"><div class="mini-row"><span>تاريخ النسخة</span><b>${formatDateTime(pkg.exportedAt)}</b></div><div class="mini-row"><span>الشركة</span><b>${esc(pkg.companyName||'-')}</b></div><div class="mini-row"><span>المرفقات</span><b>${(pkg.attachments||[]).length}</b></div><div class="mini-row"><span>الملفات الفريدة</span><b>${(pkg.blobs||[]).length}</b></div><div class="mini-row"><span>بصمة التحقق</span><b>سليمة ✅</b></div></div><label class="toggle-line mt-12"><input id="restoreSafetyBackup" type="checkbox" checked> إنشاء نسخة احتياطية خارجية من الوضع الحالي أولًا <b>(موصى به)</b></label>`;m.classList.add('show');f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector<HTMLButtonElement>('[type=submit]');if(btn)btn.disabled=true;try{if((document.getElementById('restoreSafetyBackup') as HTMLInputElement|null)?.checked)await Backup.export('download',{kind:'backup',label:'قبل الاستعادة'});await Backup.restorePackage(pkg)}catch(err){toast(err.message,'error');if(btn)btn.disabled=false}}}catch(e){toast(e.message,'error')}},
 async createSnapshot(){try{this.requireProtectionAdmin();await CommercialSupport.createSnapshot('نسخة خادمية يدوية');toast('تم إنشاء النسخة الخادمية والتحقق من سلامتها','ok');CommercialPages.loadBackups()}catch(e){toast(e.message,'error')}},
 async pinSnapshot(id,pinned){try{await CommercialSupport.pinSnapshot(id,pinned);toast(pinned?'تم تثبيت النسخة':'تم إلغاء التثبيت','ok');CommercialPages.loadBackups()}catch(e){toast(e.message,'error')}},
 async verifySnapshot(id){try{const x=await CommercialSupport.verifySnapshot(id);toast(x.ok?'النسخة سليمة ✅':'فشل التحقق ❌',x.ok?'ok':'error');CommercialPages.loadBackups()}catch(e){toast(e.message,'error')}},
 restoreSnapshot(id){UI.confirmAction('استعادة نسخة خادمية','سيتم استبدال بيانات التشغيل بالحالة الموجودة في هذه النسخة ثم تسجيل الخروج.',async()=>{try{await CommercialSupport.restoreSnapshot(id);location.reload()}catch(e){toast(e.message,'error')}})},
 deleteSnapshot(id){UI.confirmAction('حذف نسخة خادمية','سيتم حذف هذه النسخة يدويًا حتى لو كانت مثبتة. لا يمكن التراجع عن الحذف.',async()=>{try{await CommercialSupport.deleteSnapshot(id);toast('تم حذف النسخة','ok');CommercialPages.loadBackups()}catch(e){toast(e.message,'error')}})},
 async cleanupSnapshots(){try{const x=await CommercialSupport.cleanupSnapshots();toast(`تم تنظيف ${x.deleted||0} نسخة قديمة غير مثبتة`,'ok');CommercialPages.loadBackups()}catch(e){toast(e.message,'error')}},
 async previewArchive(){try{this.requireProtectionAdmin();const end=S((document.getElementById('archivePeriodEnd') as HTMLInputElement|null)?.value);if(!end)throw new Error('حدد سنة الأرشفة');const p=await CommercialSupport.archivePreview(end);ArchiveCenter.preview=p;const blockers=p.check?.blockers||[],warnings=p.check?.warnings||[],m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement;document.getElementById('modalTitle').textContent='مراجعة إغلاق الفترة';document.getElementById('modalSubtitle').textContent='قبل الإغلاق سيُنشئ النظام نسخة خادمية تلقائيًا بنفس وظيفة النسخ، ثم يحفظ أرشيف السنة للقراءة فقط.';document.getElementById('modalIcon').innerHTML=icon(blockers.length?'warning':'archive');document.getElementById('modalSubmitText').textContent=blockers.length?'إغلاق':'إغلاق وأرشفة الفترة';document.getElementById('modalBody').innerHTML=`<div class="grid two"><div class="mini-row"><span>السجلات المؤرشفة</span><b>${p.archivedRecords||0}</b></div><div class="mini-row"><span>التوفير في بيانات التشغيل</span><b>${CommercialActions.bytes(p.reductionBytes||0)}</b></div><div class="mini-row"><span>قيد افتتاحي</span><b>${p.opening?.lines||0} سطر</b></div><div class="mini-row"><span>فحص البيانات</span><b>${blockers.length?'يوجد مانع ❌':'سليم ✅'}</b></div></div>${blockers.map(x=>`<div class="danger-note mt-12">${esc(x)}</div>`).join('')}${warnings.map(x=>`<div class="warn-note mt-12">${esc(x)}</div>`).join('')}`;m.classList.add('show');f.onsubmit=async e=>{e.preventDefault();if(blockers.length)return UI.closeModal(true);await (CommercialActions as any).confirmArchive()}}catch(e){toast(e.message,'error')}},
 async confirmArchive(){const p=ArchiveCenter.preview;if(!p)return toast('راجع الأرشفة أولًا','warning');const btn=document.querySelector<HTMLButtonElement>('#modalForm [type=submit]');try{if(btn)btn.disabled=true;const out=await CommercialSupport.archiveClose({periodEnd:p.periodEnd,revision:p.revision,token:p.token});UI.closeModal(true);toast(`تم إنشاء أرشيف ${p.periodEnd.slice(0,4)} بنجاح — سليم ✅`,'ok');setTimeout(()=>{ArchiveCenter.preview=null;UI.renderCurrent()},300)}catch(e){toast(e.message,'error');if(btn)btn.disabled=false}},
 async openArchive(id){try{const a=await CommercialSupport.archive(id);ArchiveViewer.open(a.payload,{label:a.period_label,archiveThrough:a.period_end,checksum:a.checksum_sha256,integrity:a.integrity_status})}catch(e){toast(e.message,'error')}},
 async openArchiveFile(file){try{const pkg=await Backup.read(file);if(pkg.kind!=='archive')throw new Error('اختر ملف .erparchive');ArchiveViewer.open(pkg.data,{label:pkg.label,archiveThrough:pkg.archiveThrough,checksum:pkg.checksum,integrity:'verified'})}catch(e){toast(e.message,'error')}},
 async downloadArchive(id){try{const pkg=await CommercialSupport.archiveExport(id);await Backup.verifyPackage(pkg);await Backup.deliver(pkg,'download');toast('تم تنزيل ملف .erparchive كامل','ok')}catch(e){toast(e.message,'error')}},
 async archiveInfo(id){try{const a=await CommercialSupport.archive(id),s=a.summary||{},m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement;document.getElementById('modalTitle').textContent='معلومات الأرشيف';document.getElementById('modalSubtitle').textContent=a.period_label||'';document.getElementById('modalIcon').innerHTML=icon('info');document.getElementById('modalSubmitText').textContent='إغلاق';document.getElementById('modalBody').innerHTML=`<div class="mini-list"><div class="mini-row"><span>الفترة</span><b>${esc(a.period_label||a.period_end)}</b></div><div class="mini-row"><span>تاريخ الإغلاق</span><b>${formatDateTime(a.created_at)}</b></div><div class="mini-row"><span>العملاء</span><b>${s.customers||0}</b></div><div class="mini-row"><span>الموردون</span><b>${s.suppliers||0}</b></div><div class="mini-row"><span>الفواتير</span><b>${s.invoices||0}</b></div><div class="mini-row"><span>الحجوزات</span><b>${s.bookings||0}</b></div><div class="mini-row"><span>القيود</span><b>${s.journals||0}</b></div><div class="mini-row"><span>المرفقات</span><b>${a.attachment_manifest?.length||0}</b></div><div class="mini-row"><span>الحجم</span><b>${this.bytes(a.size_bytes||0)}</b></div><div class="mini-row"><span>بصمة التحقق</span><b>${esc(a.checksum_sha256||'-')}</b></div><div class="mini-row"><span>السلامة</span><b>${a.integrity_status==='failed'?'فشل التحقق ❌':'سليم ✅'}</b></div></div>`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();UI.closeModal(true)}}catch(e){toast(e.message,'error')}},
 deleteArchive(id){UI.confirmAction('حذف الأرشيف نهائيًا','هذا أرشيف فترة مالية مغلقة. الحذف للإدارة فقط ولن يمكن استعادته إلا من ملف .erparchive سبق تنزيله.',async()=>{try{await CommercialSupport.archiveDelete(id);toast('تم حذف الأرشيف','ok');CommercialPages.loadArchives()}catch(e){toast(e.message,'error')}})},
 openFactoryReset(){try{this.requireProtectionAdmin();const m=document.getElementById('modal'),f=document.getElementById('modalForm') as HTMLFormElement;document.getElementById('modalTitle').textContent='إعادة تهيئة النظام';document.getElementById('modalSubtitle').textContent='سيتم حذف بيانات التشغيل مع الحفاظ على هوية الشركة والترخيص وحساب المدير السابق لاستعادة الدخول.';document.getElementById('modalIcon').innerHTML=icon('warning');document.getElementById('modalSubmitText').textContent='متابعة';document.getElementById('modalBody').innerHTML=`<div class="danger-note"><b>تحذير:</b> العملاء والموردون والفواتير والحجوزات والقيود والمرفقات والمستخدمون التشغيليون سيتم تصفيرهم. سيُحتفظ بحساب المدير السابق فقط لتتمكن من اختيار «مستخدم حالي» بعد إعادة التهيئة.</div><label class="toggle-line mt-12"><input id="resetSafetyBackup" type="checkbox" checked> إنشاء نسخة احتياطية كاملة أولًا <b>(موصى به)</b></label><p class="muted mt-12">إذا ألغيت النسخة الاحتياطية سيُطلب منك كتابة كلمة التأكيد RESET كخطوة أمان إضافية.</p>`;m.classList.add('show');f.onsubmit=async e=>{e.preventDefault();try{const safe=(document.getElementById('resetSafetyBackup') as HTMLInputElement|null)?.checked;if(safe)await Backup.export('download',{kind:'backup',label:'قبل إعادة تهيئة النظام'});UI.closeModal(true);(CommercialActions as any).confirmFactoryReset(!safe)}catch(err){toast(err.message,'error')}}}catch(e){toast(e.message,'error')}},
 confirmFactoryReset(requireTyped=false){const typed=requireTyped?prompt('للمتابعة بدون نسخة احتياطية اكتب RESET بالحروف الإنجليزية:'):'RESET';if(typed!=='RESET')return toast('تم إلغاء إعادة التهيئة','warning');UI.confirmAction('تأكيد نهائي لإعادة التهيئة','ستعود بيانات التشغيل إلى حالة أول استخدام، ثم ستظهر شاشة تختار منها «مستخدم حالي» أو «مستخدم جديد». النسخ والأرشيفات المحفوظة لا تُحذف.',async()=>{try{if(APP.offlineEdition===true){await DB.factoryReset();return}await ServerStore.factoryReset('RESET');await AttachmentStore.clear();await DataStore.localPut(deep(Seed));location.reload()}catch(e){toast(e.message,'error')}})}
});
Object.assign(Actions,CommercialActions);
