import { N, S, esc, icon, iid, now, toast, today } from '../core/runtime';
import { Numbering } from '../core/numbering';
import { DB } from '../persistence/browser-store';
import { BranchScope } from './product';
import { Transactions } from '../accounting/transactions';
import { Auth } from '../security/auth';
import { UI } from '../core/late-bindings';
const CommercialData={
 csv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<=text.length;i++){const c=text[i]??'\n',n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));cell='';if(row.some(x=>S(x).trim()))rows.push(row);row=[]}else cell+=c}return rows},
 async unzipEntry(buf,name){const dv=new DataView(buf),len=dv.byteLength,min=Math.max(0,len-66000);let eocd=-1;for(let i=len-22;i>=min;i--)if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}if(eocd<0)throw new Error('ملف إكسل غير صالح');const count=dv.getUint16(eocd+10,true),off=dv.getUint32(eocd+16,true);let p=off;for(let i=0;i<count;i++){if(dv.getUint32(p,true)!==0x02014b50)break;const method=dv.getUint16(p+10,true),size=dv.getUint32(p+20,true),fn=dv.getUint16(p+28,true),ex=dv.getUint16(p+30,true),cm=dv.getUint16(p+32,true),lo=dv.getUint32(p+42,true),file=new TextDecoder().decode(new Uint8Array(buf,p+46,fn));if(file===name){if(dv.getUint32(lo,true)!==0x04034b50)throw new Error('بنية ملف إكسل غير صالحة');const lfn=dv.getUint16(lo+26,true),lex=dv.getUint16(lo+28,true),start=lo+30+lfn+lex,raw=new Uint8Array(buf,start,size);if(method===0)return raw;if(method===8&&typeof DecompressionStream!=='undefined'){const ds=new DecompressionStream('deflate-raw'),out=await new Response(new Blob([raw]).stream().pipeThrough(ds)).arrayBuffer();return new Uint8Array(out)}throw new Error('طريقة ضغط ملف إكسل غير مدعومة في هذا المتصفح')}p+=46+fn+ex+cm}return null},
 col(ref){let n=0;for(const c of S(ref).replace(/\d/g,''))n=n*26+(c.charCodeAt(0)-64);return n-1},
 async xlsx(file){const buf=await file.arrayBuffer(),ssRaw=await this.unzipEntry(buf,'xl/sharedStrings.xml'),shRaw=await this.unzipEntry(buf,'xl/worksheets/sheet1.xml');if(!shRaw)throw new Error('لم يتم العثور على الورقة الأولى داخل ملف إكسل');const xp=new DOMParser(),shared=[];if(ssRaw){const doc=xp.parseFromString(new TextDecoder().decode(ssRaw),'application/xml');for(const si of doc.querySelectorAll('si'))shared.push([...si.querySelectorAll('t')].map(x=>x.textContent||'').join(''))}const doc=xp.parseFromString(new TextDecoder().decode(shRaw),'application/xml'),rows=[];for(const r of doc.querySelectorAll('sheetData row')){const out=[];for(const c of r.querySelectorAll('c')){const idx=this.col(c.getAttribute('r')),type=c.getAttribute('t'),v=c.querySelector('v')?.textContent??c.querySelector('is t')?.textContent??'';out[idx]=type==='s'?shared[N(v)]??'':v}rows.push(out.map(x=>x??''))}return rows},
 async rows(file){const name=S(file?.name).toLowerCase();if(name.endsWith('.xlsx'))return this.xlsx(file);return this.csv(await file.text())},
 norm(s){return S(s).trim().toLowerCase().replace(/[\s_\-]+/g,'')},
 objects(rows){if(rows.length<2)throw new Error('الملف لا يحتوي بيانات كافية');const heads=rows[0].map(x=>S(x).trim());return rows.slice(1).filter(r=>r.some(x=>S(x).trim())).map(r=>Object.fromEntries(heads.map((h,i)=>[h,S(r[i]??'').trim()])))},
 pick(o,...keys){const map=new Map(Object.entries(o).map(([k,v])=>[this.norm(k),v]));for(const k of keys){const v=map.get(this.norm(k));if(v!==undefined&&S(v).trim()!=='')return S(v).trim()}return''},
 mapRow(type,o){if(type==='customers')return{name:this.pick(o,'name','الاسم','اسم العميل'),phone:this.pick(o,'phone','الهاتف','الموبايل'),whatsapp:this.pick(o,'whatsapp','واتساب'),email:this.pick(o,'email','البريد'),nationalId:this.pick(o,'nationalId','الرقم القومي'),passport:this.pick(o,'passport','رقم الجواز'),address:this.pick(o,'address','العنوان'),type:this.pick(o,'type','النوع')||'individual'};if(type==='suppliers')return{name:this.pick(o,'name','الاسم','اسم المورد'),phone:this.pick(o,'phone','الهاتف'),whatsapp:this.pick(o,'whatsapp','واتساب'),email:this.pick(o,'email','البريد'),taxNo:this.pick(o,'taxNo','الرقم الضريبي'),type:this.pick(o,'type','نوع المورد')||'أخرى',currency:this.pick(o,'currency','العملة')||DB.data.settings.baseCurrency,address:this.pick(o,'address','العنوان')};if(type==='agents')return{name:this.pick(o,'name','الاسم','اسم المندوب'),phone:this.pick(o,'phone','الهاتف'),email:this.pick(o,'email','البريد'),commissionRate:N(this.pick(o,'commissionRate','العمولة','نسبة العمولة'))};throw new Error('نوع الاستيراد غير مدعوم')},
 duplicate(type,x,target=DB.data[type]||[]){const eq=(a,b)=>a&&b&&this.norm(a)===this.norm(b),digits=v=>S(v).replace(/\D/g,'');return target.find(y=>{if(type==='customers'){if(eq(x.nationalId,y.nationalId)||eq(x.passport,y.passport))return true;if(x.phone&&y.phone&&digits(x.phone)===digits(y.phone))return true;if(x.email&&y.email&&eq(x.email,y.email))return true}else if(type==='suppliers'){if(eq(x.taxNo,y.taxNo))return true;if(x.phone&&y.phone&&digits(x.phone)===digits(y.phone))return true;if(x.email&&y.email&&eq(x.email,y.email))return true}else if(type==='agents'){if(x.phone&&y.phone&&digits(x.phone)===digits(y.phone))return true;if(x.email&&y.email&&eq(x.email,y.email))return true}return eq(x.name,y.name)&&(!x.phone||digits(x.phone)===digits(y.phone))})},
 async preview(file,type){Auth.require('dataexchange','import');if(!file)throw new Error('اختر ملفًا');const rows=await this.rows(file),objects=this.objects(rows),mapped:any[]=objects.map(o=>this.mapRow(type,o)).filter(x=>x.name),m=document.getElementById('modal'),f=document.getElementById('modalForm'),heads=Object.keys(mapped[0]||{});document.getElementById('modalTitle').textContent=`استيراد ${type==='customers'?'عملاء':type==='suppliers'?'موردين':'مندوبين'}`;document.getElementById('modalSubtitle').textContent=`تمت قراءة ${mapped.length} سجل. راجع عينة قبل الاعتماد.`;document.getElementById('modalIcon').innerHTML=icon('csv');document.getElementById('modalSubmitText').textContent='اعتماد الاستيراد';document.getElementById('modalBody').innerHTML=`<div class="form-intro">الاستيراد لا يحذف أي بيانات موجودة. يتم رفض السجل بدون اسم، ويكشف التكرار بالأولوية للهوية/الجواز أو الرقم الضريبي ثم الهاتف والبريد ثم الاسم.</div>${UI.table(heads.map(esc),mapped.slice(0,10).map((x,i)=>`<tr>${heads.map(h=>`<td>${esc(x[h])}</td>`).join('')}</tr>`),mapped.length?'':'لا توجد بيانات',{search:false,export:false})}`;m.classList.add('show');f.onsubmit=e=>{e.preventDefault();try{const result=this.commit(type,mapped,file.name);UI.closeModal(true);DB.save();toast(`تم استيراد ${result.added} وتخطي ${result.skipped}`)}catch(err){toast(err.message,'error')}}},
 commit(type,rows,fileName=''){let added=0,skipped=0;const target=DB.data[type]||[];for(const x of rows){const dup=this.duplicate(type,x,target);if(dup){skipped++;continue}if(type==='customers')Transactions.addCustomer({...x,branchId:BranchScope.currentId()});else if(type==='suppliers')Transactions.addSupplier({...x,branchId:BranchScope.currentId()});else if(type==='agents'){const a={id:iid(),no:Numbering.next('agent'),...x,active:true,branchId:BranchScope.currentId()};DB.data.agents.push(a);DB.log('import','agent',a.id,a.name)}added++}DB.data.dataImports.unshift({id:iid(),date:now(),type,fileName,added,skipped,userId:Auth.user?.id||'',branchId:BranchScope.currentId()});DB.log('import',type,'',`${fileName}: ${added} added, ${skipped} skipped`);return{added,skipped}},
 template(type){const headers=type==='customers'?['الاسم','الهاتف','واتساب','البريد','الرقم القومي','رقم الجواز','العنوان']:type==='suppliers'?['اسم المورد','نوع المورد','الهاتف','واتساب','البريد','الرقم الضريبي','العملة','العنوان']:['اسم المندوب','الهاتف','البريد','نسبة العمولة'];this.downloadCsv(`Template_${type}.csv`,[headers])},
 exportType(type){Auth.require('dataexchange','export');const arr=DB.data[type]||[];if(!arr.length)throw new Error('لا توجد بيانات للتصدير');const keys:string[]=[...new Set<string>(arr.flatMap((x:any)=>Object.keys(x)).filter((k:string)=>!['passwordHash','passwordSalt'].includes(k)))];this.downloadCsv(`${type}_${today()}.csv`,[keys,...arr.map(x=>keys.map(k=>typeof x[k]==='object'?JSON.stringify(x[k]??''):x[k]??''))])},
 downloadCsv(name,rows){const cell=v=>`"${S(v).replace(/"/g,'""').replace(/\r?\n/g,' ')}"`,blob=new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
};
export { CommercialData };
