const CommercialPages:any={
 owner(){const d=DB.data,base=d.settings.baseCurrency,branchId=BranchScope.currentId(),month=today().slice(0,7),bl=Accounting.lines('', '',{branchId}).filter(x=>x.date.startsWith(month)&&x.refType!=='year-close'),sales=bl.filter(l=>Accounting.account(l.accountId)?.type==='revenue').reduce((s,l)=>s+l.baseCredit-l.baseDebit,0),cost=bl.filter(l=>Accounting.account(l.accountId)?.type==='expense').reduce((s,l)=>s+l.baseDebit-l.baseCredit,0),profit=sales-cost,cash=(d.treasuries||[]).filter(t=>t.active!==false&&(!branchId||t.branchId===branchId)).reduce((s,t)=>s+Currency.toBase(Accounting.treasuryBalance(t.id),t.currency),0),activePrograms=[...(d.umrahPrograms||[]),...(d.programs||[]).filter(x=>!(d.umrahPrograms||[]).some(u=>u.id===x.id))].filter(x=>x.active!==false&&live(x)&&!['returned','completed','cancelled','closed'].includes(x.status)).length,alerts=Commercial.notifications().length;return Pages.head('لوحة الإدارة','مؤشرات مالية مرحلة من الأستاذ العام مع ملخص سريع للسيولة والذمم والتشغيل.')+`<div class="grid kpi-grid">${UI.kpi('إيرادات الشهر',money(sales,base),'من القيود المرحلة','good','profit')}${UI.kpi('تكاليف ومصروفات',money(cost,base),'من القيود المرحلة','bad','expenses')}${UI.kpi('صافي نتيجة الشهر',money(profit,base),profit>=0?'ربح فعلي مرحل':'خسارة فعلية مرحلة',profit>=0?'good':'bad','profit')}${UI.kpi('تنبيهات تحتاج متابعة',alerts,alerts?'راجع التنبيهات والرقابة':'لا توجد تنبيهات حالية',alerts?'warn':'good','bell')}</div><div class="dashboard-grid"><div class="card"><div class="card-head"><h3>السيولة والذمم</h3></div><div class="mini-list"><div class="mini-row"><span>إجمالي السيولة الحالية</span><b class="money-in">${money(cash,base)}</b></div><div class="mini-row"><span>مستحقات العملاء — الشركة</span><b class="money-in">${money(Insights.customerReceivablesBase(),base)}</b></div><div class="mini-row"><span>مستحقات الموردين — الشركة</span><b class="money-out">${money(Insights.supplierPayablesBase(),base)}</b></div><div class="mini-row"><span>البرامج النشطة</span><b>${activePrograms}</b></div><div class="mini-row"><span>الفرع الحالي</span><b>${esc(BranchScope.current()?.name||'-')}</b></div></div></div><div class="card"><div class="card-head"><h3>إجراءات الإدارة السريعة</h3></div><div class="action-menu-grid"><button class="btn primary" data-ui-page="workcenter">مركز العمل اليومي</button><button class="btn soft" data-ui-page="reports">التقارير</button><button class="btn soft" data-ui-page="audit">الرقابة</button><button class="btn soft" data-ui-page="support">حالة النظام</button><button class="btn soft" data-ui-page="branches">الفروع</button></div></div></div>`},
 branches(){const rows=(DB.data.branches||[]).map(b=>Pages.row(b.id,`<td><b>${esc(b.code)}</b></td><td>${esc(b.name)}</td><td>${esc(b.phone||'-')}</td><td>${esc(b.address||'-')}</td><td>${(DB.data.users||[]).filter(u=>(u.allowedBranchIds||[]).includes(b.id)).length}</td><td>${b.active!==false?'<span class="badge green">نشط</span>':'<span class="badge gray">موقوف</span>'}</td><td>${Auth.can('branches','edit')?`<button class="btn small ghost" data-commercial-action="branch" data-commercial-id="${b.id}">تعديل</button>`:'-'}</td>`));return Pages.head('الفروع',`كل عملية جديدة تحمل الفرع الحالي تلقائيًا. الترخيص يسمح بـ ${License.maxBranches()} فرع.`,Auth.can('branches','add')?'<button class="btn primary" data-commercial-action="branch">+ فرع</button>':'')+`<div class="grid kpi-grid">${UI.kpi('الفروع النشطة',(DB.data.branches||[]).filter(x=>x.active!==false).length,'حد الترخيص '+License.maxBranches(),'info','customers')}${UI.kpi('الفرع الحالي',esc(BranchScope.current()?.name||'-'),'يستخدم للعمليات الجديدة','good','treasury')}${UI.kpi('المستخدمون',DB.data.users.filter(x=>x.active!==false).length,'حسب الفروع','purple','users')}${UI.kpi('الترخيص',Commercial.statusText(),'من الخادم','warn','shield')}</div>${UI.table(['الكود','الفرع','الهاتف','العنوان','المستخدمون','الحالة','إجراء'],rows,'لا توجد فروع')}`},
 sessions(){setTimeout(()=>CommercialPages.loadSessions(),30);return Pages.head('الجلسات والأجهزة','الجلسات الحقيقية محفوظة على الخادم ويمكن لمدير النظام إنهاؤها.')+'<div id="commercialSessions"><div class="empty-state">جاري تحميل الجلسات...</div></div>'},
 async loadSessions(){const box=document.getElementById('commercialSessions');if(!box)return;try{const b=await CommercialSupport.sessions(),rows=b.items.map(x=>`<tr><td>${esc(x.userName||x.userId)}</td><td>${esc(x.ip||'-')}</td><td>${esc(S(x.userAgent).slice(0,70))}</td><td>${formatDateTime(x.createdAt)}</td><td>${formatDateTime(x.lastSeenAt)}</td><td><button class="btn small danger" data-commercial-action="revokeSession" data-commercial-id="${x.id}">إنهاء</button></td></tr>`);box.innerHTML=UI.table(['المستخدم','عنوان الشبكة','الجهاز','بدأت','آخر نشاط','إجراء'],rows,'لا توجد جلسات',{export:false})}catch(e){box.innerHTML=`<div class="danger-note">${esc(e.message)}</div>`}},
 dataexchange(){const importTypeLabel={customers:'العملاء',suppliers:'الموردون',agents:'المندوبون'},imports=(DB.data.dataImports||[]).slice(0,30).map(x=>`<tr><td>${formatDateTime(x.date)}</td><td>${esc(importTypeLabel[x.type]||x.type)}</td><td>${esc(x.fileName||'-')}</td><td>${x.added}</td><td>${x.skipped}</td></tr>`);return Pages.head('استيراد وتصدير البيانات','استيراد من إكسل أو ملف CSV مع معاينة قبل الحفظ. السجلات الموجودة لا تُحذف تلقائيًا.')+`<div class="settings-grid"><div class="card"><h3>استيراد العملاء</h3><p class="muted">يمكن مطابقة أسماء الأعمدة العربية أو الأجنبية تلقائيًا.</p><label class="btn primary">اختيار إكسل / ملف CSV<input type="file" hidden accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" data-commercial-preview="customers"></label> <button class="btn ghost" data-commercial-template="customers">تنزيل نموذج</button></div><div class="card"><h3>استيراد الموردين</h3><label class="btn primary">اختيار إكسل / ملف CSV<input type="file" hidden accept=".csv,.xlsx" data-commercial-preview="suppliers"></label> <button class="btn ghost" data-commercial-template="suppliers">تنزيل نموذج</button></div><div class="card"><h3>استيراد المندوبين</h3><label class="btn primary">اختيار إكسل / ملف CSV<input type="file" hidden accept=".csv,.xlsx" data-commercial-preview="agents"></label> <button class="btn ghost" data-commercial-template="agents">تنزيل نموذج</button></div><div class="card"><h3>تصدير البيانات</h3><div class="action-menu-grid"><button class="btn soft" data-commercial-export="customers">العملاء — ملف CSV</button><button class="btn soft" data-commercial-export="suppliers">الموردون — ملف CSV</button><button class="btn soft" data-commercial-export="agents">المندوبون — ملف CSV</button><button class="btn success" data-ui-page="backup-center">النسخ الاحتياطي والاستعادة</button></div></div></div><div class="card mt-16"><h3>سجل الاستيراد</h3>${UI.table(['التاريخ','النوع','الملف','تمت إضافته','تم تخطيه'],imports,'لا توجد عمليات استيراد',{export:false})}</div>`},
 support(){setTimeout(()=>CommercialPages.loadSupport(),0);const connected=ServerStore.available===true,company=ServerStore.company||{};return Pages.head('مركز الدعم وحالة النظام','بيانات تشخيص تساعد الدعم الفني بدون الدخول لقاعدة البيانات يدويًا.')+`<div id="commercialSupport"><div class="grid kpi-grid">${UI.kpi('الخادم',connected?'متصل':'جارٍ التحقق',`v${esc(APP.version)}`,connected?'good':'warn','check')}${UI.kpi('قاعدة التشغيل','جاري الحساب','قاعدة بيانات مركزية','info','treasury')}${UI.kpi('المرفقات','جاري الحساب',`${(DB.data.attachments||[]).length} سجل`,'purple','documents')}${UI.kpi('الجلسات','جاري الحساب','من الخادم','warn','users')}</div><div class="split-equal mt-16"><div class="card"><h3>هوية النسخة</h3><div class="mini-list mt-12"><div class="mini-row"><span>معرّف الشركة</span><b>${esc(company.companyId||DB.data?.company?.companyId||'-')}</b></div><div class="mini-row"><span>المنتج</span><b>${esc(APP.name)} • ${esc(APP.product)}</b></div><div class="mini-row"><span>المطور</span><b>${esc(APP.manufacturer)}</b></div><div class="mini-row"><span>الإصدار الحالي</span><b>v${esc(APP.version)}</b></div><div class="mini-row"><span>الترخيص</span><b>${esc(Commercial.licenseStatusLabel(DB.data?.license||{}))} / ${esc(EditionDefinitions[DB.data?.license?.edition]?.label||'غير محددة')}</b></div></div></div><div class="card"><h3>حماية البيانات</h3><p class="muted">يمكن فتح مركز النسخ والاستعادة فورًا، بينما يتم تحديث أرقام التشخيص في الخلفية.</p><button class="btn primary mt-12" data-ui-page="backup-center">فتح النسخ الاحتياطي والاستعادة</button></div></div><div class="info-note mt-16">جاري تحديث تفاصيل حالة النظام في الخلفية...</div></div>`},
 async loadSupport(){const box=document.getElementById('commercialSupport');if(!box)return;try{const d=await CommercialSupport.diagnostics();box.innerHTML=`<div class="grid kpi-grid">${UI.kpi('الخادم',d.ok?'متصل':'خطأ',`v${esc(d.version)}`,d.ok?'good':'bad','check')}${UI.kpi('قاعدة التشغيل',CommercialActions.bytes(d.databaseBytes),'قاعدة بيانات مركزية','info','treasury')}${UI.kpi('المرفقات',CommercialActions.bytes(N(d.files?.bytes)),`${d.files?.count||0} ملف`,'purple','documents')}${UI.kpi('الجلسات',d.activeSessions,'جلسة نشطة','warn','users')}</div><div class="split-equal"><div class="card"><h3>هوية النسخة</h3><div class="mini-list mt-12"><div class="mini-row"><span>معرّف الشركة</span><b>${esc(d.license?.companyId||d.company?.companyId||d.license?.installationId||'-')}</b></div><div class="mini-row"><span>المنتج</span><b>${esc(APP.name)} • ${esc(APP.product)}</b></div><div class="mini-row"><span>المطور</span><b>${esc(APP.manufacturer)}</b></div><div class="mini-row"><span>الإصدار الحالي</span><b>v${esc(d.version||APP.version)}</b></div><div class="mini-row"><span>الترخيص</span><b>${esc(Commercial.licenseStatusLabel(d.license||{}))} / ${esc(EditionDefinitions[d.license?.edition]?.label||'غير محددة')}</b></div><div class="mini-row"><span>رقم المراجعة</span><b>${d.revision}</b></div></div><button class="btn ghost mt-12" data-commercial-action="downloadDiagnostics">تنزيل ملف تشخيص</button></div><div class="card"><h3>حماية البيانات</h3><p class="muted">النسخ الكاملة الخارجية تُحفظ على جهازك أو أي خدمة تخزين سحابي. أما النسخ الخادمية فتُحفظ دون تكرار الملفات، مع الاحتفاظ بآخر 3 نسخ غير مثبتة فقط.</p><button class="btn primary mt-12" data-ui-page="backup-center">فتح النسخ الاحتياطي والاستعادة</button></div></div>`}catch(e){box.innerHTML=`<div class="danger-note">${esc(e.message)}</div>`}},
 programProfitability(){if(!Commercial.canViewCosts())throw new Error('لا تملك صلاحية مشاهدة تكاليف وربحية البرامج');const branchId=BranchScope.currentId(),rows=(DB.data.umrahPrograms||[]).filter(p=>!branchId||!p.branchId||p.branchId===branchId).map(p=>{const x=Commercial.programProfit(p.id);return`<tr><td>${esc(p.no||'')}</td><td>${esc(p.name)}</td><td>${x.bookings}</td><td>${money(x.sales,DB.data.settings.baseCurrency)}</td><td>${money(x.supplier+x.expenses+x.commissions,DB.data.settings.baseCurrency)}</td><td class="${x.profit>=0?'money-in':'money-out'}">${money(x.profit,DB.data.settings.baseCurrency)}</td><td>${fmt(x.margin,1)}%</td></tr>`});return Print.wrap('ربحية برامج العمرة',`<div class="print-meta"><span>حتى ${formatDate(today())}</span></div>`,`<table class="print-table"><thead><tr><th>الكود</th><th>البرنامج</th><th>حجوزات</th><th>الإيراد</th><th>التكلفة</th><th>النتيجة</th><th>الهامش</th></tr></thead><tbody>${rows.join('')||'<tr><td colspan="7">لا توجد برامج</td></tr>'}</tbody></table>`)}
};
Object.assign(Pages,{owner:CommercialPages.owner,branches:CommercialPages.branches,sessions:CommercialPages.sessions,dataexchange:CommercialPages.dataexchange,support:CommercialPages.support});

Object.assign(CommercialPages,{
 marketReadiness(){
  const d=DB.data,c=d.company||{},s=d.settings||{},l=d.license||{},admins=(d.users||[]).filter(x=>x.active!==false&&(x.role==='admin'||x.permissions?.all)),checks=[
   {ok:!!S(c.name).trim()&&!['اسم الشركة','الشركة'].includes(S(c.name).trim()),title:'اسم وهوية الشركة',text:'اسم حقيقي يظهر في النظام والمستندات.',page:'settings',action:'إكمال بيانات الشركة',essential:true},
   {ok:!!(c.phone||c.email),title:'وسيلة تواصل للشركة',text:'هاتف أو بريد لاستقبال استفسارات العملاء.',page:'settings',action:'إضافة وسيلة تواصل',essential:true},
   {ok:!!c.logo,title:'شعار الشركة',text:'يظهر في الواجهة والمستندات المطبوعة.',page:'settings',action:'رفع الشعار'},
   {ok:!!(c.taxNo||c.commercialNo),title:'البيانات القانونية',text:'رقم ضريبي أو سجل تجاري على المستندات.',page:'settings',action:'إضافة البيانات'},
   {ok:(d.branches||[]).some(x=>x.active!==false),title:'فرع تشغيل نشط',text:'العمليات الجديدة تُسند للفرع الحالي.',page:'branches',action:'مراجعة الفروع',essential:true},
   {ok:(d.treasuries||[]).some(x=>x.active!==false),title:'خزنة أو بنك نشط',text:'مطلوب لدورة القبض والصرف.',page:'treasury',action:'مراجعة الخزن',essential:true},
   {ok:admins.length>0,title:'حساب مدير نشط',text:'مسؤول عن الصلاحيات والإعدادات.',page:'users',action:'مراجعة المستخدمين',essential:true},
   {ok:(d.users||[]).filter(x=>x.active!==false).every(x=>x.role==='admin'||x.permissions?.all||x.permissions),title:'صلاحيات المستخدمين',text:'كل مستخدم غير إداري له صلاحيات محددة.',page:'users',action:'مراجعة الصلاحيات',essential:true},
   {ok:!License.expired()&&!!(l.status||l.mode),title:'الترخيص صالح',text:Commercial.statusText(),page:'support',action:'فتح حالة الترخيص',essential:true},
   {ok:ServerStore.available===true,title:'اتصال الخادم المركزي',text:ServerStore.available===true?'قاعدة البيانات والجلسات المركزية متاحة.':'التشغيل الحالي محلي/تدريبي؛ اربط خادم الشركة قبل البيع.',page:'support',action:'فحص الخادم',essential:true},
   {ok:ServerStore.emailRecovery?.configured===true,title:'استعادة الحساب بالبريد',text:ServerStore.emailRecovery?.configured===true?'خدمة إرسال رسائل الاستعادة مفعلة.':'خدمة البريد تحتاج إعدادًا على الخادم.',page:'support',action:'مراجعة إعداد البريد',essential:true},
   {ok:!!s.printFooter,title:'تذييل المستندات',text:'بيانات ثابتة أسفل الفواتير والسندات.',page:'settings',action:'ضبط الطباعة'},
   {ok:(d.auditLog||[]).length>0,title:'سجل النشاط',text:'توجد أحداث قابلة للمراجعة والتتبع.',page:'activity',action:'فتح سجل النشاط'}
  ],done=checks.filter(x=>x.ok).length,essential=checks.filter(x=>x.essential),essentialDone=essential.filter(x=>x.ok).length,score=Math.round(done/checks.length*100),ready=essentialDone===essential.length;
  const rows=checks.map(x=>`<div class="info-row"><div><b>${x.ok?'✓':'!'} ${esc(x.title)}</b><small>${esc(x.text)}</small></div><div class="quick-actions"><span class="badge ${x.ok?'green':x.essential?'red':'orange'}">${x.ok?'مكتمل':x.essential?'ضروري':'موصى به'}</span>${x.ok?'':`<button class="btn small ${x.essential?'primary':'ghost'}" data-ui-page="${x.page}">${esc(x.action)}</button>`}</div></div>`).join('');
  return Pages.head('جاهزية البيع والتشغيل','فحص ذاتي محلي يوضح ما يمكن استكماله الآن قبل تسليم النظام لأي عميل.',`<button class="btn ghost" data-ui-render-current="1">إعادة الفحص</button><button class="btn soft" data-ui-page="quick-guide">دليل البدء</button>`)+`<div class="grid kpi-grid">${UI.kpi('نسبة الجاهزية',score+'%',`${done} من ${checks.length} بند`,ready?'good':'warn','check')}${UI.kpi('الضروريات',`${essentialDone}/${essential.length}`,ready?'مكتملة':'تحتاج استكمال',ready?'good':'bad','shield')}${UI.kpi('الإصدار','v'+APP.version,'نسخة النظام الحالية','info','info')}${UI.kpi('بيئة البيانات',ServerStore.available===true?'خادم مركزي':'محلية / تدريب',ServerStore.available===true?'متصلة':'لا تستخدم كإنتاج',ServerStore.available===true?'good':'warn','treasury')}</div><div class="${ready?'ok-note':'warn-note'} mt-16"><b>${ready?'الأساسيات مكتملة.':'توجد أساسيات يجب استكمالها.'}</b> ${ready?'يمكن متابعة اختبار القبول والنسخ الاحتياطي قبل التسليم.':'ابدأ بالعناصر الحمراء؛ العناصر البرتقالية تحسن المظهر والاحترافية.'}</div><div class="card mt-16"><div class="card-head"><h3>قائمة تجهيز العميل</h3><span class="badge ${ready?'green':'orange'}">${done}/${checks.length}</span></div><div class="mini-list mt-12">${rows}</div></div><div class="card mt-16"><h3>أمور خارج هذه النسخة</h3><p class="muted">النطاق الرسمي، مفاتيح Railway، المراقبة الخارجية، سياسة الخصوصية واختبار الضغط على بيئة الإنتاج تُستكمل عند تجهيز البنية النهائية للعميل.</p></div>`;
 },
 quickGuide(){
  const steps=[
   ['1','بيانات الشركة والطباعة','أضف الاسم والشعار والهاتف والبيانات القانونية، ثم راجع شكل الفاتورة.','settings','فتح الإعدادات'],
   ['2','الفروع والخزن','أنشئ الفروع المطلوبة واربط خزنة أو بنك بكل دورة تشغيل مناسبة.','branches','إعداد الفروع'],
   ['3','المستخدمون والصلاحيات','أنشئ حسابًا لكل موظف وامنحه أقل صلاحيات يحتاجها فقط.','users','إدارة المستخدمين'],
   ['4','البيانات الأساسية','أدخل العملاء والموردين أو استوردهم من إكسل أو CSV بعد مراجعة العينة.','dataexchange','الاستيراد والتصدير'],
   ['5','أول دورة تجريبية','نفّذ فاتورة تجريبية وسند قبض، ثم راجع القيود وميزان المراجعة.','invoices','بدء الفواتير'],
   ['6','الحج والعمرة','أنشئ برنامجًا تجريبيًا ثم حجزًا، وراجع الجاهزية والموردين والمستندات.','umrah-program-new','إنشاء برنامج'],
   ['7','الرقابة والنسخ','راجع مركز الرقابة، ثم أنشئ نسخة احتياطية وتأكد من إمكانية استعادتها.','support','مركز الدعم والنسخ'],
   ['8','الاعتماد قبل التسليم','افتح فحص جاهزية البيع وأغلق جميع العناصر الضرورية قبل تشغيل العميل.','market-readiness','فحص الجاهزية']
  ];
  return Pages.head('دليل البدء السريع','مسار عملي قصير لتجهيز شركة جديدة بدون الحاجة لدليل خارجي.',`<button class="btn primary" data-ui-page="market-readiness">فحص الجاهزية الآن</button>`)+`<div class="grid two">${steps.map(([no,title,text,page,action])=>`<div class="card"><div class="section-head"><div><span class="badge blue">الخطوة ${no}</span><h3 class="mt-12">${esc(title)}</h3><p>${esc(text)}</p></div></div><button class="btn soft mt-12" data-ui-page="${page}">${esc(action)}</button></div>`).join('')}</div><div class="form-intro mt-16"><b>قاعدة التسليم:</b> استخدم بيانات تدريبية في التجربة، ولا تُدخل بيانات عميل حقيقية قبل تفعيل الخادم المركزي والنسخ الاحتياطي.</div>`;
 }
});
Object.assign(Pages,{'market-readiness':CommercialPages.marketReadiness,'quick-guide':CommercialPages.quickGuide});

const BackupCenter={
 statusText(kind){const x=Backup.status()?.[kind];return x?.at?`${formatDateTime(x.at)} • ${esc(x.name||'')}`:'لم يتم على هذا الجهاز بعد'},
 page(){setTimeout(()=>CommercialPages.loadBackups?.(),0);const admin=Auth.user?.role==='admin'||Auth.user?.permissions?.all;return Pages.head('النسخ الاحتياطي والاستعادة','مركز موحد للنسخ الخارجية والاستعادة والنسخ الخادمية دون تكرار المرفقات.')+`<div class="grid two"><div class="card"><h3>نسخة احتياطية كاملة</h3><p class="muted">ملف مستقل يشمل البيانات والمرفقات والبيانات الوصفية وبصمة التحقق. احفظه على الكمبيوتر أو الموبايل أو شاركه إلى خدمة تخزين سحابي أو واتساب أو البريد.</p><div class="quick-actions mt-12"><button class="btn success" data-commercial-action="externalBackup" data-commercial-mode="download">حفظ نسخة على الجهاز</button><button class="btn soft" data-commercial-action="externalBackup" data-commercial-mode="share">مشاركة / تخزين سحابي</button></div><div class="mini-row mt-12"><span>آخر نسخة على هذا الجهاز</span><b>${this.statusText('backup')}</b></div></div><div class="card"><h3>استعادة نسخة من ملف</h3><p class="muted">اختر ملف <b>.erpbackup</b>. يتم فحص بصمة التحقق والمرفقات وهوية الشركة قبل الاستعادة.</p><input id="backupRestoreFile" type="file" accept=".erpbackup,application/json" hidden data-restore-file="1"> <button class="btn primary mt-12" data-trigger-file="backupRestoreFile">استعادة نسخة احتياطية</button></div></div><div class="card mt-16"><div class="card-head"><div><h3>النسخ الخادمية</h3><p class="muted">يحتفظ النظام تلقائيًا بآخر 3 نسخ غير مثبتة فقط. المثبتة لا تُحذف تلقائيًا.</p></div><div class="quick-actions"><button class="btn primary" data-commercial-action="createSnapshot">إنشاء نسخة خادمية الآن</button><button class="btn ghost" data-commercial-action="cleanupSnapshots">تنظيف القديمة</button></div></div><div id="serverSnapshots"><div class="loading-state">جاري تحميل النسخ...</div></div></div>`}
};
const ArchiveCenter={
 preview:null,
 suggestedEnd(){const last=S(DB.data.meta?.lastArchivedThrough||''),y=last?Number(last.slice(0,4))+1:Number(today().slice(0,4))-1;return`${y}-12-31`},
 page(){setTimeout(()=>CommercialPages.loadArchives?.(),0);return Pages.head('الأرشفة الذكية','إغلاق فترة سنوية، عرض الأرشيفات، وصحة البيانات فقط. النسخ والاستعادة في المركز الموحد.',`<button class="btn ghost" data-ui-page="backup-center">النسخ الاحتياطي والاستعادة</button>`)+`<div class="grid two"><div class="card"><h3>الفترة الحالية</h3><p class="muted">الأرشفة تنقل فقط العمليات القديمة المكتملة إلى أرشيف للقراءة فقط وتُبقي العمليات المفتوحة في التشغيل.</p><div class="form-grid mt-12"><div class="field"><label>إغلاق وأرشفة حتى</label><input id="archivePeriodEnd" type="date" value="${esc(this.suggestedEnd())}"></div></div><button class="btn primary" data-commercial-action="previewArchive">اختبار الأرشفة بدون تنفيذ</button></div><div class="card"><h3>صحة البيانات</h3><p class="muted">قبل الإغلاق يتم فحص القيود والفترات والعمليات المفتوحة. لن يتم الإغلاق إذا وُجد مانع حرج.</p><button class="btn ghost mt-12" data-ui-page="audit">فتح فحص المحاسبة</button></div></div><div class="card mt-16"><div class="card-head"><div><h3>الأرشيفات السنوية</h3><p class="muted">لا تخضع لسياسة آخر 3؛ تبقى حتى الحذف اليدوي من الإدارة.</p></div><div><input id="archiveOpenFile" type="file" accept=".erparchive,application/json" hidden data-archive-file="1"> <button class="btn soft" data-trigger-file="archiveOpenFile">فتح أرشيف من ملف</button></div></div><div id="archiveList"><div class="loading-state">جاري تحميل الأرشيفات...</div></div></div>`}
};
Object.assign(Pages,{'backup-center':()=>BackupCenter.page(),'period-archiving':()=>ArchiveCenter.page()});

Object.assign(CommercialPages,{
 async loadBackups(){const box=document.getElementById('serverSnapshots');if(!box)return;try{const b=await CommercialSupport.backups(),items=b.items||[],typeLabel={manual:'يدوي',automatic:'تلقائي','pre-upgrade':'قبل تحديث','pre-period':'قبل إغلاق فترة',snapshot:'نسخة خادمية'},safety=x=>x.integrity_status==='failed'?'<span class="badge red">فشل ❌</span>':'<span class="badge green">سليم ✅</span>',state=x=>x.pinned?'<span class="badge blue">📌 مثبت</span>':'<span class="badge gray">عادي</span>',actions=x=>`<button class="btn small ghost" data-commercial-action="verifySnapshot" data-commercial-id="${x.id}">فحص</button><button class="btn small soft" data-commercial-action="pinSnapshot" data-commercial-id="${x.id}" data-commercial-flag="${x.pinned?'false':'true'}">${x.pinned?'إلغاء التثبيت':'تثبيت'}</button><button class="btn small primary" data-commercial-action="restoreSnapshot" data-commercial-id="${x.id}">استعادة</button><button class="btn small danger" data-commercial-action="deleteSnapshot" data-commercial-id="${x.id}">حذف</button>`;box.innerHTML=items.length?`<div class="data-protection-desktop"><div class="table-wrap"><table><thead><tr><th>النوع</th><th>التاريخ</th><th>الحجم</th><th>السلامة</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(typeLabel[x.source]||x.source||'-')}</td><td>${formatDateTime(x.created_at)}</td><td dir="ltr">${CommercialActions.bytes(x.size_bytes||0)}</td><td>${safety(x)}</td><td>${state(x)}</td><td><div class="quick-actions">${actions(x)}</div></td></tr>`).join('')}</tbody></table></div></div><div class="data-protection-mobile snapshot-mobile-list">${items.map(x=>`<article class="dp-mobile-card"><div class="dp-card-head"><div><small>نوع النسخة</small><h4>${esc(typeLabel[x.source]||x.source||'-')}</h4></div>${state(x)}</div><div class="dp-meta-grid"><div><small>التاريخ</small><b>${formatDateTime(x.created_at)}</b></div><div><small>الحجم</small><b dir="ltr">${CommercialActions.bytes(x.size_bytes||0)}</b></div><div><small>السلامة</small>${safety(x)}</div></div><div class="dp-actions">${actions(x)}</div></article>`).join('')}</div>`:'<div class="empty-state">لا توجد نسخ خادمية بعد</div>'}catch(e){box.innerHTML=`<div class="danger-note">${esc(e.message)}</div>`}},
 async loadArchives(){const box=document.getElementById('archiveList');if(!box)return;try{const b=await CommercialSupport.archives(),items=b.items||[],records=x=>N(x.summary?.records||0)||N(x.summary?.invoices||0)+N(x.summary?.bookings||0)+N(x.summary?.journals||0)+N(x.summary?.attachments||0),size=x=>N(x.size_bytes)>0?CommercialActions.bytes(x.size_bytes):'غير محسوب',safety=x=>x.integrity_status==='failed'?'<span class="badge red">فشل ❌</span>':'<span class="badge green">سليم ✅</span>',actions=x=>`<button class="btn small primary" data-commercial-action="openArchive" data-commercial-id="${x.id}">فتح</button><button class="btn small soft" data-commercial-action="downloadArchive" data-commercial-id="${x.id}">تنزيل</button><button class="btn small ghost" data-commercial-action="archiveInfo" data-commercial-id="${x.id}">معلومات</button><button class="btn small danger" data-commercial-action="deleteArchive" data-commercial-id="${x.id}">حذف</button>`;box.innerHTML=items.length?`<div class="data-protection-desktop"><div class="table-wrap"><table><thead><tr><th>الفترة</th><th>تاريخ الإغلاق</th><th>السجلات</th><th>الحجم</th><th>السلامة</th><th>إجراءات</th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc(x.period_label||String(x.period_end||'').slice(0,4))}</b></td><td>${formatDateTime(x.created_at)}</td><td>${records(x)||'—'}</td><td dir="ltr">${size(x)}</td><td>${safety(x)}</td><td><div class="quick-actions">${actions(x)}</div></td></tr>`).join('')}</tbody></table></div></div><div class="data-protection-mobile archive-mobile-list">${items.map(x=>`<article class="dp-mobile-card"><div class="dp-card-head"><div><small>الفترة</small><h4>${esc(x.period_label||String(x.period_end||'').slice(0,4))}</h4></div>${safety(x)}</div><div class="dp-meta-grid"><div><small>تاريخ الإغلاق</small><b>${formatDateTime(x.created_at)}</b></div><div><small>السجلات</small><b>${records(x)||'—'}</b></div><div><small>الحجم</small><b dir="ltr">${size(x)}</b></div></div><div class="dp-actions">${actions(x)}</div></article>`).join('')}</div>`:'<div class="empty-state">لا توجد أرشيفات سنوية بعد</div>'}catch(e){box.innerHTML=`<div class="danger-note">${esc(e.message)}</div>`}}
});
